### ISSUE TITLE
Обработка результата запроса "ПОСЛЕ"  - не работает - вместо вызова функции вызывается процедура

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#1012]
ИТК_ОбработкаОбъектов.ВыполнениеОбработкиПосле - это процедура, а вызывается как функция

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль разработчика
2. Написать простейший запрос "выбрать 1"
3. Перейти Инструменты\Обработка результата
4. На закладке ПОСЛЕ написать "а=1;"
5. Нажать Обработать\Обработать ВСЕ

Появится ошибка "Обращение к процедуре объекта как к функции Обращение к процедуре объекта как к функции (ВыполнениеОбработкиПосле)"

**Окружение:**

Infostart Toolkit PROF 2024.3.01

Платформа: 8.3.24.1548 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.19.60)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: 3.1.10.295

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.3.3
