### ISSUE TITLE
Ошибка при поиске таблицы в конструкторе запросов

### ISSUE THREAD

**Issue by KorniltsevMikhail** [infostart-hub/toolkit#1014]
**Описание ошибки**
Поле объекта не обнаружено (Представление)
{InfostartToolkitCORP ОбщаяФорма.ИТК_ПоискТаблицыВКонструктореЗапросов.Форма(58)}:ИмяКоллекция = ДоступнаяТаблицаСхемыЗапроса.Представление;
{InfostartToolkitCORP ОбщаяФорма.ИТК_ПоискТаблицыВКонструктореЗапросов.Форма(41)}:ОбновитьРезультатПоискаНаСервере();
{InfostartToolkitCORP ОбщаяФорма.ИТК_ПоискТаблицыВКонструктореЗапросов.Форма(17)}:ОбновитьРезультатПоиска();

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть конструктор запросов
2. Нажать "поиск таблицы"
3. Ввести в поле поиска что угодно и нажать энтр
4. Выпадает ошибка

**Ожидаемое поведение, если бы ошибки не было**
Нашлсь нужная таблица

**Скриншоты**
![image](https://github.com/user-attachments/assets/c071f271-3471-4595-84f6-e5bb78dfc092)

**Окружение:**

Infostart Toolkit CORP 2024.3.04

Платформа: 8.3.24.1667 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 (6.1.02.07)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_20
Версия БСП: 3.1.6.347

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Приветствую, не могу воспроизвести ошибку.
Могу подключится или поставь останавливаться по ошибке.
Нужно больше информации

**Comment by KorniltsevMikhail** [comment]
Падает на этой строчке. Судя по синтаксис помощнику - такого свойства у "ДоступнаяТаблицаСхемыЗапроса" действительно не существует
![image](https://github.com/user-attachments/assets/ec05ab2d-f9e5-4f3f-9361-c0bedd980f66)

**Comment by Evg-lylyk** [comment]
> Падает на этой строчке. Судя по синтаксис помощнику - такого свойства у "ДоступнаяТаблицаСхемыЗапроса" действительно не существует ![image](https://private-user-images.githubusercontent.com/13355723/376285952-ec05ab2d-f9e5-4f3f-9361-c0bedd980f66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTc4NzUsIm5iZiI6MTcyODkxNzU3NSwicGF0aCI6Ii8xMzM1NTcyMy8zNzYyODU5NTItZWMwNWFiMmQtZjllNS00ZjNmLTkzNjEtYzBiZWRkOTgwZjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDE0NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyZTNhZWU3NGIyNDQ4ZmE3MjAwOTI5ZmNjNThkZTI3Yzk5NzRiM2MyZjUzYTkwMjE1OGJiZjI4MmVkMDkwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zClW1S7E43eDCWxfgv_2ier5TnAoSbrQStC-dEWNKqI)

Воспроизвести все равно не могу, но уже более менее понятно

**Comment by Evg-lylyk** [comment]
Наверное исправил, игнорирую этот тип при обходе. Воспроизвести так и не смог

**Comment by Evg-lylyk** [comment]
В версии 2024.3.5
