### ISSUE TITLE
Ошибка при запустить под пользователем при возврате настроек.

### ISSUE THREAD

**Issue by deni-tda** [infostart-hub/toolkit#1019]
1.	Воспроизведение ошибки
НСИ и администрирование – Настройки пользователей и прав – Настройки входа.
Ошибка воспроизведется при настройке:
«Запретить повторение пароля среда последних» = Да; И
Значение > 1, в данном случае = 3.
 
![изображение](https://github.com/user-attachments/assets/acadac50-4462-4996-b90c-95544a2dc2a0)

На примере пользователя – у пользователя включена только Аутентификация ОС, стандартная аутентификация отключена:
 
![изображение](https://github.com/user-attachments/assets/d86463bf-d2e6-4251-a68b-495971e3c796)

Используем обработку Пользователи (Toolkit), заходим под пользователем– Запустить под пользователем - Запуск.
![изображение](https://github.com/user-attachments/assets/99de68e6-d5c2-4d07-a661-0075e00f7b21)
 
Происходит вход под пользователем. Если в окне запуска нажать «Закрыть», то в момент закрытия окна возникает служебное сообщение:
 
![изображение](https://github.com/user-attachments/assets/2a3cdeed-4171-4ccc-8307-52a8b9a0a4d8)

В журнале регистрации появляется ошибка:
 
![изображение](https://github.com/user-attachments/assets/ca889898-4f4c-4c70-936b-c4714bb878b6)

Затем в карточке пользователя, под которым выполняется вход, устанавливается стандартная аутентификация и появляется предупреждение в верхней части формы:
 
![изображение](https://github.com/user-attachments/assets/385aae1c-3136-4dd6-8f9f-797532472560)

2.	Сценарий тестирования
Пользователь с правами администратора.
Выполняется настройка:
НСИ и администрирование – Настройки пользователей и прав – Настройки входа.
 «Запретить повторение пароля среда последних» = Да; И
Значение = 3.
 
При входе под пользователями не возникает ошибок в журнале регистрации, служебных сообщений в окне запуска под пользователем. Стандартная аутентификация не остается включенной после входа под пользователем.

**Comment by deni-tda** [comment]
Нашли решение проблемы
Может и не самое красивое, но работает
обработка: ИТК_Пользователи
Форма: ЗапускПодПользователем  
Функция ПодменитьДанныеАвторизации 

  Функция ПодменитьДанныеАвторизации(УникальныйИдентификаторПользователя)
	
	ПользовательИБ = ПользователиИнформационнойБазы.НайтиПоУникальномуИдентификатору(УникальныйИдентификаторПользователя);
	
	Результат = Новый Структура;
	Результат.Вставить("УникальныйИдентификатор", ПользовательИБ.УникальныйИдентификатор);
	Результат.Вставить("АутентификацияСтандартная", ПользовательИБ.АутентификацияСтандартная);
	Результат.Вставить("ЗапрещеноИзменятьПароль", ПользовательИБ.ЗапрещеноИзменятьПароль);
	Результат.Вставить("СохраняемоеЗначениеПароля", ПользовательИБ.СохраняемоеЗначениеПароля);
	
	ПользовательИБ.АутентификацияСтандартная = Истина;
	ПользовательИБ.ЗапрещеноИзменятьПароль = Истина;
	
		//++ТДА 24.10.2024 Обход ошибки при настройке  "Запрет повторения пароля среди последних - "
	Если ПользователиСлужебныйПовтИсп.Настройки().ОбщиеНастройкиВхода Тогда
	
	НастройкиВхода = ПользователиСлужебный.НастройкиВхода();	
	КолВоПовторений=1; 
	Пароль="Qwerty123456789!";
	Пока КолВоПовторений<=НастройкиВхода.Пользователи.ЗапретитьПовторениеПароляСредиПоследних Цикл
		Пароль=Пароль+Строка(КолВоПовторений);
		ХешированиеДанных = Новый ХешированиеДанных(ХешФункция.SHA1);
		ХешированиеДанных.Добавить(Пароль);
		
		СохраняемоеЗначениеПароля = Base64Строка(ХешированиеДанных.ХешСумма);
		
		ХешированиеДанных = Новый ХешированиеДанных(ХешФункция.SHA1);
		ХешированиеДанных.Добавить(ВРег(Пароль));
		
		СохраняемоеЗначениеПароля = СохраняемоеЗначениеПароля + ","
			+ Base64Строка(ХешированиеДанных.ХешСумма);
       	ПользовательИБ.СохраняемоеЗначениеПароля = СохраняемоеЗначениеПароля; 

		ПользовательИБ.Записать(); 
		КолВоПовторений=КолВоПовторений+1;

	КонецЦикла;
	КонецЕсли;
	//--ТДА
	
	СохраняемоеЗначениеПароля = "UFsxOq/KlPH4n3Txbhh6F6hgG+A=,aQp2yfJ4uMWBrAqjri9wVyXy/M4="; //Это хэш-функция строки "Qwerty123456789!"
	ПользовательИБ.СохраняемоеЗначениеПароля = СохраняемоеЗначениеПароля;
	
	ПользовательИБ.Записать();
	
	Возврат Результат;
	
КонецФункции

**Comment by Evg-lylyk** [comment]
> Нашли решение проблемы Может и не самое красивое, но работает обработка: ИТК_Пользователи Форма: ЗапускПодПользователем Функция ПодменитьДанныеАвторизации
> 
> Функция ПодменитьДанныеАвторизации(УникальныйИдентификаторПользователя)
> 
> ```
> ПользовательИБ = ПользователиИнформационнойБазы.НайтиПоУникальномуИдентификатору(УникальныйИдентификаторПользователя);
> 
> Результат = Новый Структура;
> Результат.Вставить("УникальныйИдентификатор", ПользовательИБ.УникальныйИдентификатор);
> Результат.Вставить("АутентификацияСтандартная", ПользовательИБ.АутентификацияСтандартная);
> Результат.Вставить("ЗапрещеноИзменятьПароль", ПользовательИБ.ЗапрещеноИзменятьПароль);
> Результат.Вставить("СохраняемоеЗначениеПароля", ПользовательИБ.СохраняемоеЗначениеПароля);
> 
> ПользовательИБ.АутентификацияСтандартная = Истина;
> ПользовательИБ.ЗапрещеноИзменятьПароль = Истина;
> 
> 	//++ТДА 24.10.2024 Обход ошибки при настройке  "Запрет повторения пароля среди последних - "
> Если ПользователиСлужебныйПовтИсп.Настройки().ОбщиеНастройкиВхода Тогда
> 

Спасибо это поможет быстрее разобраться

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.3.5
