### ISSUE TITLE
Не работает заполнение параметров в консоли запросов

### ISSUE THREAD

**Issue by Efim-wq** [infostart-hub/toolkit#1028]
ВСЁ ХОРОШО! ПРИНОШУ ИЗВИНЕНИЯ, ЭТО ОШИБКА НАШЕГО ПРОГРАММИСТА В ДОКУМЕНТЕ. ВИЖУ ТАКУЮ ВПЕРВЫЕ - ПОЭТОМУ ОБВИНИЛ ИНСТРУМЕНТЫ.
**Описание ошибки**
Вот такое сообщение
![image](https://github.com/user-attachments/assets/67196cb0-fe2b-411e-bb2b-d6efe20bb18d)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Написать такой запрос:
ВЫБРАТЬ
	ЗапросКлиентаГрузы.Ссылка КАК Запрос,
	ЗапросКлиентаГрузы.ЛУК_Груз КАК Груз,
	ЗапросКлиентаГрузы.КоличествоМест КАК Количество
ИЗ
	Документ.ЗапросКлиента.Грузы КАК ЗапросКлиентаГрузы
		ВНУТРЕННЕЕ СОЕДИНЕНИЕ Документ.ЛУК_МесячныйПлан.Состав КАК МесячныйПланСостав
		ПО (ЗапросКлиентаГрузы.Ссылка = МесячныйПланСостав.ЗапросКлиента)
ГДЕ
	МесячныйПланСостав.Ссылка = &МесячныйПлан
3. Перейти на Параметры
4. Выбрать документ "Месячный план"

**Ожидаемое поведение, если бы ошибки не было**
Открытие формы списка документов "Месячный план"

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

   - Платформа 1С: 1С:Предприятие 8.3 (8.3.23.2040)
   - Имя конфигурации: Управление перевозками (1.0.0.3)
   - Язык: Русский
   - Операционная система: *Вин 10
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Efim-wq** [comment]
Infostart Toolkit PROF 2024.3.04

Платформа: 8.3.23.2040 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление перевозками (1.0.0.3)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.7.343

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
ОК. Хорошего дня :)
