### ISSUE TITLE
При выводе результата запроса для избранных полей выводить GUID ссылки

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#103]
От [пользователя xnd](https://infostart.ru/profile/9566/)

Имеется две конфигурации на основе 1С между ними настроена интеграция ( XML файлы, RabbitMQ)
Очень часто выясняется что какой то реквизит одного объекта нужно доинтегрировать в другой.
Мы это учитываем в интеграции, но паралельно возникает задача по дозаполнению реквизита - регистрировать все объекты к обмену - это не наш вариант - объектов может быть очень много.
Как мы выходим из ситуации.
В базе источнике формируем запрос, который возвращает ГУИД объекта и требуемое значение какого либо реквизита
В базе приемнике загружаем результат запроса и кодом обрабатываем объекты, записывая значения нужного реквизита.

**Comment by xnd1124** [comment]
@Evg-lylyk возможно что данная задача не столь актуальна - т.к. решил другим способом

Консоль запросов использую только как средство отладки запроса а затем
1)в конфигурации источнике выполняю запрос в коде и выгружаю через
ЗначениевФайл
2) в конфигурации приемнике тоже консоль кода и значениеИзФайла
т.к. время не тратится на отображение тз на форме ( а она может быть очень большой) то все работает очень быстро.
При малых объемах можно использовать буфер обмена, а при больших внутреннее значение в файле

**Comment by xnd1124** [comment]
![image](https://user-images.githubusercontent.com/6578710/98251786-d9305e00-1f81-11eb-92fe-4f5b19013e04.png)
![image](https://user-images.githubusercontent.com/6578710/98251869-f6652c80-1f81-11eb-9afa-6e10520c8634.png)

**Comment by Evg-lylyk** [comment]
Суть я уловил, постараюсь учесть

**Comment by Evg-lylyk** [comment]
Проверил, работает как говорил считывает из Расшифровке при работе с MXL.
Шапку само собой удалить
