### ISSUE TITLE
Не до конца отрабатывает поиск по ссылки в редакторе объектов

### ISSUE THREAD

**Issue by Filin-S** [infostart-hub/toolkit#1031]
**Описание ошибки**
Не до конца отрабатывает поиск по ссылки в редакторе объектов. Ссылка находится, но не определяется тип. В итоге реквизиты не заполняются.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Копирую ссылку объекта
2. Вставляю в Редактор объекта
3. Ссылка определяется
4. реквизиты объекта не выводятся

**Ожидаемое поведение, если бы ошибки не было**
При вставке ссылки по ней же определять ТИП

**Скриншоты**
<img width="433" alt="image" src="https://github.com/user-attachments/assets/31702f9a-f4ed-4659-b935-89ad0a9d594e">

Если вручную выбрать тип объекта а потом вставить ссылку все отрабатывает
**Окружение:**

   - Платформа 1С: (8.3.24.1667)
   - Имя конфигурации: 1C:ERP. Управление холдингом (3.2.5.3)
   - Язык: русский (Россия)
   - Операционная система: Windows Server 2022 Standard
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Filin-S** [comment]
Версия 1.9.8
По типовому скопированная внутренняя ссылка

**Comment by Evg-lylyk** [comment]
Так это очень старая версия, обновится ;)
