### ISSUE TITLE
Не работает копирование кода 

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#104]
**Описание ошибки**
Копирование/вставка через буфер обмена не работает

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создаю новый код в консоли разработчика, пишу строку кода
2. Выделяю ее, нажимаю Ctrl-C
3. Открываю новый текстовый файл - пытаюсь вставить - ничего не вставляется
P.S. хотя в консоль кода вставка происходит нормально - проблема со сторонними вкладками или программами

**Ожидаемое поведение, если бы ошибки не было**
Вставка происходит в любой программе

**Скриншоты**
![image](https://user-images.githubusercontent.com/6578710/98251056-e8fb7280-1f80-11eb-93e3-e4023ab91990.png)
![image](https://user-images.githubusercontent.com/6578710/98251119-fb75ac00-1f80-11eb-9bc0-301b6b4652c2.png)

**Окружение:**

   - Платформа 1С:  (8.3.16.1148
   - Имя конфигурации: 1С:ERP Управление предприятием 2 (2.4.12.80)
   - Язык: Русский
   - Локализация: русский
   - Операционная система: Microsoft Windows Server 2016 DataCenter

- Типовая или не типовая конфигурация Да
- Включен ли режим защиты от опасных действий: Режим отключен ( для отладки запросов)
Работа через RDP соединение

**Comment by Evg-lylyk** [comment]
Проблема известная база редактора это [bsl_console] (https://github.com/salexdv/bsl_console)
там в конце в разделе известные проблемы это написано:
На платформах до 8.3.16 могут не работать горячие клавиши CTRL+C, CTRL+V и CTRL+Z и т.п.
На платформах до 8.3.18 команды копировать/вставить работают только в пределах окна редактора
К сожалению пока нет пути решения этой проблемы
