### ISSUE TITLE
В конструкторе запроса (выделенный текст) недоступны внешние источники данных

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#106]
1) вызываю основной конструктор - источники доступны
![image](https://user-images.githubusercontent.com/6578710/98279072-24f2ff80-1fa2-11eb-8ed5-cf260f0bce74.png)
2) в условии где вызываю конструктор выделенного текста
![image](https://user-images.githubusercontent.com/6578710/98279201-376d3900-1fa2-11eb-9324-098d72aa959f.png)
3)В списке таблиц отсутствует внешний источник
![image](https://user-images.githubusercontent.com/6578710/98279238-48b64580-1fa2-11eb-8966-928d247ae53c.png)

**Comment by Evg-lylyk** [comment]
Исправлено в версии 1.5 (аналогичная ошибка была при открытии вложенного запроса)
