### ISSUE TITLE
Поиск ссылок на объект открывается без контекста 

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#109]
1) в форме объекта не указано сочетание клавиш Ctrl- Alt -F
![image](https://user-images.githubusercontent.com/6578710/98362926-c330a500-2036-11eb-81c3-bf81ace188a7.png)

2) сочетание работает, но форма открывается без контекста вызвавшего его объекта ( аналогичная команда редактора объекта отрабатывает корректно)
![image](https://user-images.githubusercontent.com/6578710/98362935-c9268600-2036-11eb-94d1-8ee8f6ad2b3e.png)
Подозреваю что срабатывает глобальная команда ( хотя при выборе мышкой форма открывается с контекстом)

**Comment by Evg-lylyk** [comment]
Нормальное поведение, глобальная команда открывает из любого места, а контекстная из контекста, у редактора локальная команда

**Comment by xnd1124** [comment]
Хотелось бы такое же поведение как и с редактором объекта - есть локальная контекстная команда и она гораздо интереснее чем глобальная открывающая форму с пустым контекстом

**Comment by Evg-lylyk** [comment]
Данное поведение менять пока не планируется, локальная команда бывает недоступна.
