### ISSUE TITLE
Поиск по ГУИД

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#110]
**Существует проблема**
При интеграции объект одного типа в исходной системе может преобразовываться в объект иного типа в целевой системе.
Например справочник "работники" может переходить в "сотрудники" и "физ. лица"

**Хотелось бы иметь следующую функциональность**
в редакторе объектов  осуществлять поиск в ссылочных полях только по Гуид без указания типов.
Если в базе есть несколько объектов с таким Гуид, то предлагать выбор из нескольких объектов

**Comment by Evg-lylyk** [comment]
Реализовано в 1.5
