### ISSUE TITLE
Обработка результата: доступ к данным обработки в алгоритме перед обработкой

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#113]
Зачастую в алгоритмах обработки необходимо кешировать какие либо данные.
Было бы удобно иметь возможность перед обработкой данных вычислять какие-либо данные в кеше, исходя из состава обрабатываемых данных и затем через доп. свойства передавать их в основной алгоритм.

**Comment by Evg-lylyk** [comment]
Реализовано в 1.5
