### ISSUE TITLE
Ошибка "несоответствие типов" при обращении к параметру запроса

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#114]
**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть Запрос (из отладки).mcr
[Запрос (из отладки).zip](https://github.com/infostart-hub/toolkit/files/5552390/default.zip)

2. Перейти к параметрам 
3. Щелкнуть на "ТЧ Товары"
![image](https://user-images.githubusercontent.com/6578710/99370721-b62d7480-28c6-11eb-93e3-220d4ac553c1.png)
Несоответствие типов
{InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(156)}:	Элемент.ДоступныеТипы = ДоступныеТипы;
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(752)}:		ИТК_ФормаКлиент.АктивизацияЗначенияВФорме(Элементы.ПараметрыЗапросаЗначение, ЗначениеПараметра, СтрокаПараметр.ТипЗначения);

по причине:
Несоответствие типов

**Окружение:**

   - Платформа 1С: (8.3.16.1148
   - Имя конфигурации: 1С:ERP Управление предприятием 2 (2.4.12.80)
   - Язык: русский
   - Локализация: русский
   - Операционная система: Windows 2016 Data Centre

**Comment by xnd1124** [comment]
Версия расширения 1.4.4

**Comment by Evg-lylyk** [comment]
Исправлена 1.4.5
