### ISSUE TITLE
В редакторе кода не отображается вызов конструктора запроса

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#120]
По правой кнопке мыши нет вызова конструктора запросов

Версия обработки 1.5.0 (Тестовая)
 Платформа 1С: (8.3.16.1148

![image](https://user-images.githubusercontent.com/6578710/100095768-af24da00-2e63-11eb-8e1e-3b2a4bee4eac.png)

**Comment by xnd1124** [comment]
Проверил на 8.3.18.1128 - тоже нет в контекстном меню конструктора

**Comment by Evg-lylyk** [comment]
Беда, элемент создается программно, а там нужно Автозаполнение контекстного меню выключить, а программно его не выключить.
Наверное придется отказаться от программного создания элемента

**Comment by xnd1124** [comment]
@Evg-lylyk может вытащить на форму в конфигураторе "элемент-болванку" - у него установить отключить свойство автозаполнение и при программном заполнении использовать этот элемент при построении интерфейса?

**Comment by Evg-lylyk** [comment]
Да приходится отказываться от динамического создания. Решаю

**Comment by Evg-lylyk** [comment]
Проблема решена в 1.5.1
