### ISSUE TITLE
Восстанавливать последний открытый объект в редакторе объекта опционально

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#121]
Хочу открыть редактор объекта без контекста ALT-E и указать вручную редактируемый объект
Сейчас открывается редактор и сразу подставляет последний редактируемый объект и вместо того чтобы сразу искать нужный объект я должен 2 раза очищать поле поиска - в первый раз чтобы избавиться от ссылки на объект, второй раз чтобы от типа
Предложение сделать восстановление последнего редактируемого объекта опциональным.

**Comment by Evg-lylyk** [comment]
в 1.5.1 просто убрал восстановление
