### ISSUE TITLE
Не кешируется вызов СоответствиеСтрокаТипКартинка в общем модуле ИТК_ТипыПовтИсп

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#122]
Функция объявлена как не экспортная, а согласно ИТС кешируются только экспортные
https://its.1c.ru/db/metod8dev/content/4594/hdoc
"При обращении к экспортируемым методам таких модулей из клиентского приложения кэширование значений, возвращаемых методами, выполняется как на клиенте, так и на сервере."

**Comment by Evg-lylyk** [comment]
в версии 1.5.1
Исправлено, и дополнительно оптимизировано чтение значений набором
