### ISSUE TITLE
Добавить инструмент: Запуск 1С под другим пользователем

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#129]
На внедрениях очень часто для расследования инцидентов необходимо логиниться под определенным пользователем.
Сейчас помогает эта обработка.
https://infostart.ru/public/153667/
Хотелось бы видеть в составе расширения.

**Comment by xnd1124** [comment]
[153667_Zapusk_1S_pod_drugim_polzovatelem.zip](https://github.com/infostart-hub/toolkit/files/5606856/153667_Zapusk_1S_pod_drugim_polzovatelem.zip)
Сама обработка

**Comment by Evg-lylyk** [comment]
Реализовано в 1.6
