### ISSUE TITLE
Ошибка открытия иерархического плана видов характеристик в редакторе объекта

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#132]
Если открыть любой объект из иерархического ПВХ - возникает ошибка 

Поле объекта не обнаружено (ВидИерархии)
{InfostartToolkit ОбщийМодуль.ИТК_Метаданные.Модуль(92)}:				ИЛИ ИТК_Метаданные.ЭтоПланВидовХарактеристик(Объект))
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(718)}:	ОбъектСИерархией = ИТК_Метаданные.ОбъектСИерархией(ОбъектМетаданных);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(656)}:		ДанныеОбъекта = ПрочитатьДанныеОбъекта(ИзменяемыйОбъект, ОбъектЗаполнения, УникальныйИдентификатор);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1481)}:	ЗаполнениеДанныхПоОбъекту(ОбрабатываемыйОбъект);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1076)}:	ОбновитьДанныеОбъекта();
{InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(60)}:		ВыполнитьОбработкуОповещения(ДополнительныеПараметры.Оповещение, Результат);
{InfostartToolkit ОбщаяФорма.ИТК_РедактированиеТипаЗначения.Форма(806)}:		Закрыть(Результат);
{InfostartToolkit ОбщаяФорма.ИТК_РедактированиеТипаЗначения.Форма(184)}:	ВыбраноЗначение(Элемент.ТекущиеДанные);
![image](https://user-images.githubusercontent.com/6578710/100841131-88782c00-347f-11eb-9c1f-e6bbbb5d3b65.png)

**Comment by xnd1124** [comment]
Для примера в Демо ЕРП можно открыть ПВХ "Статьи Расходов"

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.3
