### ISSUE TITLE
Поиск и замена ссылок: Отбор среди найденных в регистрах сведений.

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#133]
Конфигурация ЕРП:
Имеется Партнер1, у него есть Контрагент11 и Контрагент12
Тут мы поняли что Контрагент12 не должен принадлежать Партнер1, а должен например НовыйПартнер
Мы ищем все ссылки на Партнер1, накладываем отбор Контрагент = Контрагент12 и в них заменяем Партнер1 на НовыйПартнер.
Но есть такая сущность как КлючиАналитикиПоПартнерам (РегистрСведений) и нам нужно произвести замену только в тех ключах аналитики, в которых Контрагент = Контрагент12 ( пока мы не можем этого сделать)

**Comment by Evg-lylyk** [comment]
Реализовано в 1.6
