### ISSUE TITLE
Ошибка при подборе параметра запроса ссылочного типа по представлению

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#134]
При поиске параметра запроса по строке  (в случае если искомых значений нет) выходит ошибка:
Недопустимое значение параметра (параметр номер '1')
{InfostartToolkit ОбщийМодуль.ИТК_ФормаВызовСервера.Модуль(22)}:		УникальныйИдентификатор = Новый УникальныйИдентификатор(Текст);
{InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(315)}:		ИТК_ФормаВызовСервера.АвтоПодборЗначения(Текст, Элемент.ДоступныеТипы, Элемент.ОграничениеТипа, ДанныеВыбора);
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(919)}:	ИТК_ФормаКлиент.АвтоПодборЗначенияВФорме(Текст, Элемент, ДанныеВыбора, СтандартнаяОбработка);

по причине:
Недопустимое значение параметра (параметр номер '1')

![image](https://user-images.githubusercontent.com/6578710/100859070-77d3b000-3497-11eb-9e5c-5d86b863bba8.png)
![image](https://user-images.githubusercontent.com/6578710/100859080-7b673700-3497-11eb-91ba-84f2f2234bf5.png)

Версия: 1.5.2

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.3
