### ISSUE TITLE
Ошибка вставки ссылки на объект БД в не улучшенном редакторе кода

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#135]
При нажатии на кнопку выходит ошибка
Поле объекта не обнаружено (Документ)
{InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(465)}:	Возврат Элемент.Документ.defaultView;
{InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(243)}:	defaultView = ДокументHTML(Элемент);
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(2193)}:	ИТК_РедакторКодаКлиент.ПодключаемыйОбработчикКоманд(ЭтотОбъект, Команда.Имя);
![image](https://user-images.githubusercontent.com/6578710/100884027-abbfcd00-34b9-11eb-8525-3f3940430fca.png)

**Comment by Evg-lylyk** [comment]
Исправлено 1.5.3
