### ISSUE TITLE
Невозможно задать значение параметра запроса с типом Граница 

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#136]
Версия 1.5.3
При попытке задать значение ничего не происходит.
![image](https://user-images.githubusercontent.com/6578710/100983084-8088bc80-3551-11eb-9731-f2fe2bb0723d.png)
![image](https://user-images.githubusercontent.com/6578710/100983115-8c747e80-3551-11eb-8ef9-9b5f9772d74b.png)

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.4
