### ISSUE TITLE
В консоли разработчика для кода добавить возможность работы с параметрами

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#137]
Есть универсальный алгоритм, которому на вход подаются параметры ссылочного типа.
Сейчас эти параметры приходится описывать в коде путем поиска по ГУИД - кажется было бы удобнее сделать их интерактивными как параметры запроса.

**Comment by Evg-lylyk** [comment]
Ждем реализации фичи https://github.com/salexdv/bsl_console/issues/35

**Comment by Evg-lylyk** [comment]
Реализовано в новой консоли запросов 2023.4
