### ISSUE TITLE
Ошибка загрузки данный из настроек по кнопке "Загрузить"

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#138]
При попытке загрузить настройки по двойному щелчку мыши все работает а при нажатии на кнопку "Загрузить"
выходит сообщение об ошибке:
"Ошибка при загрузке данных: Значение не является значением объектного типа (Получить)"
![image](https://user-images.githubusercontent.com/6578710/101014749-07985d80-356f-11eb-9002-52d7c1ec78fa.png)
![image](https://user-images.githubusercontent.com/6578710/101015021-6e1d7b80-356f-11eb-83fe-2ce292e9a770.png)

Версия 1.5.3

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.4
