### ISSUE TITLE
Ошибка при заполнении значения параметра запроса типа Граница

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#139]
После указания типа Граница, выбора типа даты и попытки указать дату возникает ошибка "Непредвиденное исключение"
![image](https://user-images.githubusercontent.com/6578710/101044367-ef810800-3587-11eb-89ad-5be8e31bba14.png)
![image](https://user-images.githubusercontent.com/6578710/101044469-06275f00-3588-11eb-9995-8f804c63b59d.png)

Версия 1.5.4

**Comment by Evg-lylyk** [comment]
Исправлена в 1.5.5
