### ISSUE TITLE
Ошибка при попытке просмотра источника запроса только что созданного внешнего источника запроса

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#140]
1.Создаю в консоли запросов новый запрос
2.Добавляю внешний источник
3.Не настраивая вызываю контекстное меню "Запрос источника"
Получаю ошибку
Недопустимое значение параметра (параметр номер '1')
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6376)}:		Значение = ПолучитьИзВременногоХранилища(Описание.Значение);
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(2111)}:	КолонкиИсточника = КолонкиВнешнегоИсточника(ОписаниеИсточника);
![image](https://user-images.githubusercontent.com/6578710/101045645-1c81ea80-3589-11eb-8a9a-eb2a06b33344.png)
![image](https://user-images.githubusercontent.com/6578710/101045690-24418f00-3589-11eb-87a1-e33299336219.png)

Версия 1.5.4

**Comment by Evg-lylyk** [comment]
Исправлено 1.5.5
