### ISSUE TITLE
Выполнение кода на клиенте завершается с ошибкой "Поле объекта не обнаружено (РежимВыполнения)"

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#142]
Выполнение кода на клиенте завершается с ошибкой:
Поле объекта не обнаружено (РежимВыполнения)
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3726)}:				Если ИТК_ОбщийКлиентСервер.ЭтоРежимВыполненияСРезультатом(Результат.РежимВыполнения) Тогда
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3602)}:	ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3563)}:		ВыполнитьОперациюНаКлиенте(ОбрабатываемаяСтрока, НаименованиеОперации, Режим);
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(1357)}:	ВыполнитьОперацию("Перечисление.ИТК_РежимВыполненияКода.НаКлиенте");

![image](https://user-images.githubusercontent.com/6578710/101151932-0a588880-362b-11eb-83e4-2cd2b740c10b.png)

Версия 1.5.4

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.5
