### ISSUE TITLE
Открытие некоторых документов в Редакторе объекта проходит с ошибкой Таблица не найдена ...ДополнительныеРеквизиты

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#144]
При попытке открыть документ в редакторе объекта возникает ошибка
{(7, 2)}: Таблица не найдена "Документ.ОтчетОРозничныхПродажах.ДополнительныеРеквизиты"
<<?>>Документ.ОтчетОРозничныхПродажах.ДополнительныеРеквизиты КАК ТаблицаСвойств
{ОбщийМодуль.УправлениеСвойствами.Модуль(1035)}:	Результат = Запрос.Выполнить().Выгрузить();
{ОбщийМодуль.УправлениеСвойствами.Модуль(1377)}:	Возврат ЗначенияСвойств(ВладелецСвойств, ПолучатьДопРеквизиты, ПолучатьДопСведения, МассивСвойств);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(912)}:	ЗначенияСвойств = МодульУправлениеСвойствами.ПолучитьЗначенияСвойств(СсылкаЗначенийСвойств, , , Свойства);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(809)}:	ДобавитьДополнительныеРеквизитыИСведения(Реквизиты, ИзменяемыйОбъект, ОбъектЗаполнения, ЗаполнениеПоОбъекту);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(656)}:		ДанныеОбъекта = ПрочитатьДанныеОбъекта(ИзменяемыйОбъект, ОбъектЗаполнения, УникальныйИдентификатор);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1485)}:	ЗаполнениеДанныхПоОбъекту(ОбрабатываемыйОбъект);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(127)}:	ОбновитьДанныеОбъекта();
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1838)}:	ОбрабатываемыйОбъектПриИзменении(Элемент);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(61)}:	ОбрабатываемыйОбъектИзменен(ОбрабатываемыйОбъект);
{InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(620)}:	ОткрытьФорму("Обработка.ИТК_РедакторОбъекта.Форма", Параметры, , Объект.УникальныйИдентификатор());
{InfostartToolkit ОбщийМодуль.ИТК_ИнтеграцияВКонфигурациюКлиент.Модуль(5)}:	ИТК_ФормаКлиент.ОткрытьРедакторОбъекта(Ссылка);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(257)}:			ВыполнитьОбработкуОповещения(Обработчик, ПараметрКоманды);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(64)}:	ПродолжитьВыполнениеКоманды(ПараметрыВыполнения);
{Документ.ОтчетОРозничныхПродажах.Форма.ФормаДокумента.Форма(745)}:	ПодключаемыеКомандыКлиент.ВыполнитьКоманду(ЭтотОбъект, Команда, Объект);

по причине:
{(7, 2)}: Таблица не найдена "Документ.ОтчетОРозничныхПродажах.ДополнительныеРеквизиты"
<<?>>Документ.ОтчетОРозничныхПродажах.ДополнительныеРеквизиты КАК ТаблицаСвойств

**Сценарий воспроизведения**
Шаги по воспроизведению:
В Демо конфигурации ЕРП 2.4.13.46 (Можно попробовать взять аналогичную УТ)
1. Открыть в редакторе объекта документ по ссылке e1cib/data/Документ.ОтчетОРозничныхПродажах?ref=8e500050568b35ac11e7f79a7e782f7c
![image](https://user-images.githubusercontent.com/6578710/101321643-5c3d2080-386e-11eb-8275-4be5780af9fe.png)

Версия расширения: 1.5.3

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.5
