### ISSUE TITLE
Периодически возникает ошибка, когда пытаюсь развернуть ветку объектов в дереве метаданных выбора таблиц. Точной закономерности появления ошибки не нашел, может происходить при разных сценариях действий. 

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#146]
Ошибка в конструкторе. Версия 1.5.4
![1](https://user-images.githubusercontent.com/48444742/101446031-87d60e80-3933-11eb-9ef9-a1980caf71a5.jpg)
Попробуй тут повторить. "Запрос №1", открыть конструктор и и развернуть ветку
Теперь во такая:
![2](https://user-images.githubusercontent.com/48444742/101446053-8dcbef80-3933-11eb-8e55-35789c79119a.png)

**Comment by xnd1124** [comment]
@Evg-lylyk наблюдал такую ошибку даже в обычном конструкторе запросов, вызываемом в режиме 1С Предприятия - предположительно причина в сервере 1С - т.к. возникала на платформе 8.3.14 и лечилась только перезапуском службы
 с переходом на 8.3.16 перестали ловить подобного рода ошибки

**Comment by Evg-lylyk** [comment]
Спасибо, это у нас в рабочей версия 8.3.17

**Comment by xnd1124** [comment]
@Evg-lylyk я бы попробовал при воспроизведении ошибки тут же вызвать обычный конструктор

**Comment by Evg-lylyk** [comment]
Не воспроизводится, раз я ее словил за 100 запусков повторно никак
