### ISSUE TITLE
В редакторе таблицы значения внешнего источника добавить возможность удалить колонку

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#147]
На данный момент отсутствует возможность удаления лишней колонки, например необходимо удалить Колонку 1
![image](https://user-images.githubusercontent.com/6578710/101453438-016ffb80-3938-11eb-928a-2d73488aa3c9.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 1.5.5
