### ISSUE TITLE
Ошибка при переименовании колонки таблицы значений после повторного заполнения из буфера обмена

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#148]
После повторной вставки таблицы из буфера нельзя переименовать колонки
![ezgif-4-215fae813d63](https://user-images.githubusercontent.com/6578710/101455317-0da98800-393b-11eb-8a6c-a62a43792ac5.gif)

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.5
