### ISSUE TITLE
Ошибка при сохранении запроса для отладки, когда в параметрах запроса есть табличная часть

### ISSUE THREAD

**Issue by salexdv** [infostart-hub/toolkit#149]
**Описание ошибки**
При попытке сохранения запроса для отладки возникает ошибка
_**ОбщийМодуль.ИТК_XML.Модуль(30)}: Значение не является значением объектного типа (ИмяТипа)**_
Происходит это из-за того, что в параметры запроса передана табличная часть. Если табличную часть заменить на таблицу значений, то проблем нет, но в типовых часто передается именно табличная часть.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть [обработку](https://github.com/infostart-hub/toolkit/files/5664400/default.zip) в любой конфигурации, где есть документ "Реализация товаров и услуг"
2. В результате на форме отобразится ошибка

**Ожидаемое поведение, если бы ошибки не было**
Успешное сохранение

**Окружение:**

   - Платформа 1С: 8.3.18.891
   - Имя конфигурации: ERP, УТ, БП
   - Версия InfostartToolkit: 1.5.3

**Comment by Evg-lylyk** [comment]
Реализовано в 1.5.6
