### ISSUE TITLE
Заполнение по другому объекту или из XML не заполняет табличные части

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#152]
**Сценарий воспроизведения**
ERP 2.4.13.46
1.Открываю редактор объекта, выбираю реализацию товаров и услуг, не выбираю ссылку, оставляю пустой редактор
2. Вызываю заполнить по другому объекту
3. Шапка заполнилась, но в табличных частях кол-во заполнено, а по факту табличная часть пустая
P.S. Такая же ошибка при загрузке из XML
![image](https://user-images.githubusercontent.com/6578710/101737936-2e561700-3ace-11eb-8341-95b796381462.png)

Версия Расширения 1.5.6

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.7
