### ISSUE TITLE
Редактирование параметра запроса с типом уникальный идентификатор

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#153]
**Описание ошибки**
В редакторе параметров запроса (консоль запросов) при очистке значения выдает ошибку (для параметра с типом значение ГУИД).

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Задано непустое значение 
![image](https://user-images.githubusercontent.com/18395787/102015299-cd4b6f00-3d6b-11eb-9238-f786f5fec107.png)

2. Открываю редактор. Нажимаю delete
![image](https://user-images.githubusercontent.com/18395787/102015310-e5bb8980-3d6b-11eb-8e22-4f9df5d9673a.png)

3.Получаю ошибку
![image](https://user-images.githubusercontent.com/18395787/102015323-0683df00-3d6c-11eb-8ba8-01af3d04304d.png)

Если очистить по кнопке - то все Ок.
![image](https://user-images.githubusercontent.com/18395787/102015344-21eeea00-3d6c-11eb-8e3a-269a8d44b7fd.png)

**Окружение:**

   - Платформа 1С: 1С:Предприятие 8.3 (8.3.12.1790)
   - toolkit 1.5.6

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.7
