### ISSUE TITLE
Добавить информацию в меню "О Программе".

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#154]
**Существует проблема**
Для того чтобы можно было быстро оставлять сведения об используемом окружении (при описании ошибки) можно добавить вывод этих сведений в меню "О программе" (с возможностью копирования).

Вывод в таком виде
![image](https://user-images.githubusercontent.com/18395787/102016066-fc63df80-3d6f-11eb-844e-3a15028bdfb8.png)

или например как сделан вывод в инструментах разработчика
![image](https://user-images.githubusercontent.com/18395787/102016044-e81fe280-3d6f-11eb-9a32-5641717216ee.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 1.6
