### ISSUE TITLE
Установка на базу без БСП.

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#161]
**Описание ошибки**
что конкретно происходит
![image](https://user-images.githubusercontent.com/18395787/102493111-bc5c6f80-4083-11eb-9c41-419586a8ed09.png)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Создать пустую базу
2. Запустить Установщик.epf
3. Устанавливаем.

**Окружение:**

   - Платформа 1С:  8.3.12

**Comment by Evg-lylyk** [comment]
Исправлено в 1.5.7
