### ISSUE TITLE
Изменение в конструкторе запросов, вызываемый через Консоль разработчика

### ISSUE THREAD

**Issue by IvanShurygin** [infostart-hub/toolkit#165]
**Существует проблема**
Оптимизация поиска объектов метаданных, ускорение процесса написания запроса

**Хотелось бы иметь следующую функциональность**
1. Когда открывается дерево объектов метаданных:

- При вводе с клавиатуры нет быстрого поиска, в итоге поиск нужной таблицы занимает время. Предлагаю реализовать как в обработке "Структура конфигурации", где есть текстовое поле, я просто вбиваю часть названия - он находит нужную мне таблицу. Можно также предусмотреть фильтр по реквизитам (Например везде где есть табличная часть "ШтрихкодыУпаковок", даже если в ряде документов она называется "txl_ШтрихкодыУпаковок"
- Фильтр по подсистемам конфигурации. Часто разработчик все время работает в одной подсистеме. И все запросы выполняет только в ее рамках.  Я очень часто этим пользуюсь.
2. На закладке "Связи" нет выбора построения простой связи. Это реально увеличивает срок написания связей. Просто 3 поля, выбор поля из первой таблицы, вид сравнения и поле из второй таблицы. (Как в стандартном конструкторе)

**Comment by Evg-lylyk** [comment]
По п.1. проблема в сложности реализации нет платформенных механизмов фильтров дерева, только с 15 платформы что то есть. В целом нужно изучать, искать решение. Постараюсь учесть
Поясните п.2? вроде все как в толстом конструкторе

**Comment by IvanShurygin** [comment]
![image](https://user-images.githubusercontent.com/76583103/103129880-61420280-46ab-11eb-91fa-aa643349a45c.png)
Вот пример по пункту 2.

**Comment by IvanShurygin** [comment]
А по пункту №1 я бы реализовал иначе, я бы таблицу значений (скрытую от пользователя) в ней, когда начинаешь набирать текст делал бы фильтр. Для каждого реквизита (или табличной части) выводил бы родительский элемент 1 "Документы", родительский элемент 2 "Реализация товаров и услуг". И уже этим данным бы перестраивал дерево. Например используя реквизит "ВыводитьПользователю", Тип Булево, используя отбор строк.  Тут варианты для обсуждения возможны. Как крайний вариант. в принципе дерево заменять таблицей значений, если поле поиска заполнено.

**Comment by Evg-lylyk** [comment]
> А по пункту №1 я бы реализовал иначе, я бы таблицу значений (скрытую от пользователя) в ней, когда начинаешь набирать текст делал бы фильтр. Для каждого реквизита (или табличной части) выводил бы родительский элемент 1 "Документы", родительский элемент 2 "Реализация товаров и услуг". И уже этим данным бы перестраивал дерево. Например используя реквизит "ВыводитьПользователю", Тип Булево, используя отбор строк. Тут варианты для обсуждения возможны. Как крайний вариант. в принципе дерево заменять таблицей значений, если поле поиска заполнено.
> 
> По сути какую задачу решает разработчик используя поиск?
> 
> * Найти конкретный объект, не используя префикс
> * Найти ряд объектов, в которых существует нужный нам реквизит

Полезность всего этого бесспорна, вы же понимаете как все это будет тормозить в ERP. Учту обязательно.

**Comment by Evg-lylyk** [comment]
По п.2. понял

**Comment by IvanShurygin** [comment]
> > А по пункту №1 я бы реализовал иначе, я бы таблицу значений (скрытую от пользователя) в ней, когда начинаешь набирать текст делал бы фильтр. Для каждого реквизита (или табличной части) выводил бы родительский элемент 1 "Документы", родительский элемент 2 "Реализация товаров и услуг". И уже этим данным бы перестраивал дерево. Например используя реквизит "ВыводитьПользователю", Тип Булево, используя отбор строк. Тут варианты для обсуждения возможны. Как крайний вариант. в принципе дерево заменять таблицей значений, если поле поиска заполнено.
> > По сути какую задачу решает разработчик используя поиск?
> > 
> > * Найти конкретный объект, не используя префикс
> > * Найти ряд объектов, в которых существует нужный нам реквизит
> 
> Полезность всего этого бесспорна, вы же понимаете как все это будет тормозить в ERP. Учту обязательно.

У вас есть встроенный навигатор по конфигурации. Он то работает отлично... Если сложность именно в реквизитах и табл частях. то это можно оставить как доп. доп. функционал. А поиск просто по объекту метаданных - очень удобная вещь
.

**Comment by Evg-lylyk** [comment]
Согласен что полезно, нет в IS Toolkit навигатора

**Comment by Evg-lylyk** [comment]
Еще раз проанализировал тикет п.1,2 точно не планах, сложности в реализации. По связям в конструкторе есть более приземленные задачи #28, #40
