### ISSUE TITLE
Копирование/вставка в обработке результата запроса.

### ISSUE THREAD

**Issue by AnanyevAl** [infostart-hub/toolkit#174]
Некорректно работает CTRL+C/V  в форме обработки результат запроса.

Шаги по воспроизведению:
1. Копируем текст из любого текстового редактора
2. Открываем в консоли разработчика инструмент "Обработка результата запроса"
3. Жмем CTRL+V (или ПКМ -> Вставить)
4. Ни чего не происходит

**Comment by Evg-lylyk** [comment]
Речь идет о редакторе с подцветкой? Какая у вас версия платформы?

**Comment by AnanyevAl** [comment]
> Речь идет о редакторе с подцветкой? Какая у вас версия платформы?
Да, речь о редакторе с подсветкой.
Платформа 1С:Предприятие 8.3 (8.3.16.1063)

**Comment by Evg-lylyk** [comment]
Новый редактор использует https://github.com/salexdv/bsl_console
Есть платформенные проблемы:
Пока выходом является поставить платформу 8.3.17, в дальнейшем постараемся решить эту проблему
![ПроблемыСКопироватьВставить](https://user-images.githubusercontent.com/48444742/104994436-7ead8680-5a35-11eb-80fa-d451fa9bc8ef.png)
Есть задача #170 орентировочно постараемся решить в версии 1.7
