### ISSUE TITLE
Не запускается инструмент "Регламентные и фоновые задания"

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#180]
**Описание ошибки**
При попытке запуска инструмента "Регламентные и фоновые задания" возникает ошибка

Метод объекта не обнаружен (РаботаСВнешнимиРесурсамиЗаблокирована)

Infostart Toolkit 1.6.0

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.46)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.6.1
