### ISSUE TITLE
Очищается текст запроса при проверке в консоли разработчика

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#181]
**Описание ошибки**
При нажатии на кнопку Проверить очищается тест запроса

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Добавить в консоль новый запрос
2. Указать текст выбрать спр.ссылка из Справочник.Номенклатура как Спр где спр.Ссылка = &ССЫЛКА
3. Нажать на Конструктор ( выйдет сообщение об ошибке - проигнорировать его, нажать Отмена)
4. Нажать Проверить  - текст запроса очищается

Infostart Toolkit 1.6.0

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.46)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.6.1
