### ISSUE TITLE
Не сохраняются Настройки расширения

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#182]
**Описание ошибки**
При попытке сохранить настройки расширения возникает ошибка
Несоответствие типов (параметр номер '1')
{InfostartToolkit ОбщийМодуль.ИТК_АнализЗапроса.Модуль(29)}:		Схема.УстановитьТекстЗапроса(Текст);
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(5761)}:			ОбновитьСтруктуруЗапросаСервер(ОбрабатываемаяСтрока, ИТК_АнализЗапроса.РазборСтруктуры(Данные.Текст));
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(5479)}:	ОбновитьСтруктуруЗапросовСервер();
{InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(5490)}:	НастройкиИзмененыСервер();
{InfostartToolkit 

**Сценарий воспроизведения**
1. Открыть Сервис/Настройки
2. Нажать Сохранить

Infostart Toolkit 1.6.0

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.46)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не уверен что исправил 1.6.1 уже потом не удалось воспроизвести, предположение что некорректный текст запроса
