### ISSUE TITLE
Не сравниваются результаты запросов

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#183]
**Описание ошибки**
При попытке сравнения результатов запроса ничего показывается результат

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Добавить запрос с текстом: Выбрать 1 
2.Добавить запрос с текстом: Выбрать 2
3. Выделить запрос 1 и 2 и в контекстном меню выбрать сравнить
4. Переключить в настройках на "Результаты", Нажать Сравнить

**Ожидаемое поведение, если бы ошибки не было**
Ожидаю результата сравнения - но ничего не появляется

Infostart Toolkit 1.6.0

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.46)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проблема в том что сравнение результатов не работает в тонком клиенте
с 1.6.1 добавил предупреждение
