### ISSUE TITLE
Не выполняются запросы при открытии приложенного файла 

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#184]
**Описание ошибки**
При попытке выполнить запрос возникает ошибка "Синтаксическая ошибка "ПОМЕСТИТЬ"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть в консоли файл "Тест параметров.mcr"
2. Попытаться выполнить самый первый запрос 
[тест параметров.zip](https://github.com/infostart-hub/toolkit/files/5856858/default.zip)

**Скриншоты**
![image](https://user-images.githubusercontent.com/6578710/105511111-38c41d00-5cd8-11eb-95ea-6ac29cf6c9c5.png)

**Окружение:**

   -Infostart Toolkit 1.6.0

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.46)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
У меня данных типов нет, воспроизвел аналогичный вопрос и уже в моей 1.6.1 нет, скорее всего связано с сопутствующими проблемами, когда выйдет 1.6.1 посмотри
