### ISSUE TITLE
Не сохраняются ручные измения запроса

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#185]
https://user-images.githubusercontent.com/48444742/105514822-02d96580-5ce5-11eb-868e-49b0c6f02899.mp4

**Comment by AnatoliyBritko** [comment]
![Ручное редактировани](https://user-images.githubusercontent.com/18395787/105515724-16390080-5ce6-11eb-92a4-e56d29ed7979.gif)

**Comment by Evg-lylyk** [comment]
Не могу воспроизвести данную ошибку, напиши номер платформы?, может в какой то отдельной проявляется

**Comment by AnatoliyBritko** [comment]
Infostart Toolkit 1.6.0

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by AnatoliyBritko** [comment]
Сегодня смотрю - нормально сохраняет изменения.
какая-то плавающая проблема

**Comment by Evg-lylyk** [comment]
Наверное какая то ошибка взаимодействия платформы и HTML
Использовать более свежую версию этой же 16 платформы
Закрываю задачу
