### ISSUE TITLE
Не определяет корректно параметры запроса

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#186]
![Параметры запроса](https://user-images.githubusercontent.com/18395787/105541248-8a849b80-5d08-11eb-828a-ed2be1b1530e.gif)

после окончания редактирования текста запроса - не определяет параметры запроса
после того как переключился с одного запроса на др - параметры определило корректно

**Comment by Evg-lylyk** [comment]
ОК, это уже поправил в 1.6.1
