### ISSUE TITLE
Очищается тест запроса после попытки вызова конструктора

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#191]
**Сценарий воспроизведения**
Шаги по воспроизведению:
1.Открыть консоль запроса, добавить текст "Выбрать 1 2"
2. Нажать кнопку Конструктор 
3. На вопрос продолжить - отказаться, выбрав "Отмена"
4. Наблюдаю пустой текст запроса

**Окружение:**

   -Infostart Toolkit 1.6.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.103)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.362

Клиент:
ОС: Windows x86-64 (Microsoft Windows 8.1 version 6.3  (Build 9600))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 1.6.2
