### ISSUE TITLE
Не работает контекстное меню "Вырезать"

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#192]
**Описание ошибки**
Текст не удаляется

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть новое окно консоли запроса
2. В тексте запроса указать Выбрать 1
3.Выделить весь текст и в контекстном меню выбрать "Вырезать"
4.Текст запроса не изменился

**Ожидаемое поведение, если бы ошибки не было**
Ожидаю удаление выделенного фрагмента
Infostart Toolkit 1.6.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.13.103)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.362

Клиент:
ОС: Windows x86-64 (Microsoft Windows 8.1 version 6.3  (Build 9600))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.6.3
