### ISSUE TITLE
Редактор объектов: хранилище значений в ТЧ

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#201]
**Описание ошибки**
Возникает ошибка при просмотре в редакторе объекта табличной части, содержащей реквизит типа "ХранилищеЗначения".

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запустить базу со встроенной БСП
2. Открыть редактор объекта.
3. Выбрать тип объекта "Справочник.ВерсииФайлов"
4. Перейти на закладку табличных частей.
5. Нажать кнопку "Отображать пустые".

Появится окно с ошибкой следующего содержания:

> Недопустимый тип реквизита. Имя: "Подпись"
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1214)}:	ИзменитьРеквизиты(ДобавляемыеРеквизиты, УдаляемыеРеквизиты);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1170)}:			ОбновитьРедактируемуюТаблицуЗначенийНаСервере(ИмяРеквизита, Адрес);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1915)}:		ОбновитьРедактируемуюТаблицуЗначений(Элементы.ТабличныеЧасти, "РедактируемаяТабличнаяЧасть");
> {ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(63)}:			ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
> {InfostartToolkit ОбщийМодуль.ИТК_ДлительныеОперацииКлиент.Модуль(149)}:		Модуль.ОжидатьЗавершение(ДлительнаяОперация, ОповещениеОЗавершении, ПараметрыОжидания);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1881)}:	ИТК_ДлительныеОперацииКлиент.ОжидатьЗавершение(ДлительнаяОперацияПолучениеТабличнойЧасти, ОповещениеОЗавершении, ПараметрыОжидания);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1176)}:				ЗапуститьПолучениеТабличнойЧастиОбъекта(ТекущиеДанные.Имя);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1148)}:	ОбновитьРедактируемуюТаблицуЗначений(Элементы.ТабличныеЧасти, "РедактируемаяТабличнаяЧасть");
> 
> по причине:
> Недопустимый тип реквизита. Имя: "Подпись"
> 

**Окружение:**

   - Платформа 1С: 8.3.16.1876
   - Имя конфигурации: 1С:ERP. Управление холдингом (3.0.4.4)
   - Язык: ru
   - Операционная система: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))

**Comment by Evg-lylyk** [comment]
Да знаю подобная проблема #168
