### ISSUE TITLE
Выбор групп в редакторе объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#207]
**Описание ошибки**
Нет возможности выбрать группу справочника в редакторе объекта.

**Ожидаемое поведение, если бы ошибки не было**
Ожидается, что редактировать реквизиты группы также можно будет с помощью редактора, т.к. не всегда группы содержат только стандартные реквизиты. Плюс редактором удобно смотреть идентификатор ссылки.

**Comment by Evg-lylyk** [comment]
Вроде проработан этот вариант. Кнопкой "Выбрать"
![Выбор группы кнопкой выбрать](https://user-images.githubusercontent.com/48444742/107030303-33160f00-678f-11eb-8c38-0fc79a2c2ef8.png)
Может у тебя какой особый случай, уточни

**Comment by d-hurricane** [comment]
Способ воспроизведения похоже такой:
* выбрать тип объекта;
* выбрать элемент справочника;
* попытаться выбрать группу.

**Comment by d-hurricane** [comment]
Если первой выбирать именно группу, то проблем действительно не наблюдается.

**Comment by Evg-lylyk** [comment]
У меня так тоже не воспроизводится

**Comment by d-hurricane** [comment]
Пробую на пустой базе. В ней только роль и справочник.

Infostart Toolkit 1.6.3

Платформа: 8.3.16.869 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Конфигурация ()
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: БСП не установлена

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
![2021-02-05_17-55-04](https://user-images.githubusercontent.com/59051827/107036536-9f1e6480-67db-11eb-80d8-4a7588fe5ac6.gif)

**Comment by Evg-lylyk** [comment]
ОК, воспроизвелось в пустой

**Comment by Evg-lylyk** [comment]
Исправлено в 1.6.4
