### ISSUE TITLE
не хватает возможности из подпунктов "Схема" или "Вариант" создать "Запрос" с уже заполненными параметрами для дальнейшего исследование виртуальных таблиц

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#213]

**Comment by BProg-Gladkov** [comment]
Немного уточню:
Для исследования запроса будет удобно если запрос будет создаваться без удаления СКД.
Это позволит одновременно видеть СКД и запрос.

**Comment by Evg-lylyk** [comment]
Думаю сделать так: кнопку добавить запрос для любой ветки, строка запрос будет добавлятся ниже текущей позиции с именем анализируемый запрос скд

**Comment by Evg-lylyk** [comment]
Реализовано в 1.7
