### ISSUE TITLE
Не работает сохранение данных консоли в настройках

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#214]
**Описание ошибки**
Не удается сохранить текущее состояние консоли разработчика в настройках (не в файл). Кнопка сохранения в диалоге не реагирует на нажатия.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль разработчика, подготовить любой запрос.
2. Нажать в главном меню консоли "Данные / Настройка / Сохранить как..."
3. В появившемся диалоговом окне ввести произвольное имя сохраняемой настройки и нажать "Сохранить".
4. Убедиться, что сохранение не происходит: диалог не закрывается, нового элемента в списке сохранений не появляется, при перезапуске консоли сохраненных найти не удается.

**Окружение:**

Infostart Toolkit 1.6.3

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.6.4
