### ISSUE TITLE
Ошибка передачи мутабельного значения при работе с СКД

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#215]
**Описание ошибки**
При попытке сформировать результат отчета при работе с СКД в консоли разработчика, когда активна строка с пользовательскими настройками, возникает ошибка следующего содержания:

> Попытка передачи с клиента на сервер мутабельного значения 1-го параметра метода XMLТекст ().
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(5126)}:		ИТК_КонсольРазработчикаДанныеКлиент.ИзменитьПоле(ЭтотОбъект, Строка, "Текст", ИТК_СКДВызовСервера.XMLТекст(КомпоновщикНастроек.ПользовательскиеНастройки));
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(513)}:	СохранитьИзмененныеДанныеСтроки();
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(2376)}:		ЗагрузитьДанныеВКомпоновщикНастроек(ПолныеДанныеСКД(ТекущаяСтрока));
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(563)}:	ОбновитьЭлементыФормы();
> 
> по причине:
> Попытка передачи с клиента на сервер мутабельного значения 1-го параметра метода XMLТекст ().

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль разработчика.
2. Добавить в дерево данных "Схему компоновки данных".
3. Добавить в подчинение новой СКД "Пользовательскую настройку СКД".
4. Выделив строку пользовательских настроек в дереве данных нажать в главном меню кнопку "Выполнить".
5. Появится окно с сообщение об ошибке, текст которого приведен выше. 

**Окружение:**

Infostart Toolkit 1.6.3

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.6.4
