### ISSUE TITLE
Открывать консоль разработчика в с пустым деревом данных.

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#216]
**Существует проблема**
Всякий раз при открытии консоли разработчика, а также при создании новых данных, в дереве данных по умолчанию содержится элемент типа "Запрос". Если я обращаюсь к консоли не для работы с запросами, а для работы с кодом или СКД, для собственного удобства приходится удалять созданный элемент данных.

**Хотелось бы иметь следующую функциональность**
При открытии консоли разработчика создавать пустое дерево данных. Поведение можно сделать опциональным с помощью глобальных настроек.
Предлагаю также рассмотреть вариант создания нескольких глобальных команд открытия консоли с разным начальным заполнением: с запросом, с СКД или же с кодом. При этом для разных консолей (СКД можно опустить) назначить разные горячие клавиши.

**Comment by Evg-lylyk** [comment]
Понятно, были такие мысли. Сделаем

**Comment by Evg-lylyk** [comment]
Реализовал в 1.9 (пришлось выпилить фичу Восстанавливать последние данные при запуске)
и задумал реализацию #307
