### ISSUE TITLE
Проблема сравнения текстов Монако когда второй текст пустой

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#217]
Отображается как пустой текст, ожидается удаленные строки красным

**Comment by salexdv** [comment]
Вызов **_compare_** c пустым текстом фактически [отключает](https://github.com/salexdv/bsl_console/blob/master/docs/compare.md) режим сравнения. Для корректного поведения, если текст пустой, нужно передать пробел.
Например,
```js
defaultView.compare(' ')
```

**Comment by Evg-lylyk** [comment]
Спасибо, попробую

**Comment by Evg-lylyk** [comment]
Порядок, исправил в версии 1.7
