### ISSUE TITLE
Некорректно форматируется текст запроса после слова "КАК"

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#219]
**Описание ошибки**
В редакторе запроса весь текст, расположенный за ключевым словом "КАК" не форматируется, т.е. не расскрашивается должными цветами.

**Сценарий воспроизведения**
Открыть консоль разработчика. Ввести любой из представленных ниже текстов запроса. Убедиться, что после первой встречи со словом "КАК" все остальные слова в строке будут раскрашены лишь в черный цвет, не смотря на то, что среди них есть форматируемые ключевые слова.

Пример 1. 
```
ВЫБРАТЬ
    ВЫРАЗИТЬ(1 КАК ЧИСЛО(10,0)) КАК Поле1
```
Пример 2.
```
ВЫБРАТЬ
    1 КАК Поле1 ПОМЕСТИТЬ ВТ
```

**Ожидаемое поведение, если бы ошибки не было**
Все ключевые слова запроса должны быть раскрашены вне зависимости от того, располагаются ли они на одной строке со словом "КАК" или нет.

**Окружение:**
Infostart Toolkit 1.6.3

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.7
