### ISSUE TITLE
В каких-то условиях в редакторе Monaco не работают горячие клавиши

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#220]
На сервере разработки (по RDP) не работают горячие клавиши `Ctrl+C`, `Ctrl+Z`.

Условия и как расследовать непонятны. При переключении режима редактора на обычный все сочетания работают.

> Infostart Toolkit 1.6.4
> 
> Платформа: 8.3.15.1830 (Windows x86-64)
> Режим БД: клиент-серверный
> 
> Конфигурация:
> Управление холдингом, редакция 3.1 (3.1.4.9)
> Основной режим запуска: Управляемое приложение
> Режим совместимости: Версия8_3_14
> Версия БСП: 3.1.2.541
> 
> Клиент:
> ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
> Язык: ru
> Режим запуска: Управляемое приложение
> Режим защиты от опасных действий выключен.
> Прав администратора нет.

На своём локальном компе на 8.3.15 x64 всё работает.

**Comment by Evg-lylyk** [comment]
Проблема платформы, в редакторе монако В некоторых платформах не работают, выход ставить более свежии версии платформы или пользоваться контектекстным меню
