### ISSUE TITLE
Вылетает сеанс установке в табличном документе Уровень группировки ...

### ISSUE THREAD

**Issue by Magogui** [infostart-hub/toolkit#221]
**Описание ошибки**
При попытке группировки результата запроса в табличном поле вылетает сеанс

**Сценарий воспроизведения**
Нажимаю на уровни группировок в результате запроса

   - Платформа 1С: 1С:Предприятие 8.3 (8.3.18.1208)*
   - Имя конфигурации: Ерп*
   - Язык: Ру*
   - Операционная система: Win server 2016*

- Типовая или не типовая конфигурация ? - Нет
- Включен ли режим защиты от опасных действий - Нет

![Вылет](https://user-images.githubusercontent.com/17365311/107917642-530cb600-6f79-11eb-9089-a19a73bb055a.png)

**Comment by Magogui** [comment]
Было на версии 1.5.7, также наблюдается и на 1.6.4 версии расширения

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести
там простой код:
Уровень = ИТК_Строки.ИндексИдентификатора(Команда.Имя) - 1;
ТабличныйДокументРезультат.ПоказатьУровеньГруппировокСтрок(Уровень);

Нужно больше информации
Попробуйте на более стабильной платформе
