### ISSUE TITLE
Неверно вычисляется строка с ошибкой в коде

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#222]
**Описание ошибки**
В случае, если при исполнении некоторого кода в консоли разработчика возникает ошибка, связанная с выполнением запроса, неверно определяется место возникновения ошибки. В этом случае "красной" строкой всегда считается первая строка кода. Аналогичное поведение наблюдается и при работе с объектом "СхемаЗапроса", когда допускаются ошибки при конструировании текста запроса.

**Сценарий воспроизведения**
Открыть консоль разработчика. Добавить в дерево данных элемент типа "Код". Ввести в поле кода следующий текст:

> Запрос = Новый Запрос;
> Запрос.Текст = "ВЫБРАТЬ 1 ИЗ 123";
> Результат = Запрос.Выполнить().Выгрузить();

Нажать кнопку "Выполнить". Убедиться, что красным цветом будет выделена не третья строка, где реально возникла ошибка выполнения запроса, а первая.

**Окружение:**
Infostart Toolkit 1.6.3

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
После дополнительной проверки выяснил, что проблема касается не только запросов. Вот еще код, позиция ошибки в котором неверно диагностируется:

> Стр = Новый Структура;
> Сообщить(Стр.НесуществующееПоле);

**Comment by Evg-lylyk** [comment]
Исправлено в 1.7
