### ISSUE TITLE
Отображение результата выполнение кода в отдельном окне

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#223]
**Существует проблема**
В версии 1.6.3 инструментов есть возможность просмотреть все сообщения пользователю в отдельной таблице формы результата выполнения кода. Однако каждая строка таблицы отображает лишь первую строку текста сообщения, что доставляет неудобство при выводе многострочного текста в сообщениях.

**Хотелось бы иметь следующую функциональность**
Открывать полный текст сообщения в отдельном окне, например, двойным кликом мыши.

**Comment by Evg-lylyk** [comment]
Реализовано в 1.7
