### ISSUE TITLE
В редакторе Монако пропадает отображение текста запроса, конструктор при этом запрос продолжает открывать

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/toolkit#224]
**Описание ошибки**

При редактировании текста запроса в редакторе Монако он подвисает и перестает не только реагировать, но и отображать текст запроса (выглядит так, как будто он пропал), текстовый курсор пропадает тоже  и ничего сделать с этим нельзя, только перезапуск.

При этом выглядит так, как будто я текст запроса потерял, но если открыть конструктор запроса - текст в нем остался.

К сожалению, воспроизводится нестабильно, у меня возникало уже трижды, дважды на сложных, сегодня на очень простом запросе (буквально 15 строк, включая пустые), поэтому решил написать.

**Сценарий воспроизведения**

Включен редактор Монако в редакторе запросов.

Набираю простейший текст запроса `Выбрать Ссылка из Документ.ЗаказКлиента` и нажимаю "Конструктор запроса" (так делаю, т.к. мне так быстрее сделать, чем искать в дереве заказ и кликать мышкой).

Далее дорабатываю конструктором запрос, нажимаю "ОК".
Текст запроса попадает в редактор.

В редакторе начинаю двигать клавишами управления курсором (стрелки), конкретно в текущей ситуации, я двигал курсор вниз, чтобы перепроверить условие запроса, которое оказалось за нижней границей редактора и я хотел проскролить к области ГДЕ запроса.

В какой-то момент нажатия клавиши "Стрелка вниз" весь текст запроса пропадает.

**Ожидаемое поведение, если бы ошибки не было**

Ничего не должно пропадать.

**Скриншоты**

Вот так выглядит "подвисший" редактор Монако (выглядит, как будто его вообще нет или он не проинициализировался):

![2021-02-15_16-04](https://user-images.githubusercontent.com/1042299/107945461-1789e000-6fa9-11eb-9a76-9a320b597bd1.png)

При этом в поле ввода текста запроса я ничего сделать не могу: не курсор подвинуть (он пропал), ни текст написать снова. По маркеру текущей строки рядом с полосой скроллбара при этом видно, что я доскролил до середины текста запроса.

Все другие элементы управления Тулкита могу кликать, могу открыть конструктор запроса, выполнить запрос и т.п.

**Окружение:**
```
Infostart Toolkit 1.6.3

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.4.13.103)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.362

Клиент:
ОС: Windows x86 (Microsoft Windows 8.1 version 6.3  (Build 9600))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Спасибо, Александр.
Буду разбираться

**Comment by Evg-lylyk** [comment]
Если у тебя воспроизводится сделай пожалуйста gif
Мне сожалению не удается воспроизвести, буду разбираться
Написал автору BSL_Console: Он говорит да есть такая проблема отловить пока не удается, посмотрит.

**Comment by Evg-lylyk** [comment]
В версии 1.7.6 это должно исправится, но 100% уверенности нет. Если снова воспроизведется восстанови задачу
