### ISSUE TITLE
Назначение собственных горячих клавиш в разделе Infostart Toolkit

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#225]
**Существует проблема**
В настоящий момент для общих команд раздела "Infostart Toolkit" доступен вызов горячими клавишами лишь трех инструментов, при этом сами комбинации клавиши предопределены.

**Хотелось бы иметь следующую функциональность**
Было бы здорово иметь возможность самостоятельно назначать собственные комбинации клавиш для наиболее востребованных мною инструментов. 

**Дополнительный контекст**
Т.к. речь идет об общих командах конфигурации, и в пользовательском режиме изменение горячих клавиш недоступно, было бы удобно использовать для назначения клавиш Установщик инструментов. Как я понимаю, совместимость с различными конфигурациями обеспечивается путем вырезания из исходников поставки ненужных модулей и объектов с последующей сборкой готового расширения. Соответственно здесь же можно "подсунуть" выбранные мной в обработке Установщика горячие клавиши для общих команд раздела Инструментов.

**Comment by Evg-lylyk** [comment]
С версии 1.7. установщик возвращается к установке готовых cfe при таком подходе меньше непонятных проблем.
Логично конечно чтобы это было доступно в "Настройки действий", но от 1С врятли дождемся

Варианты:
1. Могу рассмотреть предложенные и назначить горячие клавиши предопределенно 
2. Вы можете самостоятельно модифицировать расширение, сохранить и при обновлении объединять общие команды

Сейчас еще есть момент чтобы комбинация клавиш писалась в названии команды я вношу общую команду и ей прописываю наименование
