### ISSUE TITLE
Отображать пустые значения бледным

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#227]
Сейчас в результирующей таблице пустые значения выводятся жирным шрифтом:  
![Пустые жирным](https://user-images.githubusercontent.com/2562878/108324371-e0017a80-71d8-11eb-8e8c-836959cab90b.png)

Хочется, чтобы пустые значения отображались совсем ненавязчиво: серым и не жирным, как-то так:
![image](https://user-images.githubusercontent.com/2562878/108325441-1f7c9680-71da-11eb-9c22-e6dc67fe1f73.png)

**Comment by Evg-lylyk** [comment]
Хорошая мысль, учту. NULL наверно не так тускло обычным шрифтом

**Comment by Evg-lylyk** [comment]
Реализовано с версии 1.7

**Comment by shureek** [comment]
> Хорошая мысль, учту. NULL наверно не так тускло обычным шрифтом

Лучше всё-таки не обычным. Чтобы `Null` отличалось от строки `"<NULL>"`
