### ISSUE TITLE
Ошибка открытия файла после экспорта в MXL

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#228]
При экспорте результата запроса в файл MXL если поставить галку "Открыть после сохранения" возникает ошибка:

> Файл не обнаружен 'C:\Users\raykova_I\Documents\Результат.mxl'

![Экспорт](https://user-images.githubusercontent.com/2562878/108336783-79368e00-71e5-11eb-9532-44eceeecac94.png)

Видимо, это происходит из-за того, что файл сохраняется на клиенте, а читается на сервере:

> Файл не обнаружен 'C:\Users\raykova_l\Documents\Результат.mxl'
> {InfostartToolkit ОбщийМодуль.ИТК_ТабличныйДокумент.Модуль(207)}:	Результат.Прочитать(ИмяФайла);
> {InfostartToolkit ОбщийМодуль.ИТК_ТабличныйДокументВызовСервера.Модуль(158)}:	Возврат ИТК_ТабличныйДокумент.ПрочитатьИзФайла(ИмяФайла);
> {InfostartToolkit ОбщийМодуль.ИТК_ТабличныйДокументКлиент.Модуль(365)}:		ТабличныйДокументФайла = ИТК_ТабличныйДокумент**ВызовСервера**.ПрочитатьИзФайла(ИмяФайла);

**Comment by Evg-lylyk** [comment]
Исправлено в 1.7
