### ISSUE TITLE
Не отображается ни один параметр сеанса

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#229]
**Описание ошибки**
Открываю инструмент и в списке пусто

**Скриншоты**
если применимо, приложите скриншоты
![image](https://user-images.githubusercontent.com/6578710/108508106-f9332580-72c3-11eb-967c-067619ed60b7.png)
![image](https://user-images.githubusercontent.com/6578710/108508142-07814180-72c4-11eb-8332-8b7a47e05c7d.png)

**Окружение:**

  Infostart Toolkit 1.7.0

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.6.98)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.7.1
