### ISSUE TITLE
Кнопка "Записать" в редакторе параметров сеанса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#233]
**Описание ошибки**
Сразу при открытии редактора параметров сеанса кнопка записи изменений имеет заголовок "<Записать>".

**Ожидаемое поведение, если бы ошибки не было**
Заголовок должен быть без кавычек, т.е. "Записать".

**Окружение:**
Версия 1.7.1

**Comment by Evg-lylyk** [comment]
Исправлено в 1.7.2
