### ISSUE TITLE
Невозможно выделить ячейки результата с прокруткой таблицы

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#235]
В результате запроса не получается выделить ячейки результата с прокруткой таблицы.

Выглядит это так:  
[![Невозможно выделить ячейки с прокруткой](https://img.youtube.com/vi/AdNRTT6QOxc/0.jpg)](https://www.youtube.com/watch?v=AdNRTT6QOxc)

**Comment by shureek** [comment]
Возможно, проблема из-за раскраски текущей строки, но не нашёл в настройках отключения этой опции

**Comment by Evg-lylyk** [comment]
Понял, попытаюсь решить, пока не понимаю из- за чего такое
Сейчас как обход выделить снизу

**Comment by shureek** [comment]
> Сейчас как обход выделить снизу

Снизу тоже пробовал — не получилось. Могу тоже видео сделать

**Comment by Evg-lylyk** [comment]
Тогда подожди решения.
Снизу у меня получается.

**Comment by Evg-lylyk** [comment]
Действительно проблема была функции выделения активной строки
Такое поведение при установке ЦветФона области
Сделал опцию отключения этой функции
Решено в версии 1.8
