### ISSUE TITLE
Сделать удобный выбор предопределенных данных в консоли разработчика

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#236]
Очень удобно в консоли разработчика вставлять предопределенные значения. Но хотелось бы этот функционал ещё улучшить:

добавить возможность выбора предопределенного элемента из таблицы с отображением доп. колонок (возможно, из формы выбора).

**Пример**

Выбираю бух. счет:  
![image](https://user-images.githubusercontent.com/2562878/109276442-12d5ef00-7827-11eb-9e2b-b0ac5ca31aab.png)

и не вижу кода счета, не помню как он называется, приходится лезть в Конфигуратор

**Comment by Evg-lylyk** [comment]
Хорошая мысль, реализую

**Comment by Evg-lylyk** [comment]
Реализовано в 1.7.4
Поиск по содержит, представление плана счетов с кодом
![Screenshot_2](https://user-images.githubusercontent.com/48444742/109519074-f2729280-7abb-11eb-89a5-c4408bed27e3.png)
