### ISSUE TITLE
Не работает контекстная подсказка по предопределенным элементам (Монако)

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#243]
**Описание ошибки**
В редакторе запроса Монако при вводе имени предопределенного возникает программная ошибка.

**Сценарий воспроизведения**
Запустить демо базу БСП. Открыть консоль разработчика и в поле текста запроса начать вводить запрос:
```
ВЫБРАТЬ
    ЗНАЧЕНИЕ(Справочник.ВидыКонтактнойИнформации.
```
После ввода последнего символа - точки - появится ошибка с текстом:

> Несоответствие типов (параметр номер '1')
> {InfostartToolkit ОбщийМодуль.ИТК_Метаданные.Модуль(434)}:		Результат.ЗагрузитьЗначения(ИменаПредопределенных);
> {InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаПовтИсп.Модуль(207)}:			Предопределенные = ИТК_Метаданные.Предопределенные(ОбъектМетаданных);
> {InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаПовтИсп.Модуль(8)}:		ОписаниеМетаданных = ОписаниеОбъектаМетаданных(ТипОбъектов, ОбластьОбновления);
> {InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаВызовСервера.Модуль(5)}:	Возврат ИТК_РедакторКодаПовтИсп.ОбработкаСобытияПолученияМетаданных(Метаданные);
> {InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(581)}:		Результат = ИТК_РедакторКодаВызовСервера.ОбработкаСобытияПолученияМетаданных(ПараметрыСобытия);
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(480)}:	ИТК_РедакторКодаКлиент.ОбработкаСобытий(ЭтотОбъект, Элемент, ДанныеСобытия, Модифицированность, ОписаниеОповещения);
> 
> по причине:
> Несоответствие типов (параметр номер '1')

**Ожидаемое поведение, если бы ошибки не было**
После ввода точки ожидается появление контекстного меню с выбором имени предопределенного элемента для справочника контактной информации.

**Окружение:**
Infostart Toolkit 1.7.5

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.7.6
