### ISSUE TITLE
Контекстная подсказка по аргументам функции ДАТАВРЕМЯ

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#244]
**Описание ошибки**
В редакторе запроса Монако некорректно отображается контекстная подсказка для второго аргумента (месяц). Фокус съезжает на подсказку к третьему аргументу (ДеньМесяца), при том выделяя не все слово целиком, а лишь его часть.

**Сценарий воспроизведения**
Открыть консоль разработчика и в поле ввода текста запроса начать вводить:
```
ВЫБРАТЬ
    ДАТАВРЕМЯ(1,
```
После установки запятой контекстная подсказка по аргументам функции будет отображаться некорректно (см. снимок экрана).

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/109814859-ce948580-7c50-11eb-83e6-10ad6533ef38.png)

**Окружение:**
Infostart Toolkit 1.7.5

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 1.7.6
