### ISSUE TITLE
Контекстная подсказка по аргументам функции ПОДСТРОКА

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#245]
**Описание ошибки**
В редакторе запроса Монако некорректно отображается контекстная подсказка для первого аргумента (ИсходнаяСтрока) функции ПОДСТРОКА - нет фокуса.

**Сценарий воспроизведения**
Открыть консоль разработчика и в поле ввода текста запроса начать вводить:
```
ВЫБРАТЬ
    ПОДСТРОКА("Коробка"
```
Сразу после ввода открывающей скобки контекстная подсказка по аргументам функции будет отображаться некорректно (см. снимок экрана).

**Ожидаемое поведение, если бы ошибки не было**
Первый аргумент в подсказке должен быть выделен жирным шрифтом и подчеркнут.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/109816605-bfaed280-7c52-11eb-91ee-87133b031ad6.png)

**Окружение:**
Infostart Toolkit 1.7.5

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0 (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 1.7.6
