### ISSUE TITLE
Контекстная подсказка в строковых литералах кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#246]
**Описание ошибки**
В редакторе кода Монако на встроенном языке 1С внутри строковых литералов работает контекстная подсказка аналогично тому, как она работает вне литерала. Это несколько затрудняет ввод кода.

**Сценарий воспроизведения**
Открыть консоль кода. Добавить элемент в дереве данных типа "Код". В поле ввода кода ввести следующий текст:
```bsl
Запрос = Новый Запрос;
Запрос.Текст = 
"Выбрать Знач
```
Убедиться, что появилась контекстная подсказка для слова "Знач", но контекст выбран неверно, т.к. это текст запроса, а не метод модуля.

**Ожидаемое поведение, если бы ошибки не было**
В самом простом случае ожидается, что контекстная подсказка для строковых литералов будет отключена вовсе. В лучшем случае - будет определено, что это контекст запроса и начнет работать подсказка для языка запросов.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/109817779-1e288080-7c54-11eb-9191-f34815269715.png)

**Окружение:**
Infostart Toolkit 1.7.5

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.264

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 1.7.7
