### ISSUE TITLE
Дополнительные колонки списка регл. заданий (БСП)

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#248]
**Существует проблема**
Благодаря БСП включение и отключение некоторых типовых регламентных заданий зависит от определенных функциональных опций, а также от признака блокировки работы с внешними ресурсами. Однако получить такую информацию о зависимостях можно только анализируя программный код.

**Хотелось бы иметь следующую функциональность**
Будет здорово, если в списке регламентных заданий будет доступен вывод информации о том, работает ли задание с внешними ресурсами (в первую очередь) и от каких функциональных опций зависит работа задания (в последнюю очередь).

**Дополнительный контекст**
Для БСП 3.1 всю необходимую информацию можно получить методом:
`ЗависимостиЗаданий = РегламентныеЗаданияСлужебный.РегламентныеЗаданияЗависимыеОтФункциональныхОпций()`

**Comment by Evg-lylyk** [comment]
Реализовал в 1.8
По умолчанию эти колонки скрыты
