### ISSUE TITLE
Неверно форматируется строковый литерал в консоли запросов

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#259]
**Описание ошибки**
Некорректно форматируется текст запроса в случае, когда в одной строке дважды встречается строковый литерал. Форматер считает, что все символы между ними также являются частью строкового литерала.

**Сценарий воспроизведения**
Открыть консоль запросов и ввести следующий текст запроса:
```
ВЫБРАТЬ
    ЕСТЬNULL(NULL, "пусто") <> "пусто" КАК Поле
```
Убедиться, что текст между двумя строковыми литералами `"пусто"`, а именно закрывающая скобка и знак неравенства, также раскрашиваются, как и строковые литералы.

**Скриншоты**
![2021-03-23_23-32-29](https://user-images.githubusercontent.com/59051827/112199587-227f0280-8c30-11eb-85ab-afd481e35974.png)

**Окружение:**
Infostart Toolkit 1.7.7

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.8
