### ISSUE TITLE
Сохранение курсора в редакторе запроса, метки перехода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#260]
**Существует проблема**
При работе с большим текстом в редакторе запроса (Монако) есть неудобства навигации по тексту. Во-первых, нет возможности (или они мне неизвестны) установить закладки для быстрого перехода к нужной позиции. Во-вторых, при сохранении запроса в файл текущее положение курсора теряется, он устанавливается в начало текста. Из-за чего при частом сохранении приходится всякий раз проматывать большой текст к месту последних правок для продолжения работы над текстом.

**Хотелось бы иметь следующую функциональность**
* Больше возможностей для навигации при редактировании текста запроса в редакторе Монако. Если вносятся изменения параллельно в несколько операторов запроса, было бы удобно использовать закладки в тексте. К слову, обычный текстовый редактор поддерживает данную функциональность.
* Необходимо сохранять текущую позицию курсора при сохранении запроса в файл. При редактировании большого запроса часто инстинктивно горячими клавишами сохраняю результат. И в последствии страдаю от необходимости вернуться к месту последних правок, дабы продолжить работу.

**Дополнительный контекст**
Infostart Toolkit 1.7.7
Платформа: 8.3.16.1876 (Linux x86-64)

**Comment by Evg-lylyk** [comment]
Реализовано в 1.8 восстановление выделения
Метки может в будущем в Монако такого по умолчанию нет, в 1С это не реализовать
