### ISSUE TITLE
Поле поиска при редактировании типа колонки

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#261]
**Описание ошибки**
При описании внешнего источника в редакторе запроса после повторного открытия диалога выбора типа колонки пропадает поле поиска объектов метаданных по подстроке.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль разработчика.
2. При редактировании запроса перейти на закладку "Внешние источники". Добавить новый источник.
3. Кликнув на гиперссылку "<Таблица значений>" в строке нового источника открыть диалог его редактирования.
4. Нажать на кнопку "Добавить..." для добавления новой колонки источника.
5. В поле "Тип" нажать на кнопку выбора "..." для открытия диалога выбора типа новой колонки.
6. Убедиться, что диалог выбора типа **содержит** поле поиска.
7. Выбрать произвольный тип, например число, и нажать "Ок".
8. Вновь нажать на "..." поля "Тип" для редактирования ранее выбранного типа.
9. Убедиться, что повторно открытое окно выбора типа **не содержит** поле поиска.

**Ожидаемое поведение, если бы ошибки не было**
Поле поиска объектов метаданных по подстроке должно присутствовать всегда.

**Окружение:**
Infostart Toolkit 1.7.7

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 1.8
