### ISSUE TITLE
Диалог выбора типа позволяет устанавливать несколько флажков для несоставного типа

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#262]
**Описание ошибки**
Если в диалоге выбора типа воспользоваться поиском по подстроке, обнаружиться возможность выбрать несколько элементов результата поиска (установить флажки) даже в случае, если признак типа "Составной" сброшен. При нажатии на "Ок" будет выбран один из отмеченных типов, ошибки не будет.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль разработчика для редактирования запроса. Добавить новый внешний источник и перейти к его редактированию.
2. Добавить новую колонку внешнего источника, начать редактировать тип колонки.
3. Не устанавливать флажок "Составной". В поле поиска ввести любую подстроку, которая покажет в результате несколько подходящих вариантов. Например, "номенкл" в конфигурации ERP (УТ, КА).
4. Когда отобразиться результат поиска попытаться поставить флажки выбора всем найденным вариантам. Убедиться, что при установке флажков ранее установленные не сбрасываются, хотя тип не составной.

**Ожидаемое поведение, если бы ошибки не было**
Также, как и без отбора по подстроке, в один момент времени флажок должен быть установлен только у одного элемента, т.к. редактируется не составной тип.

**Скриншоты**
![2021-03-24_12-03-30](https://user-images.githubusercontent.com/59051827/112268587-03688b00-8c99-11eb-9522-5dcf5c234534.png)

**Окружение:**
Infostart Toolkit 1.7.7

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.8
