### ISSUE TITLE
Переименование параметра запроса приводит к потере его значения

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#264]
**Описание ошибки**
При переименовании параметра запроса с помощью соответствующей команды контекстного меню теряется введенное ранее значение параметра. Оно сохраняется за прежним именем параметра, в чем можно убедиться переименовав параметр обратно.

**Сценарий воспроизведения**
Открыть консоль разработчика. Ввести следующий текст запроса:
```
ВЫБРАТЬ
   &А КАК Поле
```
Убедиться, что на закладке параметров появился новый параметр "А". Установить ему некоторое значение, например строку "тест".
Переименовать параметр с помощь команды контекстного меню "Переименовать...", задав ему новое имя "Б". Убедиться, что в тексте запроса параметр также переименован. При этом ранее введенное значение параметра "тест" пропало, параметр "Б" имеет пустое значение.

**Ожидаемое поведение, если бы ошибки не было**
При переименовании параметра его значение должно сохраняться.

**Окружение:**
Infostart Toolkit 1.7.7

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.8
