### ISSUE TITLE
Неверно форматируется содержащий число идентификатор в запросе

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#265]
**Описание ошибки**
В редакторе запроса (Монако) неверно форматируется поле таблицы, если само поле содержит цифры, а псевдоним таблицы состоит из одного символа. В этом случае цифры внутри идентификатора поля форматируются как числа, а не как часть имени поля.

**Сценарий воспроизведения**
Открыть редактор запроса (Монако). Ввести следующий текст запроса:
```
ВЫБРАТЬ
    Т.Поле1Пустое КАК Поле1
ИЗ
    Т КАК Т
```
Убедиться, что внутри имени поля "Поле1Пустое" цифра "1" имеет отличный от окружающих ее символов цвет.

**Ожидаемое поведение, если бы ошибки не было**
Все символы поля "Поле1Пустое" должны быть одного цвета, вне зависимости от псевдонима таблицы.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/112433951-c4a00700-8d64-11eb-8c1f-f1fa94c8834d.png)

**Окружение:**
Infostart Toolkit 1.7.7

Платформа: 8.3.16.1876 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.8
