### ISSUE TITLE
Не открываются зависимые формы через "Все функции"

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#266]
**Описание ошибки**
Если основная форма объекта метаданных имеет свойство "РежимОткрытияОкна" отличное от "Независимый", то такая форма объекта не откроется с помощью диалога "Все функции" инструментов разработчика.

**Сценарий воспроизведения**
1. На демо базе БСП 3.1 запустить диалог "Все функции" из раздела Infostart Toolkit (Alt+A).
2. Найти в ветке обработок "Универсальный обмен данными в формате XML". 
3. Дважды кликнуть на обработку для выбора.
4. Убедиться, что вопреки ожиданиям диалог "Все функции" закроется, но форма универсального обмена открыта не будет.

**Ожидаемое поведение, если бы ошибки не было**
Ожидается, что форма объекта метаданных будет открыта вне зависимости от ее свойства "РежимОткрытияОкна".

**Окружение:**
Infostart Toolkit 1.7.7

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 1.8.
Дополнил ОткрытьФорму
	ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы**, , , , , , РежимОткрытияОкнаФормы.Независимый**);
