### ISSUE TITLE
При открытии "Всех функций" фоном заполнять дерево метаданных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#267]
**Существует проблема**
Преимуществом нынешней реализации диалога "Все функции" перед платформенным является быстрый запуск окна за счет отложенного чтения объектов метаданных. Если разработчик пользуется полем поиска, то метаданные читаются перед первым поиском объекта по подстроке, что в конечном счете нивелирует преимущество быстрого открытия окна: вместо долго открытия диалога долго осуществляется поиск.

**Хотелось бы иметь следующую функциональность**
Разработчикам, что пользуют строку поиска чаще, чем разворачивают нужную ветку дерева метаданных и самостоятельно ищут в ней нужный объект, хотелось бы получить преимущество в скорости поиска за счет фонового чтения дерева объектов метаданных при открытии "Всех функций". Для этого есть небольшой запас времени от момента открытия "Всех функции" и до осуществления поиска, т.е. пока разработчик набирает текст в поле поиска.

**Дополнительный контекст**
Infostart Toolkit 1.7.7

**Comment by Evg-lylyk** [comment]
Посмотрел основное время уходит на добавление строк и обновление элементов, в ERP 5000 строк добавляется. Повторный поиск уже гораздо быстрее.
Добавить в фоновом я не могу т.к. там нет контекста формы. На счет типового там такое ощушение что форма просто не закрывается, а как то скрывается, она даже последнее положение открывает причем мгновенно. Проблему понял на искать решение.

**Comment by Evg-lylyk** [comment]
Оптимизировал, добавил кэши коллекций метаданных теперь развертывание веток повторно будет проходить быстрее.
Оптимизировал поиск по подобию для запросов с несколькими словами "поз номенкл"
Это затрагивает все подобные поиски (Подписки на события, Все функции, Форму выбора типа).
Ускорилось значительно, но все еще с задержками. Для все функции есть мысль сделать отдельное для 15-16 платформы
с учетом #88
