### ISSUE TITLE
Падает платформа при сворачивании уровней в результате запроса

### ISSUE THREAD

**Issue by LkMaksimka** [infostart-hub/toolkit#268]
**Описание ошибки**
Падает платформа при сворачивании уровней в результате запроса

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Формируем любой запрос
2. Выводим результат запроса с отдельном окне
3. Кликаем правой кнопкой мышки и выбираем "Уровень1 (Свернуть все)"
4. Падает платформа
![GIF](https://user-images.githubusercontent.com/23025375/113662951-c8f7e880-96b1-11eb-8db3-dad03ea2c68b.gif)

**Окружение:**

Infostart Toolkit 1.7.8

Платформа: 8.3.17.1851 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.6.124)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.417

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru_RU
Режим запуска: Управляемое приложение

<!-- **Дополнительный контекст**

- Типовая 
- Включен режим защиты от опасных действий

**Comment by Evg-lylyk** [comment]
Установил платформу 8.3.17.1851, ERP 2.5.6.124б попробовал нет ошибки. Возможно дело в клиент-сервер
Мне не удается воспроизвести, прошу вас попытаться разобраться.
Как с этим еще бороться?! не знаю

**Comment by LkMaksimka** [comment]
Добрый день, 
падает вот тут 

> ОбщийМодуль.ИТК_ТабличныйДокументКлиент.Модуль : 167 : 
ИТК_ТабличныйДокументКлиент.КомандаПоказатьУровеньГруппировокСтрок(ТабличныйДокумент, Команда)
[21040708.log](https://github.com/infostart-hub/toolkit/files/6269130/21040708.log)

**Comment by Evg-lylyk** [comment]
Спасибо с этой информации все нашел, исправление будет в ближайщем обновлении
