### ISSUE TITLE
Неинформативное сообщение при ошибке создания временных таблиц из параметров

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#271]
При отладке запросов типовых конфигураций часто возникают ошибки создания временных таблиц из-за некоторых типов их колонок (ОписаниеТипов и т. п.). В этих случаях нет возможности определить из-за какой ВТ произошёл сбой:

> {(63, 1)}: Тип не может быть выбран в запросе  
> <<?>> ТипЗначения  
> {InfostartToolkit ОбщийМодуль.ИТК_Запрос.Модуль(1329)}:	Запрос.Выполнить();

Было бы удобно, если бы сообщалось имя временной таблицы, из-за которой произошёл сбой. Как-то так:

> Ошибка создания временной таблицы ВидыСубконто:  
> {(63, 1)}: Тип не может быть выбран в запросе  
> <<?>>ТипЗначения:  
> "ТипЗначения"

ИТК 1.7.7

**Comment by Evg-lylyk** [comment]
Поработал с данный проблемой в 1.8.2
Спасибо за код, переработал и внес
