### ISSUE TITLE
Сохранение вариантов из консоли с помощью функционала "Файлы"

### ISSUE THREAD

**Issue by Untru** [infostart-hub/toolkit#272]
**Существует проблема**
В данный момент с консолью отчетов мы работаем как на сервере так и через тонкий клиент с других компьютеров, для того что бы работать со всеми отчетами файл настройки необходимо сохранять на разных компьютерах, что не удобно, особенно связи с тем что этот файл постоянно дорабатывается

**Хотелось бы иметь следующую функциональность**
Добавить функционал для баз основанных на бсп. "Файлы" 
Добавить меню :
Данные > Файл > Сохранить в базе 
Данные > Файл > Открыть из базы
Сам файл mcr сохранять в справочнике Файлы. 

Так же для удобства при  запуске консоли можно проверять наличие бсп в базе, и в случае отсутствия эти кнопки не отображать

Возможно для универсальности можно добавить объект свой в расширение, но это спорное решение

**Comment by Untru** [comment]
Пробовали делать через сохранение настроек, на версии 1.8.2 ошибка
при открытии от других пользователей
https://prnt.sc/11snxis

**Comment by Evg-lylyk** [comment]
Проверил, загрузилось. Нужно больше подробностей.

**Comment by Evg-lylyk** [comment]
Не пробовали?. Мне не удается обнаружить проблему, предполагаю что она может быть связана с правами

**Comment by Untru** [comment]
Повторить не удалось. сейчас все отрабатывает как положено.
