### ISSUE TITLE
Добавить альтернативу сохранения запроса при отладке

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#275]
**Существует проблема**
Требуется разобрать ошибки проведения документа в ERP, где таблицы движений формируются результатом выполнения единого запроса. Запрос формируется динамически, необходимо получить его в режиме отладки. Однако есть препятствия:
* сохранение запроса в настройках не подходит, т.к. есть транзакция, которая откатывается;
* сохранение в файл не подходит, т.к. нет файловой шары.

В качестве способа обхода пришлось воспользоваться типовой консолью запросов:
* в режиме отладки выполнить метод `ОбщегоНазначения.ЗапросВСтрокуXML`;
* скопировать результат метода (функции) в буфер обмена и вставить его в типовую консоль;
* сохранить запрос типовой консоли в файл (q1c);
* открыть сохраненный файл уже в консоли Infostart Toolkit.

**Хотелось бы иметь следующую функциональность**
Для описанного мной случая необходимо иметь альтернативу сохранения запроса в настройках и в файл при отладке. Например, иметь возможность получить сериализованный запрос обычной строкой (аналогично `ОбщегоНазначения.ЗапросВСтрокуXML`). Либо добавить возможность использовать результат функции `ОбщегоНазначения.ЗапросВСтрокуXML` непосредственно в консоли разработчика, не прибегая к типовой консоли.

**Дополнительный контекст**
Infostart Toolkit 1.7.7

**Comment by Evg-lylyk** [comment]
Реализовано в 1.9 (проверь пожалуйста как будет релиз)
