### ISSUE TITLE
Расширение устанавливается, но после перезапуска ошибка

### ISSUE THREAD

**Issue by artbear** [infostart-hub/toolkit#277]
**Описание ошибки**
```
Платформа: 1С:Предприятие 8.3 (8.3.18.1289)
Конфигурация: Инфоконф (2.1.3.1)
Режим: Файловый (без сжатия)
Приложение: Тонкий клиент
Локализация: Информационная база: русский (Россия), Сеанс: русский (Россия)
Вариант интерфейса: Такси

Ошибки:
--------------------------------------------------------------------------------
27.04.2021 19:39:52
InfostartToolkit (1.8.3): Критичная: Не найден объект ОбщийМодуль.ПодключаемыеКоманды
```

Пробовал как на 1.8.0, так и на 1.8.3

Конфигурация самописная, в ней добавлена базовая функциональность БСП

**Comment by Evg-lylyk** [comment]
БСП интегрирована без модуля ПодключаемыеКоманды
В версии 1.8.4 (выйдет сегодня) доработал чтобы установщик проверял наличие модуля и ставил версию без функционала БСП.
ИМХО лучше интегрировать подключаемые команды полезный функционал БСП
