### ISSUE TITLE
Поле не найдено

### ISSUE THREAD

**Issue by Wronglane** [infostart-hub/toolkit#278]
(20,2) Ошибка обработки представления... Поле не найдено(Субконто2)

Эта ошибка возникает, если в окно текст запроса помещаю текст, который взят из типовой Бухгалтерии 3.0:

ВЫБРАТЬ
	ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто1 КАК Справочник.Контрагенты) КАК Контрагент,
	ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто2 КАК Справочник.ДоговорыКонтрагентов) КАК Договор,
	ХозрасчетныйОстатки.Субконто3 КАК ДокументРасчетов,
	ХозрасчетныйОстатки.СуммаОстатокКт КАК Сумма,
	ХозрасчетныйОстатки.ВалютнаяСуммаОстатокКт КАК ВалютнаяСумма,
	ХозрасчетныйОстатки.Организация КАК Организация,
	ХозрасчетныйОстатки.Валюта КАК Валюта,
	ВЫБОР
		КОГДА ХозрасчетныйОстатки.Субконто3 ССЫЛКА Документ.ПоступлениеТоваровУслуг
				И ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто3 КАК Документ.ПоступлениеТоваровУслуг).СчетНаОплатуПоставщика <> ЗНАЧЕНИЕ(Документ.СчетНаОплатуПоставщика.ПустаяСсылка)
				И ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто3 КАК Документ.ПоступлениеТоваровУслуг).СчетНаОплатуПоставщика.Проведен
				И (СтатусыДокументов.Статус ЕСТЬ NULL
					ИЛИ СтатусыДокументов.Статус В (ЗНАЧЕНИЕ(Перечисление.СтатусОплатыСчета.НеОплачен), ЗНАЧЕНИЕ(Перечисление.СтатусОплатыСчета.ОплаченЧастично)))
			ТОГДА ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто3 КАК Документ.ПоступлениеТоваровУслуг).СчетНаОплатуПоставщика
		ИНАЧЕ ЗНАЧЕНИЕ(Документ.СчетНаОплатуПоставщика.ПустаяСсылка)
	КОНЕЦ КАК СчетНаОплату
ПОМЕСТИТЬ ОстаткиПоДокументамРасчетов
ИЗ
	РегистрБухгалтерии.Хозрасчетный.Остатки(
			&ГраницаОстатков,
			Счет В (&СчетаДолговПоДокументам),
			&ВидыСубконтоРасчетов,
			ВЫРАЗИТЬ(Субконто2 КАК Справочник.ДоговорыКонтрагентов).ВидДоговора В (&ВидыДоговоров)
				И ТИПЗНАЧЕНИЯ(Субконто3) В (&ТипыДокументовРасчетов)
				И (НЕ ВЫРАЗИТЬ(Субконто2 КАК Справочник.ДоговорыКонтрагентов).Валютный
					ИЛИ ВЫРАЗИТЬ(Субконто2 КАК Справочник.ДоговорыКонтрагентов).РасчетыВУсловныхЕдиницах)
				И Организация В (&СписокОрганизаций)) КАК ХозрасчетныйОстатки
		ЛЕВОЕ СОЕДИНЕНИЕ РегистрСведений.СтатусыДокументов КАК СтатусыДокументов
		ПО ХозрасчетныйОстатки.Организация = СтатусыДокументов.Организация
			И (ВЫБОР
				КОГДА ХозрасчетныйОстатки.Субконто3 ССЫЛКА Документ.ПоступлениеТоваровУслуг
						И ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто3 КАК Документ.ПоступлениеТоваровУслуг).СчетНаОплатуПоставщика <> ЗНАЧЕНИЕ(Документ.СчетНаОплатуПоставщика.ПустаяСсылка)
						И ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто3 КАК Документ.ПоступлениеТоваровУслуг).СчетНаОплатуПоставщика.Проведен
					ТОГДА ВЫРАЗИТЬ(ХозрасчетныйОстатки.Субконто3 КАК Документ.ПоступлениеТоваровУслуг).СчетНаОплатуПоставщика = СтатусыДокументов.Документ
				ИНАЧЕ ЛОЖЬ
			КОНЕЦ)

ИНДЕКСИРОВАТЬ ПО
	Организация,
	ДокументРасчетов
;

**Comment by Evg-lylyk** [comment]
Проверьте в стандартной консоли от 1С, что происходит?

**Comment by Wronglane** [comment]
Тоже ошибку показывает.
Ошибка обработки представления "РегистрБухгалтерии.Хозрасчетный.Остатки:Поле не найдено (Субконто2)"
<<?>>РегистрБухгалтерии.Хозрасчетный.Остатки(

Спасибо за ответ.
Теперь я понимаю, что проблема именно в запросе.
Хотелось бы исправить, но не понимаю, что с ним не так.

**Comment by Evg-lylyk** [comment]
Видимо у таблицы нет такого поля, попробуйте в конструкторе запроса посмотреть

**Comment by Wronglane** [comment]
Смотрел этот запрос в конфигураторе. Без проблем открывает.

**Comment by Evg-lylyk** [comment]
Имя поля используется без имени таблицы с этим бывают проблемы.
У в Туллкит для проверки запроса используется объект СхемаЗапроса... в конфигураторе видимо еще чтото
