### ISSUE TITLE
Сообщения консоли кода в отдельном окне

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#279]
**Существует проблема**
В версии 1.8 инструментов при работе с консолью кода есть возможность просмотреть все сообщения пользователю в отдельной таблице формы. Однако каждая строка таблицы отображает лишь первую строку текста сообщения, что доставляет неудобство при выводе многострочного текста в сообщениях.

Также отдельной гиперссылкой отображается результат выполнения кода. Однако гиперссылка некликабельна, если мы вернули ссылку, то открыть ее нет возможности.

**Хотелось бы иметь следующую функциональность**
Открывать полный текст сообщения в отдельном окне, например, двойным кликом мыши.

То же самое касается и гиперссылки "Результат":
* если это текст, хотелось бы открывать его кликом по гиперссылке в отдельном окне для просмотра всего содержимого целиком и возможности скопировать содержимое в буфер обмена;
* если ссылка, то открывать карточку объекта по ссылке.

![2021-04-30_10-28-56](https://user-images.githubusercontent.com/59051827/116662911-d2722900-a9af-11eb-98d6-5738e21069d6.png)

**Comment by Evg-lylyk** [comment]
Доработано в 1.9
