### ISSUE TITLE
Не работает форматирование комментариев, разрывающих многострочную строку

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#280]
**Описание ошибки**
В консоли кода комментарии, вставленные между строками многострочного литерала, и не являющиеся частью самого литерала, раскрашиваются как строка (черный), а не как комментарий (зеленый).

**Сценарий воспроизведения**
Открыть консоль кода. Ввести в поле ввода следующий текст:
```
ТекстЗапроса = 
"ВЫБРАТЬ
|   Т.Ссылка
// Произвольный комментарий
|ИЗ
|   Справочник.Номенклатура КАК Т";
```
Убедиться, что комментарий, не являясь частью текста запроса, окрашивается не в зеленый, а черный цвет, равно как и окружающий его текст.

**Ожидаемое поведение, если бы ошибки не было**
Комментарий должен быть выделен цветом, отличным от цвета строки.

**Скриншоты**
![2021-04-30_10-36-44](https://user-images.githubusercontent.com/59051827/116663592-c33fab00-a9b0-11eb-8281-58676dab1ee1.png)

**Окружение:**
Infostart Toolkit 1.8.4

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 1.9
