### ISSUE TITLE
Конструктор запроса некорректно возвращает текст функций агрегаторов

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#283]
**Описание ошибки**
Вместо выбранной функции агрегирования Сумма выводится количество

**Сценарий воспроизведения**
Шаги по воспроизведению:
1.В консоли запросов ввести текст запроса 
ВЫБРАТЬ
	"1","2"
2. Открыть конструктор и попытаться сгруппировать по Максиммум оба поля
3. Результирующий текст 
ВЫБРАТЬ
	КОЛИЧЕСТВО(РАЗЛИЧНЫЕ "1") КАК Поле1,
	МАКСИМУМ("2") КАК Поле2
Содержит Количество вместо Максимум	

**Окружение:**

   -Infostart Toolkit 1.8.4

Платформа: 8.3.19.900 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.4.148)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.4.148

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

https://user-images.githubusercontent.com/6578710/117267427-8b27e480-ae56-11eb-8bad-9562a30aff23.mp4

**Comment by Evg-lylyk** [comment]
Попробуй в стандартном конструкторе мне кажется это в нем баг

**Comment by xnd1124** [comment]
Да типовой конструктор также содержит ошибку

**Comment by Evg-lylyk** [comment]
Исследую, может смогу адекватно исправить в своем конструкторе

**Comment by Evg-lylyk** [comment]
Поправил в версии 1.9
Это происходит когда сразу нажимать ОК не успевает положить в данные т.к. там ПодключитьОбработчикОжидания
Интересно что этот баг появился с платформы 11 в 10ой его нет
