### ISSUE TITLE
В редакторе запроса Monaco возникает ошибка Couldn't read a file. Возникла после установки 1.8.4.

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#284]
**Описание ошибки**
Couldn't read a file:// file: file:///C:/Users/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80/AppData/Roaming/1C/1cv8/f4c923d4-e16f-4294-b6a1-d7e97e102cca/ad1db191-f680-42fd-8465-ab078a9f6f2f/App/ITK_Monaco1.8.4/index.html

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть редактор запроса

**Скриншоты**
![image](https://user-images.githubusercontent.com/6578710/117268317-71d36800-ae57-11eb-9f67-49e67f479948.png)

**Окружение:**
Infostart Toolkit 1.8.4

Платформа: 8.3.19.900 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.4.148)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.4.148

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Попробуй очистить указанную папку

**Comment by Evg-lylyk** [comment]
Дополнительно поработал с этой проблемой в 1.9, думаю теперь это исключено, но не уверен на 100%
