### ISSUE TITLE
Добавить инструмент сравнения произвольных объектов ИБ

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#304]
**Существует проблема**
При программном создании объектов зачастую сложно сразу определить точный состав всех реквизитов, которые требуется заполнить. 
Чаще всего руками создается "эталонный" экземпляр и потом сравнивается с созданным программно.
Хотелось бы иметь инструмент, позволяющий сравнить пореквизитный состав разных объектов ( с учетом табличных частей)
**Хотелось бы иметь следующую функциональность**
Пример реализованной функциональности
https://infostart.ru/public/1240803/
( Включен в состав Универсальных Инструментов)

**Comment by Evg-lylyk** [comment]
Реализовано в 2.3.1
