### ISSUE TITLE
Поиск по GUID не учитывает права на чтение объекта метаданных: Недостаточно прав для работы с таблицей...

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#305]
**Описание ошибки**
При поиске по GUID возникает ошибка "Недостаточно прав для работы с таблицей..." 

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. В конфигурации ERP 2.5.7.х Открыть Редактор Объекта и вставить произвольный ГУИД
2. 
![image](https://user-images.githubusercontent.com/6578710/118808298-aad4f900-b8a9-11eb-9f8b-2ee998c6009a.png)

P.S. Причина в том что даже для полных прав в типовой ЕРП убрали доступ к документу "УдалитьРегистраторГрафикаДвиженияТоваров"

**Окружение:**

Infostart Toolkit 1.8.5

Платформа: 8.3.18.1483 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.7.25)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 1.8.6
