### ISSUE TITLE
Поиск по Гуиду показывает несколько результатов, при наличии одного единственного

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#312]
**Описание ошибки**
Поиск по Гуиду показывает несколько результатов, при наличии одного единственного значения с данным ГУидом

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть редактор объекта
2. Вставить Гуид объекта из Базы
3. Отображается ошибочно несколько результатов

**Ожидаемое поведение, если бы ошибки не было**
Одно единственное найденное значение

**Скриншоты**
![image](https://user-images.githubusercontent.com/6578710/119774485-85a44400-bec2-11eb-94c7-d844bfe50d1d.png)

**Окружение:**

   Infostart Toolkit 1.8.5

Платформа: 8.3.18.1483 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.7.25)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.374

**Comment by Evg-lylyk** [comment]
Исправил в 1.8.6. Релиз сделаю сегодня
