### ISSUE TITLE
Неинформативное сообщение об ошибке в консоли кода

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#315]
**Описание ошибки**
В консоли кода прописываю код с ошибкой, возникает внутреннее сообщение об ошибке
"Преобразование к типу Число не может быть выполнено"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль кода
2. Ввожу текст "а =1" ( без ; )
3. Нажимаю выполнить
4. Возникает внутренняя ошибка "Преобразование к типу Число не может быть выполнено"

**Ожидаемое поведение, если бы ошибки не было**
Подсветка текста как ошибочного без внутренней ошибки

**Скриншоты**
![image](https://user-images.githubusercontent.com/6578710/119939518-4b07dd80-bf8e-11eb-8c21-79551b39cc99.png)

Infostart Toolkit 1.8.6

Платформа: 8.3.18.1483 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.7.25)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Точно версия 1.8.6 исправлял подобную ошибку в 1.8.5 #298

**Comment by xnd1124** [comment]
Ошибка возникает в функции ИТК_Строки.РазборПрочитатьЦелоеЧисло
Ей в качестве строки передается 
"{<Неизвестный модуль>(1,4)}: Ожидается символ ';'"
Внутри функции осуществляется поиск цифр между { и ( а в переданной строке их нет, соответственно падает на 

 Число(Результат) где Результат - пустая строка

Ожидается строка типа {(19, 2)}: Синтаксическая ошибка "Справочник.Товары"
а у меня между { и ( стоит  "<Неизвестный модуль>"
{<Неизвестный модуль>(1,5)}: Ожидается символ ';'
