### ISSUE TITLE
Сворачивание блоков кода не сохраняется при выполнении кода или запроса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#316]
**Описание ошибки**
Редактор Монако позволяет сворачивать блоки кода, что в консоли кода, что в консоли запроса, однако после нажатия кнопки "Выполнить" все свернутые ранее блоки вновь разворачиваются. Эта особенность, на мой взгляд, сводит на "нет" пользу от сворачивания, т.к. при работе с большим объемом текста после выполнения кода/запроса приходится вновь сворачивать блоки для удобства чтения. Либо отказаться от этой "фичи", дабы не тратить на нее время.

**Окружение:**
Infostart Toolkit 1.8.5

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Это я поправил в 1.9. При выполнении обновлялся текст, в дальнейшем с этим будет лучше, но при переключении строк сворачиваемость будет теряться.

**Comment by Evg-lylyk** [comment]
Еще в 1.9. появятся закладки их состояние будет сохранятся до закрытия. Ты писал об этом другой задаче

**Comment by d-hurricane** [comment]
При переключении каких строк? В дереве данных?

**Comment by Evg-lylyk** [comment]
Скорее всего и сворачиваемость будет в 1.9. Постараюсь сделать, уже возможность есть (только сделали).

**Comment by Evg-lylyk** [comment]
Реализовано в 1.9
