### ISSUE TITLE
Неверно вычисляется строка с ошибкой в коде

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#317]
**Описание ошибки**
В некоторых случая при выполнении кода в консоли разработчика неверно определяется место возникновения ошибки. В этом случае "красной" строкой всегда считается первая строка кода.

**Сценарий воспроизведения**
Открыть консоль разработчика. Добавить в дерево данных элемент типа "Код". Ввести в поле кода следующий текст:
```
Стр = Новый Структура;
Сообщить(Стр.НесуществующееПоле);
```
Нажать кнопку "Выполнить". Убедиться, что красным цветом будет выделена не вторая строка, где реально возникла ошибка обращения к полю структуры, а первая.

**Окружение:**
Infostart Toolkit 1.8.5

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP. Управление холдингом (3.0.4.19)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 1.8.7
