### ISSUE TITLE
Показывать полный стек ошибки, за исключением строки из самого Тулкита

### ISSUE THREAD

**Issue by artbear** [infostart-hub/toolkit#319]
**Существует проблема**
При показе ошибки сейчас выдается только ее краткое представление.
В итоге при выполнении собственного кода нельзя увидеть полный стек ошибки
и с ошибкой бывает сложно разобраться.

**Хотелось бы иметь следующую функциональность**
- Добавить показ полного стека ошибки вместо показа одной строки ошибки с кратким представлением
- Из полного стека лучше исключить строки кода из самого Инфостарт Тулкит
  - я делал спец.методы для подобного в Ванесса-АДД и Ванесса-Раннер

**Comment by Evg-lylyk** [comment]
Реализовал в 2.4
Корректно показывается ошибка, собирается стек.
С возможностью перехода к месту ошибки или строки стека
