### ISSUE TITLE
1.9.0 сломалась интеграция с БСП

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#324]
**Описание ошибки**
Например в формах списка справочников нельзя перейти к обработкам тулкита

**Скриншоты**
если применимо, приложите скриншоты
![image](https://user-images.githubusercontent.com/6578710/120777142-45c60800-c525-11eb-981b-278298e67e74.png)
![image](https://user-images.githubusercontent.com/6578710/120777239-5d04f580-c525-11eb-8f55-fa017b6e876e.png)

**Окружение:**

Infostart Toolkit 1.9.0

Платформа: 8.3.18.1483 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.7.25)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.374

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 1.9.1, ошибка была в установщике он ошибочно ставит версию без БСП
