### ISSUE TITLE
Не сохраняет текст запроса м-у сеансами

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#325]
**Описание ошибки**
При перезапуске сеанса из 1С текст запроса не сохраняется

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть конфигуратор. 
2. Запустить сеанс 1С из конфигуратра.
3. Открыть консоль запроса.  Написать запрос. Выполняем запрос.
4. Перезапускаем 1С из конфигуратора.
5. Открываем консоль запросов - теста запроса нет.

**Ожидаемое поведение, если бы ошибки не было**
При открытии консоли запроса (после перезапуска 1С из конфигуратора) текст запроса должен был сохраниться.

**Скриншоты**
![image](https://user-images.githubusercontent.com/18395787/121350206-09cee080-c933-11eb-8c7c-51be8a078f33.png)

**Окружение:**

  Infostart Toolkit 1.8.7

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести ошибку. Все работает. Восстанавливает сеанс как аварийно завершенный. Возможно было запущено несколько сеансов?

**Comment by AnatoliyBritko** [comment]
Да, было запущено 2 сеанса : один в административными правами, второй обычный бухгалтер.
К сожалению сейчас не могу воспроизвести проблему.

**Comment by Evg-lylyk** [comment]
> Да, было запущено 2 сеанса : один в административными правами, второй обычный бухгалтер.
> К сожалению сейчас не могу воспроизвести проблему.

И в обоих был Туллкит?
Если нет, то не в этом дело

**Comment by AnatoliyBritko** [comment]
Вот сейчас тоже повторяется.
Проблема именно на новых базах.
Т.е. :
1. восстанавливаю базу из dt
2. устанавливаю Туллкит.
3. Запускаю конфигуратор. Из под конфигуратора запускаю сеанс 1С.
4. В консоли запросов пишу запрос, выполняю его.
5. Из под конфигуратора перезапускаю сеанс 1С
6. Открываю консоль запросов.  Запросов - нет.

Сеанс 1С только один.

может подскажите по модулю где посмотреть сохранение / восстановление настроек?

**Comment by Evg-lylyk** [comment]
Спасибо, это при первом запуске или когда настройки удалены, исправил 1.9.5

**Comment by AnatoliyBritko** [comment]
Уточню еще здесь по др. вопросу...
Не работает в консоли запросов копирование по ctrl + с. Приходится постоянно через меню копировать.
Причем вставка через ctrl + v нормально отрабатывает.
Работаю на физич. машине (без rdp и пр.)
в чем может быть проблема ?

**Comment by Evg-lylyk** [comment]
Подобные вопросы можете мне писать в телеграм @EvgLylyk 
Это известная проблема BSL Monaco
https://github.com/salexdv/bsl_console
В разделе известные проблемы:
На платформах, выпущенных примерно до ноября 2020 года могут не работать горячие клавиши CTRL+SPACE, CTRL+C, CTRL+V и CTRL+Z и т.п.
