### ISSUE TITLE
Пользовательские шаблоны кода в консоли кода

### ISSUE THREAD

**Issue by Cmapnep** [infostart-hub/toolkit#327]
**Существует проблема**
Разработчик, подключаясь к клиентскому компьютеру и используя тулкит, применяет консоль кода и в ней не имеет возможности использовать шаблоны кода так, как делает это в конфигураторе 

**Хотелось бы иметь следующую функциональность**
Разработчик подключается к разным клиентам, присоединяет расширение и использует все свои шаблоны для написания обработки без открытия конфигуратора

**Дополнительный контекст**
Для реализации описанного сценария нужны не только сами пользовательские шаблоны, но и интеграция с сервисом их хранения типа fastcode

**Comment by Evg-lylyk** [comment]
С версии 2.4. добавлена возможность установить шаблоны в формате st
