### ISSUE TITLE
Добавить возможность очистки данных отладки

### ISSUE THREAD

**Issue by Karejl** [infostart-hub/toolkit#328]
В рамкам тестирования функционала создавал несколько запросов отладки. Я так понимаю их удалить нельзя? Использовать их больше не планирую, вполне хватает одного по умолчанию. 

Хотелось бы в форме отладки, там где находится справка. Получить возможность очищать не актуальные данные.

**Comment by Evg-lylyk** [comment]
Не вижу в этом необходимости, они занимают мало места, особо не мешают.
