### ISSUE TITLE
Добавить в вывод результата показ строки с названием самого запроса

### ISSUE THREAD

**Issue by artbear** [infostart-hub/toolkit#329]
**Существует проблема**
Результаты обычного запроса неудобно экспортировать.
в нем нет названия текущего запроса

**Хотелось бы иметь следующую функциональность**
Добавить в вывод результата показ строки с названием самого запроса

![image](https://user-images.githubusercontent.com/2920817/122270207-bdf9d980-cee6-11eb-9a59-a82c168af093.png)

**Comment by Evg-lylyk** [comment]
Учтено в 1.9.2
