### ISSUE TITLE
В конструкторе запроса теряется тип колонок временных таблиц

### ISSUE THREAD

**Issue by BProg-Gladkov** [infostart-hub/toolkit#332]
**Описание ошибки**
В конструкторе запроса теряется тип колонок временных таблиц

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Добавить описание ВТ
![image](https://user-images.githubusercontent.com/33430119/122554525-c3b80200-d041-11eb-8958-fbe2f0dee2d9.png)
2. Написать запрос использующий ВТ
![image](https://user-images.githubusercontent.com/33430119/122554623-e813de80-d041-11eb-8aaa-c87cd6eaada7.png)
3. Открыть конструктор запроса
![image](https://user-images.githubusercontent.com/33430119/122554757-0ed21500-d042-11eb-9684-a5cdb1e19c81.png)
В списке таблиц базы данных тип есть.
В списке таблиц запроса типа нет. Из-за ошибки неудобно редактировать запрос - нет доступа к вложенным полям.

**Окружение:**
Infostart Toolkit 1.8.8
Платформа: 8.3.18.1334 (Windows x86-64)
Режим БД: клиент-серверный

**Comment by Evg-lylyk** [comment]
Есть такая особенность когда текст пустой корректно работает, когда заполнен то описание ВТ определяется по типу, в будущем постараюсь решить эту проблему

**Comment by Evg-lylyk** [comment]
Пытался решить данный вопрос
Не удалось, из-за ограничений платформы
нужно пересоздавать источники внутри объекта СхемаЗапроса, изменить тип поля нельзя и там нет метода вставить

**Comment by Evg-lylyk** [comment]
Нашел способ :)
Решено для описаний с одним типом, в версии 2.3.3
