### ISSUE TITLE
В конструкторе запроса не отображаются входные временные таблицы при попытке заменить таблицу

### ISSUE THREAD

**Issue by BProg-Gladkov** [infostart-hub/toolkit#333]
**Описание ошибки**
В конструкторе запроса не отображаются входные временные таблицы при попытке заменить таблицу

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Добавить описание ВТ
![image](https://user-images.githubusercontent.com/33430119/122554525-c3b80200-d041-11eb-8958-fbe2f0dee2d9.png)
2. Написать запрос использующий ВТ
![image](https://user-images.githubusercontent.com/33430119/122554623-e813de80-d041-11eb-8aaa-c87cd6eaada7.png)
3. Открыть конструктор запроса
![image](https://user-images.githubusercontent.com/33430119/122555321-d1ba5280-d042-11eb-8e7e-cc947d5280d2.png)
Выбрать временную таблицу нельзя.

Важно:
До открытия окна замены таблицы не открывайте список временных таблиц в списке таблиц базы данных.
Если сначала открыть список временных таблиц в списке таблиц базы данных, то иногда выбор таблиц доступен, а иногда нет.

**Окружение:**
Infostart Toolkit 1.8.8
Платформа: 8.3.18.1334 (Windows x86-64)
Режим БД: клиент-серверный

**Comment by Evg-lylyk** [comment]
С версии 1.9.3
Убрал временные таблицы (входные) из выбора таблицы иначе там возникают проблемы которые быстро не решить.
Думаю в будущем вернутся к этой проблеме

**Comment by BProg-Gladkov** [comment]
Как можно получить исправленную версию?

Правильно ли я понял, что убрана возможность при помощи конструктора запроса работать с входными временными таблицами?

Это была фича ради которой был куплен toolKit.
В ЗУП много кода вида 
СоздатьВТ...
Запрос.Текст = "...";

Для того что бы удобно писать запросы к ВТ и был куплен инструмент.

**Comment by Evg-lylyk** [comment]
Пока версия тестовая, фича не убрана, убрана возможность использовать входные ВТ через диалог Заменить таблицу.
