### ISSUE TITLE
В конструкторе запроса при добавлении связи автоматически устанавливается флаг левого соединения.

### ISSUE THREAD

**Issue by BProg-Gladkov** [infostart-hub/toolkit#334]
**Описание ошибки**
В конструкторе запроса при добавлении связи автоматически устанавливается флаг левого соединения.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Добавить новую связь таблиц и указать внутреннее соединение.
![image](https://user-images.githubusercontent.com/33430119/122558863-38da0600-d047-11eb-9673-8f768082e03c.png)

2. При окончании редактирования строки автоматически связь заменится на левую.

Infostart Toolkit 1.8.8

**Comment by Evg-lylyk** [comment]
Исправлено в версии 1.9.3
