### ISSUE TITLE
Сделать отдельную команду для открытия редактора кода

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/toolkit#335]
**Существует проблема**

Нужно быстро выполнить какой-то код (и, возможно, выкинуть его потом), например: 
- сделать какой-то вызов, чтобы проверить результат его работы
- что-то программно единоразово исправить в тестовой базе
- аналог REPL'а: написать и отладить какой-то небольшой фрагмент кода/алгоритм, когда это проще, чем сохранять конфигурацию/обработку и перезапускать

Сейчас для этих целей я делаю следующее:
1. открываю тулкит (Alt + C)
2. выбираю Добавить - Код
3. Сворачиваю таб поле с деревом запросов/кода
4. Сворачиваю таб поле Результат

**Хотелось бы иметь следующую функциональность**

Нужна команда открытия Тулкита (+ хоткей для нее), при запуске которой шаги 1 - 4 выполнятся автоматически и сразу будет открываться окно тулкита с редактором кода вот в таком виде:

![2021-06-24_01-57](https://user-images.githubusercontent.com/1042299/123173345-86af9d80-d48f-11eb-90fe-15014e7e35c0.png)

**Comment by Evg-lylyk** [comment]
С версии 1.9 есть команда Консоль кода делает шаги 1,2
Планирую перейти к схеме когда консоль кода это отдельная обработка #307 
Спасибо, постараюсь учесть в будущем

**Comment by kuntashov** [comment]
> С версии 1.9 есть команда Консоль кода делает шаги 1,2

Спасибо, обновлюсь.

> Планирую перейти к схеме когда консоль кода это отдельная обработка #307

Это было бы круто!
