### ISSUE TITLE
Добавить команду выполнения кода для объекта

### ISSUE THREAD

**Issue by nixel2007** [infostart-hub/toolkit#336]
**Существует проблема**

Периодически над объектом нужно выполнять какие-то контекстные операции. Например, вызвать какую-то функцию, куда бы можно было передать ссылку на объект. Сейчас такую операцию можно выполнить только из консоли кода.

**Хотелось бы иметь следующую функциональность**

Было бы здорово добавить либо в редактор объекта, вызываемый по Alt-E прям с формы объекта, либо отдельной командой вызов формы, в которой можно было бы написать алгоритм с возможностью обращения к контексту вызова - объекту, записи регистра сведений и т.д. Похоже на "обработку результата" в консоли запросов, но сразу над одним объектом.

**Comment by Evg-lylyk** [comment]
Понял учту, планирую сделать что то тип Подбор и обработка объектов, ну и передача ссылок туда и разных инструментов

**Comment by d-hurricane** [comment]
Тоже возникла похожая потребность. В качестве быстрого решения могу предложить следующее:
- по команде Alt+T (Глобальное меню) разработчик запускает консоль кода;
- консоль кода при открытии уже содержит код для выбранного объекта:
```bsl
Ссылка = Справочники.ИмяСправочника.ПолучитьСсылку(Новый УникальныйИдентификатор("id"));
Объект = Ссылка.ПолучитьОбъект();
```
- дальше разработчик уже вписывает ниже нужный ему код обработки объекта.

**Comment by Evg-lylyk** [comment]
С версии 2023.4
Реализована новая консоль кода с параметрами, параметры будут передаваться
