### ISSUE TITLE
Ошибка при обновлении замера времени выполнения в консоли запросов.

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#337]
**Описание ошибки**
Ошибка при обновлении замера времени выполнения в консоли запросов.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'Консоль запросов'
2. Вводим текст запроса 
3. Нажимаем "Обновить замер времени выполнения"
4. Появляется ошибка

**Скриншоты**
![image](https://user-images.githubusercontent.com/18395787/123391238-789f7100-d5a4-11eb-8722-ce34a7e96e4c.png)

**Окружение:**

Infostart Toolkit 1.9.3

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by AnatoliyBritko** [comment]
Еще при использовании в запросе ВТ - время выполнения не обновляется.

![image](https://user-images.githubusercontent.com/18395787/123392048-4a6e6100-d5a5-11eb-8c29-9c5de41ad214.png)

Например при выполнении запроса - время выполнения не появляется.

```
ВЫБРАТЬ
	1 КАК Поле1
ПОМЕСТИТЬ Вт1
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	2 КАК Поле1
ПОМЕСТИТЬ Вт2
```

**Comment by Evg-lylyk** [comment]
Спасибо за информацию, ошибки исправлены в 1.9.4
