### ISSUE TITLE
В параметрах запроса (конструктор запроса) не устанавливает текущую дату

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#339]
**Описание ошибки**
В конструкторе запросов для параметра с типом дата выбираю из выпадающего списка "Текущая дата" (закладка параметры), но дата не подставляется 

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть '.Конструктор запроса'
2. Пишем запрос с периодом. Например

`ВЫБРАТЬ
	КурсыВалют.Период КАК Период,
	КурсыВалют.Валюта КАК Валюта,
	КурсыВалют.Курс КАК Курс
ИЗ
	РегистрСведений.КурсыВалют КАК КурсыВалют
ГДЕ
	КурсыВалют.Период = &Период`

3. Открываем закладку "Параметры", Для параметра "период" из выпадающего меню выбираем "Текущая дата"
4. В колонке "Значение"  остается пустая дата.

**Ожидаемое поведение, если бы ошибки не было**
В колонке "Значение" должно подставить сегодняшнее число

.

**Скриншоты**
![Кто добовил или изменил строку](https://user-images.githubusercontent.com/18395787/123631860-e7d4c980-d81f-11eb-97a1-fa3131aa2deb.gif)

**Окружение:**

  Infostart Toolkit 1.9.4

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо за информацию
Исправлено в 1.9.5
