### ISSUE TITLE
Ошибка вставки текста схемы СКД / запроса при использовании нескольких редакторов одновременно

### ISSUE THREAD

**Issue by MalginYuryVladimirovich** [infostart-hub/toolkit#341]
**Описание ошибки**
При использовании нескольких радиаторов одновременно, вставка кода осуществляется некорректно (текст вставляется в активную запись на момент завершения работы в конструкторе)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть инструментарий
2. Создать запрос, затем дополнительно создать схему компоновки.
3. Открыть конфигуратор компоновки, вернуться в инструментарий и спозиционироваться на запрос.
4. вернуться в конструктор СКД и завершить его работу.
5. Текст СКД будет помещен в поле с запросом.

**Ожидаемое поведение, если бы ошибки не было**
Текст разместить в элементе, от куда был вызван конструктор/
Просьба не ограничивать открытие конструктора "монопольным режимом", как реализовано для конструктора запросов.

**Скриншоты**
![image](https://user-images.githubusercontent.com/60355243/124438196-9036e080-dd80-11eb-8d58-d84b78555e8b.png)

**Окружение:**
Infostart Toolkit 1.8.8

Платформа: 8.3.19.1150 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:Комплексная автоматизация 2 (2.4.13.187)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.494

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19043))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Конструктор СКД так устроен что работает через событие ОбработкаВыбора и понять если их несколько из какой строки запущен невозможно. Поэтому открываю по возможности с блокировать владельца.
С запросом все нормально с тонким конструктором. Могу исправить если запускается один конструктор СКД, но не стал.
Нужно закрывать конструктор СКД, зачем так сделано не понимаю вы посмотрите любую консоль СКД это везде будет глючить по разному.

**Comment by MalginYuryVladimirovich** [comment]
Ок. понятно.

С уважением, Мальгин Юрий


ср, 7 июл. 2021 г. в 12:22, Люлюк Евгений ***@***.***>:
