### ISSUE TITLE
При сохранение запроса с параметрами из макета компоновки данных в отладке возникает ошибка

### ISSUE THREAD

**Issue by 6elka1703** [infostart-hub/toolkit#343]
Если в отладке сохранять запрос из макета компоновки данных, в котором есть параметр типа "Стандартный период", возникает ошибка. Возникает из-за того что toolkit не понимает что делать с параметром СКД типа "Стандартный период".
![image](https://user-images.githubusercontent.com/38560185/124763855-14ce5e00-df3d-11eb-91bb-68107d40ad2d.png)
Проблему решили таким образом: прогнали текст запроса СКД через объект "Запрос" и собрали только нужные для запроса параметры, остальные параметры СКД выкинули.
![image](https://user-images.githubusercontent.com/38560185/124763996-30d1ff80-df3d-11eb-94ee-29af385705e8.png)

**Comment by Evg-lylyk** [comment]
Решил эту проблему с версии 2.0

**Comment by Evg-lylyk** [comment]
Спасибо, за решение и пояснения
