### ISSUE TITLE
Ошибка открытия иерархического справочника с общими реквизитами в редакторе объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#354]
**Описание ошибки**
При попытке открыть в редакторе объекта элемент иерархического справочника (с иерархией групп и элементов), для которого используются общие реквизиты, возникает ошибка, редактор не открывается.

**Сценарий воспроизведения**
В конфигурации КА 2.5 для воспроизведения ошибки подходит справочник "Номенклатура":
* он иерархический;
* используется иерархия групп и элементов;
* входит в состав общих реквизитов, таких как "НаименованиеЯзык1".

Чтобы увидеть ошибку, необходимо:
1. Открыть редактор объекта в разделе Infostart Toolkit.
2. В поле ввода объекта кликнув по кнопке "Т" выбрать тип "Номенклатура".

Появится сообщение об ошибке со следующей информацией:

> Поле объекта не обнаружено (Использование)
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(854)}:			НоваяСтрока.Использование = КартинкаИспользованияПоля(Реквизит.Использование);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(679)}:		ДанныеОбъекта = ПрочитатьДанныеОбъекта(ИзменяемыйОбъект, ОбъектЗаполнения, УникальныйИдентификатор);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1595)}:	ЗаполнениеДанныхПоОбъекту(ОбрабатываемыйОбъект);
> {InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1168)}:	ОбновитьДанныеОбъекта();
> {InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(60)}:		ВыполнитьОбработкуОповещения(ДополнительныеПараметры.Оповещение, Результат);
> {InfostartToolkit ОбщаяФорма.ИТК_РедактированиеТипаЗначения.Форма(814)}:		Закрыть(Результат);
> {InfostartToolkit ОбщаяФорма.ИТК_РедактированиеТипаЗначения.Форма(233)}:	ВыбраноЗначение(Строка);

**Ожидаемое поведение, если бы ошибки не было**
Реквизиты иерархического справочника должны отобразиться в редакторе объекта, в т.ч. и общие реквизиты.

**Окружение:**
Infostart Toolkit 1.9.7

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, исправлено с 1.9.8 и 2.0
