### ISSUE TITLE
Проработка конструктора СКД

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#355]
- [ ] #951

- [x] Проблема. При отмене редактирования имени поле возвращать пред.идентификатор
- [x] Проблема. Когда имен параметра уже занято
- [x] Фича. Передача параметров в подсказку редактирования выражения

**Comment by d-hurricane** [comment]
Что нашел при беглом тестировании для версии 2.0.

1. При первом открытии конструктора предлагается добавить набор данных. Ожидается, что при выборе набора типа "Запрос" сразу же будет открыт конструктор запроса.
2. Переименование поля в наборе данных приводит к ошибке "Поле объекта не обнаружено (Имя)".
3. В колонке "Роль" не отображается представление типа остатка, бух. тип.
4. Непонятно, зачем редактор выражений в настройках роли для типа остатка. Лучше автоподбор имен.
5. В связях не работает кнопка выбора источников.
6. В связях при выборе поля приемника появляется ошибка "Поле объекта не обнаружено..."
7. В связях при выборе ссылочного поля в качестве выражения источника почему-то колонка заполняется значением "Представление(Ссылка)".
8. При редактировании оформления поля, если для параметра "Текст" выбрать тип "Поле компоновки данных", то диалог выбора поля будет пустым.
9. Горизонтальный скролл в форме редактирования оформления поля просто сводит с ума.
10. В форме редактирования оформления поля не нужно подменю "Еще".
11. В форме выбора полей для расчета ресурсов не хватает иерархических группировок.
12. В редакторе выражения для параметров не хватает контекстной подсказки для уже существующих параметров.
13. При переключении на закладку настроек КД возникает ошибка "несоответствие типов". Собственно, протестировать закладку не получилось, т.к. в результате ошибки не увидел каких-либо доступных полей.

**Comment by Evg-lylyk** [comment]
> Что нашел при беглом тестировании для версии 2.0.

Не сказать чтобы я очень хорошо знаю все нюансы СКД

1. Тут не согласен, может руками текст писать хочу или из буфера обмена вставить
2. Исправлено в 2.0.1
3,4 Тут не понял поясни
5. Вроде работает
6. Исправил в 2.0.1
7. Исправил в 2.0.1
8,9,10. Это форма от 1С, по хорошему наверное вместо нее свою нужно. Потом.
11. Исправил в 2.0.1
12. Описана выше "Фича. Передача параметров в подсказку редактирования выражения" буду делать
13. Исправил в 2.0.1

**Comment by d-hurricane** [comment]
1. Ок, согласен. В твоих инструментах в этом больше смысла, чем стандартном конструкторе. Но может воплотить эту идею в другом виде - убрать эти кнопки из подменю "Еще" и показать компактно в виде пиктограмм?
2. Ок.
3. См. картинку 
![image](https://user-images.githubusercontent.com/59051827/128036258-671a64eb-76bf-49a7-9a23-e1eef2893d47.png)
4. В форме настроек роли для поля можно выбрать роль "Остаток". В этом случае необходимо указать "Имя" и "Тип". Так вот редактор имени сейчас представляет собой редактор выражений. Но если я не ошибаюсь, это не выражение, это просто строковый идентификатор, по которому СКД объединяет поля в пары "начальный-конечный" остаток. Так вот чего в платформенном конструкторе не хватает, так это обычного выбора из списка идентификаторов. Скажем, для поля "КоличествоНачОст" я указал имя "Количество" и тип "Начальный остаток". Теперь перехожу к настройке роли для поля "КоличествоКонОст". И здесь мне бы не хотелось заново вбивать слово "Количество" в качестве имени, мне хотелось бы его выбрать из выпадающего списка.
5. Странно. У меня нет. :-) Ну ладно.

**Comment by Evg-lylyk** [comment]
4 Понял нужен выбор поля
5 Может мы про разное
![Выбор источников](https://user-images.githubusercontent.com/48444742/128038649-6fc7c9ea-d165-4725-8eec-b4e158b39e7e.png)

**Comment by Evg-lylyk** [comment]
> 3. См. картинку
В 2.0.1 это исправлено

**Comment by d-hurricane** [comment]
5. Про одно и то же. И у меня почему-то список пустой. Попробуй с одним набором данных такое провернуть.

**Comment by Evg-lylyk** [comment]
> Про одно и то же. И у меня почему-то список пустой. Попробуй с одним набором данных такое провернуть.

С одним тоже ОК

**Comment by d-hurricane** [comment]
У меня при вводе с клавиатуры список появляется, а при нажатии на стрелку - нет.

**Comment by Evg-lylyk** [comment]
> У меня при вводе с клавиатуры список появляется, а при нажатии на стрелку - нет. Платформа 8.3.17.1989

Проверил на 8.3.17.2306 все работает видимо у тебя какой-то глючок платформы

**Comment by d-hurricane** [comment]
Добавлю пожелание. Хотелось бы иметь возможность скрыть поле из набора данных с глаз долой. Когда включено автозаполнение, в доступные поля сыпется очень много полей для отбора из виртуальных таблиц запроса. Порой очень хочется отключить их (ограничением использования) и больше не видеть, пока настраиваешь прочие поля.

**Comment by d-hurricane** [comment]
Еще пожелание. Добавить в редактор выражений ссылку на встроенную справку по функциям СКД:
v8help://dcsui/SKD_Functions

**Comment by d-hurricane** [comment]
Пожелание. Заменить на закладке наборов данных заголовки колонок "Ограничения использования" пиктограммами. Так получится компактнее группа колонок. Полагаю, вот эти хорошо подойдут:
![image](https://user-images.githubusercontent.com/59051827/131748163-8676128f-8f3f-470c-9490-1448bb93608c.png)

**Comment by d-hurricane** [comment]
Пожелание. Реализовать красивое отображение многострочных выражений в ресурсах. Сейчас выгляди так:
![image](https://user-images.githubusercontent.com/59051827/131751712-01327c7e-6abf-47ea-bef1-fc6afac2b66f.png)

**Comment by Evg-lylyk** [comment]
> Пожелание. Заменить на закладке наборов данных заголовки колонок "Ограничения использования" пиктограммами. Так получится компактнее группа колонок. Полагаю, вот эти хорошо подойдут:
> ![image](https://user-images.githubusercontent.com/59051827/131748163-8676128f-8f3f-470c-9490-1448bb93608c.png)

Отличная мысль

**Comment by Evg-lylyk** [comment]
> Еще пожелание. Добавить в редактор выражений ссылку на встроенную справку по функциям СКД:
> v8help://dcsui/SKD_Functions

Не знаешь как открыть эту справку? Думал о своем синтаксис помощнике, но пока не дошел

**Comment by Evg-lylyk** [comment]
> Добавлю пожелание. Хотелось бы иметь возможность скрыть поле из набора данных с глаз долой. Когда включено автозаполнение, в доступные поля сыпется очень много полей для отбора из виртуальных таблиц запроса. Порой очень хочется отключить их (ограничением использования) и больше не видеть, пока настраиваешь прочие поля. Можно даже сделать все одной кнопкой "Отключить и скрыть", которая проставит флажки и спрячет поле.

С этим позже, пока делаю чтобы все приемлимо работало. Потом, конечно надо

**Comment by d-hurricane** [comment]
> Не знаешь как открыть эту справку? Думал о своем синтаксис помощнике, но пока не дошел

Ты не поверишь, но... :-D

`ОткрытьСправку("v8help://dcsui/SKD_Functions")`

**Comment by Evg-lylyk** [comment]
> > Не знаешь как открыть эту справку? Думал о своем синтаксис помощнике, но пока не дошел
> 
> Ты не поверишь, но... :-D
> 
> `ОткрытьСправку("v8help://dcsui/SKD_Functions")`

Добавил в форму выражения в Еще. В версии 2.1.0

**Comment by Evg-lylyk** [comment]
Часть решено часть перенесено в другие задачи
