### ISSUE TITLE
Поле объекта не обнаружено (ДоступныеТипы)

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#357]
**Описание ошибки**
При попытке открыть табличную часть документа заказ на производство в ЕРП возникает ошибка
Поле объекта не обнаружено (ДоступныеТипы)
{InfostartToolkit ОбщийМодуль.ИТК_Форма.Модуль(57)}:	НоваяКолонка.ДоступныеТипы = ДопустимыеТипы;
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1315)}:		ИТК_Форма.ДобавитьЭлементКолонкуВТаблицуЗначений(ЭтотОбъект, Колонка.Имя, Колонка.ТипЗначения, ИмяЭлементаРеквизита, ИмяРеквизита);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1260)}:		ОбновитьРедактируемуюТаблицуЗначенийНаСервере(ИмяРеквизита, Адрес);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(2023)}:		ОбновитьРедактируемуюТаблицуЗначений(Элементы.ТабличныеЧасти, "РедактируемаяТабличнаяЧасть");
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(63)}:			ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
{InfostartToolkit ОбщийМодуль.ИТК_ДлительныеОперацииКлиент.Модуль(149)}:		Модуль.ОжидатьЗавершение(ДлительнаяОперация, ОповещениеОЗавершении, ПараметрыОжидания);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1989)}:	ИТК_ДлительныеОперацииКлиент.ОжидатьЗавершение(ДлительнаяОперацияПолучениеТабличнойЧасти, ОповещениеОЗавершении, ПараметрыОжидания);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1266)}:			ЗапуститьПолучениеТабличнойЧастиОбъекта(ТекущиеДанные.Имя);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1227)}:	ОбновитьРедактируемуюТаблицуЗначений(Элементы.ТабличныеЧасти, "РедактируемаяТабличнаяЧасть");

**Причина**
Для реквизитов, связанных с полями Типа "Уникальный идентификатор" не существует свойства 
ДоступныеТипы
ВыбиратьТип
а также недоступна установка действий
**Исправление ошибки**
Производить действия только для типов не содержащих "УникальныйИдентификатор"
Пример:
![image](https://user-images.githubusercontent.com/6578710/127461478-8ab51ad6-f61f-4a74-ab60-fdd1abb2d8c1.png)

**Окружение:**
Infostart Toolkit 2.0.0

Платформа: 8.3.18.1520 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.7.108)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.252

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19041))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, исправлено в 2.0.1
