### ISSUE TITLE
Неверное позиционирование на ошибке для метода коллекций "Получить"

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#358]
**Описание ошибки**
Если в консоли кода для коллекций используется метод "Получить" (вместо квадратных скобок), и при выполнении кода на этой строке возникает ошибка выхода за границы диапазона, курсор, сигнализирующий об ошибке, позиционируется на первой строке листинга, а не на той, где реально возникла ошибка.

**Сценарий воспроизведения**
Открыть консоль кода. Ввести следующий фрагмент:
```bsl
Коллекция = Новый Массив;
Коллекция.Добавить(1);
Результат = Коллекция.Получить(3);
```
Нажать кнопку "Выполнить". Убедиться, что курсор, сигнализирующий об ошибке, указывает на первую строку:
![image](https://user-images.githubusercontent.com/59051827/127574203-41cf285b-c96d-4887-8d73-8dfe38177e51.png)

**Ожидаемое поведение, если бы ошибки не было**
Курсор ошибки должен указывать на третью строку кода.

**Окружение:**
Infostart Toolkit 2.0.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.1
