### ISSUE TITLE
Ошибка отображения результата в консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#360]
**Описание ошибки**
При попытке просмотреть результат выполнения кода в отдельном окне, кликнув для этого по гиперссылке результата, появляется окно с ошибкой отображения типов.

**Сценарий воспроизведения**
Открыть консоль кода, ввести в поле редактора следующий код:
`Результат = "0";`
Нажать кнопку "Выполнить". Убедиться, что в группе формы отобразился корректный результат выполнения кода.
Кликнуть ЛКМ по гиперссылке "0" напротив результата. Появится окно с ошибкой следующего содержания:
> Ошибка отображения типов:
> Отсутствует отображение для типа '{http://v8.1c.ru/8.1/data/core}ValueTable'
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(441)}:	РезультатВыполнения = ПолучитьИзВременногоХранилища(ТекущийРезультат.Адрес);
> 
> по причине:
> Ошибка получения значения из временного хранилища
> по причине:
> Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.
> по причине:
> Ошибка преобразования данных XDTO:
> НачалоСвойства: {http://v8.1c.ru/8.2/mngsrv/ws}response	Форма: Элемент	Тип: {http://v8.1c.ru/8.1/data/core}Structure
> по причине:
> Ошибка преобразования данных XDTO:
> НачалоСвойства: Value	Форма: Элемент	Тип: {http://www.w3.org/2001/XMLSchema}anyType
> по причине:
> Ошибка отображения типов:
> Отсутствует отображение для типа '{http://v8.1c.ru/8.1/data/core}ValueTable'

**Ожидаемое поведение, если бы ошибки не было**
Должно открыться диалоговое окно с полученным результатом выполнения кода.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/127645601-370acc9a-6a69-4a88-9365-f69f864d5482.png)

**Окружение:**
Infostart Toolkit 2.0.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.1
