### ISSUE TITLE
Ошибка вставки в код ссылки на объект БД

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#361]
**Описание ошибки**
При попытке вставить в поле редактора кода ссылку на объект БД возникает ошибка.

**Сценарий воспроизведения**
Открыть консоль кода. Кликнув ПКМ на поле ввода кода открыть контекстное меню. Выбрать команду "Вставка ссылки на объект БД..." Появится сообщение об ошибке следующего содержания:
> Поле объекта не обнаружено (ТочкиМаршрутаБизнесПроцесса)
> {InfostartToolkit ОбщийМодуль.ИТК_Форма.Модуль(206)}:		КоллекцияМетаданных = Метаданные[ИТК_Метаданные.ИмяКоллекции(ТипОбъекта)];
> {InfostartToolkit ОбщаяФорма.ИТК_ВставкаСсылкиНаОбъектБД.Форма(9)}:	ИТК_Форма.ОбновитьСписокВыбораТипОбъекта(Элементы.Тип, КодЯзыкаПрограммирования);
> {InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(591)}:	ОткрытьФорму("ОбщаяФорма.ИТК_ВставкаСсылкиНаОбъектБД", ПараметрыФормы, ФормаВладелец, , , , ОписаниеОповещенияЗавершение, РежимОткрытияОкнаФормы.БлокироватьОкноВладельца);
> {InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(997)}:	ИТК_ФормаКлиент.ОткрытьВставкуСсылкиНаОбъектБД(Элемент, ОписаниеОповещения, ВыделенныйТекст);
> {InfostartToolkit ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(524)}:		ВставкаСсылкиНаОбъектБД(Элемент);
> {InfostartToolkit Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(2121)}:	ИТК_РедакторКодаКлиент.ПодключаемыйОбработчикКоманд(ЭтотОбъект, ИмяКоманды, ОповещениеОЗавершении);

**Ожидаемое поведение, если бы ошибки не было**
Должен открыться диалог выбора объекта БД для вставки.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/127646339-39339a51-6258-4c0c-95d9-a73eb822aa3b.png)

**Окружение:**
Infostart Toolkit 2.0.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 2.0.1
