### ISSUE TITLE
Контекстная подсказка в консоли кода для имен типов

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#362]
**Существует проблема**
При использовании Монако в качестве редактора консоли кода в ряде случаев значительную помощь оказывает контекстная подсказка. Однако ее нет внутри метода `Тип(<ИмяТипа>)`.

**Хотелось бы иметь следующую функциональность**
При наборе имени типа внутри глобального метода `Тип` хотелось бы иметь релевантную контекстную подсказку для выбора существующих объектов конфигурации, образующих систему типов.

**Дополнительный контекст**
Infostart Toolkit 2.0.0
![image](https://user-images.githubusercontent.com/59051827/127646906-408e6717-7c16-4d84-84af-2e6e6804fc09.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 2.0.2
