### ISSUE TITLE
Ошибка работы с расширениями через собственный конструктор запросов

### ISSUE THREAD

**Issue by andrei-karpov** [infostart-hub/toolkit#363]
Добрый день, если в расширении был добавлен реквизит объекта, то если добавляешь вложенный запрос и в этом запросе выводишь новый реквизит из расширения, то при нажатии кнопки "ОК", реквизиты из расширения попросту удаляются.
Как воспроизвести:
1. Захватить документ в расширение и добавить в него новый реквизит.
2. Запустить 1С в режиме тонкого клиента, и начать формировать запрос через консоль запросов из Infostart Toolkit
3. Добавить вложенный запрос с этим доработанным документом, и вывести в таблицу новый реквизит.
4. Нажать ОК

**Comment by Evg-lylyk** [comment]
Приветствую, попробовал не воспроизводится у меня платформа 8.3.17.1851
Конструктор доработанный создан на основе конструктора 1С в настройках можешь попробовать включить стандартный конструктор если поведение такое же значит ошибка в конструкторе 1С
![Screenshot_1](https://user-images.githubusercontent.com/48444742/127662088-ed548afb-fb92-4a4d-82c3-7843734910f8.png)

**Comment by Evg-lylyk** [comment]
Нет информации по воспроизведению проблемы
