### ISSUE TITLE
Ошибка позиционирования курсора при ручном написании запроса

### ISSUE THREAD

**Issue by andrei-karpov** [infostart-hub/toolkit#364]
При ручном написании запроса в консоли разработчика происходит автоматическая проверка корректности ввода. При этом появляется надпись "Требуется проверка текста" и курсор автоматически переходит к этой надписи.
Из-за этого прерывается текущий ввод, и приходиться обратно переключаться на окно с запросом.
Пример окна:
![Screenshot_1](https://user-images.githubusercontent.com/18256848/127648955-f59a6625-bf87-4edd-b3c4-e929029b5600.png)

**Comment by Evg-lylyk** [comment]
Не получается воспроизвести. Уточни когда, как это происходит?

**Comment by Evg-lylyk** [comment]
Воспроизвел постараюсь решить эту проблему

**Comment by Evg-lylyk** [comment]
Поработал с этой проблемой в 2.0.1
