### ISSUE TITLE
Неверно вычисляется позиция вставки для форматной строки

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#365]
**Описание ошибки**
Если в консоли кода содержится строковый литерал, то диалог форматной строки вставляет результат своей работы некорректно, считая строковый литерал частью редактируемой форматной строки.

**Сценарий воспроизведения**
Открыть консоль кода. Ввести следующий текст:
```bsl
Текст = "Произвольный";
ФСтрока = 
```
В конце второй строки расположить курсор и с помощью контекстного меню открыть конструктор форматной строки. Убедиться, что перед открытием конструктора не появился вопрос о создании новой форматной строки.

Произвольным образом отредактировать в диалоге форматную строку и нажать "ОК". Убедиться, что форматная строка была вставлена в конец первой строки кода, удалив при этом вторую.

**Ожидаемое поведение, если бы ошибки не было**
Форматная строка должна быть вставлена в конец второй строки кода, без удаления фрагментов текста.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/127651622-a2dd8da9-656b-4392-add9-066872296c2f.png)
![image](https://user-images.githubusercontent.com/59051827/127651634-a0469869-d2fe-490e-a6af-33eea0c9dfa2.png)

**Окружение:**
Infostart Toolkit 2.0.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.1
