### ISSUE TITLE
Отсутствует контекстная подсказка по методам массива

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#366]
**Описание ошибки**
В консоли кода контекстная подсказка для объекта типа "Массив" не содержит методов массива.

**Сценарий воспроизведения**
Открыть консоль кода. В поле редактора кода ввести текст:
```bsl
МассивСсылок = Новый Массив;
МассивСсылок.Добав
```
Убедиться, что при наборе фразы `Добав` после точки отображается контекстная подсказка, не содержащая методов массива.

**Ожидаемое поведение, если бы ошибки не было**
Ожидается, что в приведенном выше примере подсказка будет содержать методы `Добавить`, `Вставить` и другие методы массива.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/127835413-5c56f206-97e8-48ac-8f22-75960a34ef94.png)

**Окружение:**
Infostart Toolkit 2.0.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
Уточнение. Оказалось, контекстная подсказка работает, если объекты создавать с помощью конструктора без параметров, но при этом не опуская скобки:
```bsl
МассивСсылок = Новый Массив();
```
Аналогично и для других объектов, например `СписокЗначений`, `ТаблицаЗначений `и другие. Не знаю даже, ошибка это, или можно переквалифицировать мой issue в пожелание.

**Comment by Evg-lylyk** [comment]
Известная проблема, решим

**Comment by Evg-lylyk** [comment]
Исправлен 2.0.3
