### ISSUE TITLE
Вывод особых значений

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#367]
**Существует проблема**
В текущей реализации консоли запросов (версия 2.0.0) есть возможность вывода т.н. особых значений в результате запроса. К ним относятся значения NULL, пустая строка и пустая ссылка. Однако здесь не хватает еще пустых значений: `0` и `Неопределено`. Без отображения этих значений становится непонятно, что именно за значение оказалось в ячейке, т.к. к нему нет своего представления.

Дополнительно к этому особняком стоит значение `NULL`, которое также относится к особым значениям, опционально выводимым в таблице результата, однако от прочих пустых значений отличается цветом текста.

**Хотелось бы иметь следующую функциональность**
Не помешало бы дополнить перечень особых значений, выводимых в результате, значениями `0` и `Неопределено`. Также, хотелось бы унифицировать оформление таких значений, выводя значение `NULL` серым цветом.

**Comment by Evg-lylyk** [comment]
Решено, в версии 2.0.1 будет
