### ISSUE TITLE
Выбор составного типа в консоли запросов

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#368]
**Описание ошибки**
В запросе пишу условие условие на реквизит составного типа.

![image](https://user-images.githubusercontent.com/18395787/128230954-efeb8c32-baf0-41c5-b1e6-a41c441ae7af.png)

на закладке параметры - указывают значение реквизита.

![image](https://user-images.githubusercontent.com/18395787/128229657-f12df4c8-075e-461c-b369-9d971ed01c4e.png)

**Окружение:**

   Infostart Toolkit 2.0.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Исправил в 2.0.2
