### ISSUE TITLE
Редактор объекта: Поле объекта не обнаружено (Использование)

### ISSUE THREAD

**Issue by AimDima** [infostart-hub/toolkit#369]
**Описание ошибки**
Ошибка при вызове редактора объекта для справочника "Номенклатура":

Поле объекта не обнаружено (Использование)
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1090)}:		Результат = (Объект.Использование = ИспользованиеРеквизита.ДляГруппыИЭлемента)
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(840)}:		Если ОбъектСИерархией 
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(679)}:		ДанныеОбъекта = ПрочитатьДанныеОбъекта(ИзменяемыйОбъект, ОбъектЗаполнения, УникальныйИдентификатор);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1595)}:	ЗаполнениеДанныхПоОбъекту(ОбрабатываемыйОбъект);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(135)}:	ОбновитьДанныеОбъекта();
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1948)}:	ОбрабатываемыйОбъектПриИзменении(Элемент);
{InfostartToolkit Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(69)}:	ОбрабатываемыйОбъектИзменен(ОбрабатываемыйОбъект);
{InfostartToolkit ОбщийМодуль.ИТК_ФормаКлиент.Модуль(664)}:	ОткрытьФорму("Обработка.ИТК_РедакторОбъекта.Форма", Параметры, , Объект.УникальныйИдентификатор());
{InfostartToolkit ОбщийМодуль.ИТК_ИнтеграцияВКонфигурациюКлиент.Модуль(5)}:	ИТК_ФормаКлиент.ОткрытьРедакторОбъекта(Ссылка);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(190)}:			ВыполнитьОбработкуОповещения(Обработчик, ПараметрКоманды);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(60)}:	ПродолжитьВыполнениеКоманды(Контекст);
{Справочник.Номенклатура.Форма.ФормаЭлемента.Форма(2310)}:	ПодключаемыеКомандыКлиент.ВыполнитьКоманду(ЭтотОбъект, Команда, Объект);

**Сценарий воспроизведения**
1. Вызов редактора через форму элемента справочника "Номенклатура" / Выбор справочника "Номенклатура" непосредственно в редакторе

**Окружение:**
Infostart Toolkit 1.9.7

Платформа: 8.3.16.1876 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация для Беларуси, редакция 2.4 (2.4.12.111)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.2.500

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19043))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
Возможно дубль #354

**Comment by Evg-lylyk** [comment]
> Возможно дубль #354

Да, спасибо

**Comment by Evg-lylyk** [comment]
Ошибка исправлена в 1.9.8 и 2.0.0, подождите обновления
