### ISSUE TITLE
Возможность указать прямой порядок вывода результатов запроса (сейчас выводит в обратном)

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/toolkit#370]
**Существует проблема**

Отлаживаю пакетный запрос:

Запрос пакета 1
Запрос пакета 2

В результаты у меня вывод в обратном порядке:

Результат запроса пакета 2
Результат запроса пакета 1

Из-за этого у меня взрывается мозг: я смотрю в дерево запросов и вижу там порядок 1 - 2 и автоматически результаты сопоставляю с ними в порядке следования таблиц, потом вижу, что таблицы по составу полей другие и уже начинает включаться голова, смотришь заголовки таблиц результатов и понимаешь, что порядок обратный.

**Хотелось бы иметь следующую функциональность**

Хотелась бы, чтобы можно было сказать "покажи мне результаты в порядке следования запросов.
Это удобнее когда в пакете несколько запросов, результат которых не помещается во временную таблицу.

**Дополнительный контекст**

![2021-08-06_15-27](https://user-images.githubusercontent.com/1042299/128504392-d57c9ca4-2fd1-41ec-99d9-58f1e69831a7.png)

**Comment by Evg-lylyk** [comment]
Задумывалось что чаще всего результат в конце пакета для этого!, а так есть настройка ты не первый :)
![Screenshot_1](https://user-images.githubusercontent.com/48444742/128508378-a7f7ce40-cd79-483a-92f4-e3bca795e124.png)

**Comment by kuntashov** [comment]
Отлично, спасибо! А ведь я смотрел, прежде чем написать, но почему-то не увидел.
Почему так сделано я понимаю, но у меня привычка другая.
