### ISSUE TITLE
Просмотр объектов встроенного языка

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#371]
**Существует проблема**
Довольно часто при работе с консолью кода появляется желание просмотреть содержимое коллекций встроенного языка, таких как структура, соответствие, таблица значений. Например, при получении объектов указанного типа как результата некоторой функции типовой конфигурации. И для просмотра всякий раз приходится писать код по выводу содержимого коллекций в сообщениях.

**Хотелось бы иметь следующую функциональность**
Нужна возможность отображения в отдельном окне содержимого результата выполнения кода в консоли, если результат имеет тип:
- [x] Структура
- [x] Массив
- [x] Соответствие
- [x] ФиксированнаяСтруктура
- [x] ФиксированныйМассив
- [x] ФиксированноеСоответствие
- [x] СписокЗначений
- [x] ТаблицаЗначений
- [x] ДеревоЗначений
- [ ] ХранилищеЗначения

Для отображения объектов встроенного языка мне представляется отдельное диалоговое окно, похожее (не обязательно) на окно вычисления выражений в отладчике. Окно открывается при клике на гиперссылке "Результат" в консоли кода. Также должна сохраниться возможность просмотра вложенных объектов.

Возможность просмотра объектов встроенного языка помимо консоли кода будет актуальна и для инструментов: "Редактор параметров сеанса", "Редактор констант", иногда "Редактор объекта"

**Дополнительный контекст**
Infostart Toolkit 2.0.1

**Comment by dipsy** [comment]
Присоединяюсь к просьбе

**Comment by Evg-lylyk** [comment]
Частично реализовано в версии 2023.4 в новой консоли, не все типы поддерживаются, пока только начало
![image](https://github.com/infostart-hub/toolkit/assets/48444742/a61370de-5465-4995-a7a6-30b9975fc2ec)
и в отдельном окне
![image](https://github.com/infostart-hub/toolkit/assets/48444742/b1e54288-77eb-4f14-b470-9d7b5518d2c9)
Буду анализировать, доделывать удобство и внедрять в другие места

**Comment by Evg-lylyk** [comment]
В основном задача реализовано, детали буду дорабатывать в других задачах и по обратной связи
