### ISSUE TITLE
Неверно переносятся параметры из пользовательских настроек в анализ запроса

### ISSUE THREAD

**Issue by toypaul** [infostart-hub/toolkit#373]
**Описание ошибки**
Если в консоли СКД выполнить отчет с пользовательскими настройками, то далее из анализа запроса неверно переносятся значения параметров.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Формируем отчет с пользовательской настройкой. У меня в отчете 2 набора и только в одном наборе добавляются параметры (может это важно?)
2. Затем жмем "анализ запросов" рядом с кнопкой выполнить
3. Здесь значения параметров верные
4. Выбираем второй набор (его запрос нужно анализировать)
5. Жмем "Анализировать запрос"
6. При это в консоли добавляется запрос с параметрами, но значение параметра не перенеслось. Хотя
сам параметр и вид сравнение перенеслись

**Ожидаемое поведение, если бы ошибки не было**
Нужно чтобы значение параметра переносилось также

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

   - Платформа 1С: *
   - Имя конфигурации: *
   - Язык: *
   - Операционная система: *
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Исправлено в  2.0.4
