### ISSUE TITLE
Контекстная подсказка по объектам метаданных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#374]
**Существует проблема**
В настоящее время (Infostart Toolkit 2.0.3) консоль кода при использовании редактора Монако не поддерживает контекстную подсказку по именам объектов метаданных.
![image](https://user-images.githubusercontent.com/59051827/131869676-31fb836f-3ad7-489f-86b3-606d2cd2442d.png)

**Хотелось бы иметь следующую функциональность**
Аналогично тому, как это реализовано для менеджеров объектов конфигурации, хотелось бы видеть и контекстную подсказку для коллекций метаданных. Дополнительным приятным бонусом было бы вычисление типа переменной как "ОбъектМетаданных", дабы можно было видеть подсказку и дальше по общим методам для всех объектов метаданных ("Имя", "ПолноеИмя"). Совсем замечательно было бы, если б тип переменной вычислялся с точностью до конкретного объекта метаданных, и мы могли бы видеть полноценную подсказку по полям и методам объекта. Например, для объекта типа "ОбъектМетаданных: РегистрСведений" можно было получить в подсказке "Измерения", "Ресурсы" и т.д.

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.3.1
