### ISSUE TITLE
Конструктор СКД: фоку при добавлении набора данных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#379]
**Описание ошибки**
При первом открытии конструктора СКД и добавлении первого набора данных фокус ввода оказывается на добавленном наборе данных. При этом курсор в поле текста запроса мерцает, и кажется, будто фокус ввода располагается именно в поле ввода. Т.о. сразу при наборе текста с клавиатуры вместо ожидаемого ввода текста запроса включается редактирование имени набора данных.

Переименование набора данных - редкая операция. Лучше фокус ввода переводить на поле ввода текста запроса.

**Окружение:**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправил в 2.2.0
