### ISSUE TITLE
Конструктор СКД: очистка роли поля

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#380]
**Описание ошибки**
Поле набора данных имеет уже заполненную колонку роли. Если используя контекстное меню выполнить очистку роли, то колонка визуально очистится, но роль никуда не денется. При открытии редактора роли поля ранее проставленные флажки останутся на месте.

**Ожидаемое поведение, если бы ошибки не было**
После очистки роли поля через контекстное меню все флажки в редакторе роли должны оказаться сброшенными.

**Окружение:**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.4
