### ISSUE TITLE
Конструктор СКД: ввод имени остатка для роли поля

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#381]
**Описание ошибки**
В редакторе роли для поля набора данных есть поле ввода имени остатка. Оно предлагает выбрать имеющееся поле набора, что неверно. Имя остатка - это строковый идентификатор, по которому поля набора попарно группируются. Оно может быть совершенно произвольным и к именам полей набора не имеет никакого отношения.

**Ожидаемое поведение, если бы ошибки не было**
Удобно было бы следующее. Пусть имеется 4 поля набора данных:
1. КоличествоНачальныйОстаток
2. КоличествоКонечныйОстаток
3. СуммаНачальныйОстаток
4. СуммаКонечныйОстаток

Редактируем роли полей последовательно, каждому из них указываем роль "Остаток" и заполняем "Имя":
1. Вводим имя для **КоличествоНачальныйОстаток**. Конструктор умный: видит, что поле заканчивается на "НачальныйОстаток" или "КонечныйОстаток" (плюс возможны вариации сокращений типа "НачОст") и предлагает выбрать имя **Количество**. Его и выбираю.
2. Вводим имя для **КоличествоКонечныйОстаток**. Конструктор предлагает тот же вариант - **Количество**. Выбираю.
3. Вводим имя для **СуммаНачальныйОстаток**. Конструктор умный: предлагает мне вариант **Сумма**. Мне по какой-то причине не нравится такой вариант и я самостоятельно ввожу руками **Стоимость**.
4. Вводим имя для **СуммаКонечныйОстаток**. Конструктор уже предлагает два варианта: **Сумма** (извлек из имени поля) и **Стоимость** (ранее вводили для другого поля). Я выбираю второй.

Резюмирую:
* Для просты случаев, когда имя поля набора задано по шаблону "<Ресурс>НачальныйОстаток" или "<Ресурс>КонечныйОстаток" предлагать в качестве имени остатка <Ресурс>.
* Дополнять предложение конструктора теми именами остатка, что я уже вводил для данного набора полей.

**Окружение:**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Реализовал в 2.2.0
