### ISSUE TITLE
Конструктор СКД: кнопки добавления наборов данных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#387]
**Хотелось бы иметь следующую функциональность**
Вынести кнопки добавления наборов данных из подменю "Еще", закрепив в командной панели списка наборов, при этом отображать их только в виде пиктограммы.

**Дополнительный контекст**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Мне кажется это некритичным можно нажать Добавить и выбрать
