### ISSUE TITLE
Конструктор СКД: не обновляется счетчик параметров

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#391]
**Описание ошибки**
После набора текста запроса, если в нем указан параметр запроса, то соответствующий параметр СКД появляется на закладке "Параметры", но счетчик параметров (в заголовке закладки) не обновляется.

Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.4
