### ISSUE TITLE
Конструктор СКД: предлагать выбор параметров в связях набора

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#392]
**Хотелось бы иметь следующую функциональность**
При добавлении связей между наборами данных в колонке "Параметр" хотелось бы иметь возможность выбирать из имеющихся.

**Дополнительный контекст**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Реализовано в 2.2.0
