### ISSUE TITLE
Конструктор СКД: ошибка при редактировании заголовка вычисляемого поля

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#393]
**Описание ошибки**
При завершении редактирования заголовка вычисляемого поля в отдельном окне возникает ошибка:

> Поле объекта не обнаружено (Имя)
> {InfostartToolkitPROF Обработка.ИТК_КонструкторСКД.Форма.Основная.Форма(4283)}:	ТекущиеДанные["ЗаголовокПредставление"] = ПредставлениеЗаголовкаПоляКоллекции(Результат, ТекущиеДанные[ИмяПоля]);
> {InfostartToolkitPROF ОбщаяФорма.ИТК_КонструкторСтрокНаРазныхЯзыках.Форма(53)}:	Закрыть(Результат);

**Окружение:**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.4
