### ISSUE TITLE
Конструктор СКД: нет иерархических группировок для расчета ресурсов

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#394]
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
![image](https://user-images.githubusercontent.com/48444742/132531969-0f218bc9-7620-48c5-a699-22c4ea301769.png)
Ты про это? Вроде есть

**Comment by d-hurricane** [comment]
Да, я про это.

Перепроверил. Этой строчки нет для полей набора данных типа "Объект".

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.4
