### ISSUE TITLE
СтандартныйПериод в контекстной подсказке Монако

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#395]
**Существует проблема**
В редакторе кода на основе Монако отсутствует поддержка подсказом по объекту встроенного языка "СтандартныйПериод". Это заметно в первую очередь при работе с параметрами в конструкторе СКД.

**Дополнительный контекст**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Реализовано в 2.1.0
