### ISSUE TITLE
Конструктор СКД: не работает кнопка "Удалить ресурс".

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#396]
**Описание ошибки**

> Недопустимое значение параметра (параметр номер '1')
> {InfostartToolkitPROF Обработка.ИТК_КонструкторСКД.Форма.Основная.Форма(1399)}:	Ресурсы.Удалить(ТекущиеДанные);
> 
> по причине:
> Недопустимое значение параметра (параметр номер '1')

**Окружение:**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.4
