### ISSUE TITLE
Контекстная подсказка по аргументам реагирует на запятые в строковых литералах

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#397]
**Описание ошибки**
В редакторе кода Монако при наборе аргументов метода отображение подсказки по аргументам реагирует на наличие запятых внутри строкового литерала как на разделитель аргументов.

**Ожидаемое поведение, если бы ошибки не было**
Запятые внутри строки не должны влиять на подсказку.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/132376387-bc705d11-f9c8-487f-aa3d-5ea7d116d816.png)

**Окружение:**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправлено в 2.1.1
