### ISSUE TITLE
Конструктор СКД: кнопка отмены

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#399]
**Существует проблема**
После внесения изменений в СКД и при нажатии "Отмена" появляется окно с предложением сохранить схему. Кажется это действие нелогичным: зачем мне сохранять то, что я пытаюсь отменить.

**Хотелось бы иметь следующую функциональность**
При нажатии на "Отмена" либо не задавать вопрос вовсе и тихо отменять внесенные правки, либо предупреждать о возможной потери изменений и предлагать прервать процесс отмены.

**Дополнительный контекст**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Исправлено в 2.1.0. Закрываю без предупреждение, такое же поведение в стандартном конструкторе
