### ISSUE TITLE
Отметка <Авто> для номера и кода в редакторе объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#407]
**Существует проблема**
Нет.

**Хотелось бы иметь следующую функциональность**
В редакторе объекта, аналогично тому, как это сделано для ссылки нового объекта, выводить в поле "Код" справочников и "Номер" документов надпись "<Авто>", если у объекта метаданных установлен признак автонумерации.
![image](https://user-images.githubusercontent.com/59051827/132855198-3739f44f-ccbd-4cdb-8804-66bb1daf9373.png)

**Дополнительный контекст**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Реализовано в 2.2.0
