### ISSUE TITLE
Некорректно работает отбор подписок по подстроке

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#408]
**Описание ошибки**
На панели "Подписки на события" некорректно работает поиск по подстроке: в результат поиска попадают лишь те подписки, что содержат подстроку поиска и в имени, и в синониме. Т.е. когда выполняются **оба** условия.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть конфигуратор ИБ. Добавить подписку на событие с именем "МояПодписка" и синонимом "Подписка". Добавить любой источник события подписки и общий модуль с обработчиком.
2. Обновить конфигурацию ИБ и запустить ее.
3. Открыть панель "Подписки на события".
4. Ввести в поле отбора подписок строку "Моя" и нажать Enter. Убедиться, что добавленная на первом шаге подписка найдена не была.

**Ожидаемое поведение, если бы ошибки не было**
В результате поиска должны оказаться подписки, что содержат подстроку поиска либо в имени, либо в синониме, т.е. при выполнении хотя бы **одного** из этих условий.

**Окружение:**
Infostart Toolkit 2.0.3

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.0.4
