### ISSUE TITLE
Конструктор СКД: выражения полей ресурсов по умолчанию

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#409]
**Существует проблема**
В настоящий момент при добавлении поля в список ресурсов в зависимости от типа поля применяется свое выражение ресурса:
* для числовых полей - Сумма;
* для остальных - Количество

**Хотелось бы иметь следующую функциональность**
Незначительное пожелание - дополнить зависимость выражения иными примитивными типами:
* для числовых полей - Сумма;
* для булево и дат - Максимум;
* для строк - СоединитьСтроки;
* для остальных - Количество.

**Дополнительный контекст**
Infostart Toolkit 2.0.3

**Comment by Evg-lylyk** [comment]
Реализовано в 2.1.0, вместе с незначительными пожеланиями ;)
