### ISSUE TITLE
Автовысота строк в условиях конструктора запросов

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#41]
Когда условие многострочное не видно весь текст обычно отображается 2-ве строки

**Comment by AnatoliyBritko** [comment]
![image](https://user-images.githubusercontent.com/18395787/94804964-50f3f180-03f4-11eb-8157-66ceaf18d70a.png)

надо эти свойства настроить

**Comment by Evg-lylyk** [comment]
Реализовано в версии 1.4. поставил не более 5 строк
