### ISSUE TITLE
Не работает контекстная подсказка по методам модуля

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#416]
**Описание**
Попытка использовать метод "ОбщегоНазначения.ЗначенияРеквизитовОбъекта" (БСП) окончилась неудачей.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/135345570-1e50dc0b-cf4f-4866-ba9d-d0eb66f582a4.png)

**Окружение:**
Infostart Toolkit 2.1.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.220)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.535

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проверяю на Файлах БСП 3.1.5.146 все ОК
![image](https://user-images.githubusercontent.com/48444742/135395898-828ca211-8949-45bc-b434-bcc6aaca5dd8.png)

**Comment by Evg-lylyk** [comment]
Загрузил файлы БСП 3.1.3.535, тоже все ОК
У тебя список меньше может попробовать писать название дальше
У меня другой набор функций, отличается от твоего скрина

**Comment by Evg-lylyk** [comment]
У тебя подсказки глобального контекста, настройка выгруженные файлы задана?!
Нужно больше деталей, у меня все работает

**Comment by d-hurricane** [comment]
Да, прошу прощения, в настройки не заходил. Указал каталог с выгрузкой, и все заработало.

В таком случае хочу отметить, что поведение не очевидное:
* если не указан каталог, подсказка есть, но не соответствует контексту
* каталог в "прочих" настройках, когда есть настройки редактора (может консоль кода вынести на отдельную закладку настроек?)
* ну и кнопка выбора в поле настройки каталога не помешает ;-)

Спасибо, буду пробовать новый функционал.

**Comment by Evg-lylyk** [comment]
> * если не указан каталог, подсказка есть, но не соответствует контексту
Я это проверял у меня после точки нет подсказки видимо если потом нажать Ctrl + Space

> * каталог в "прочих" настройках, когда есть настройки редактора (может консоль кода вынести на отдельную закладку настроек?)
Подумал что обращение к модулям может понадобится в других инструментах например сейчас в Подписках на события можно добавить возможность открывать и просматривать модуль подписки
Будет новость в ней будет описание где указывать путь к модулям

> * ну и кнопка выбора в поле настройки каталога не помешает ;-)
Не стал делать т.к. это не критично и будущем наверно нужна будет возможностей указывать несколько путей через ";"
для считывания объектов расширений

**Comment by d-hurricane** [comment]
> Я это проверял у меня после точки нет подсказки видимо если потом нажать Ctrl + Space
Нет, при наборе текста, после ввода первого же символа за точкой.

**Comment by Evg-lylyk** [comment]
Подсказка не идеальна :(, в будущем решим этот вопрос

**Comment by d-hurricane** [comment]
Да все равно супер. Прям на порядок легче с консолью работать стало.
