### ISSUE TITLE
Консоль запросов: не обновляется текст запроса во временной таблице дерева запросов

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#417]
**Описание ошибки**
Не обновляется текст запроса во временной таблице дерева запросов

**Сценарий воспроизведения**
Шаги по воспроизведению:
Открыл сохраненный запрос из "Настройка"
Скопировал запрос в "Запрос - копия"
Начал править текст в запросе

**Ожидаемое поведение, если бы ошибки не было**
Запрос в временной таблице изменится

**Скриншоты**
![КонсольЗапросов](https://user-images.githubusercontent.com/65346358/135389871-d6ed0d2e-7113-48d6-a0ac-637126addf11.gif)

**Окружение:**

Infostart Toolkit 2.0.4

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.18.120)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.295

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Нужно нажимать Проверить запрос
Если бы после каждого изменения перестраивалось дерево это бы доставляло неудобства
