### ISSUE TITLE
Консоль запросов - Конструктор запросов: Не обновляются поля в конструкторе параметров связи

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#418]
**Описание ошибки**
Добавляю поле в временную таблицу, а в следующем пакете, при составлении связей, оно не появляется

**Сценарий воспроизведения**
Шаги по воспроизведению:
Открыть конструктор запроса
Добавить поле в пакет
В следующем пакете открыть конструктор связи

**Ожидаемое поведение, если бы ошибки не было**
Поле должно появиться

**Скриншоты**

![КонсольЗапросов_КонструкторЗапросов](https://user-images.githubusercontent.com/65346358/135390843-68fa6454-af3b-426e-945a-87443a1cb977.gif)

[ЗапросОшибка.zip](https://github.com/infostart-hub/toolkit/files/7256817/default.zip)

**Окружение:**

Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

Infostart Toolkit 2.0.4

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.18.120)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.295

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Улучшенный конструктор базируется на стандартном от 1С, а в нем всегда был такой баг, он записан внизу #75
в будущем планируется его исправить.
