### ISSUE TITLE
Ошибка при сохранении схемы компоновки данных (СКД)

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#425]
**Описание ошибки**
Ошибка при попытке сохранения схему компоновки данных из конструктора

**Сценарий воспроизведения**

Выбираю сохранить схему

![image](https://user-images.githubusercontent.com/18395787/136512998-8b0ee250-f1b1-4c9b-95f8-1971aa3d76cb.png)

появляется такая ошибка

![image](https://user-images.githubusercontent.com/18395787/136513075-90e0ce3c-45f5-4d9b-b8c5-544c811191e6.png)
![image](https://user-images.githubusercontent.com/18395787/136513087-108bd2bc-5e4e-4dea-93b4-15a3089d418d.png)

отсюда нормально сохраняет

![image](https://user-images.githubusercontent.com/18395787/136513143-32634460-aa17-4058-90ec-4625ae49e69e.png)

и еще можно эти кнопки вытащить из раскрывающегося меню ?

![image](https://user-images.githubusercontent.com/18395787/136513308-857679e0-9f99-4afa-8469-97e01c900dfa.png)

Infostart Toolkit 2.1.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
> и еще можно эти кнопки вытащить из раскрывающегося меню ?
Это вы можете сделать самостоятельно через Изменить форму...
Пока выносить не планирую, хочется сделать минималистичный интерфейс

**Comment by AnatoliyBritko** [comment]
> Это вы можете сделать самостоятельно через Изменить форму...

да. я это понимаю
просто думал что будет для всех удобнее т.к. для ОФ они вынесены на форму

![image](https://user-images.githubusercontent.com/18395787/136525217-7cd32d7e-7b7f-411e-89b6-7c5771a10d98.png)

**Comment by Evg-lylyk** [comment]
Исправил в 2.1.2. Добавил видимость по умолчанию кнопок как у стандартного конструктора
