### ISSUE TITLE
Пропадают элементы в группе отборов настроек СКД

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#426]
**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Загружаю из конфигуратора.
настройки есть

![image](https://user-images.githubusercontent.com/18395787/136526307-05f920f6-8ed6-45b4-b309-b38a37a1d236.png)

нажимаю ОК.
Открываю заново конструктор

![image](https://user-images.githubusercontent.com/18395787/136526335-c953c450-5b5f-49a9-9f0e-22a7988b0f9a.png)

**Окружение:**

  Infostart Toolkit 2.1.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.1.2
