### ISSUE TITLE
Ошибка поиска строкового литерала для редактирования конструктором

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#433]
**Описание ошибки**
В некоторых ситуациях редактор кода (Монако) неверно вычисляет позицию строкового литерала, внутри которого открывается какой-либо конструктор (например, конструктор запроса). По наблюдениям это происходит, если строковый литерал стоит первым в строке.

**Сценарий воспроизведения**
Открыть редактор кода. Ввести следующий текст на двух строчках без отступов:
```bsl
ТекстЗапроса = 
"";
```
Установить курсор между двойными кавычками на второй строке. С помощью контекстного меню открыть конструктор запроса. На предложение о создании нового запроса ответить утвердительно.

Отредактировать произвольным образом запрос в конструкторе и нажать "Ок". Убедиться, что текст запроса, сгенерированный конструктором, окажется не между ранее введенными двойными кавычками, а справа от них. При этом пропадет точка с запятой.

**Ожидаемое поведение, если бы ошибки не было**
Текст запроса должен быть вставлен между кавычками. Ни кавычки, ни точка с запятой пропасть не должны.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/139434025-f3b1894e-82a2-4c52-8a5c-9dab6999a08d.png)
![image](https://user-images.githubusercontent.com/59051827/139433924-1a318d3d-dcb8-42fa-a594-2dbbf6d4fdf0.png)

**Окружение:**
Infostart Toolkit 2.1.2

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление нашей фирмой, редакция 1.6 (1.6.25.236)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.368

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 2.2.0
