### ISSUE TITLE
Некорректный вопрос о применении изменений в конструкторе запроса тонкого клиента

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#434]
**Описание ошибки**
В продвинутом конструкторе запроса для тонкого клиента имеется возможность отредактировать текст запроса вручную. Для этого необходимо нажать в левом нижнем углу конструктора кнопку "Запрос" и в появившемся окне отредактировать текст как нужно. Если же внесенные изменения оказались не нужны, при нажатии на кнопку "Отмена" разработчику будет задан вопрос: "Применить изменения?" с вариантами ответов "Да/Нет/Отмена".

Вопрос сам по себе некорректен, т.к. не соответствует совершаемым мной действиям, ведь я пытаюсь именно отменить изменения, а не внести их.

**Ожидаемое поведение, если бы ошибки не было**
Кажется, что здесь подошел бы иной вопрос: "Изменения будут утеряны. Продолжить?" с теми же вариантами ответов.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/139435862-bd4bdcba-af40-4854-b263-4b33c537dbe0.png)

**Окружение:**
Infostart Toolkit 2.1.2

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление нашей фирмой, редакция 1.6 (1.6.25.236)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.368

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проанализировал. С одной стороны ты прав, но чтобы это исправить нужно менять привычный диалог. В толстом конструкторе он такой же. Решил не делать
