### ISSUE TITLE
Метод недоступен для невидимого элемента

### ISSUE THREAD

**Issue by igorefremovsmm** [infostart-hub/toolkit#435]
**Описание ошибки**
В конструкторе запросов, при добавлении новой таблицы в соединение и переходе на вкладку "Связи" ошибка:
`Метод недоступен для невидимого элемента.
{InfostartToolkitPROF Обработка.ИТК_QueryWizard17181920.Форма.QueryWizard.Форма(292)}:				Items.Joins.Expand(Joins.GetItems().Get(0).GetID(), True);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard17181920.Форма.QueryWizard.Форма(186)}:		PostFillAtClient(PagesItems);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard17181920.Форма.QueryWizard.Форма(4640)}:	FillPagesAtClient();

по причине:
Метод недоступен для невидимого элемента.`

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть Консоль запросов
2. Нажать Конструктор...
3. Добавить в Таблицы любые два запроса 
4. Перейти на вкладку "Связи", будет ошибка

**Окружение:**
Infostart Toolkit 2.1.2

Платформа: 8.3.18.1563 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Собственная разработка
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: БСП не установлена

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, разобрался ошибка проявляется в высоких режимах совместимости
Исправил с версии 2.2.0

**Comment by Evg-lylyk** [comment]
Также будет отдельное исправление 2.1.3
