### ISSUE TITLE
Преобразование текста запроса после вставки из модуля

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#437]
При копировании/вставке текста запроса из программного модуля его нужно преобразовать в нормальный вид:
 - удалить начальные отступы вместе с `|`
 - двойные кавычки преобразовать в одинарные

**Пример**

```
ВЫБРАТЬ
        |    Т.Ссылка КАК Ссылка,
        |    Т.Наименование КАК Наименование,
        |    ВЫБОР
        |        КОГДА Т.ЭтоГруппа
        |            ТОГДА ""Группа""
        |        ИНАЧЕ ""Элемент""
        |    КОНЕЦ КАК Вид
        |ИЗ
        |    Справочник.Номенклатура КАК Т
```

нужно преобразовать в

```
ВЫБРАТЬ
    Т.Ссылка КАК Ссылка,
    Т.Наименование КАК Наименование,
    ВЫБОР
        КОГДА Т.ЭтоГруппа
            ТОГДА "Группа"
        ИНАЧЕ "Элемент"
    КОНЕЦ КАК Вид
ИЗ
    Справочник.Номенклатура КАК Т
```

Можно для этого сделать специальную кнопку в меню Инструменты.

**Comment by Evg-lylyk** [comment]
Приветствую, уже есть такое
![Screenshot_1](https://user-images.githubusercontent.com/48444742/140319106-47b340f8-31de-46c5-988f-cafc0459c620.png)
