### ISSUE TITLE
Выбор выводимых результатов пакета запросов

### ISSUE THREAD

**Issue by shureek** [infostart-hub/toolkit#449]
**Существует проблема**
При отладке пакетных запросов из типовых конфигураций в них бывает очень много запросов. Не все их результаты требуют внимания.

**Хотелось бы иметь следующую функциональность**
Хотелось бы иметь возможность выбирать какой из результатов выводить. Видел подобную фичу в другой консоли. Там сбоку есть такая панелька со всеми запросами пакета, с кол-вом результатов, временем выполнения и флагом выводить/нет:  
![image](https://user-images.githubusercontent.com/2562878/141103620-9c244c83-314e-4d6b-8b13-ceea00fcb691.png)

**Comment by Evg-lylyk** [comment]
В консоли разработчика для запросов есть на закладке Прочее - Настройка вывода таблиц
для анализа времени выполнения Инструменты - Замер пакетного запроса

Есть одна особенность настройки вывода... что результирующие запросы не включаются отдельно. Потому как есть сценарий: 1. Добавляем пакет 3 запроса ставим что результат 2 не выводить, 2. Потом заходим в конструктор меняем на 1 запрос
и как корректно определять что выводить что нет, не говорю что это не решаемо, но не боролся с этими сложностями. В других инструментах эта проблема просто не учитывается

**Comment by shureek** [comment]
Да, вспомнил что видел эту настройку. Она либо не работает, либо работает некорректно. Опишу в отдельную issue
