### ISSUE TITLE
Контекстная подсказка в консоли кода для имен типов в описании типа

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#451]
**Существует проблема**
При использовании Монако в качестве редактора консоли кода в ряде случаев значительную помощь оказывает контекстная подсказка. Однако ее нет внутри конструктора объектов типа `ОписаниеТипов` при вводе типов строкой.

**Хотелось бы иметь следующую функциональность**
При наборе имени типа внутри строкового литерала конструктора `ОписаниеТипов()` хотелось бы иметь релевантную контекстную подсказку для выбора существующих объектов конфигурации, образующих систему типов.

**Дополнительный контекст**
Infostart Toolkit 2.1.2
![image](https://user-images.githubusercontent.com/59051827/141279927-4c0505fd-2041-4570-bb4d-ea97bbccffe3.png)

**Comment by salexdv** [comment]
Со своей стороны доработал.

**Comment by Evg-lylyk** [comment]
> Со своей стороны доработал.

Спасибо. Будет работать с 2022.3.1
