### ISSUE TITLE
Контекстная подсказка по параметрам метода всегда предлагает первый вариант

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#452]
**Описание ошибки**
При вводе аргументов некоторого метода в редакторе Монако отображается контекстная подсказка с описанием параметров этого метода. Если вариантов ввода параметров несколько, с помощью горячих клавиш "Ctrl+Up" и Ctrl+Down" можно переключать описание вариантов в подсказке. Одна при дальнейшем вводе кода контекстная подсказка обратно переключается на первый вариант.

**Сценарий воспроизведения**
1. Открыть консоль кода. Ввести текст:
`Т = Новый ОписаниеТипов(`
2. Появится контекстная подсказка с описанием параметров. Сочетанием клавиш "Ctrl+Down" переключиться на второй вариант (см. рис. 1).
3. Продолжить ввод аргументов конструктора типов: `"Число"`. Контекстная подсказа автоматически переключиться на первый вариант (см. рис. 2).
4. Вернемся ко второму варианту "Ctrl+Down" (рис. 3)
5. Поставим запятую как разделитель аргументов. Подсказка вновь переключится на первый вариант (рис. 4)

**Ожидаемое поведение, если бы ошибки не было**
Контекстная подсказка по параметрам метода не должна самостоятельно переключаться. По крайней мере в ситуациях, когда текущему набору аргументов может соответствовать несколько вариантов. В приведенном выше примере автопереключение подсказки мешает вычислять позицию аргумента с квалификаторами типов.

**Скриншоты**
Рисунок 1.
![image](https://user-images.githubusercontent.com/59051827/141755504-2eb18682-f1b5-419b-9e01-3fe3eabf78a3.png)
Рисунок 2.
![image](https://user-images.githubusercontent.com/59051827/141756183-458acead-cde0-4e23-bff3-3a33d27cc02f.png)
Рисунок 3.
![image](https://user-images.githubusercontent.com/59051827/141756210-ace56e59-b4a6-43f3-baab-56920d6b3c36.png)
Рисунок 4.
![image](https://user-images.githubusercontent.com/59051827/141756242-992082f8-b849-4df8-8e4e-18fbdc05a74b.png)

**Окружение:**
Infostart Toolkit 2.1.2

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление нашей фирмой, редакция 1.6 (1.6.25.236)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.368

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by salexdv** [comment]
В редакторе данная ошибка устранена

**Comment by Evg-lylyk** [comment]
> В редакторе данная ошибка устранена

Спасибо, в туллкит с версии 2.4.2 тоже
