### ISSUE TITLE
Ошибка при попытке сохранить из отладки запрос с параметром Тип("Неопределено")

### ISSUE THREAD

**Issue by SeiOkami** [infostart-hub/toolkit#454]
**Описание ошибки**
Проблема при попытке в отладке сохранить запрос в настройки.
Если в параметрах запроса есть параметр с Типом (в моём случае - Неопределено)

**Сценарий воспроизведения**

Шаги по воспроизведению:

Выполнить на сервере код:

Запрос = Новый Запрос("ВЫБРАТЬ ТИПЗНАЧЕНИЯ(Неопределено) = &ТипНеопределено");
Запрос.УстановитьПараметр("ТипНеопределено", Тип("Неопределено"));
ИТК.Отл(Запрос);

**Ожидаемое поведение, если бы ошибки не было**
Сохранение должно быть произведено 

**Скриншоты**

![2021-11-20 20_25_43-Демонстрационная база _ 1С_ERP Управление предприятием 2](https://user-images.githubusercontent.com/42138875/142735592-1af175ed-c4c4-44ab-ab04-50d140d76f5e.png)

**Окружение:**

Пробовал на разных конфигурациях. Указал типовую демо

Infostart Toolkit 2.1.3

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.6.291)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.573

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru_RU
Режим запуска: Управляемое приложение

 **Дополнительный контекст**
Данный запрос выполняется успешно. И сохраняется из консоли в файл. Но при попытке сохранить из отладки будет ошибка

**Comment by Evg-lylyk** [comment]
Исправлено в версиях 2.2.4, 2.3
