### ISSUE TITLE
Баги при увеличении шрифта при помощи Ctrl+КолесоМыши

### ISSUE THREAD

**Issue by SeiOkami** [infostart-hub/toolkit#455]
**Описание ошибки**
При увеличении шрифта в поле текста запроса проявляются баги отображения.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль запроса
2. Увеличить шрифт в поле текста при помощи Ctrl+КолесоМыши
3. Вводить текст запроса

**Ожидаемое поведение, если бы ошибки не было**
Интерфейс подстраивается под увеличенный шрифт
Или при изменении шрифта менять его в настройках подсистемы, или заблокировать вообще такую возможность

**Скриншоты**

![1](https://user-images.githubusercontent.com/42138875/142736379-9f86db9b-534e-4f01-af9a-7f173add76e2.png)

**Окружение:**

Infostart Toolkit 2.1.3

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.6.291)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.573

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проблема известна и на данный момент не имеет решения
https://github.com/salexdv/bsl_console/issues/128
