### ISSUE TITLE
Ошибочное свойство: "FieldsList"

### ISSUE THREAD

**Issue by igorefremovsmm** [infostart-hub/toolkit#456]
**Описание ошибки**
Синтаксический контроль ругается на свойство "FieldsList" объекта QuerySchemaAvailableTableParameterType, т.к. свойство называется "FieldList" (без s).

**Сценарий воспроизведения**
Выполнить проверку конфигурации с галкой "Расширенная проверка"

**Ожидаемое поведение, если бы ошибки не было**
Заменить QuerySchemaAvailableTableParameterType.FieldsList на QuerySchemaAvailableTableParameterType.FieldList

**Comment by Evg-lylyk** [comment]
В какой момент это происходит? Какие проблемы вызывает?
Какая версия платформы. Там много ошибок при проверке расширения

**Comment by igorefremovsmm** [comment]
Только в конфигураторе при проверки конфигурации с галкой "Расширенная проверка".
Проблем не вызывает, только ошибки в SonarQube.
Версия платформы: 8.3.18.1563

**Comment by Evg-lylyk** [comment]
QueryWizart - это тонкий конструктор от 1С доработанный
Нам есть такой код "QuerySchemaAvailableTableParameterType.FieldsList" видимо он никогда не выполняется.
Не обращайте внимания себе QueryWizard занес в исключения, там что то такое править не планирую чтобы не было отличий от конструктора 1С
