### ISSUE TITLE
Ошибка при открытии сохранённого кода в Консоли кода

### ISSUE THREAD

**Issue by igorefremovsmm** [infostart-hub/toolkit#457]
**Описание ошибки**
При открытии сохранённого кода в Консоли кода, поле "Код" пустое, а при попытке что-либо внести, выдаётся ошибка:
`Получение элемента по индексу для значения не определено
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонсольРазработчикаДанныеКлиент.Модуль(45)}:	Если Данные[Имя] <> Значение Тогда
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6356)}:	ИТК_КонсольРазработчикаДанныеКлиент.ИзменитьПоле(ЭтотОбъект, ТекущаяСтрока, "Текст", ТекстКод);
{InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(703)}:			ВыполнитьОбработкуОповещения(ОповещениеМодификации);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(442)}:	ИТК_РедакторКодаКлиент.ОбработкаСобытий(ЭтотОбъект, Элемент, ДанныеСобытия, СтандартнаяОбработка, ОписаниеОповещения);`

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть Консоль кода
2. Ввести любой код, например Сообщить("Текст");
3. Нажимаем "Сохранить данные" (кнопка с картинкой "автомат с газировкой"), сохраняем куда-нибудь.
4. Закрываем Консоль кода
5. Открываем консоль кода
6. Нажимаем "Данные - Файл - Открыть", открываем сохранённый файл
7. Видим, что поле "Код" - пустое.
8. Пытаемся что-то ввести в это поле, получаем ошибку

**Ожидаемое поведение, если бы ошибки не было**
Видно сохранённый код, ошибок нет

**Окружение:**

Infostart Toolkit PROF 2.2.3

Платформа: 8.3.18.1563 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
OMS (23.25)
Основной режим запуска: Управляемое приложение
Режим совместимости: **Версия8_3_17**
Версия БСП: БСП не установлена

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru
Режим запуска: Управляемое приложение

**Дополнительный контекст**

- Не типовая конфигурация
- Режим защиты от опасных действий выключен

**Comment by Evg-lylyk** [comment]
Спасибо, за информацию, ошибка исправлена в след. версии 2.2.4
