### ISSUE TITLE
В редакторе объекта многострочный текст ячейки ТЧ открывается в одну строку

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#458]
**Описание ошибки**
В редакторе объекта, если открыть объект с табличной частью, одна из колонок которого содержит многострочный текст, то обнаружится невозможность просмотреть этот текст в отдельном окне. При открытии значения такой колонки в отдельной форме текст сольется в одну строку, заменяя символы переноса на знаки непечатаемых символов.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запустить демо-базу БСП.
2. Открыть в редакторе объекта любой объект, содержащий контактную информацию.
3. Перейти на закладку с табличными частями, выбрать ТЧ "КонтактнаяИнформация" и найти колонку "Значение". В найденной колонке должен содержаться адрес в формате json.
4. Навести курсор мыши на значение колонки и дождаться отображение всплывающей подсказки с содержимым колонки (см. рис. 1).
5. Начать редактирование значение. Кликнув на кнопку выбора [...] открыть значение в отдельном диалоговом окне.
6. Убедиться, что текст в окне открывшегося редактора записан в одну строку (см. рис. 2).

**Ожидаемое поведение, если бы ошибки не было**
В описанной ситуации редактор должен содержать многострочный текст.

**Скриншоты**
Рисунок 1. Подсказка содержит многострочный текст.
![image](https://user-images.githubusercontent.com/59051827/143412547-9a4c6be9-236a-49c0-b0cb-b8806206a001.png)

Рисунок 2. Редактор отображает многострочный текст в одну строку.
![image](https://user-images.githubusercontent.com/59051827/143412611-9b460601-1c05-4348-98de-fe42c2f47e62.png)

**Окружение:**
Infostart Toolkit PROF 2.2.3

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.291)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.573

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо за детальную информацию, проблема исправлена в 2.2.5
