### ISSUE TITLE
Редактирование типа значений для групп ПВХ

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#459]
**Описание ошибки**
В редакторе объекта доступно редактирование стандартного реквизита "ТипЗначения" плана видов характеристик, если выбрана группа.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть редактор объекта.
2. Выбрать для редактирования любой ПВХ, содержащий группы. Это могут быть "СтатьиДоходов" (ERP).
3. Выбрать в качестве редактируемого объекта любую группу ПВХ.
4. Убедиться, что реквизит "ТипЗначения" доступен для изменения.

**Ожидаемое поведение, если бы ошибки не было**
Тип значения для групп не имеет значения, поэтому должен быть недоступен для редактирования, либо вовсе скрыт.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/143417678-d519761d-0a7b-4c78-8a97-e515c90fe656.png)

**Окружение:**
Infostart Toolkit PROF 2.2.3

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.291)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.573

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.2.5
