### ISSUE TITLE
Диагностика ошибок в модуле с более 1000 строк кода.

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#460]
**Описание ошибки**
Если в редакторе кода вызвать некий метод из общего модуля, который во-первых, располагается на строке модуля больше 1000, а во-вторых, выбрасывает исключение, то такое исключение редактор кода не сможет корректно диагностировать. Вместо понятной диагностики появится сообщение о внутренней ошибке инструментов разработчика.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть демо-базу БСП 3.1. Запустить редактор кода.
2. Ввести следующий код: `М = ОбщегоНазначения.ОбщийМодуль("НекийНесуществующиМодуль");`
3. Запустить выполнение кода.
4. Убедиться, что на экране возникает сообщение об ошибке внутри модулей "ИТК".

**Ожидаемое поведение, если бы ошибки не было**
Вместо сообщение о внутренней ошибке ИТК в редакторе кода введенная строка должна загореться красным цветом, а ниже поля ввода кода должно появиться сообщение об отсутствии общего модуля "НекийНесуществующиМодуль".

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/143439317-b4d4294b-dce6-412b-aacb-f2a5f73ba6de.png)

**Окружение:**
Infostart Toolkit PROF 2.2.3

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.6.291)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.3.573

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена в 2.2.5
