### ISSUE TITLE
Ошибка получения регламентных заданий в конфигурации с отсутствующей подсистемой "РаботаВМоделиСервиса"

### ISSUE THREAD

**Issue by SeiOkami** [infostart-hub/toolkit#461]
**Описание ошибки**
Есть конфигурация, которая частично на БСП 3.1.1.151
Установлен Toolkit 2.2.5 НЕ для БСП (так как в конфигурации не хватает объекта для применения БСПшной версии)
В консоли регламентных заданий при обновлении списка фоновое задание падает с ошибкой. При этом в самом списке это не видно и список просто остается пустой

Ошибка происходит при обращении:

`ПодсистемаРаботаВМоделиСервиса = Метаданные.Подсистемы["СтандартныеПодсистемы"].Подсистемы["РаботаВМоделиСервиса"];`

Так как в конфигурации нет такой подсистемы, то падает ошибка. При этом в методе РазделениеВключеноБСП2_4ИВыше() есть проверка на существование подсистемы:

`Если Не СуществуетПодсистема("СтандартныеПодсистемы.РаботаВМоделиСервиса") Тогда`

Сейчас исправил тем, что перед ошибочной строкой кода проверяю существование подсистемы

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Взять конфигурацию БЕЗ подсистемы РаботаВМоделиСервиса
2. Применить расширение 2.2.5 (не для БСП)
3. Запустить консоль регламентных заданий
4. Список заданий пуст. При попытке добавить задание оно просто закрывается без записи. 

**Ожидаемое поведение, если бы ошибки не было**
+ Должен отображаться список регламентных заданий и должна быть возможность добавлять новые
+ Если произошла ошибка, то выводить её на экран

**Скриншоты**

На этой строке кода ошибка:
![1](https://user-images.githubusercontent.com/42138875/145156178-9e13624f-da7f-467e-8797-8fecd9afd906.png)

В другом методе есть такая проверка:
![2](https://user-images.githubusercontent.com/42138875/145156219-89801b51-73c2-4f5e-84e0-207d9c2257de.png)

Список регламентных заданий пуст

![5](https://user-images.githubusercontent.com/42138875/145156265-525af205-e541-4541-bec5-8f7e82717df5.png)

**Окружение:**

Infostart Toolkit PROF 2.2.5

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Корпоративная информационная система (1.4.118.0)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.1.151

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19043))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо за информацию, ошибка исправлена в 2.2.6 и 2.3
