### ISSUE TITLE
Работа отчета Анализ прав доступа с подсистемой прав БСП

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#462]
Группа пользователя
Пользователь водит в группы (может несколько)
Добавить в группировки, отбор (Информация в регистре СоставыГруппПользователей (фильтровать пользователей))

Профили групп доступа
Роли входят в группы доступа ТЧ Роли (элемент Идентификатор МД)
Добавить в группировки, отбор

Группы доступа
Пользователи входят в группы
Добавить в группировки, отбор Хранение ТЧ Пользователе (справочник пользователи)

Работа расшифровки открытии Пользователе, групп и других объектов
Учет регистра праваДоступа для версии с БСП

**Comment by Evg-lylyk** [comment]
Поле колонок - возможность ставить "отсутствует"
Отбор по профиляем доступа
Настройки Профили доступа - Роли

Работа отчета Анализ прав доступа с подсистемой прав БСП #462

Группа пользователя
Пользователь водит в группы (может несколько)
Добавить в группировки, отбор (Информация в регистре СоставыГруппПользователей (фильтровать пользователей)) собирать только группы

Профили групп доступа
Роли входят в группы доступа ТЧ Роли (элемент Идентификатор МД, поле ПолноеИмя)
Добавить в группировки, отбор

Группы доступа
Поле Профиль связь с профилем

Пользователи или группы пользователей входят в группы доступ ТЧ Пользователи поле пользователь
Добавить в группировки, отбор Хранение ТЧ Пользователе (справочник пользователи или группы)

Регистр сведений ПраваРолей
Работа расшифровки открытии Пользователе, групп и других объектов

4 поля
1. Пользователь (БСП)
2. Группа пользователей (БСП)
3. Профили групп доступа (БСП)
4. Группы доступа (БСП)

Команды из карточки Профили групп доступа, Пользователи и подобные
Команда Анализ прав доступа по пользователю из инструмента пользователи

**Comment by Evg-lylyk** [comment]
Что то похожее на https://infostart.ru/marketplace/997086/

**Comment by Cmapnep** [comment]
Еще такой кейс - найти пересечение прав на объект из за которых РЛС тормозит
До уровня ролей можно текущим функционалом дойти, а вот в какие профили входят роли узнать нельзя
