### ISSUE TITLE
Консоль запросов - не сохраняет значения параметра запросов с типом список

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#464]
**Описание ошибки**
При редактировании параметров запроса с типом "Список" - сохраняет только первое значение из списка.

**Сценарий воспроизведения**
В консоль набираю текст запроса с условием В (&Ссылка)

`ВЫБРАТЬ
	Контрагенты.Ссылка КАК Ссылка
ИЗ
	Справочник.Контрагенты КАК Контрагенты
ГДЕ
	Контрагенты.Ссылка В (&Ссылка)`

![image](https://user-images.githubusercontent.com/18395787/147252275-3e3c7dc2-fa49-48f0-af33-971a1eb725f9.png)

При повторном открытии редактора значения остается только первый элемент из списка.

**Окружение:**
Infostart Toolkit PROF 2.3.0

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.3.1
