### ISSUE TITLE
Ключевые слова в формах выбора типа и объектов метаданных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#466]
**Существует проблема**
В настоящий момент в форме выбора типа и форме выбора объектов метаданных (в т.ч. и "Все функции") есть поле поиска для отбора объектов конфигурации по части имени. Однако при использовании в качестве слов поиска общие термины, например "товар", результат поиска оказывается слишком большим. В него могут попасть объекты разных классов: константы, справочники, документы и прочее. Не редки ситуации, когда вместо дополнительного уточняющего слова для поиска по имени хотелось бы указать класс метаданных, среди которых нужно искать. Например, искать только среди справочников.

**Хотелось бы иметь следующую функциональность**
В ТурбоКонф эта задача решается через спец. символы. С помощью слеша в поле поиска можно указать слово для поиска не по имени объектов конфигурации, а по имени их классов. Например, для поиска товаров среди справочников достаточно ввести следующей текст в поле поиска: `товар /спр`

Хотелось бы в инструментах разработчика иметь схожую функциональность - использование спец. символов для поиска не только по части имени объектов, но и по другим свойствам. Для начала хотя бы по имени класса объектов.

**Дополнительный контекст**
Infostart Toolkit PROF 2.3.0

**Comment by Evg-lylyk** [comment]
Задача понятна, вижу как не особо полезная, усложняющая функциональность.
В большинстве вариантов можно запросом уточнить поиск

**Comment by d-hurricane** [comment]
...или пролистать список найденных объектов. :-)
Да, это не очень важная функциональность. Но на мой вкус полезная. При том без дополнительной нагрузки на интерфейс форм.

**Comment by Evg-lylyk** [comment]
я больше ориентируюсь на полнотекстовый поиск платформ старше 16, а там такое не реализовать
Закрою пока
