### ISSUE TITLE
Ошибка редактирования выражения для параметра запроса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#467]
**Описание ошибки**
В консоли запросов при попытке редактирования значения параметра, тип которого установлен как "Выражение", появляется сообщение об ошибке, редактор не открывается:

> Метод объекта не обнаружен (ОткрытьРедактированиеКода)
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(844)}:		ИТК_ФормаКлиент.ОткрытьРедактированиеКода(ЗаголовокФормы, ЗначениеПараметра.Значение, ДополнительныеПараметры);

**Окружение:**
Infostart Toolkit PROF 2.3.0

**Comment by Evg-lylyk** [comment]
Исправлена в 2.3.1
