### ISSUE TITLE
Редактор Монако перехватывает нажатие клавиши Escape

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#468]
**Существует проблема**
На примере конструктора запроса: открываем редактирование поля выборки в отдельном окне, а затем пытаемся закрыть окно без сохранения изменений, но не кнопкой "Отмена", а нажатием клавиши Esc на клавиатуре. К сожалению, окно не закроется. Этого недостатка лишен конструктор запроса платформы, а посему привычка нажимать Esc осталась.

**Хотелось бы иметь следующую функциональность**
Закрывать окно редактирования клавишей Esc, даже если в окне присутствует поле ввода редактора Монако. Мелочь, конечно, но привычка уже сформирована, и от нее не отказаться.

**Дополнительный контекст**
Infostart Toolkit PROF 2.3.0

**Comment by Evg-lylyk** [comment]
Решено в 2023.2
