### ISSUE TITLE
Окно сравнения - ошибка при копировании

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#474]
**Описание ошибки**
В окне сравнения при копировании теста - появляется ошибка

**Сценарий воспроизведения**
Шаги по воспроизведению:
Сравниваю тексты запросов

![image](https://user-images.githubusercontent.com/18395787/148729855-d223b99d-58a7-40ab-8819-8207abb18b25.png)

при копировании получаю ошибку

![image](https://user-images.githubusercontent.com/18395787/148729884-cf9ff5c3-3fed-450c-a8f5-36fde6e7ff79.png)

**Окружение:**
Infostart Toolkit PROF 2.3.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.3.2
