### ISSUE TITLE
Не работает генератор кода для обхода итогов результата запроса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#477]
**Описание ошибки**
Если текст запроса состоит из двух подзапросов, первый из которых есть создание временной таблицы, а второй содержит итоги по некоторым полям, то в форме генератора кода на встроенном языке будет недоступна настройка "По группировкам".

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль запросов. Ввести текст запроса:
```
ВЫБРАТЬ
	1 КАК Поле1,
	2 КАК Поле2
ПОМЕСТИТЬ ВТ;

ВЫБРАТЬ
	ВТ.Поле1 КАК Поле1,
	ВТ.Поле2 КАК Поле2
ИЗ ВТ КАК ВТ
ИТОГИ ПО
	Поле1
```
2. В меню "Инструменты" выбрать "Код на встроенном языке...".
3. Убедиться, что в открывшемся окне есть код обхода выборки результата запроса, но он не содержит обхода группировки по полю "Поле1", и вложенного обхода по детальным записям.
4. Убедиться, что настройка "По группировкам" недоступна для изменения.

**Ожидаемое поведение, если бы ошибки не было**
Настройка "По группировкам" должна быть доступна для изменения. При ее установке код обхода выборки должен содержать вложенный обход детальных записей.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/149917173-24e97110-4fdd-445f-8b6d-6681e8512f41.png)

**Окружение:**
Infostart Toolkit PROF 2.3.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.4.13.278)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.573

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.4
