### ISSUE TITLE
Сообщать об отключенной расшифровке таблиц значений в результате запроса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#478]
**Существует проблема**
В версии Infostart Toolkit PROF 2.3.0, если в настройках консоли отключена расшифровка таблиц значений, то результате запроса вместо значения будет отображено "<Неопределено>". Такое представление малоинформативно, и может вводить пользователя в заблуждение. Совсем неочевидно, что это не реальное значение поля в базе данных, а "заглушка" для данных, отображение которых отключено.

**Хотелось бы иметь следующую функциональность**
Лучше выводить в ячейку результата запроса более релевантную информацию, говорящую о том, что это не значение "Неопределено", а скрыты реальные данные. Например:
* Расшифровка отключена
* Таблица значений
* Документ.ЗаказКлиента.ТабличнаяЧасть
* и т.д.
При том можно оставить отображение содержимого ячейки в виде гиперссылки, но при нажатии на нее не выводить содержимое таблицы значений, а показывать сообщение о том, что расшифровка отключена.

**Дополнительный контекст**
![image](https://user-images.githubusercontent.com/59051827/149935937-ca39847e-c669-4396-b355-c11b224c4c80.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 2.4
