### ISSUE TITLE
Уменьшить шрифт, убрать акцент с ТаблицыЗначений в результате запроса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#479]
**Существует проблема**
Гиперссылка "Таблица значений (?)" в результате запроса сильно выделяется на фоне значений в остальных ячейках результата. Из-за увеличенного шрифта и неудачного автоподбора ширины колонки каждая строка результат к тому же становится многострочной.

**Хотелось бы иметь следующую функциональность**
Кажется, что лучше уменьшить шрифт, отключить полужирность, т.е. выводить гиперссылку стандартным шрифтом, аналогично прочим значениям в таблице. Нет смысла в акценте на значениях именно этого типа в результате запроса.

**Дополнительный контекст**
Пример форматирования результата запроса: первые 3 строки - стандартное, последние 2 - каким хотелось бы видеть.

![image](https://user-images.githubusercontent.com/59051827/149938383-75908392-317b-466f-9e82-0807f49f8ff6.png)

**Comment by Evg-lylyk** [comment]
Сделал в 2.4. И добавил пояснение в настройках
