### ISSUE TITLE
Обработка для просмотра структуры 

### ISSUE THREAD

**Issue by pavelpribytkin96** [infostart-hub/toolkit#484]
В инструментах разработчика хотелось бы иметь инструмент для просмотра структуры хранения базы данных.
В форме обработки должно отображаться дерево метаданных с описаниями структуры таблиц, индексов и полей базы данных в терминах модели базы данных 1С или используемой СУБД.
Пример реализации похожего инструмента - [https://master1c8.ru/obrabotki-i-ottchet/8552/](https://master1c8.ru/obrabotki-i-ottchet/8552/).

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.1, в свойствах объекта метаданных - инструмент Метаданные
