### ISSUE TITLE
Поиск во "Все функции" по имени и синониму одновременно

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#487]
**Существует проблема**
Иногда приходится искать объекты метаданных попеременно по имени и синониму, из-за чего приходится постоянно переключать поиск, что не удобно

**Хотелось бы иметь следующую функциональность**
Поиск одновременно по имени и синониму, как в дереве конфигурации

**Дополнительный контекст**
Так же, было бы не плохо вынести переключатель поиска в быстрый доступ из пункта "Еще"
![image](https://user-images.githubusercontent.com/65346358/152095189-de0990f6-16d3-40c9-a7bd-b3722148fa10.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 2.4. Выводится основное представление имя или синоним и в скобках (дополнение: имя или синоним)
если они отличаются. 
Элементы расположить как вам удобно можно через изменить форму.
Нужно посмотреть понравится ли новый вариант работы
