### ISSUE TITLE
Предупреждение перед закрытием конструктора запроса если не выбрано ни одного поля

### ISSUE THREAD

**Issue by flanchev** [infostart-hub/toolkit#492]
Если завершить редактирование запроса в конструкторе запроса, но при этом не выбрать ни одного поля, то конструктор просто закроется и удалит этот запрос из пакета запросов.

Необходимо предупреждение перед закрытием конструктора запроса если не выбрано ни одного поля, как это было в старом конструкторе на обычных формах.

**Comment by Evg-lylyk** [comment]
Вроде есть подобный вопрос
![Screenshot_2](https://user-images.githubusercontent.com/48444742/161031548-29b60a6c-cba7-4a02-9140-b1059e54dc75.png)

**Comment by Evg-lylyk** [comment]
Воспроизвести можно так:
1. Добавляем временную таблицу
2. Добавляем ещё один запрос в пакет
3. Выбираем в нем созданную в п.1 временную таблицу, но поля не добавляем
4. Нажимаем "ОК" - вопроса нет

**Comment by Evg-lylyk** [comment]
Это баг платформы он анализирует все запросы пакета, а должен текущий
Исправил в 2022.3.1
