### ISSUE TITLE
Автообновление инструментов, пакетная установка

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#496]
**Существует проблема**
Инструменты разработчика могут использоваться одновременно в нескольких базах, например, в продуктовой и паре баз разработки/тестирования. При выходе новой исправительной версии во всех базах необходимо вручную обновлять Инструменты, что есть не очень удобно.

**Хотелось бы иметь следующую функциональность**
Процесс установки и обновления должен быть более простым, и реализовываться одним или всеми сценариями:
1. В пользовательском интерфейсе в разделе Инструментов должна быть команда проверки обновления. Если таковые имеются, они должны также по команде быть скачаны с удаленного ресурса и установлены в ИБ.
2. Внешняя обработка "Установщик.epf" должна поддерживать пакетный запуск и установку расширения. Это позволит мне написать простой скрипт с подхватыванием новой версии инструментов и установкой их во все необходимые ИБ.

**Дополнительный контекст**
Версия 2.3.8

**Comment by Evg-lylyk** [comment]
В 2022.3.1 реализована пакетная установка
https://github.com/infostart-hub/toolkit/blob/master/auto_install.md
На автообновление можешь создать отдельную задачу, но это не в ближ. время
