### ISSUE TITLE
Запрос теряет определение параметра при его удалении их запроса

### ISSUE THREAD

**Issue by DitriXNew** [infostart-hub/toolkit#499]
Есть запрос, там есть параметр который вычисляется через выражение.
Я оптимизирую запрос и удаляю иногда параметры, потом опять включаю.
И в какой то момент система просто теряет мое определение запроса, что приводит к печали и потраченным часам.

**Comment by Evg-lylyk** [comment]
Какую версию используешь? Чтобы исправить мне нужно больше информации для воспроизведения, а так могу только посочувствовать :)

**Comment by DitriXNew** [comment]
Просте не удаляй папраметры если они были определены ранее, но перестали использоваться.
Можешь их перечеркивать, но не удалять и не скрывать.
А удаляются они при сохранении, как я понял.

**Comment by Evg-lylyk** [comment]
> Просте не удаляй папраметры если они были определены ранее, но перестали использоваться. Можешь их перечеркивать, но не удалять и не скрывать. А удаляются они при сохранении, как я понял.

Почему не удалять? При сохранении неиспользуемые не сохраняются

**Comment by Evg-lylyk** [comment]
В сеансе работы с консоли они не удаляются
