### ISSUE TITLE
Ошибка при анализе плана запроса

### ISSUE THREAD

**Issue by Daabramov** [infostart-hub/toolkit#501]
**Описание ошибки**
При нажатии кнопки анализа плана запроса выскакивает сообщение об ошибке

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль запросов
2. Нажать выполнить запрос
3. Нажать "План запроса"а

**Ожидаемое поведение, если бы ошибки не было**
Отсутствие ошибки

**Скриншоты**
Во вложении

Во вложении

**Окружение:**

   - Платформа 1С: * 8.3.20.1590
   - Имя конфигурации: * Самописка
   - Язык: * Русский
   - Операционная система: * Windows Server 2012 
   
[_20220210165727.zip](https://github.com/infostart-hub/toolkit/files/8041539/_20220210165727.zip)

**Comment by Evg-lylyk** [comment]
Подключался удаленно, дикий план запросов! Не удалось выйти на какие-то исправления анализатора планов.
Спасибо, Дмитрий
