### ISSUE TITLE
Ошибка при вызове глобального меню

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#504]
**Описание ошибки**
При вызове меню по alt+T появляется ошибка:
"
Проверка мутабельных значений на заполненность не поддерживается
{InfostartToolkitPROF ОбщийМодуль.ИТК_ГлобальноеМенюКлиент.Модуль(198)}:	Если НЕ ЗначениеЗаполнено(Поле) Тогда
{InfostartToolkitPROF ОбщийМодуль.ИТК_ГлобальноеМенюКлиент.Модуль(186)}:	ДобавитьПолеОбъекта(ПоляОбъекта, Поле);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ГлобальноеМенюКлиент.Модуль(57)}:					ДобавитьПолеКоллекцииОбъектаСПопыткой(ПоляОбъекта, ОкноКлиентскогоПриложения, ТекущийЭлемент.Имя);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ГлобальноеМенюКлиент.Модуль(24)}:	ЗаполнитьПараметры(АктивноеОкно, Параметры);
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Команда.ГлобальноеМеню.МодульКоманды(6)}:	ИТК_ГлобальноеМенюКлиент.Открыть(ПараметрыВыполненияКоманды);

по причине:
Проверка мутабельных значений на заполненность не поддерживается
"

**Сценарий воспроизведения**
Шаги по воспроизведению:
В карточку сотрудника (справ.Сотрудники.ФормаЭлемента) в расширении вынес реквизит ФизическоеЛицо (Сотрудник.ФизическоеЛицо).
При активизации этого элемента и вызове глобального меню, выходит ошибка.

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

Должно открыться меню с учетом контекста

**Скриншоты**
если применимо, приложите скриншоты
![image](https://user-images.githubusercontent.com/65346358/153825353-10a75685-06f3-4d83-be1a-0aff96648fa0.png)

**Окружение:**

Infostart Toolkit PROF 2.3.8

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.20.97)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.274

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by mrChOP93** [comment]
![image](https://user-images.githubusercontent.com/65346358/153990547-4b519de7-dd02-45e3-8c69-670f0e1b5c30.png)

**Comment by Evg-lylyk** [comment]
Странно Неопределено не является мутабельным значением

**Comment by mrChOP93** [comment]
Ой, стоп, не там точку останова поставил, мой косяк
![image](https://user-images.githubusercontent.com/65346358/153997158-e74354f1-23b0-4d0c-833e-ed87de07d4c5.png)

**Comment by Evg-lylyk** [comment]
Спасибо, за информацию. Исправил попыткой
Будет исправлено с 2.4
