### ISSUE TITLE
Добавить разные иконки в глобальное меню

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#505]
**Существует проблема**
Визуально сложно сразу найти нужный пунк из-за одинаковых иконок

**Хотелось бы иметь следующую функциональность**
разные иконки

![image](https://user-images.githubusercontent.com/65346358/153825896-074930f6-7e49-4878-8127-f3c6550909c3.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.3.1
