### ISSUE TITLE
Ошибочное открытие регл. задание при вводе с клавиатуры

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#507]
**Описание ошибки**
В списке регламентных заданий, если по привычке попытаться начать поиск вводом по строке, то вместо отбора строк открывается форма настроек регламентного задания для текущей строки.

**Сценарий воспроизведения**
1. Открыть в разделе инструментов список "Регламентные задания".
2. Нажать любую клавишу, отличную от Enter, например "Й".
3. Убедиться, что открылось окно настроек текущего регламентного задания.

**Ожидаемое поведение, если бы ошибки не было**
В самом простом случае, ничего не должно произойти. Форма настроек регл. задания не должна открываться. В лучшем случае, должен сработать поиск по строке введенных символов.

**Окружение:**
Infostart Toolkit PROF 2.4.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление торговлей, редакция 11 (11.4.13.180)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.482

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2.4.1
