### ISSUE TITLE
Избранные регламентные задания

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#508]
**Существует проблема**
При работе с регламентными заданиями всегда есть парочка заданий, запускать вручную которые приходится регулярно. К таким заданиям, например, можно отнести "Отложенное обновление ИБ" (БСП), которое включается после обновления конфигурации на новый релиз, либо после запуска ИБ со специальным параметром.

Искать такие задания в общем списке всякий раз немного раздражает. Бывает, что одно и то же задание приходится запускать по несколько раз подряд, перезапуская при этом ИБ. Порой дело осложняется еще и необходимостью вспомнить имя нужного регламентного задания, если используется оно крайне редко. Но при этом мы точно знаем, что когда-нибудь настанет момент запустить его вновь.

**Хотелось бы иметь следующую функциональность**
Пожелание заключается в возможность хранить отдельные регламентные задания в некоем списке избранного. Сам список может храниться в пользовательских настройках. Форма списка регл. заданий должна предоставить возможность отличить избранные регл. задания от других, например, с помощью колонки с пиктограммой в виде звездочки. Также форма списка должна предоставить возможность быстро отфильтровать регл. задания, оставив видимыми только избранные.

**Дополнительный контекст**
Infostart Toolkit PROF 2.4.0

**Comment by krv2k** [comment]
Предлагаю интегрировать в инструменты вот эту обработку https://infostart.ru/public/563177/
Готов доработать по 8.3 самостоятельно (избавиться от модальности и исправить несколько ошибок, которые накопились).

**Comment by Evg-lylyk** [comment]
> Предлагаю интегрировать в инструменты вот эту обработку https://infostart.ru/public/563177/ Готов доработать по 8.3 самостоятельно (избавиться от модальности и исправить несколько ошибок, которые накопились).

Приветствую, желание доделать могу только приветствовать, только есть уже аналогичная обработка можно обсудить какие фичи нужны и сделать. У меня специфичный подход не хочется инструменты перегружать они должны быть простыми. Разработка ведется в github и EDT

**Comment by krv2k** [comment]
> У меня специфичный подход не хочется инструменты перегружать они должны быть простыми. Разработка ведется в github и EDT
Последние несколько лет очень много работал с РЗ, и почти весь функционал обработки использовался. Хотя, возможно, имеет смысл упростить основное окно.

**Comment by Evg-lylyk** [comment]
Пути брать твою и внедрять не вижу, я так не делаю. В той что у меня есть свои фичи.
А вот какие-то отдельные фичи можно реализовать. Инструмент достаточно редко используемый тратить на него много времени не планирую

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.1
