### ISSUE TITLE
Неверная информация о состоянии регламентного задания

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#509]
**Описание ошибки**
В форме списка регл. заданий Инструментов разработчика и в форме БСП различаются результаты выполнения регламентного задания.

**Сценарий воспроизведения**
Сценарий не готовил, просто выполнил отложенное обновление ИБ. Если необходимо получить точную последовательность действий, то займусь этим.

**Ожидаемое поведение, если бы ошибки не было**
Состояния должны совпадать.

**Скриншоты**
Инструменты разработчика.
![image](https://user-images.githubusercontent.com/59051827/154059790-a194a67d-5c4e-400e-9203-8c5801802e02.png)

Библиотека стандартных подсистем.
![image](https://user-images.githubusercontent.com/59051827/154059830-98ff73b8-376c-4518-835f-0d9a524e43d4.png)

**Окружение:**
Infostart Toolkit PROF 2.4.0

Платформа: 8.3.17.1989 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление торговлей, редакция 11 (11.4.13.180)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.482

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
В фоновых заданиях аналогично.

Инструменты разработчика:
![image](https://user-images.githubusercontent.com/59051827/154060735-71430b61-774d-4129-ba3b-f3d092d1baef.png)

Библиотека стандартных подсистем:
![image](https://user-images.githubusercontent.com/59051827/154060806-0c66a313-2198-494d-9b8d-861a21a45607.png)

**Comment by Evg-lylyk** [comment]
Исправлено в 2.4.1
Оказывается вручную запущенные задания не получаются через ПолучитьФоновые с отбором РегламентноеЗадание
их нужно получать через отбок Ключ = Регл.задание.УникальныйИдентификатор
и потом определять какое было последнее
