### ISSUE TITLE
Внутреннее представление типа в результате запроса

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#510]
**Существует проблема**
Не часто, но случаются ситуации, когда необходимо анализировать типы данных в некоторых регистрах или справочниках. Например, появилась потребность узнать, какие типы ссылок присутствуют в регистре сведений "НеудаленныеОбъекты", где измерение "Объект" имеет тип "ЛюбаяСсылка". Еще один пример: проанализировать типы регистраторов в некотором регистре накопления, которые в действительности сделали движения.

Для решения описанной задачи выполняется запрос, например, такой:
```
ВЫБРАТЬ РАЗЛИЧНЫЕ
	ТИПЗНАЧЕНИЯ(Объект) КАК ТипОбъекта
ИЗ
	РегистрСведений.НеудаленныеОбъекты
```
Здесь поле "ТипОбъекта" в результате запроса будет иметь тип "Тип". Однако по его строковому представлению не всегда можно точно понять, что именно за тип объекта оказался в результате, т.к. строковое представление типа зачастую совпадает с синонимом объекта метаданных (если речь про ссылки). Например, `Встреча`. Такое представление типа затрудняет анализ данных регистра. В частности, непонятно, что за класс объектов метаданных перед нами.

**Хотелось бы иметь следующую функциональность**
Было бы здоров иметь, пусть и опциональную, возможность получить внутреннее имя типа, как оно задается во встроенном языке 1С. Например, `ДокументСсылка.Встреча`. В самом простом случае это может быть результат следующего выражения: `ТекстЯчейки = XMLТип(Выборка.Поле).ИмяТипа;`

**Дополнительный контекст**
Infostart Toolkit PROF 2.4.0

**Comment by Evg-lylyk** [comment]
Думаю эту проблему должно решить открытие "исследователя значения"

**Comment by d-hurricane** [comment]
Да, если он будет работать в том числе и в расшифровке результата запроса. Не слишком удобно, конечно, кликать на каждую ячейку таблицы, чтобы получше рассмотреть ее содержимое. Но операция редкая, поэтому действительно, можно обойтись и "исследователем значений".

**Comment by Evg-lylyk** [comment]
Ещё можно колонку с типом тип после вывода обработать

**Comment by d-hurricane** [comment]
В смысле "Инструменты / Обработка результата..."? Об этом не подумал, спасибо. Действительно, в моей ситуации помогло бы. В общем случае, конечно, не так все таки наглядно, но как один из способов решения задачи подойдет.

**Comment by Evg-lylyk** [comment]
> В смысле "Инструменты / Обработка результата..."? Об этом не подумал, спасибо. Действительно, в моей ситуации помогло бы. В общем случае, конечно, не так все таки наглядно, но как один из способов решения задачи подойдет.

Нет, я про то что нужно сделать доработку чтобы перед выводом результата запроса обрабатывать колонки с типом тип и подменить значения

**Comment by d-hurricane** [comment]
А, ну я предполагал, что представление типа будет переопределено механизмом вывода особых значений, как то Неопределено, пустые даты, ссылки и т.д.

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.3.1
![Screenshot_3](https://user-images.githubusercontent.com/48444742/161254319-ecbdba72-b9d5-4506-a584-d4cfb9775d6d.png)
