### ISSUE TITLE
Подключение нескольких файлов шаблонов *.st в консоль кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#511]
Infostart Toolkit PROF 2.4.0

**Comment by d-hurricane** [comment]
Наверное, нет в этом большого смысла. Мои шаблоны в исходном виде не очень подходят для консоли кода, т.к. добавляют в контекстную подсказку слишком много ненужного мусора, актуального только для конфигуратора. Поэтому мне проще подготовить отдельный файл шаблонов.

Закрыть задачу?

**Comment by Evg-lylyk** [comment]
Да, давай закроем. Мне кажется и в консоли это будет использовать 10% пользователей
