### ISSUE TITLE
Рефакторинг - заменить в тексте на значение в конструкторе запросов

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#512]
**Описание ошибки**
При попытке замены параметра запроса на значение в тексте запроса получают ошибку "Слишком много фактических параметров
"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. 
![image](https://user-images.githubusercontent.com/18395787/154636987-0f5aac9b-af55-4b2a-a3fe-0d30c24fa011.png)

2. 
![image](https://user-images.githubusercontent.com/18395787/154637047-f76c696d-bf86-4dc0-b57d-0c73def60da7.png)

**Окружение:**

Infostart Toolkit PROF 2.4.0

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, поправлено в 2.4.1
