### ISSUE TITLE
Консоль запросов - Итератор для значения не определен

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#513]
**Описание ошибки**
При закрытии конструктора запросов и переходе в консоль запросов появляется ошибка "Итератор для значения не определен"

![image](https://user-images.githubusercontent.com/18395787/154973863-95c44e1c-fa9e-4bc4-a0d4-e9577619544a.png)

Шаги.
Открываем конструктор запроса.
Вводим текст запроса (см. ниже).
Нажимаем Ок.
Получаем ошибку.

Пример запроса с ошибкой

ВЫБРАТЬ
	Валюты.Ссылка КАК Ссылка,
	Валюты.Код КАК Код
ПОМЕСТИТЬ ВременнаяТаблица
ИЗ
	Справочник.Валюты КАК Валюты
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	Валюты.Ссылка КАК Ссылка,
	Валюты.Наименование КАК Наименование,
	ВременнаяТаблица.Код КАК Код
ИЗ
	ВременнаяТаблица КАК ВременнаяТаблица
		ЛЕВОЕ СОЕДИНЕНИЕ Справочник.Валюты КАК Валюты
		ПО (ВременнаяТаблица.Ссылка = Валюты.Ссылка)

УПОРЯДОЧИТЬ ПО
	Код

**Окружение:**

 Infostart Toolkit PROF 2.4.1

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, ошибка исправлена в 2.4.2. Вариант обхода - отключить разбор структуры запроса.
