### ISSUE TITLE
Ошибка при вызове Редактора объекта на записи РС

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#515]
**Описание ошибки**
При открытии редактора объекта на записи регистра сведений

"
Метод объекта не обнаружен (УникальныйИдентификатор)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиент.Модуль(130)}:		Уникальность = Параметр.УникальныйИдентификатор();
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиент.Модуль(79)}:	ЗаполнитьПараметрыЗапускаИнструмента(Инструмент, ПараметрыФормы, Параметр, Уникальность);
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(190)}:	ИТК_ТуллкитКлиент.ОткрытьИнструмент(Строка.Идентификатор, Строка.Объект);
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(183)}:	ОткрытьФормуПоСтроке(Строка);
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(67)}:	ВыбраноЗначение(Элементы.ДоступныеОперации.ТекущиеДанные);
"
На строчке "Уникальность = Параметр.УникальныйИдентификатор();"
Параметр﻿ = Значение:РегистрСведенийКлючЗаписи.КадроваяИсторияСотрудников Тип:РегистрСведенийКлючЗаписи.КадроваяИсторияСотрудников

**Сценарий воспроизведения**
Шаги по воспроизведению:
Открыть форму списа РС КадроваяИсторияСотрудников
Вызвать через меню (alt +T) редактор объекта записи

**Окружение:**
Infostart Toolkit PROF 2.3.8

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Исправлено в 2.4.2
