### ISSUE TITLE
Поиск в "Все функции"

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#517]
**Описание ошибки**
Не находит документ по имени

**Ожидаемое поведение, если бы ошибки не было**
Должен найти по имени

**Скриншоты**
![image](https://user-images.githubusercontent.com/65346358/156709097-7a969d4e-1785-4b05-aac1-99c574d7b352.png)
![image](https://user-images.githubusercontent.com/65346358/156709121-c13e3f66-6466-490a-8953-a33441a4f9da.png)

**Окружение:**

Infostart Toolkit PROF 2.4.1

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by mrChOP93** [comment]
З.Ы.
Если выбрать представление "Имя", то находит
![image](https://user-images.githubusercontent.com/65346358/156709425-010dc146-2b6b-450c-9f22-7edb30d87dca.png)

**Comment by Evg-lylyk** [comment]
Исправлено в 2.4.2
