### ISSUE TITLE
Ошибка загрузки запроса из отладки

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#518]
**Описание ошибки**
{InfostartToolkitPROF ОбщийМодуль.ИТК_ОбщийКлиентСервер.Модуль(626)}: Итератор для значения не определен
		Для Каждого Значение Из Источник Цикл

**Сценарий воспроизведения**
Сохранить запрос при помощи "ИТК.Отл(Запрос)"
Попытаться открыть запрос

**Скриншоты**
![image](https://user-images.githubusercontent.com/65346358/157412961-6e9e991c-02d6-42c4-a118-c3a9841c0171.png)

**Окружение:**

Infostart Toolkit PROF 2.4.1

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Ошибка исправлена в 2.4.2, пока вариант обхода отключить структуру запроса в настройках
