### ISSUE TITLE
Ошибка загрузки запроса из отладки

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#519]
**Описание ошибки**
Выдает ошибку, что поле не найдено Person_Id/Код

Запрос:
```
Запрос = Новый Запрос;
	Запрос.Текст = 
		"ВЫБРАТЬ
		|	РабПерс.Person_Id КАК Person_Id,
		|	РабПерс.Tab_Nom КАК Tab_Nom
		|ПОМЕСТИТЬ #Перс
		|ИЗ
		|	&РабПерс КАК РабПерс
		|;
		|
		|////////////////////////////////////////////////////////////////////////////////
		|ВЫБРАТЬ
		|	ТаблицаСотрудников.Сотрудник КАК Сотрудник
		|ПОМЕСТИТЬ #Сотруд
		|ИЗ
		|	&ТаблицаСотрудников КАК ТаблицаСотрудников
		|;
		|
		|////////////////////////////////////////////////////////////////////////////////
		|ВЫБРАТЬ
		|	Перс.Person_Id КАК Person_Id,
		|	Сотруд.Сотрудник КАК Сотрудник
		|ИЗ
		|	#Перс КАК Перс
		|		ВНУТРЕННЕЕ СОЕДИНЕНИЕ #Сотруд КАК Сотруд
		|		ПО Перс.Tab_Nom = Сотруд.Сотрудник.Код
		|ГДЕ
		|	Сотруд.Сотрудник.Person_Id = 0";
	
	Запрос.Параметры.Вставить("РабПерс", РабПерс);
	Запрос.Параметры.Вставить("ТаблицаСотрудников", ТаблицаСотрудников);
	
	РезультатЗапроса = Запрос.Выполнить();
```

В параметре "ТаблицаСотрудников" тз с полем Сотрудник, которое является элементом справочника Сотрудники. Сам запрос отрабатывает без ошибок в программе.

Далее, если в консоли убрать обращение к этим полям, то появляются параметры, но они не заполнены, хотя, через отладку в них есть данные

**Сценарий воспроизведения**
Шаги по воспроизведению:
-Запустить запрос
-Сохранить запрос с помощью "ИТК.Отл(Запрос)"
-Открыть сохраненный запрос
-Получить ошибки
-Убрать обращение к полям с ошибкой
 ```
"ПО Перс.Tab_Nom = Сотруд.Сотрудник
  ГДЕ
	  Сотруд.Сотрудник = 0"
```
-Появляются параметры, но они не заполнены

**Скриншоты**
![image](https://user-images.githubusercontent.com/65346358/157628517-f2bd79ff-9bd6-4e40-9c1a-b665f6fb9430.png)

![image](https://user-images.githubusercontent.com/65346358/157629082-2d5f48f5-1956-415d-9de8-6b58a8fe017d.png)

![image](https://user-images.githubusercontent.com/65346358/157629400-cff0008b-5eea-4583-b42e-273a82ed4391.png)

![image](https://user-images.githubusercontent.com/65346358/157629721-0c3cffa3-71d0-4346-8259-3072cfa37d20.png)

**Окружение:**

Infostart Toolkit PROF 2.3.4

Платформа: 8.3.18.1289 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Спасибо за подробное описание, эта проблема уже зафиксирована #453, но что с ней делать пока не знаю. Наверное сделаю чтобы не смотря на ошибку он выполнялся.
