### ISSUE TITLE
Ошибка в конструкторе запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#524]
**Описание ошибки**
"Задано неправильное имя атрибута структуры
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(1073)}:Поля.Вставить(Поле.Имя, Поле.ТипЗначения);
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(634)}:СобратьДанныеИсточников(Источник, Результат, Кэш);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(511)}:Возврат ИТК_КонструкторЗапросов.ПользовательскиеОбъектыПодсказки(ЭтотОбъект);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(346)}:ДополнительныеПараметры.Вставить("ПользовательскиеОбъекты", ПользовательскиеОбъектыПодсказки());

Запрос:
"
ВЫБРАТЬ
	КадровыеДанныеСотрудников.ФизическоеЛицо КАК ФизическоеЛицо,
	КадровыеДанныеСотрудников.ТабельныйНомер КАК ТабельныйНомер,
	КадровыеДанныеСотрудников.Подразделение КАК Подразделение,
	КадровыеДанныеСотрудников.Должность КАК Должность,
	КадровыеДанныеСотрудников.ГрафикРаботы.id КАК ГрафикРаботыid,
	КадровыеДанныеСотрудников.Состояние КАК Состояние,
	КадровыеДанныеСотрудников.Сотрудник.id КАК Сотрудникid,
	ВЫБОР
		КОГДА КОРВ_РазрешениеНаСвободныйВход.Ссылка ЕСТЬ NULL
			ТОГДА ЛОЖЬ
		ИНАЧЕ ИСТИНА
	КОНЕЦ КАК СвободныйВход
ИЗ
	ВТКадровыеДанныеСотрудников КАК КадровыеДанныеСотрудников
		ЛЕВОЕ СОЕДИНЕНИЕ Документ.КОРВ_РазрешениеНаСвободныйВход КАК КОРВ_РазрешениеНаСвободныйВход
		ПО (КадровыеДанныеСотрудников.Сотрудник = КОРВ_РазрешениеНаСвободныйВход.Сотрудник)
			И (КОРВ_РазрешениеНаСвободныйВход.ДатаНачалаДействия <= &Дата)
			И (КОРВ_РазрешениеНаСвободныйВход.ДатаОкончанияДействия >= &Дата)
"

по причине:
Задано неправильное имя атрибута структуры"

**Сценарий воспроизведения**
Шаги по воспроизведению:
При попытке открыть редактор произвольного выражения поля в конструкторе запроса

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
![image](https://user-images.githubusercontent.com/65346358/158949461-06c10553-9cce-48ed-82af-a582f137a839.png)

**Окружение:**

Infostart Toolkit PROF 2.4.2

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Нашел путь решения до не сильно в нем уверен т.к. проблему не удалось воспроизвести

Требуется помощь нужны значения из отладки
![Screenshot_1](https://user-images.githubusercontent.com/48444742/161002164-9427d8cf-021c-4347-8862-d7c8bd34c90f.png)

**Comment by Evg-lylyk** [comment]
Исправлено в 2.4.3, 2022.3.1
