### ISSUE TITLE
Отображение подсистемы в решениях на базе БСП версии 3.1.6 и выше

### ISSUE THREAD

**Issue by Daabramov** [infostart-hub/toolkit#525]
В версии БСП 3.1.6 добавилась новая функциональность, которая облегчает администрирование расширения. В связи с этим все роли расширений имена которых заканчиваются на `БазовыеПрава, ПолныеПрава, ОбщиеПрава` автоматически подключаются соответствующим пользователям, по этой причине подсистема тулкита начинает отображаться у всех пользователей

Шаги по воспроизведению:
1. Открыть демо БСП версии 3.1.6
2. Установить расширение
3. Запустить тонкий клиент под пользователем с ограниченными правами
4. Подсистема отображается у пользователя с ограниченными права

**Ожидаемое поведение, если бы ошибки не было**
Подсистема не должна отображаться у пользователя с ограниченными правами

**Скриншоты**
![image](https://user-images.githubusercontent.com/31928832/159434100-39ec4d5a-16b3-4eed-aefe-c771d88d238b.png)
![image](https://user-images.githubusercontent.com/31928832/159434198-db36842b-a2bf-43e7-88ea-f9b2b3df1661.png)

**Окружение:**

Infostart Toolkit PROF 2.4.1
Платформа: 8.3.20.1710 (Windows x86-64)
Режим БД: клиент-серверный
Конфигурация:
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.6.137
Клиент:
ОС: Windows x86-64 (Microsoft Windows 8.1 version 6.3  (Build 9600))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 2.4.3 и 2022.3.1, переименовав роль в ...ОсновныеПрава
Молодцы конечно!? добавляют всем пользователям базовые права на все расширения, а если расширение это расширение не должно быть доступно для большинства пользователей...?!

**Comment by Daabramov** [comment]
На партнёрке было обсуждение, что бсп не будет поддерживать платформенные основные роли что-ли, могу поискать если интересно

**Comment by Evg-lylyk** [comment]
> На партнёрке было обсуждение, что бсп не будет поддерживать платформенные основные роли что-ли, могу поискать если интересно

Если есть возможность, пожалуйста

**Comment by Daabramov** [comment]
> > На партнёрке было обсуждение, что бсп не будет поддерживать платформенные основные роли что-ли, могу поискать если интересно
> 
> Если есть возможность, пожалуйста

https://partners.v8.1c.ru/forum/t/1890103/m/2051035
