### ISSUE TITLE
Невозможно одновременно открыть консоль кода и консоль запросов

### ISSUE THREAD

**Issue by Polubotinok** [infostart-hub/toolkit#527]
Невозможно одновременно открыть консоль кода и консоль запросов.

Шаги по воспроизведению:
1. Открыть 'Консоль запросов' из раздела "Infostart toolkit"
2. Вернуться в раздел "Infostart toolkit", вызвать команду "Консоль кода"
3. Ошибка: консоль кода не открывается, переключаемся на уже открытую консоль запросов.
4. Если первой открыть консоль кода, то параллельно невозможно открыть консоль запросов.

**Ожидаемое поведение, если бы ошибки не было**
Должно открыться новое окно с обработкой "Консоль кода".

**Окружение:**

Infostart Toolkit PROF 2.4.2

Платформа: 8.3.18.1616 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.18.396)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.4.489

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 18363))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Консоль разработчика позволяет вести работы с запросами, СКД, кодом в одном инструменте
![Screenshot_1](https://user-images.githubusercontent.com/48444742/159855201-091be336-6112-406b-82c8-719135403708.png)
В будущем планируется перейти к отдельным  обработкам  #307
