### ISSUE TITLE
Добавить в консоль запросов кнопку копирования запросов с символом "|"

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#528]
**Существует проблема**
При копировании текста запроса в модуль, приходится отдельно добавлять символы переноса "|", что не очень удобно.

**Хотелось бы иметь следующую функциональность**
Иметь кнопку, которая бы помещала в буфер обмена запрос, обрамленный кавычками и символами переноса текста "|"
Пример: 
Запрос 

```
ВЫБРАТЬ
	Валюты.Ссылка КАК Ссылка
ИЗ
	Справочник.Валюты КАК Валюты
```

Копировался в формате

```
"ВЫБРАТЬ
|	Валюты.Ссылка КАК Ссылка
|ИЗ
|	Справочник.Валюты КАК Валюты"
```

**Comment by Evg-lylyk** [comment]
Используйте генерацию кода на встроенном языке
Инструменты - Код на встроенном языке

**Comment by mrChOP93** [comment]
Имхо, это еще менее удобно, чем копировать текст запроса из онка и добавлять символ при помощи кнопки в конфигураторе. Подскажите пожалуйста, если я сам добавлю эту кнопку, Что произойдет, при использовании обработки обновления тулкита? Версия затрется на новую, или ошибка какая будет?

**Comment by Evg-lylyk** [comment]
> Имхо, это еще менее удобно, чем копировать текст запроса из онка и добавлять символ при помощи кнопки в конфигураторе.

Не согласен. Используется шире и это достаточно редкая функция.

> Подскажите пожалуйста, если я сам добавлю эту кнопку, Что произойдет, при использовании обработки обновления тулкита? Версия затрется на новую, или ошибка какая будет?

При обновлении заместится на версию поставщика и вам снова нужно вносить изменения
