### ISSUE TITLE
Искажаются типы параметров запроса при сохранении его для отладки

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#529]
**Описание ошибки**
В некоторых ситуациях при открытии сохраненного запроса для отладки `ИТК.Отл(Запрос)` могут искажаться типы значений параметров. Связано это как-то с приведением к типу поля таблицы в запросе, с которым сравнивается значение параметра.

**Сценарий воспроизведения**
Любым удобным способом, например в консоли кода, выполнить в режиме предприятия следующий код:
```
Запрос = Новый Запрос;
Запрос.Текст = 
"ВЫБРАТЬ ПЕРВЫЕ 1
|	Т.Ссылка
|ИЗ
|	Справочник.Номенклатура КАК Т
|ГДЕ
|	Т.Ссылка = &Ссылка
|		ИЛИ &Ссылка = Неопределено";

Запрос.УстановитьПараметр("Ссылка", Неопределено);
ИТК.Отл(Запрос);
Результат = Запрос.Выполнить().Пустой();
```
Убедиться, что при выполнении кода `Результат = Ложь`, т.е. не пустой.

Найти в меню Консоли запросов InfostartToolkit сохраненный "Запрос (из отладки)", открыть его. Выполнить открытый запрос. Убедиться, что результат получился ошибочно пустой.

Перейти на закладку параметров запроса, найти в списке параметр "Ссылка". Если переключить тип параметра на "Выражение", то можно убедиться, что значение параметра есть **пустая ссылка**, вместо ожидаемого **Неопределено**.

**Ожидаемое поведение, если бы ошибки не было**
Результаты в консоли запросов и в консоли кода не должны различаться и должны быть непустыми. Значение параметра запроса из отладки должно восстанавливаться как `Неопределено`.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/160088529-7ff84deb-4cf3-4526-9569-c8156db97c64.png)
![image](https://user-images.githubusercontent.com/59051827/160088654-500ab74e-ed66-4701-b450-c03818de868b.png)

**Окружение:**
Infostart Toolkit PROF 2.4.1

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.7.269)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.256

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Даже не знаю что с этим делать по тексту запросу ф. НайтиПараметры() должна была определить тип как "СправочникСсылка.Номенклатура, **Неопределено**", а определяет просто "СправочникСсылка.Номенклатура" моё мнение это ошибка платформы.
Если я добавлю во все ссылочные типы Неопределено то будет непонятный выбор типа.
Если заменю на выражение для тех параметров для которых значение не входит в ТипЗначения то могут быть проблемы при преобразовании, да и в интерактивном режиме невозможно будет задать нужно давать менять тип.

**Comment by d-hurricane** [comment]
> Если заменю на выражение для тех параметров для которых значение не входит в ТипЗначения

А если не менять на выражение, а расширить тип параметра?

**Comment by Evg-lylyk** [comment]
> А если не менять на выражение, а расширить тип параметра?

Писал выше, для каждого ссылочного параметра будет выбор типа

**Comment by d-hurricane** [comment]
Не. Я имел ввиду не всегда, а именно когда значение параметра не вписывается в тип.

**Comment by Evg-lylyk** [comment]
> Не. Я имел ввиду не всегда, а именно когда значение параметра не вписывается в тип.

Варианты решения есть, но все они не простые. Сейчас есть ф. Поиска параметров в тексте запроса она определяет тип, значения в нее не передаются. Допустим передал, сделал. Дальше проблема что если значение поменяют на ссылку произойдет потеря Неопределено. Нужно расширять использование кнопки задания типа параметра... сейчас она нужна только чтобы задать МоментВремени, Границу

**Comment by d-hurricane** [comment]
Хм. Может и не нужно решать проблему вписывания значения в тип параметра. Этот момент хотя бы как-то диагностировать. Дело ведь в том, что это запрос из отладки, потому и в голову не придет, что он может работать в консоли не так, как работает в отладчике. Как-нибудь хотя бы оповестить, что-то загрузилось не так.

**Comment by Evg-lylyk** [comment]
Проблема понятна, будем решать. Быстрого решения не обещаем

**Comment by Evg-lylyk** [comment]
Решил пойти простым путем при таком значении это будет выражение Результат = Неопределено
Реализовано в 2023.4.6
