### ISSUE TITLE
Универсальный Динамический список

### ISSUE THREAD

**Issue by Cmapnep** [infostart-hub/toolkit#530]
**Нет инструмента Динамический список**
Нет универсального инструмента для просмотра списка объектов метаданных в обход отборов и создания новых элементов в тех формах, где это не предусмотрено разработчиками

**Хотелось бы иметь следующую функциональность**
* Произвольные отборы
* Создание нового элемента 
* Открытие существующего элемента в редакторе объекта

Варианты реализации 
* https://infostart.ru/public/635478/
* https://github.com/cpr1c/tools_ui_1c

**Дополнительный контекст**
Очень удивился, что такого ишуза до сих пор нет - инструмент очень нужный

**Comment by Evg-lylyk** [comment]
Принято

**Comment by Evg-lylyk** [comment]
Связано с #445

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.1
![image](https://user-images.githubusercontent.com/48444742/164032063-3ecfacae-6caf-4f8d-891a-f38d0c895b4b.png)
Еще проведу небольшую работу по интеграции в имеющиеся инструменты #445
