### ISSUE TITLE
Ошибка "Тип "Массив" не может использоваться в данных формы" при попытке выполнения команды "Анализ исполняемых запросов" для варианта СКД из отладки

### ISSUE THREAD

**Issue by Cmapnep** [infostart-hub/toolkit#531]
**Описание ошибки**
Ошибка "Тип "Массив" не может использоваться в данных формы" при попытке выполнения команды "Анализ исполняемых запросов" для варианта СКД из отладки

Полный текст ошибки:
Тип "Массив" не может использоваться в данных формы
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.АнализИсполняемыхЗапросов.Форма(20)}:		НоваяСтрока.Значение = Значение;
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6346)}:	ОткрытьФорму("Обработка.ИТК_КонсольРазработчика.Форма.АнализИсполняемыхЗапросов", ПараметрыФормы, ЭтотОбъект, , , , ОповещениеОЗакрытии, РежимОткрытияОкнаФормы.БлокироватьОкноВладельца);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3615)}:			ОткрытьФормуАнализаИсполняемыхЗапросов(Результат.АдресИсполняемыхЗапросовСКД);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(63)}:			ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
{(1)}:Модуль.ОжидатьЗавершение(Параметры[0],Параметры[1],Параметры[2])
{InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(49)}:		Выполнить(Выражение);
{InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(14)}:	ВыполнитьМетод(ПолноеИмя, Параметры);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ДлительныеОперацииКлиент.Модуль(215)}:		ИТК_БСПКлиентСервер.ВыполнитьПроцедуру("ДлительныеОперацииКлиент.ОжидатьЗавершение", ПараметрыПроцедуры);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3506)}:	ИТК_ДлительныеОперацииКлиент.ОжидатьЗавершение(ДлительнаяОперация, ОповещениеОЗавершенииВыполнения(Строка), ПараметрыОжидания);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3443)}:		ВыполнитьОперациюЧерезДлительныеОперации(ОбрабатываемаяСтрока, НаименованиеОперации, Режим, ИгнорироватьЛимитСтрок);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(1920)}:	ВыполнитьОперацию(ИТК_Перечисления.РежимВыполненияСКДПолучениеИсполняемыхЗапросов());
по причине:
Тип "Массив" не может использоваться в данных формы

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Сохранить схему компоновки из отладки (ИТК.Отл(СхемаКомпоновкиДанных, , НастройкиКомпоновкиДанных, ВнешниеНаборыДанных))
2. Получить схему в консоли
3. Выбрать узле дерева "Вариант"
4. Нажать на кнопку "Анализ исполняемых запросов"

**Ожидаемое поведение, если бы ошибки не было**
Открывается окно анализа исполняемого запроса с параметрами, заполненными из варианта

**Скриншоты**
если применимо, приложите скриншоты
![изображение](https://user-images.githubusercontent.com/36537592/160409724-19691c84-f404-4c0e-b30d-9546f4ece56a.png)

**Окружение:**

   - Платформа 1С: 8.3.18.1334
   - Имя конфигурации: Бухгалтерия предприятия КОРП, редакция 3.0 БИТ.ФИНАНС 3.1 (3.0.103.12/3.1.50.3)
   - Язык: Русский
   - Операционная система: Windows Server 2019 Standard
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

Infostart Toolkit PROF 2.4.2

Платформа: 8.3.18.1334 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Бухгалтерия предприятия КОРП, редакция 3.0 (3.0.103.12/3.1.50.3)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.5.180

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

<!-- **Дополнительный контекст**

- Типовая или не типовая конфигурация: Нет
- Включен ли режим защиты от опасных действий: Нет

**Comment by Evg-lylyk** [comment]
Проблема исправлена в 2.4.3, 2022.3.1
