### ISSUE TITLE
Ошибка при раскрытии временной таблицы для указания полей связи.

### ISSUE THREAD

**Issue by opyshnoy** [infostart-hub/toolkit#532]
При попытке раскрыть временную таблицу для выбора поля связи выходит ошибка:

Значение не является значением объектного типа (Source)
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.МодульОбъекта(236)}:Query = Operator.Sources.Get(Positions[Pos]).Source.Query;
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.МодульОбъекта(74)}:Query = GetSchemaQuery(QuerySchema, CurrentQuerySchemaSelectQuery, NestedQueryPositionAddress);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(208)}:MainObject.SourcesBeforeExpandAtServer(QueryWizardAddress, CurrentQuerySchemaSelectQuery,
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(182)}:SourcesBeforeExpandAtServer(QueryWizardAddress, CurrentQuerySchemaSelectQuery,

Infostart Toolkit PROF 2.4.2
Платформа: 8.3.20.1710 (Windows x86-64)
Режим БД: клиент-серверный
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.110
Язык: ru
Режим запуска: Управляемое приложение

<img width="980" alt="1234" src="https://user-images.githubusercontent.com/45829839/160738290-6e2ffe9c-be94-4cc7-a45e-2c0c2fa9a172.png">

**Comment by Evg-lylyk** [comment]
Не удалось воспроизвести подобный случай, скиньте запрос на котором возникает такая ошибка

**Comment by opyshnoy** [comment]
Временный глюк какой то был. Сегодня у меня тоже не выходит ошибка.

**Comment by Evg-lylyk** [comment]
Ок, закрываю проблему
С конструктором стандартным и улучшенным бывают непонятные ошибки платформы, которые лечаться перезапуском и чисткой кэша.
