### ISSUE TITLE
Ошибка замены таблицы в конструкторе запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#533]
**Описание ошибки**
"Поле объекта не обнаружено (ITK_Картинка)
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(459)}:NewElement[ИдентификаторКолонкиТипПоля()] = ИТК_Типы.КартинкаОписания(Source.ValueType);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.МодульОбъекта(426)}:ИТК_КонструкторЗапросов.МодульОбъектаAddSourceItemИначеЕслиAvailableField(Source, NewElement);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.МодульОбъекта(318)}:AddSourceItem(ItemsTree, Items.Get(Pos), Pos, AvailableTables, EnableSort,
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.МодульОбъекта(260)}:FillSourcesItems(ItemsTree, Source, SourcesImagesCacheAddress, ExpressionsImagesCacheAddress,
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.МодульОбъекта(37)}:FillSourcesByIndex(CurrentItems.GetItems(), Query.AvailableTables, SourcesImagesCacheAddress, ExpressionsImagesCacheAddress,
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.TableSelecting.Форма(160)}:MainObject.AvailableTablesBeforeExpandAtServer(QueryWizardAddress, CurrentQuerySchemaSelectQuery,
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.TableSelecting.Форма(128)}:AvailableTablesBeforeExpandAtServer(QueryWizardAddress, CurrentQuerySchemaSelectQuery, NestedQueryPositionAddress, RootItem.GetID(),
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.TableSelecting.Форма(22)}:FindTable(QueryWizardAddress,
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.QueryWizard.Форма(9898)}:OpenForm("DataProcessor.ИТК_QueryWizard1718192021.Form.TableSelecting", Params, ThisForm,,,,Notification,
"

**Сценарий воспроизведения**
Шаги по воспроизведению:
При попытке заменить таблицу в конструкторе запроса

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
![Ошибка](https://user-images.githubusercontent.com/65346358/161199174-5c7808b8-6e2c-499e-b063-76c06d1fcd16.gif)

**Окружение:**

Infostart Toolkit PROF 2.4.3

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести.
Попробуйте, переустановить, почистить кэш.

**Comment by Evg-lylyk** [comment]
Нужна информация по воспроизведению проблемы

**Comment by mrChOP93** [comment]
Попробовал на рабочей базе, ошибка повторилась, на тестовой удалил и установил заново расширение, та же ситуация
![image](https://user-images.githubusercontent.com/65346358/161707198-7966574e-da88-4059-8b47-152eec0bf258.png)

**Comment by Evg-lylyk** [comment]
Нужно больше информации не удается воспроизвести
![Ошибка в конструкторе не воспроизводиться](https://user-images.githubusercontent.com/48444742/161709598-11185537-7910-4a00-b50e-2152289e1b0f.gif)
При создании формы добавляется реквизит
![Screenshot_1](https://user-images.githubusercontent.com/48444742/161709738-544d2605-efd3-4153-a619-eea8a4cf2b0d.png)

**Comment by mrChOP93** [comment]
OnCreateAtServer(Cancel, StandardProcessing)
Туда вообще не заходит

**Comment by Evg-lylyk** [comment]
> OnCreateAtServer(Cancel, StandardProcessing)
Туда вообще не заходит

Должен, проверил процедура прописана в форме.
Попробуй очистить кэш, простой способ удалить базу из списка и добавить снова

**Comment by mrChOP93** [comment]
Ступил, заходит, просто точку останова поставил на ИТК_КонструкторЗапросов.ФормаВыбораТаблицыПриСозданииНаСервере(ЭтотОбъект);
Туда не доходит
![image](https://user-images.githubusercontent.com/65346358/161721307-781334ce-4cc0-4fac-8f4a-8544c425c347.png)

**Comment by Evg-lylyk** [comment]
> Ступил, заходит, просто точку останова поставил на ИТК_КонструкторЗапросов.ФормаВыбораТаблицыПриСозданииНаСервере(ЭтотОбъект); Туда не доходит ![image](https://user-images.githubusercontent.com/65346358/161721307-781334ce-4cc0-4fac-8f4a-8544c425c347.png)

Там нигде возврата нет, должен доходить

**Comment by Evg-lylyk** [comment]
Попробуй
	// ITK2 + {
	ИТК_КонструкторЗапросов.ФормаВыбораТаблицыПриСозданииНаСервере(ЭтотОбъект);
	// }
в начало процедуры перенести

**Comment by mrChOP93** [comment]
Сработало

Var StartTableName;
	Var Prop;	
	
	// ITK2 + {
	ИТК_КонструкторЗапросов.ФормаВыбораТаблицыПриСозданииНаСервере(ЭтотОбъект);
	// }
	
	AvailableTablesBase = GetFromTempStorage(Parameters["AvailableTablesAddress"]);
	ValueToFormAttribute(AvailableTablesBase, "AvailableTables");
	                                  
	StartTableName = Parameters["StartTableName"];     
	DisplayChangesTables = Parameters["DisplayChangesTables"];
	QueryWizardAddress = Parameters["QueryWizardAddress"];
	CurrentQuerySchemaSelectQuery = Parameters["CurrentQuerySchemaSelectQuery"];
	NestedQueryPositionAddress = Parameters["NestedQueryPositionAddress"];


![image](https://user-images.githubusercontent.com/65346358/161723872-522c91d5-fa34-40bd-aa6b-bf04960633da.png)

**Comment by Evg-lylyk** [comment]
Спасибо за разбор, исправлю в ближ. время

**Comment by Evg-lylyk** [comment]
Будет исправлено в 2022.3.2
