### ISSUE TITLE
Ошибка открытия окна редактирования условия связи таблиц

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#534]
**Описание ошибки**
"Задано неправильное имя атрибута структуры
{InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКода.Модуль(167)}:СвойстваОбъекта.Вставить(Свойство.Ключ, ОписаниеСвойства);
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(1077)}:ОписаниеПолей = ИТК_РедакторКода.ОписаниеПользовательскогоОбъекта(Кэш, , Поля);
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(634)}:СобратьДанныеИсточников(Источник, Результат, Кэш);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(511)}:Возврат ИТК_КонструкторЗапросов.ПользовательскиеОбъектыПодсказки(ЭтотОбъект);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(346)}:ДополнительныеПараметры.Вставить("ПользовательскиеОбъекты", ПользовательскиеОбъектыПодсказки());

по причине:
Задано неправильное имя атрибута структуры"

**Сценарий воспроизведения**
Шаги по воспроизведению:
При открытии окна редактирования условия связи таблиц

**Скриншоты**
![Снимок экрана 2022-04-01 103708](https://user-images.githubusercontent.com/65346358/161201813-eb83f96f-0ef9-408e-ba69-a4b6d957675e.png)
![Снимок экрана 2022-04-01 103634](https://user-images.githubusercontent.com/65346358/161201815-45020787-86e0-44c5-ac69-44020b39cda4.png)
![Снимок экрана 2022-04-01 103616](https://user-images.githubusercontent.com/65346358/161201816-74ff089f-a20c-4251-8040-e3b670c3d295.png)

**Окружение:**

Infostart Toolkit PROF 2.4.3

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Проблема исправлена в 2.4.4, 2022.3.1
