### ISSUE TITLE
Зависание всего клиента 1С в консоле кода при редактировании текста

### ISSUE THREAD

**Issue by JohnyDeath** [infostart-hub/toolkit#537]
**Описание ошибки**
Зависание тонкого клиента.
Причем зависает намертво, перезапуск отладки не помогает. Только убийство процесса 1С

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'Консоль кода'
2. Вбить код:
 ```bsl
ТекстЗапроса = "Выбрать *
|ИЗ 
```
после "ИЗ" пытаемся нажать пробел и получаем зависание. Сам процесс 1С при этом жрет процессор

**Скриншоты**
![image](https://user-images.githubusercontent.com/5936030/161725145-c35868ff-4020-4ae1-9595-f120e1883b3d.png)

**Окружение:**

Infostart Toolkit PROF 2022.3.01

Платформа: 8.3.18.1334 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Бухгалтерия предприятия + БИТ.Финанс (3.0.108.36/3.1.51.6)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.3.2
