### ISSUE TITLE
Ошибка при нажатии "Копировать" в окне генерации кода консоли запросов

### ISSUE THREAD

**Issue by JohnyDeath** [infostart-hub/toolkit#538]
**Описание ошибки**
![image](https://user-images.githubusercontent.com/5936030/161746839-fcf1db9d-a8f6-48e9-831c-b43b885ad251.png)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'Консоль запросов'
2. Нажать 'Инструменты - код на встроенном языке...'
3. Нажать "Копировать"
Вываливается ошибка как на скрине
```
Произошла исключительная ситуация: Ошибка при вызове OpenClipboard

{InfostartToolkitPROF ОбщийМодуль.ИТК_БуферОбменаКлиент.Модуль(42)}:	Возврат htmlfile.ParentWindow.ClipboardData.Getdata("Text");
{InfostartToolkitPROF ОбщийМодуль.ИТК_БуферОбменаКлиент.Модуль(13)}:	Если Текст = Текст() Тогда
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.КодНаВстроенномЯзыке.Форма(204)}:	ИТК_БуферОбменаКлиент.Копировать(Текст);

по причине:
Произошла исключительная ситуация: Ошибка при вызове OpenClipboard

```

**Окружение:**

Infostart Toolkit PROF 2022.3.01

Платформа: 8.3.18.1334 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Бух + Бит.Финанс (3.0.108.36/3.1.51.6)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Видимо какие-то настройки безопасности или среда не позволяют отработать.
У себя проверяю все работает. 
https://helpf.pro/faq/view/705.html
Может ты знаешь какой-то надежный код или такой, который работает у тебя?

**Comment by JohnyDeath** [comment]
Как-то странно всё. Иногда у меня проходит без ошибок.
Буду наблюдать

**Comment by Evg-lylyk** [comment]
Закрываю, нет информации по всопроизведению
