### ISSUE TITLE
Отображает не все поля во временной таблице в колонке таблицы в конструкторе запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#539]
**Описание ошибки**
При замене таблицы в тексте запроса в конструкторе, в таблице отображаются не все поля

**Сценарий воспроизведения**
Шаги по воспроизведению:
![Ошибка](https://user-images.githubusercontent.com/65346358/162160190-5ab49500-35e7-4a8d-b7e2-4364ae6acea8.gif)

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

Infostart Toolkit PROF 2.4.3

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
При работе с конструктором включай пожалуйста стандартный от 1С и если в нем проблема такая же нужно это здесь написать

**Comment by mrChOP93** [comment]
Так таблица заменяется на временную из группы "Временные таблицы (входные)". А в стандартном конструкторе нет такой группы

**Comment by Evg-lylyk** [comment]
> Так таблица заменяется на временную из группы "Временные таблицы (входные)". А в стандартном конструкторе нет такой группы

Тут да, согласен

**Comment by Evg-lylyk** [comment]
Решена в 2024.1
