### ISSUE TITLE
Ошибка добавления поля в конструкторе запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#543]
**Описание ошибки**

{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(1077)}:		ОписаниеПолей = ИТК_РедакторКода.ОписаниеПользовательскогоОбъекта(Кэш, , Поля);
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(634)}:				СобратьДанныеИсточников(Источник, Результат, Кэш);
{InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.ArbitraryExpression.Форма(511)}:	Возврат ИТК_КонструкторЗапросов.ПользовательскиеОбъектыПодсказки(ЭтотОбъект);
по причине:
Задано неправильное имя атрибута структуры

![image](https://user-images.githubusercontent.com/65346358/162370599-22d4079a-d086-4dca-8f1b-b2fd7ef5e87f.png)

**Сценарий воспроизведения**
Шаги по воспроизведению:
Нажать на кнопку добавления поля в конструкторе запроса

**Окружение:**

Infostart Toolkit PROF 2.4.3

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.306

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Уже во многих задачах это есть не понимаю как у тебя имя поля содержит точку воспроизвести это не получается

**Comment by mrChOP93** [comment]
¯\_(ツ)_/¯  Могу только в телеге скинуть сохраненный запрос, не более

**Comment by Evg-lylyk** [comment]
Не могу понять как такое возникает... вставил пропуск полей "." чтобы ошибка не возникала
