### ISSUE TITLE
Консоль запросов. Подсказка по ВнешнимИсточникамДанных

### ISSUE THREAD

**Issue by JohnyDeath** [infostart-hub/toolkit#552]
Хотелось бы в подсказках иметь не только "Документ.ВидДокумента", "Справочник.ВидСправочника" и т.п.
но и таблицы из Внешних источников данных

Пример запроса:
```sdbl
ВЫБРАТЬ
	Автомобили.ГосНомер КАК ГосНомер
ИЗ
	ВнешнийИсточникДанных.БазаМашин.Таблица.Автомобили КАК Автомобили
```
Где "БазаМашин" - имя внешнего источника данных (их может быть сколь угодно много)
"Таблица" - зарезервированное слово. Есть еще Кубы и Функции, но одних Таблиц будет достаточно
"Автомобили" - имя таблицы

Протестировать достаточно просто - добавить в любую конфигурацию внешний источник данных через ODBC. Например, файл Excel или любую таблицу базы 1с

**Comment by salexdv** [comment]
Со своей стороны реализовал всё необходимое. Возможно, нужно доработать обновление структуры метаданных в части внешних источников данных со стороны ITK

**Comment by Evg-lylyk** [comment]
> Со своей стороны реализовал всё необходимое. Возможно, нужно доработать обновление структуры метаданных в части внешних источников данных со стороны ITK

Супер, спасибо! В новом мажорном релизе добавлю.

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.1
