### ISSUE TITLE
Ошибка при открытии конструктора запросов

### ISSUE THREAD

**Issue by StefanovSV** [infostart-hub/toolkit#559]
**Описание ошибки**
Перед открытием редактора запросов выходит предупреждение
![2022-04-25_11-29-17](https://user-images.githubusercontent.com/104351112/165053093-5b934e13-5c44-4439-b4f9-8806fe762481.png)
После этого невозможно продолжать работу, только перезапуск приложения клиента 1с

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Alt + T
2. В пустом поле текста запроса вызываю контекстное меню, выбираю конструктор...
3. Появляется это предупреждение

Раньше это случалось иногда, я терпеливо перезапускал 1с Предприятие. но сегодня - три раза подряд.

**Окружение:**

		"platformType": "Windows_x86_64",
		"appVersion": "8.3.17.1989",
		"appName": "1CV8C",
		"systemInfo": {
			"osVersion": "Microsoft Windows 7 version 6.1  (Build 7600)",
			"fullRAM": 8588906496,
			"freeRAM": 2247737344,
			"processor": "GenuineIntel Intel64 Family 6 Model 85 Stepping 7 2900 MHz",
			"clientID": "2e28169b-0532-4093-8dba-cf2d55d4eefe"

**Способ обхода**
Перед вызовом конструктора запросов, в поле текста запроса написать "Выбрать 1"
   
**Дополнительный контекст**

Infostart Toolkit PROF 2.4.3

Платформа: 8.3.17.1989 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление торговлей, редакция 11 (11.4.11.100)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.3.261
режим защиты от опасных действий - выключен

**Comment by Evg-lylyk** [comment]
Подобная проблема возникала неоднократно, лечиться очисткой кэша

**Comment by StefanovSV** [comment]
Но я уже понял, что это проблема платформы 1с, т.к. на обычной консоли в тонком - тоже самое

**Comment by StefanovSV** [comment]
Проблема осталась, буду пока пользоваться толстым клиентом. Поскольку это не проблема IS Toolkit, заявку закрываю.
