### ISSUE TITLE
Ошибка при открытии редактора ТЗ в параметрах запроса

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#560]
**Описание ошибки**

В консоли запросов задан запрос (затащил при отладке из конфигуратора)
`
ВЫБРАТЬ  
	РасчетыСПоставщикамиОбороты.*  
ИЗ  
РегистрНакопления.РасчетыСПоставщиками КАК РасчетыСПоставщикамиОбороты  
ГДЕ  
	РасчетыСПоставщикамиОбороты.Валюта В(&ТаблицаОплаты)  `

&ТаблицаОплаты - это таблица значений с соотв. колонками (в данном случае есть колонка Валюты)

При попытке открытия на редактирование параметра запроса - получаю ошибку.

**Скриншоты**
![image](https://user-images.githubusercontent.com/18395787/165088240-bbefbf6d-42f0-415c-a36f-84f2e8061a51.png)

**Окружение:**

 Infostart Toolkit PROF 2022.3.02

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2  (2.4.7.166)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.1.434

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.3.3
