### ISSUE TITLE
Устанавливать имя запроса при импорте из отладки

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#572]
**Существует проблема**
При импорте запроса все запросы добавляются с именем "Запрос №"

**Хотелось бы иметь следующую функциональность**
Хотелось чтобы имена запросов имели имя, которое указывает пользователь при импорте из отладки

1. Выбираю
![image](https://user-images.githubusercontent.com/18395787/167567002-db101386-968b-4b94-875a-78622801ebbb.png)
2.При добавлении запроса - хотелось бы видеть такое имя
![image](https://user-images.githubusercontent.com/18395787/167567050-0801fb46-35c7-46d1-9952-539088c3d052.png)

**Comment by Evg-lylyk** [comment]
А файлы ты сохранял новой версий? Cделал чуть по другому, при сохранении из отладки присваивается заданное имя, соответственно при объединении будут разные имена.
