### ISSUE TITLE
Не показывает значения параметров с типом "Список"

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#573]
**Существует проблема**
В консоли запросов при переходе на вкладку "Параметры" не показывает значения параметров с типом "Список". Значения показывает только при активизации строки.
Хотелось бы чтобы значения были видны сразу при переходе на вкладку "Параметры".

![Параметры](https://user-images.githubusercontent.com/18395787/167567546-d7fa6d96-7917-4192-9c06-48d5ad8ca0e5.gif)

Infostart Toolkit PROF 2022.3.03

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление холдингом, редакция 3.1 (3.1.14.27)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.5.180

Клиент:
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Ошибка исправлена в 2022.3.4
