### ISSUE TITLE
В версии без БСП не открывается обработка "Журнал регистрации"

### ISSUE THREAD

**Issue by igorefremovsmm** [infostart-hub/toolkit#574]
**Описание ошибки**
В версии без БСП не открывается обработка "Журнал регистрации"
Проверка конфигурации выдаёт следующие ошибки:

`{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(140,30)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
					СобытиеЖурнала.Данные = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку( (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(146,30)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
					СобытиеЖурнала.Данные = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку( (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(190,28)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
			СобытиеЖурнала.Данные = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(НСтр("ru = 'Имя: %1, ...'; (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(205,37)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
			СобытиеЖурнала.ИмяПользователя = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(НСтр("ru = '%1 <Удален>'; (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(495,17)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
		Ограничение = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(НСтр("ru = 'События (%1)'; (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(500,17)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
		Ограничение = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(НСтр("ru = 'Сеансы (%1)'; (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(530,19)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
				Ограничение = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(Ограничение, ПредставлениеОграничения, ЗначениеОграничения); (Проверка: Сервер)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ЖурналРегистрации.Модуль(202,37)}: Переменная не определена (Пользователи)
			СобытиеЖурнала.ИмяПользователя = <<?>>Пользователи.ПолноеИмяНеУказанногоПользователя(); (Проверка: Сервер)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(385,3)}: Переменная не определена (ДлительныеОперации)
		<<?>>ДлительныеОперации.ОтменитьВыполнениеЗадания(ИдентификаторЗадания); (Проверка: Сервер)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(404,24)}: Переменная не определена (ДлительныеОперации)
	ПараметрыВыполнения = <<?>>ДлительныеОперации.ПараметрыВыполненияВФоне(УникальныйИдентификатор); (Проверка: Сервер)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(409,24)}: Переменная не определена (ДлительныеОперации)
	РезультатВыполнения = <<?>>ДлительныеОперации.ВыполнитьВФоне("ИТК_ЖурналРегистрации.ПрочитатьСобытияЖурналаРегистрации", (Проверка: Сервер)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(258,22)}: Переменная не определена (ДлительныеОперацииКлиент)
	ПараметрыОжидания = <<?>>ДлительныеОперацииКлиент.ПараметрыОжидания(ЭтотОбъект); (Проверка: Тонкий клиент)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(262,2)}: Переменная не определена (ДлительныеОперацииКлиент)
	<<?>>ДлительныеОперацииКлиент.ОжидатьЗавершение(РезультатВыполнения, ОповещениеОЗавершении, ПараметрыОжидания); (Проверка: Тонкий клиент)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(336,7)}: Переменная не определена (ЖурналРегистрацииКлиент)
	Если <<?>>ЖурналРегистрацииКлиент.УстановитьОтборПоЗначениюВТекущейКолонке( (Проверка: Тонкий клиент)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.РедакторСоставаСвойства.Форма(175,15)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
	СтрокиПути = <<?>>СтроковыеФункцииКлиентСервер.РазложитьСтрокуВМассивПодстрок(Представление, ".", Истина, Истина); (Проверка: Сервер)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.Событие.Форма(35,14)}: Переменная не определена (СтроковыеФункцииКлиентСервер)
	Заголовок = <<?>>СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(НСтр("ru = '%1 от %2'"),  (Проверка: Сервер)
`

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть обработку "Журнал регистрации"

**Ожидаемое поведение, если бы ошибки не было**
Обработка "Журнал регистрации" открывается без ошибок.

**Окружение:**

Infostart Toolkit PROF 2022.3.04

Платформа: 8.3.20.1838 (Windows x86-64)
Режим БД: файловый

Конфигурация:
OMS (24.3)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_18
Версия БСП: БСП не установлена

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by igorefremovsmm** [comment]
Всё ещё не открывается в 2022.3.5.
Теперь ошибка:

Значение не является значением объектного типа (РазделениеВключено)
{InfostartToolkitPROF ОбщийМодуль.ИТК_БСППовтИсп.Модуль(152)}:Возврат Модуль.РазделениеВключено();
{InfostartToolkitPROF ОбщийМодуль.ИТК_БСППовтИсп.Модуль(73)}:Результат = РазделениеВключеноБСП2_3();
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(16)}:МодельСервиса = ИТК_БСППовтИсп.РазделениеВключено()
{InfostartToolkitPROF ОбщийМодуль.ИТК_ФормаКлиент.Модуль(662)}:ОткрытьФорму("Обработка.ИТК_ЖурналРегистрации.Форма", Параметры);
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Команда.ИТК_ЖурналРегистрации.МодульКоманды(6)}:ИТК_ФормаКлиент.ОткрытьЖурналРегистрации();

Проверка конфигурации выдаёт ошибку:
InfostartToolkitPROF Обработка.ИТК_QueryWizard1718192021.Форма.DataCompositionAvailableTableParameters.Форма Возможно ошибочное свойство: "FieldsList"
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(258,22)}: Переменная не определена (ДлительныеОперацииКлиент)
	ПараметрыОжидания = <<?>>ДлительныеОперацииКлиент.ПараметрыОжидания(ЭтотОбъект); (Проверка: Тонкий клиент)
{InfostartToolkitPROF Обработка.ИТК_ЖурналРегистрации.Форма.ЖурналРегистрации.Форма(262,2)}: Переменная не определена (ДлительныеОперацииКлиент)
	<<?>>ДлительныеОперацииКлиент.ОжидатьЗавершение(РезультатВыполнения, ОповещениеОЗавершении, ПараметрыОжидания); (Проверка: Тонкий клиент)


Нужен новый тикет?

**Comment by Evg-lylyk** [comment]
> 
> Нужен новый тикет?

Не надо

**Comment by Evg-lylyk** [comment]
Еще раз исправил ))
