### ISSUE TITLE
Развитие пакетной установки инструментов

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#575]
**Существует проблема**
В версии 2022.3.4 установка происходит так:
* если инструменты уже установлены и версия установленного старая, расширение обновляется;
* в противном случае расширение устанавливается как новое.
При таком подходе, если попытаться в пакетном режиме обновить уже обновленное расширение инструментов, то обновление завершиться ошибкой, при этом окно сеанса работы с 1С останется открытым. И закрыть его некому, т.к. запускал установку скрипт. Особенно такое поведение мешает разработке и отладке своего скрипта-установщика.

Дополнительно не хватает обратной связи от установщика. Информации о том, как прошла установка: установлено ли обновление, или оно не требуется.

**Хотелось бы иметь следующую функциональность**
Во-первых, при пакетной установке вне зависимости от того, как прошла сама установка, хотелось бы, чтобы окно 1С закрывалось в любом случае. Вообще, попытка повторной установки уже обновленных Инструментов мне кажется не является исключительной ситуацией, и скрипт должен отработать без ошибок.

Во-вторых, было бы здорово получить от установщика обратную связь. К сожалению, платформа не позволяет при закрытии окна предприятия вернуть код ошибки. Но вполне устроила бы и возможность указать файл лога, куда установщик запишет результат. А скрипт его уже потом разберет как обычный текст. Можно было бы в файл лога выводить все то, что видит пользователь на экране при интерактивной установке.

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.1
Дополненное описание https://github.com/infostart-hub/toolkit/blob/master/auto_install.md
Как выйдет релиз проверь пожалуйста

**Comment by d-hurricane** [comment]
Попробовал на версии 2022.4.1

Первый запуск скрипта прошел успешно, ошибок не наблюдалось, расширение обновилось. Файл лога с какой-либо информацией не появился.

Повторный запуск скрипта, выполненный с целью посмотреть, как будут обновляться уже обновленные базы, завершился ошибкой как на скрине:
![image](https://user-images.githubusercontent.com/59051827/170517176-26cb0fd0-9754-4e75-93f1-dba0c1e47f88.png)

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.4.2
