### ISSUE TITLE
Не сохраняется ТЗ как параметр запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#577]
Не сохраняется ТЗ как параметр запроса через ИТК.Отл(Запрос)

**Сценарий воспроизведения**
Сохранить запрос через "ИТК.Отл(Запрос)"

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
![image](https://user-images.githubusercontent.com/65346358/169454999-4247de61-1ce2-4774-aa5f-cee566b39a3a.png)
![image](https://user-images.githubusercontent.com/65346358/169455079-95f0bc8d-8d60-4db2-9aa0-97bcfd935925.png)

**Окружение:**
Infostart Toolkit PROF 2022.3.05

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.21.75)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.349

Клиент:
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22000))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проверил у себя на тестовом примере, ошибка не воспроизводиться, тебе нужно более детально разобраться
Могу подключиться посмотреть, но только в будние дни

**Comment by mrChOP93** [comment]
Ок, напомни в будни, скажу, когда можно подключиться.

**Comment by Evg-lylyk** [comment]
Пиши как будет возможность

**Comment by mrChOP93** [comment]
Ок, примерно минут через 40

**Comment by Evg-lylyk** [comment]
Проблема возникает из за ошибки в запросе, параметры не считываются, наверное нужно перейти к другому варианту определения использования параметра в запросе
Попробую решить вопрос в задаче #453
