### ISSUE TITLE
Обработка "Анализ прав доступа" не анализирует "внешние источники данных"

### ISSUE THREAD

**Issue by JohnyDeath** [infostart-hub/toolkit#578]
Тулкит версии 2.4.2
Обработка "Анализ прав доступа" не анализирует таблицы "внешних источников данных".

Их нет ни в отборе по метаданным, ни в результирующем отчете, если его построить по ролям, которые устанавливают права на таблицы внешних источников

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.1
