### ISSUE TITLE
Контекстное открытие редактора кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#579]
**Существует проблема**
Редактор объекта доступен для открытия из карточки объекта (за счет подключаемых команд), однако он позволяет производить над объектом самые простые манипуляции - присваивать конкретные значения полям объекта. Если нужна чуть более сложная обработка объекта, то на помощь приходит консоль кода, но ее нельзя открыть непосредственно из карточки некоторого объекта.

Сейчас для решения проблемы поступаю так:
1. В карточке объекта копирую навигационную ссылку на объект;
2. Комбинацией "Alt + T" открываю глобальное меню, оттуда перехожу к консоли кода.
3. Вбиваю в поле кода `Объект = `, затем открываю диалог вставки ссылки на объект ИБ, где выбираю нужные метаданные и вставляю скопированную навигационную ссылку. Выбираю подобранный объект, объект попадает в код.
4. Продолжаю писать код обработки объекта...

**Хотелось бы иметь следующую функциональность**
Хотелось бы упростить себе работу с подбором нужного объекта в консоли кода в ситуациях, когда я уже нахожусь в карточке нужного объекта. Для этого хочется увидеть в меню инструментов еще и команду открытия консоли кода. По нажатию на нее будет открываться консоль кода с уже набранным кодом:
`Объект = <Ссылка на объект, в контексте которого открыли редактор>`

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.01

**Comment by Evg-lylyk** [comment]
Есть такая задача и проблема #336 
Обязательно решу когда буду переделывать консоль кода выносить в отдельную обработку

**Comment by Evg-lylyk** [comment]
> Более того, я оставил в той задаче комментарий. :-) Уже и забыл. Извини за дубль.

Да все норм
