### ISSUE TITLE
Контекстная подсказка для типа ПеречислимыеСвойстваОбъектовМетаданных 

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#580]
**Существует проблема**
В настоящий момент отсутствует контекстная подсказка в консоли кода для объекта типа ПеречислимыеСвойстваОбъектовМетаданных, т.е. при наборе кода `Метаданные.СвойстваОбъектов`.

**Хотелось бы иметь следующую функциональность**
Такая контекстная подсказка часто нужна, когда кодом исследуется большая конфигурация типа ERP.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.01

**Comment by salexdv** [comment]
Реализовано

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.2
