### ISSUE TITLE
Метод ТипВсеСсылки для менеджеров объектов

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#581]
**Существует проблема**
В контекстной подсказке редактора кода отсутствует подсказка для метода `ТипВсеСсылки` менеджеров объектов, таких как ДокументМенеджер, СправочникМенеджер и др.

**Хотелось бы иметь следующую функциональность**
Метод `ТипВсеСсылки` хочется видеть в контекстной подсказке редактора кода.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.01

**Comment by salexdv** [comment]
Со своей стороны доработал

**Comment by Evg-lylyk** [comment]
Внедрено в 2022.5
