### ISSUE TITLE
Отсутствует подсказка по параметрам методов при наличии переноса строки

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#582]
**Описание ошибки**
Подсказка по параметрам метода работает только если курсор находится в той же строке, что и сам метод. При переносе курсора на следующую строку подсказка пропадает, и отобразить ее уже не представляется возможным.

**Сценарий воспроизведения**
1. Открыть консоль кода.
2. Ввести код `Поле = Новый Структура(`
3. Убедиться, что после ввода открывающейся скобки появилась подсказка по параметрам конструктора структуры.
4. Не закрывая скобки нажать Enter для перехода на новую строку.
5. Убедиться, что не смотря на то, что формально курсор по-прежнему находится внутри скобок конструктора структуры, подсказки по параметрам уже нет. Комбинация клавиш Ctrl + Shift + Space не приводит к появлению подсказки.

**Ожидаемое поведение, если бы ошибки не было**
Отображение подсказки по параметрам не должно зависеть от пробельных символов, располагающихся до курсора ввода. Подсказка по параметрам метода должна работать в не зависимости от того, записываются ли параметры в одной строке или в разных.

**Окружение:**
Infostart Toolkit PROF 2022.4.01

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.7.269)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.256

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by salexdv** [comment]
Подсказку по параметрам доработал

**Comment by Evg-lylyk** [comment]
Исправлена в 2022.4.2
