### ISSUE TITLE
Оповещать открытые формы об изменениях в редакторе объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#583]
**Существует проблема**
При записи нового или редактирования существующего объекта в редакторе, привнесенные изменения не видны сразу в открытых динамических списках. Например, при изменении наименования номенклатуры, чтобы тут же увидеть изменение в открытом форме списка номенклатуры необходимо выполнить команду обновления этого списка.

**Хотелось бы иметь следующую функциональность**
После записи объекта в редакторе открытые формы должны оповещаться о выполненном изменении. В самом простом случае (т.е. без учета движений) это:
`ОповеститьОбИзменении(Ссылка);`

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.02

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.4.3
