### ISSUE TITLE
Не устанавливается собственный идентификатор новому объекту в редакторе объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#584]
**Описание ошибки**
При создании нового в редакторе объекта еще до первой записи есть возможность установить собственный идентификатор для будущей ссылки (UID). Однако при записи установленный вручную идентификатор не используется, и генерируется платформой свой.

**Сценарий воспроизведения**
1. Открыть редактор объекта. Выбрать любой тип объекта, например "Склад".
2. В строке UID указать произвольный уникальный идентификатор. Заполнить обязательные поля объекта при необходимости (например, наименование).
3. Нажать "Записать".
4. Убедиться, что в строке UID значение идентификатора изменилось. Объекту присвоен иной идентификатор, отличный от заданного вручную.

**Ожидаемое поведение, если бы ошибки не было**
Если идентификатор ссылки задается вручную, именно он и должен использоваться при записи нового объекта.

**Окружение:**
Infostart Toolkit PROF 2022.4.02

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.7.269)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.256

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, исправлено в 2022.4.3
