### ISSUE TITLE
Открытие кода обработчика регламентного задания

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#586]
**Существует проблема**
В карточке регламентного задания можно посмотреть имя обработчика, но чтобы прикинуть, что он из себя представляет, необходимо уже открывать конфигурацию и искать обработчик там.

**Хотелось бы иметь следующую функциональность**
Консоль кода имеет удобную функцию перехода к определению, открывающую в новой форме код метода с подцветкой синтаксиса работает эта функция при указании пути к выгрузке конфигурации. Хотелось бы аналогичную фишку для регламентного задания: открытия обработчика регл. задания прямо из карточки задания.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.02

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.5
