### ISSUE TITLE
Обработка "Регламентные и фоновые задания" не сохраняет настройки

### ISSUE THREAD

**Issue by igorefremovsmm** [infostart-hub/toolkit#588]
**Описание ошибки**
Не запоминаются настройки в обработке "Регламентные и фоновые задания":
![image](https://user-images.githubusercontent.com/93524974/174083262-a1444bc2-8ed3-430a-8c4e-0467e88a77eb.png)

Соответственно, каждый раз список долго открывается.

И добавьте ещё, пожалуйста, сортировку для столбцов
![image](https://user-images.githubusercontent.com/93524974/174083794-fd7d04bd-b976-4dbd-b9bc-80f68b4dba13.png)

Infostart Toolkit PROF 2022.4.03

Платформа: 8.3.20.1838 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
OMS (25.25)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_18
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
`Не запоминаются настройки в обработке "Регламентные и фоновые задания"`
Так задумано, каждый раз открывается для разных задач пока список формируется в фоне можно задать отборы и если благодаря отбору он сформируется быстро сразу будет результат

По сортировке : список может обновиться при некоторых действиях, поясни зачем нужна сортировка?

**Comment by Evg-lylyk** [comment]
> Понимаю, что это, возможно, нужно только нам, по этому прошу галки сохранять.

Думаю можно сделать

> По сортировке не понял противоречия. Я же штатную прошу добавить - а это три настройки на форме :)

Минималистичность интерфейса.
Сортировку по умолчанию проанализируем, добавим сортировки в Еще

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.5
