### ISSUE TITLE
Параметры регламентных заданий

### ISSUE THREAD

**Issue by nixel2007** [infostart-hub/toolkit#590]
**Существует проблема**
Описание существующей проблемы [...]

У регламентных заданий могут быть существовать параметры, передаваемые в метод-обработчик регламентного задания. Из существующей обработки невозможно управлять списком и значениями этих параметров.

**Хотелось бы иметь следующую функциональность**

Хотелось бы видеть хотя бы список значений с параметрами (хранится в данных экземпляра РЗ как массив) с возможностью изменения значений и количества параметров.
Как второй шаг, можно было бы подцепить исходники конфигурации и показывать названия этих параметров из сигнатуры метода-обработчика.

Дополнительно предусмотреть, чтобы при копировании регламентного задания в новый экземпляр РЗ переносились бы и параметры.

**Дополнительный контекст**
Любая дополнительная информация

Пример формы регламентного задания с параметрами в консоли заданий от Душелова:

![image](https://user-images.githubusercontent.com/1132840/174763015-8a5d380b-542b-48c7-9d4f-88f1e07d4e92.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.4
