### ISSUE TITLE
Обработка результата запроса - поле объекта не обнаружено

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#591]
**Сценарий воспроизведения**
Шаги по воспроизведению:
0. Конфигурация запущена в РежимОтладки 
1. В конструкторе запросов выполняю запрос.
2. Открываю "Обработка результата"
3. При нажатии на кнопку "Обработать" получаю ошибку "Поле объекта не обнаружено (ФоновоеВыполнение)"
```
Поле объекта не обнаружено (ФоновоеВыполнение)
{InfostartToolkitPROF ОбщийМодуль.ИТК_НастройкиКлиентСервер.Модуль(6)}:	Возврат Настройки[Имя];
{InfostartToolkitPROF ОбщийМодуль.ИТК_НастройкиКлиент.Модуль(24)}:	Возврат ИТК_НастройкиКлиентСервер.ЗначениеОбщейНастройки(Форма, Имя);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.ОбработкаРезультата.Форма(1114)}:	ФоновоеВыполнение = ИТК_НастройкиКлиент.ЗначениеОбщейНастройки(ЭтотОбъект, "ФоновоеВыполнение");
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.ОбработкаРезультата.Форма(358)}:	ВыполнитьОбработку(ОбрабатываемыеСтроки);
```

**Скриншоты**

![image](https://user-images.githubusercontent.com/18395787/175260961-9e7bdcd7-2c97-4a14-9c3a-990be88942e2.png)

Infostart Toolkit PROF 2022.4.04

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 для Беларуси (2.4.7.166)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.1.434

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 2022.4.5
