### ISSUE TITLE
Ошибка при выполнении запроса из пакета запросов

### ISSUE THREAD

**Issue by Batsy66** [infostart-hub/toolkit#592]
**Описание ошибки**
Имеем пакетный запрос, в параметры запроса передаём _таблицу значений_. При попытке выполнить запрос к временной таблице, в рамках пакета, получаем ошибку. 
> Неверный параметры "Параметр_Таблица".
При этом выполнение пакетного запроса происходит без ошибок

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть `консоль запросов`
2. Вставить текст запроса

```bsl
ВЫБРАТЬ	
	Т.Поле Как Поле
ПОМЕСТИТЬ ВТ
ИЗ &Параметр_Таблица КАК Т;

ВЫБРАТЬ 
	1
;
```
3. Перейти на вкладку **Параметры**
4. Заполнить таблицу-параметр `Параметр_Таблица` любым количество строк
5. В дереве выбрать временную таблицу `ВТ`
6. Нажать **Выполнить**
7. Получить ошибку
> (5, 2) Неверные параметры "Параметр_Таблица"
> <<?>> &Параметр_Таблица КАК Т

==При пакетном выполнении всё работает==

**Ожидаемое поведение, если бы ошибки не было**
Выводить результат выполнения запроса

**Скриншоты**
- Выполнение по запросу пакета 
    ![image](https://user-images.githubusercontent.com/18735099/176702725-14e67b98-0728-4423-b866-4d1dffde2a3f.png)
- Пакетное выполнение 
    ![image](https://user-images.githubusercontent.com/18735099/176702600-ebc0e8b4-a054-4d73-a156-960e0f50787e.png)

**Окружение:**

   - Платформа _1С: Платформа: 8.3.20.1710 (Windows x86-64) Режим БД: клиент-серверный_
   - Имя конфигурации: _БСП_
   - Язык: _русский_
   - Операционная система: _Windows 10 Pro 21H2 19044.1766_
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

<!-- **Дополнительный контекст**

- Типовая или не типовая конфигурация ?
   Самописные на основе БСП. 
- Включен ли режим защиты от опасных действий
   Нет
---
- На какой версии работало?
   На версии **2.3.5** всё работает

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести ошибку, на версии 2022.4.5 все ОК

**Comment by Batsy66** [comment]
> Не удается воспроизвести ошибку, на версии 2022.4.5 все ОК
Попробовал по тем же параметрам, что в ошибке, восстановить получилось. Прикладываю файл запросов. 

[is_toolkit_error.zip](https://github.com/infostart-hub/toolkit/files/9062102/is_toolkit_error.zip)

**Comment by Evg-lylyk** [comment]
> > Не удается воспроизвести ошибку, на версии 2022.4.5 все ОК
> > Попробовал по тем же параметрам, что в ошибке, восстановить получилось. Прикладываю файл запросов.
> 
> [is_toolkit_error.zip](https://github.com/infostart-hub/toolkit/files/9062102/is_toolkit_error.zip)

Проверил все работает, может кэш почистить.
