### ISSUE TITLE
Просмотр таблиц внешнего источника данных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#593]
**Существует проблема**
Отсутствует возможность просмотреть данные внешнего источника, кроме как с использованием консоли запросов.

**Хотелось бы иметь следующую функциональность**
Открывать формы списков для таблиц внешнего источника данных с помощью инструментов "Все функции" и/или "Динамический список".

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.02

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.1.1
Добавлено в динамический список и Все функции
