### ISSUE TITLE
Добавить в код обработки результат запроса в цикл выборки

### ISSUE THREAD

**Issue by Karejl** [infostart-hub/toolkit#596]
**Существует проблема**
Описание существующей проблемы [...]

**Хотелось бы иметь следующую функциональность**
Просьба добавить возможность добавлять код обработки результата запроса в "Код на встроенном языке"?

**Дополнительный контекст**
Любая дополнительная информация

**Comment by Evg-lylyk** [comment]
ИМХО это можно сделать уже потом после вставки кода в конфигуратор
