### ISSUE TITLE
Вернуть Кнопку "Редактор объекта" в подменю тулкита, в объектах метаданных, в начале списка кнопок.

### ISSUE THREAD

**Issue by Karejl** [infostart-hub/toolkit#597]
**Существует проблема**
Описание существующей проблемы [...]

**Хотелось бы иметь следующую функциональность**
Просьба вернуть "редактор объекта" в начале списка кнопок, т.к. эта функция используется чаще остальных.

**Дополнительный контекст**
Любая дополнительная информация

**Comment by Evg-lylyk** [comment]
Сделано в 2022.4.7
