### ISSUE TITLE
Редактор записей независимых регистров сведений

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#598]
**Существует проблема**
Среди инструментов не хватает аналога редактора объектов, но для записей регистров. Сейчас редактор объекта предоставляет широкие возможности разработчику: создать объект с нужным идентификатором, записать значение реквизита без учета параметров выбора значений, указанный в метаданных этого реквизита. Аналогичная потребность порой возникает и для регистров. И если для редактирования регистров, подчиненных регистратору, подходит тот же редактор объекта, то для записей независимого регистра сведений ничего подобного нет: мы не можем произвольным образом редактировать поля записи регистра.

**Хотелось бы иметь следующую функциональность**
Нужен инструмент для работы с записями независимых регистров сведений. Это может быть как отдельный инструмент, так и редактор объекта может обзавестись соответствующим функционалом.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.06

**Comment by Evg-lylyk** [comment]
Реализация планируется в ближ. 2024.1
Нужно чтобы в форме списка регистра сведений открывался редактор по ключу записи в глобальном меню

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.1
