### ISSUE TITLE
Добавить в подсказку консоли кода перечень реквизитов объектов метаданных

### ISSUE THREAD

**Issue by salexdv** [infostart-hub/toolkit#600]
**Существует проблема**
Отсутствуют подсказки по реквизитам объектов метаданных. Сейчас в подсказку попадают только стандартные реквизиты и табличные части

![ITK_ОтсутствующиеРеквизиты_1](https://user-images.githubusercontent.com/6356534/181232572-9725fa25-e075-4b47-893c-a3a9548e3e8e.png)
![ITK_ОтсутствующиеРеквизиты_2](https://user-images.githubusercontent.com/6356534/181232644-13295ad8-65b9-4841-a4ff-6d7a26c7e46d.png)

В функции `ИТК_РедакторКодаПовтИсп.ОписаниеОбъектаМетаданных` в принципе отсутствует получение списка реквизитов

**Хотелось бы иметь следующую функциональность**
Хотелось бы видеть реквизиты объектов в подсказках консоли кода 

**Окружение:**
Infostart Toolkit PROF 2022.4.06
Платформа: 8.3.18.1616 (Windows x86-64)
Режим БД: клиент-серверный

**Comment by salexdv** [comment]
Этот функционал точно был раньше. Например, он есть в версии 2.2.2, а вот в 2022.4.5 и 2022.4.6 уже нет.

**Comment by Evg-lylyk** [comment]
Да, спасибо. Видимо где-то по ошибке удалил.
Исправил в 2022.4.7
