### ISSUE TITLE
Развернуть/Свернуть результаты запроса

### ISSUE THREAD

**Issue by dipsy** [infostart-hub/toolkit#601]
Хотелось бы, чтобы можно было включить кнопки Развернуть все и Свернуть все прямо на командную панель результата запроса.
![telegram-cloud-photo-size-2-5407036291914251269-x](https://user-images.githubusercontent.com/1336665/181273149-fedd1a81-402c-4755-a0a8-b9ffee7163ec.jpg)

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.5
