### ISSUE TITLE
Поле объекта не обнаружено (КнопкаНайтиСсылкиНаОбъект)

### ISSUE THREAD

**Issue by dipsy** [infostart-hub/toolkit#602]
Поле объекта не обнаружено (КнопкаНайтиСсылкиНаОбъект)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТабличныйДокументКлиент.Модуль(259)}:КнопкаНайтиСсылкиНаОбъект = ГруппаИнструменты.ПодчиненныеЭлементы.КнопкаНайтиСсылкиНаОбъект;
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(233)}:ИТК_ТабличныйДокументКлиент.ОбработчикПриАктивизацииОбласти(ЭтотОбъект, Элемент, ТабличныйДокументРезультат, ПоследняяАктивнаяОбласть, ТекущийРезультат.АдресДанныхРасшифровки);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(495)}:ИнициализацияРедактораЗапроса();

Под пользователем с ограниченными правами (Базовые + Консоль разработчика)

**Comment by dipsy** [comment]
Также 
Нарушение прав доступа!
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитВызовСервера.Модуль(6)}:НайденныеРасширения = РасширенияКонфигурации.Получить(Отбор);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиентСерверПовтИсп.Модуль(10)}:Возврат ИТК_ТуллкитВызовСервера.Версия();
{InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(27)}:ПолноеИмяКаталога = СтрШаблон(ШаблонИмениКаталога, КаталогДанныхПользователя, ИТК_ТуллкитКлиентСерверПовтИсп.Версия());

по причине:
Нарушение прав доступа!

Хотя сама консоль работает и запросы выполняет, макеты данных выводит

**Comment by Evg-lylyk** [comment]
1. Исправлено в 2022.4.7
2. Видимо это связано с тем что для получения данных установленных расширений требуются права АдминистрированиеРасширений (можно дать эту роль), в версии 2022.5 решу это проблему

**Comment by Evg-lylyk** [comment]
Проблема роли АдминистрированиеРасширений  решена в 2022.5
