### ISSUE TITLE
Рефакторинг параметров запроса

### ISSUE THREAD

**Issue by Karejl** [infostart-hub/toolkit#604]
**Описание ошибки**
При выполнении процедуры рефакторнига в части замены параметров на предопределенные значения, если нет в базе предопределенного значения, то вставляется кривой код. 
Пример: В параметрах определил &счет добавленный в режиме предприятия  в запросе &счет  изменился на "Значение(Плансчетов.Хозрасчетный.)"  нет возможности восстановить параметр. приходится вручную весь запрос анализировать. особенно не приятно, когда сначала сделал рефакторинг по всем параметрам, а после нужно правильно восстановить утерянные параметры. Аналогично со списком значений.

**Ожидаемое поведение, если бы ошибки не было**
Если не найдено предопределенное значение( или значения в списке) оставить параметр без изменений и выдавать соответствующее предупреждение.

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

   - Платформа 1С: *
   - Имя конфигурации: *
   - Язык: *
   - Операционная система: *
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.5
