### ISSUE TITLE
Ошибка редактор объекта плансчетов

### ISSUE THREAD

**Issue by Karejl** [infostart-hub/toolkit#605]
**Описание ошибки**
При попытки открыть редактор объекта в счете
возникает ошибка:
"{(1, 17)}: Поле не найдено "Таблица.ЭтоГруппа"
ВЫБРАТЬ Таблица.<<?>>ЭтоГруппа ИЗ ПланСчетов.Хозрасчетный КАК Таблица ГДЕ Таблица.Ссылка = &Ссылка
{InfostartToolkitPROF ОбщийМодуль.ИТК_Общий.Модуль(340)}:ТаблицаЗначений = Запрос.Выполнить().Выгрузить();
{InfostartToolkitPROF ОбщийМодуль.ИТК_Общий.Модуль(324)}:Результат = ЗначенияРеквизитовОбъекта(Ссылка, ИмяРеквизита);
{InfostartToolkitPROF ОбщийМодуль.ИТК_РаботаСОбъектом.Модуль(106)}:Результат = ИТК_Общий.ЗначениеРеквизитаОбъекта(ИзменяемыйОбъект, "ЭтоГруппа");
{InfostartToolkitPROF ОбщийМодуль.ИТК_РаботаСОбъектом.Модуль(132)}:ЭтоГруппа = ЭтоГруппа(Объект, ОбъектСИерархией, БитаяСсылка);
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(699)}:ДанныеОбъекта = ИТК_РаботаСОбъектом.ПрочитатьСтруктуруИДанные(ИзменяемыйОбъект, ДополнительныеПараметры);
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1290)}:ЗаполнениеДанныхПоОбъекту(ОбрабатываемыйОбъект, , ДобавитьВИсториюВыбранных);
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1572)}:ОбновитьДанныеОбъекта(ДобавитьВИсториюВыбранных);
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(72)}:ОбрабатываемыйОбъектИзменен(ОбрабатываемыйОбъект);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиент.Модуль(31)}:ОткрытьФорму(ОписаниеИнструмента["ПолноеИмяФормы"], ПараметрыФормы, , Уникальность, , , , РежимОткрытияОкнаФормы.Независимый);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ИнтеграцияВКонфигурациюКлиент.Модуль(6)}:ИТК_ТуллкитКлиент.ОткрытьИнструмент(Инструмент, Ссылка);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(257)}:ВыполнитьОбработкуОповещения(Обработчик, ПараметрКоманды);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(64)}:ПродолжитьВыполнениеКоманды(ПараметрыВыполнения);
{ПланСчетов.Хозрасчетный.Форма.ФормаСчета.Форма(624)}:ПодключаемыеКомандыКлиент.ВыполнитьКоманду(ЭтотОбъект, Команда, Объект);

по причине:
{(1, 17)}: Поле не найдено "Таблица.ЭтоГруппа"
ВЫБРАТЬ Таблица.<<?>>ЭтоГруппа ИЗ ПланСчетов.Хозрасчетный КАК Таблица ГДЕ Таблица.Ссылка = &Ссылка"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть '...'
2. Нажать '....'
3. Запустить '....'
4. Где ошибка

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

   - Платформа 1С: 8.3.20.1914
   - Имя конфигурации: Бухгалтерия КОРП (3.0.109.61)
   - ТулКит 2022.4.06
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Исправлена в 2022.4.7
