### ISSUE TITLE
Редактор объекта. Ошибка при просмотре движений

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#606]
**Описание ошибки**
Просмотр движений документа в "Редактор объекта". Если у документа нет движений по регистрам, то при нажатии кнопки "Отображать пустые" (нажать 2 раза подряд) появляется ошибка

`Значение не является значением объектного типа (Доступность)
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(385)}:		Если ДвиженияИдентификаторПоследней <> Неопределено
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(609)}:	Элементы.Движения.ОтборСтрок = ОтборСтрок;
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(461)}:	ОбновитьЭлементыФормы();
`

![image](https://user-images.githubusercontent.com/18395787/182601522-2038b8f5-7262-40fc-bf4c-4bbab486de75.png)

**Окружение:**

   Infostart Toolkit PROF 2022.4.07

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 для Беларуси (2.4.7.166)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.1.434

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.4.8
