### ISSUE TITLE
Глюки конструктора запросов

### ISSUE THREAD

**Issue by salexdv** [infostart-hub/toolkit#608]
**Описание ошибки**

Полное зависание при попытке исключения полей из суммируемых, а также некорректное поведение при добавлении полей в суммируемые

**Сценарий воспроизведения зависания**

1. Открыть запрос в конструкторе

```bsl
ВЫБРАТЬ
	Номенклатура.Ссылка КАК Ссылка,
	МАКСИМУМ(ВЫБОР
			КОГДА Номенклатура.ЭтоГруппа
				ТОГДА ИСТИНА
			ИНАЧЕ ЛОЖЬ
		КОНЕЦ) КАК ЭтоГруппа,
	МАКСИМУМ(ВЫБОР
			КОГДА Номенклатура.ЭтоГруппа
				ТОГДА Номенклатура.ЕдиницаИзмерения
			ИНАЧЕ ЗНАЧЕНИЕ(Справочник.УпаковкиЕдиницыИзмерения.ПустаяСсылка)
		КОНЕЦ) КАК ЕдиницаИзмерения,
	МАКСИМУМ(Номенклатура.ГруппаДоступа) КАК ГруппаДоступа
ИЗ
	Справочник.Номенклатура КАК Номенклатура

СГРУППИРОВАТЬ ПО
	Номенклатура.Ссылка
```

2. Перенести поле (поля) из суммируемых

![1cv8c_QS72eBH7w1](https://user-images.githubusercontent.com/6356534/184887966-61ec79b6-a32f-44c3-94c1-c177a99e99d1.gif)

**Сценарий воспроизведения некорректного поведение при добавлении полей в суммируемые**

1. Добавить любое суммируемое поле выбрав при этом агрегатную функцию
2. Сразу нажать на кнопку переноса другого суммируемого поля

![1cv8c_EZ3fXnFxG3](https://user-images.githubusercontent.com/6356534/184888480-ae19f1b5-321b-478a-9319-78e7731d5570.gif)

**Окружение:**

Infostart Toolkit PROF 2022.4.06

Платформа: 8.3.20.1838 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.9.98)
Основной режим запуска: Managed application
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.3.87

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: en
Режим запуска: Managed application

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.5
