### ISSUE TITLE
Перейти к стоке по номеру - ошибка при отмене

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#611]
**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль запросов.
2. Перейти на вкладку "Внешние источник"
3. Открываем на редактирование "Таблицу значений"
4. Нажимаем кнопку "Перейти к строке по номеру" и нажимаем "Отмена"
5. Получаем ошибку: 
```
Преобразование значения к типу Число не может быть выполнено
{InfostartToolkitPROF ОбщийМодуль.ИТК_ПодключаемыеКомандыКлиент.Модуль(166)}:	Элемент.ТекущаяСтрока = Коллекция[НомерСтроки - 1].ПолучитьИдентификатор();
```

**Скриншоты**
![Параметры](https://user-images.githubusercontent.com/18395787/186158932-a6dcae47-9e05-4ca2-8a6f-9f952743e7d4.gif)

**Окружение:**

 Infostart Toolkit PROF 2022.4.07

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление холдингом, редакция 3.1 (3.1.14.27)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.5.180

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спс, исправлено в 2022.5
