### ISSUE TITLE
Некорректная контекстная подсказка по полям табличной части в запросе

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#612]
**Описание ошибки**
При наборе текста запроса непосредственно в консоли, без использования конструктора, некорректно отображается контекстная подсказка по полям табличной части: вместо полей табличной части видны поля основной таблицы (реквизиты шапки).

**Сценарий воспроизведения**
Открыть консоль запросов в конфигурации семейства ERP, ввести текст запроса:
```
ВЫБРАТЬ
	*
ИЗ
	Документ.ЗаказКлиента.Товары КАК Т
ГДЕ
	Т.
```
Убедиться, что после установки точки после "Т" появится контекстная подсказка, содержащая поля документа (Номер, Дата, Проведен и т.д.), а не поля табличной части товаров (НомерСтроки, Номенклатура и т.д.).

**Ожидаемое поведение, если бы ошибки не было**
Должны отобразиться поля табличной части, как то "НомерСтроки", "Номенклатура", "Количество" и т.д.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/186295601-42fbeeec-5b3c-4bd7-8cd0-f83cfd5897e1.png)

**Окружение:**
Infostart Toolkit PROF 2022.4.06

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by salexdv** [comment]
Консоль доработал. Подсказка реквизитов табличных частей будет работать.

**Comment by Evg-lylyk** [comment]
Реализовано в 2022.5
