### ISSUE TITLE
Контекстная подсказка по коллекции объектов метаданных выдает варианты для конкретного объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#613]
**Описание ошибки**
При наборе кода в консоли контекстная подсказка для класса метаданных (справочников, документов и т.д.) содержит свойства конкретного объекта метаданных (ДлинаКода, Автонумерация и т.д.)

**Сценарий воспроизведения**
Открыть консоль кода. Ввести текст:
`Значение = Метаданные.Справочники.`
Убедиться, что после ввода последней точки открылась меню контекстной подсказки, которое содержит свойства метаданных некоторого справочника: Автонумерация, БыстрыйВыбор и т.д.

**Ожидаемое поведение, если бы ошибки не было**
Для указанного кода контекстная подсказка должна содержать имена справочников в конфигурации.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/186300489-7f178339-7471-4173-9356-995532f7cc55.png)

**Окружение:**
Infostart Toolkit PROF 2022.4.06

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Обновил редактор BSL_Monaco, проблем не наблюдается. Исправлено в 2022.5.1
