### ISSUE TITLE
Сохранение выделения строк при сбросе фильтра по имени во Всех функциях

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#614]
**Существует проблема**
При очистке подстроки поиска в окне "Все функции" сбрасываются выделенные ранее строки, дерево метаданных отображается в первоначальном виде. В некоторых сценариях работы с формой это сбивает с толку, немного усложняя навигацию по метаданным конфигурации.

Пример воспроизведения:
1. В базе ERP открыть "Все функции" инструментов разработчика.
2. В поле поиска по строке ввести строку "номенклат", нажать Enter для получения результата отбора.
3. В списке найденного выделить строку со справочником "Номенклатура".
4. Нажать "крестик" в поле подстроки поиска для его очистки.
5. Убедиться, что после сброса фильтра справочник номенклатуры уже не выбран. Дерево конфигурации свернуто, выделен корень конфигурации.

**Хотелось бы иметь следующую функциональность**
При сбросе фильтра по подстроке поиска сохранять выделение строк в дереве метаданных.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.06

**Comment by Evg-lylyk** [comment]
Подправлено в 2022.5
