### ISSUE TITLE
Не выполняется запрос, если к выводу есть результат ТипЗначения

### ISSUE THREAD

**Issue by SeiOkami** [infostart-hub/toolkit#616]
**Описание ошибки**
Например, если выполнить такой запрос, то упадёт ошибка:

`ВЫБРАТЬ ТИПЗНАЧЕНИЯ(1)`

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть Консоль разработчика
2. Вставить текст запроса: `ВЫБРАТЬ ТИПЗНАЧЕНИЯ(1)`
3. Выполнить запрос
4. Ошибка

**Ожидаемое поведение, если бы ошибки не было**
Результат должен быть корректным, запрос должен выполняться. В данном примере вернётся строка с полем типа "Тип"

**Скриншоты**
![image](https://user-images.githubusercontent.com/42138875/189291699-df3fd946-b09f-4532-bcfc-e14445e58cee.png)

**Окружение:**

  Infostart Toolkit PROF 2022.4.07
  
  Платформа: 8.3.21.1393 (Windows x86-64)
  Режим БД: клиент-серверный
  
  Конфигурация:
  Самописная
  Основной режим запуска: Управляемое приложение
  Режим совместимости: Версия8_3_14
  
  Клиент:
  Тонкий клиент
  ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
  Язык: ru
  Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проблема именно с типом Число, Исправил в 2022.5

**Comment by SeiOkami** [comment]
На всякий случай: проблема с типом Число, Строка и Дата (имеющие квалификаторы)

**Comment by Evg-lylyk** [comment]
> На всякий случай: проблема с типом Число, Строка и Дата (имеющие квалификаторы)

Да спасибо, это важно
