### ISSUE TITLE
Импорт запроса в отладке - значение Неопределено.

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#618]
**Описание ошибки**
В отладке импортирую запрос в консоль запросов. При этом в консоле параметр запроса со значением Неопределено заменяется на значение ПустаяСсылка, что меняет логику выполнения запроса.

![image](https://user-images.githubusercontent.com/18395787/192698612-66699076-65ae-40a3-86e8-422bb9009ada.png)

![image](https://user-images.githubusercontent.com/18395787/192698760-360e9836-a3a3-4d67-9e1b-d57bd000a480.png)

Сам текст запроса (ВзаиморасчетыСервер.ЗаполнитьТаблицуОстатковРасчетов):

`
ВЫБРАТЬ
	АналитикаПоПартнерам.КлючАналитики КАК КлючАналитики,
	АналитикаПоПартнерам.Организация КАК Организация,
	АналитикаПоПартнерам.Партнер КАК Партнер,
	АналитикаПоПартнерам.Контрагент КАК Контрагент,
	АналитикаПоПартнерам.Договор КАК Договор

ПОМЕСТИТЬ АналитикаУчетаПоПартнерам
ИЗ
	РегистрСведений.АналитикаУчетаПоПартнерам КАК АналитикаПоПартнерам
ГДЕ
	&Партнер <> Неопределено
	И АналитикаПоПартнерам.Организация В (&Организация)
	И АналитикаПоПартнерам.Партнер = &Партнер
	И АналитикаПоПартнерам.Контрагент = &Контрагент

ОБЪЕДИНИТЬ ВСЕ

ВЫБРАТЬ
	АналитикаПоПартнерам.КлючАналитики КАК КлючАналитики,
	АналитикаПоПартнерам.Организация КАК Организация,
	АналитикаПоПартнерам.Партнер КАК Партнер,
	АналитикаПоПартнерам.Контрагент КАК Контрагент,
	АналитикаПоПартнерам.Договор КАК Договор
ИЗ
	РегистрСведений.АналитикаУчетаПоПартнерам КАК АналитикаПоПартнерам
ГДЕ
	&Партнер = Неопределено
	И АналитикаПоПартнерам.Организация В (&Организация)
	И АналитикаПоПартнерам.Контрагент = &Контрагент
	И (&ПартнерПрочиеОтношения И АналитикаПоПартнерам.Партнер.ПрочиеОтношения
		ИЛИ НЕ &ПартнерПрочиеОтношения)
`

**Окружение:**

 Infostart Toolkit PROF 2022.4.07

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 для Беларуси (2.4.7.166)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.1.434

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
Полагаю, это дубль #529

**Comment by Evg-lylyk** [comment]
> Полагаю, это дубль #529

Да спасибо, проблема уже известная.

**Comment by Evg-lylyk** [comment]
Постараемся решить, пока можно переключить в выражение встроенного языка и указать Неопределено
