### ISSUE TITLE
Переменная теряет тип как таблица значений после добавления колонки

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#622]
**Описание ошибки**
В консоли кода для переменной типа ТаблицаЗначений перестает корректно работать контекстная подсказка после добавления в таблицу первой колонки. В дальнейшем данная переменная интерпретируется ни как таблица значений, а как ее колонка.

**Сценарий воспроизведения**
Открыть консоль кода. Ввести текст:
```bsl
КоллекцияТаблиц = Новый ТаблицаЗначений();
КоллекцияТаблиц.Колонки.Добавить("ПолноеИмя");
КоллекцияТаблиц.
```
Убедиться, что в последней строке после точки контекстная подсказка не соответствует типу ТаблицаЗначений.

**Ожидаемое поведение, если бы ошибки не было**
В контекстной подсказке должны быть свойства и методы соответствующие объекту типа ТаблицаЗначений.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/195757623-5681c894-2000-4fc5-b18a-a81ed8af5611.png)

**Окружение:**
Infostart Toolkit PROF 2022.4.06

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проверил, в последних версиях нет такой ошибки. Сегодня вышлю 2022.4.8

**Comment by d-hurricane** [comment]
У меня проблема продолжает воспроизводиться.
![image](https://user-images.githubusercontent.com/59051827/199677735-f35cfebe-e863-4acd-a18d-4b522fcd827b.png)

Infostart Toolkit PROF 2022.4.08

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Уже даже не знаю попробовал на последнем редакторе 2022.5.1 все ОК
![Screenshot_1](https://user-images.githubusercontent.com/48444742/204748838-5b980aae-916f-4fdc-b416-989c00a464bc.png)
