### ISSUE TITLE
Некорректная контекстная подсказка по именам объектов метаданных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#623]
**Описание ошибки**
В редакторе кода для коллекции объектов метаданных неверно работает контекстная подсказка. Вместо отображения списка объектов метаданных виден список свойств и методов конкретного объекта.

**Сценарий воспроизведения**
Открыть консоль кода. Ввести текст:
`Объект = Метаданные.Документы.`
Убедиться, что после установки точки контекстная подсказка содержит свойства и методы метаданных документа, а не перечень документов в конфигурации.

**Ожидаемое поведение, если бы ошибки не было**
В контекстной подсказке ожидается список документов конфигурации.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/195759369-e557af55-e5a1-432d-be80-effcb59958cb.png)

**Окружение:**
Infostart Toolkit PROF 2022.4.06

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проверил, в последних версиях нет такой ошибки. Сегодня вышлю 2022.4.8
