### ISSUE TITLE
Ошибка повторной загрузки данных консоли запросов из настроек

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#625]
**Описание ошибки**
При попытке загрузки данные консоли запросов из настроек второй раз подряд данные не загружаются, консоль оказывается пустой. Такой сценарий работы встречается при работе с запросами, перехватываемыми в отладке.

**Сценарий воспроизведения**
1. Открыть консоль запросов. Ввести произвольный запрос, например `ВЫБРАТЬ 1`.
2. Сохранить данные в настройка пользователя: `Данные / Настройка / Сохранить как...`
3. Указать произвольное представление сохраняемых данных. Например, `Тест`.
4. Загрузить только что сохраненные настройки в консоли: `Данные / Настройка / Тест`. Убедиться, что сохраненный запрос загрузился корректно.
5. Вновь загрузить сохраненные настройки: `Данные / Настройка / Тест`. Убедиться, что из консоли пропали все данные, запрос не загрузился.

**Ожидаемое поведение, если бы ошибки не было**
Данные консоли должны загружаться корректно всякий раз, сколько бы мы не инициировали данную процедуру.

**Скриншоты**
После первой загрузки
![image](https://user-images.githubusercontent.com/59051827/199420097-ac4ae258-48a2-4faa-8875-4e93f12e4499.png)

После второй загрузки
![image](https://user-images.githubusercontent.com/59051827/199420128-17be0124-9686-4462-814a-e0da52bf7b94.png)

**Окружение:**
Infostart Toolkit PROF 2022.4.08

Платформа: 8.3.18.1779 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не удалось воспроизвести проблему
