### ISSUE TITLE
Добавить контекстную подсказку для пакетов XDTO

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#626]
**Существует проблема**
В консоли кода отсутствует контекстная подсказка по метаданным класса ПакетXDTO.
![image](https://user-images.githubusercontent.com/59051827/199677003-6faecf31-0978-4c01-a618-a90a736f861f.png)

**Хотелось бы иметь следующую функциональность**
Добавить подсказку по метаданным данного класса, включая его свойства.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.08

**Comment by Evg-lylyk** [comment]
Добавлено в 2022.5
