### ISSUE TITLE
Копирование объектов с использованием редактора объектов

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#627]
**Существует проблема**
Иногда появляется потребность задать уже существующему объекту информационной базы нужных внутренний идентификатор. Редактор объекта предоставляет близкие к нужным инструменты, но не в полной мере: есть возможность установить идентификатор при создании нового объекта и есть кнопка создания нового объекта для его дальнейшего редактирования.

Однако нет возможности быстро, без использования консоли кода, скопировать уже существующий объект, сохранив значения его реквизитов, но установив при этом нужный внутренний идентификатор ссылки.

**Хотелось бы иметь следующую функциональность**
Нужна возможность для аналитиков создавать на основе существующих объектов ИБ новые, но с заданным идентификатором ссылки. Например, это можно реализовать одним из способов:
* Дать возможность всегда редактировать идентификатор ссылки, а не только для новых. При редактировании идентификатора, если такого объекта не существует, переключить интерфейс редактора в режим создания нового объекта. При этом значения реквизитов измениться не должны.
* Добавить рядом с кнопкой "Создание нового" кнопку "Скопировать". При создании нового и копировании запрашивать ввод идентификатора, сохранив при этом возможность не указывать оный.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.4.08

**Comment by d-hurricane** [comment]
Да, вполне подойдет. Видимо, для меня он просто оказался не интуитивным.

**Comment by Evg-lylyk** [comment]
Ты не один такой, еще обращался человек с таким же вопросом. Твой вариант работы мне не нравиться (где указывать гуид).

**Comment by d-hurricane** [comment]
> Твой вариант работы мне не нравиться (где указывать гуид).

Который первый или второй? Или оба?

**Comment by Evg-lylyk** [comment]
> * Дать возможность всегда редактировать идентификатор ссылки, а не только для новых. При редактировании идентификатора, если такого объекта не существует, переключить интерфейс редактора в режим создания нового объекта. При этом значения реквизитов измениться не должны.

Тоже не такое уж очевидное поведение

> * Добавить рядом с кнопкой "Создание нового" кнопку "Скопировать". При создании нового и копировании запрашивать ввод идентификатора, сохранив при этом возможность не указывать оный.

Где указывать ГУИД
