### ISSUE TITLE
В консоли запросов добавить возможность вставки значений параметров запроса из буфера обмена

### ISSUE THREAD

**Issue by salexdv** [infostart-hub/toolkit#628]
**Существует проблема**
В данный момент параметры можно подбирать только вручную.

**Хотелось бы иметь следующую функциональность**
Хотелось бы для параметров с заранее известным типом иметь возможность вставки их из буфера обмена через
```bsl
ОткрытьФорму("ОбщаяФорма.ВводЗначенийСпискомСФлажками")
```

**Дополнительный контекст**
![ITK_Paste0](https://user-images.githubusercontent.com/6356534/200766486-e1420a13-e55c-4993-b762-8d72dffbc994.png)
![ITK_Paste1](https://user-images.githubusercontent.com/6356534/200766518-c5a02b1e-1208-4e90-8b0e-1485e41c6b5b.png)

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.2
