### ISSUE TITLE
Измерения в контекстной подсказке для метода Получить менеджера регистра

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#639]
**Описание ошибки**
Структура результата, полученная с помощью метода "Получить" менеджера регистра сведений, в контекстной подсказке по полям структуры ошибочно содержит не только поля ресурсов, но и поля измерений регистра.

**Сценарий воспроизведения**
1. Открыть консоль кода.
2. Ввести следующий код (пример для 1С:КА)
```
Отбор = Новый Структура("Штрихкод", "");	
Параметры = РегистрыСведений.ШтрихкодыНоменклатуры.Получить(Отбор);
Параметры.
```
3. После установки последней точки убедиться, что появившаяся контекстная подсказка ошибочно содержит поле "Штрихкод".

**Ожидаемое поведение, если бы ошибки не было**
Согласно синтаксис-помощнику, и в действительности, структура `Параметры` должна содержать только ресурсы регистра `ШтрихкодыНоменклатуры`.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/203259127-02ba6b0f-5ec7-421f-b73c-e279f1f4cf26.png)

**Окружение:**
Infostart Toolkit PROF 2022.4.08

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.1.1
