### ISSUE TITLE
Доработки инструмента Метаданные

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#640]
- [x] Вызов из конструктора запросов
- [x] выбор типа когда их несколько
- [x] Владельцы нет перехода к типу
- [x] в свойства метаданных тащить только важные
- [x] Для некоторых коллекций индексирование неактуально (видимо там где незаполнено)
- [x] При щелчке по предопределенному он должен открываться
- [x] Вызов из других инструментов положить поближе
- [x] Избранное на отдельной закладке

**Comment by d-hurricane** [comment]
Пожелания:
- [ ] При открытии из раздела разворачивать на все пространство окна, т.е. открывать независимо, не блокируя владельца.
- [ ] Показать функциональные опции, влияющие как на объект, так и на его реквизиты.
- [ ] Не показывать гиперссылку "Перейти" для отсутствующих модулей (например, для пустых модулей менеджера перечислений)
- [ ] Представление информации в виде таблиц для поиска по значениям свойств.

На вскидку сценарии исследования метаданных, которые приходилось реализовывать кодом:
1. найти объекты с заполненными полями блокировки;
2. найти справочники без кода/наименования;
3. найти справочники с длиной наименования более, чем N, документы с номерами короче, чем N;
4. сравнить состав типов двух реквизитов/подписок на события/регистраторов
5. найти документы по значению свойства "Проведение";
6. найти объекты с некоторым префиксом в имени и без комментария, представления объекта, представления списка

**Comment by Evg-lylyk** [comment]
> Пожелания:
> 
> * [ ]  При открытии из раздела разворачивать на все пространство окна, т.е. открывать независимо, не блокируя владельца.
> * [ ]  Показать функциональные опции, влияющие как на объект, так и на его реквизиты.
> * [ ]  Не показывать гиперссылку "Перейти" для отсутствующих модулей (например, для пустых модулей менеджера перечислений)
> * [ ]  Представление информации в виде таблиц для поиска по значениям свойств.
> 
> На вскидку сценарии исследования метаданных, которые приходилось реализовывать кодом:
> 
> 1. найти объекты с заполненными полями блокировки;
> 2. найти справочники без кода/наименования;
> 3. найти справочники с длиной наименования более, чем N, документы с номерами короче, чем N;
> 4. сравнить состав типов двух реквизитов/подписок на события/регистраторов
> 5. найти документы по значению свойства "Проведение";
> 6. найти объекты с некоторым префиксом в имени и без комментария, представления объекта, представления списка

Буду прорабатывать но такой универсальный отбор наверное потом, в целом все по делу учту, спасибо

**Comment by Evg-lylyk** [comment]
Отмеченное реализовано в 2022.5
