### ISSUE TITLE
Метаданные - ошибка при расшифровке типа ФиксированныйМассив

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#641]
**Описание ошибки**
В инструменте "Метаданные" для параметра сеанса типа "ФиксированныйМассив" если кликнуть по гиперссылке типа, возникает ошибка с текстом:

> Значение не является значением объектного типа (ПолноеИмя)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_Метаданные.Модуль(45)}:Результат = ОбъектМетаданных.ПолноеИмя();
> {InfostartToolkitPROF ОбщийМодуль.ИТК_МетаданныеВызовСервера.Модуль(17)}:Возврат ИТК_Метаданные.ПолноеИмя(Объект);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ИнструментМетаданныеКлиент.Модуль(25)}:ПолноеИмяОбъектаМетаданных = ИТК_МетаданныеВызовСервера.ПолноеИмя(ПервыйСсылочныйТип);
> {InfostartToolkitPROF Обработка.ИТК_Метаданные.Форма.Основная.Форма(136)}:ИТК_ИнструментМетаданныеКлиент.ОбработкаГиперссылкиСвойства(ДанныеГиперссылки, ЗначениеСвойства, ПолноеИмяОбъектаМетаданных, СтандартнаяОбработка);

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/203860498-eb771441-2104-4ca0-9fe6-3c155930b827.png)

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.5.1
