### ISSUE TITLE
Метаданные - ошибка при работе с определяемыми типами-объектами

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#642]
**Описание ошибки**
Если определяемый тип содержит тип-объект, например, СправочникОбъект.Номенклатура, то при выборе такого определяемого типа в дереве метаданных возникнет ошибка с текстом:

> Ошибка при вызове метода контекста (ОбновитьЗначениеСвойствНаФорме)
> {InfostartToolkitPROF Обработка.ИТК_Метаданные.Форма.Основная.Форма(528)}:ОбновитьЗначениеСвойствНаФорме(Результат.АдресРезультата);
> {ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(63)}:ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
> {(1)}:Модуль.ОжидатьЗавершение(Параметры[0],Параметры[1],Параметры[2])
> {InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(75)}:Выполнить(Выражение);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(20)}:ВыполнитьМетод(ПолноеИмя, Параметры);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ДлительныеОперацииКлиент.Модуль(199)}:ИТК_БСПКлиентСервер.ВыполнитьПроцедуру("ДлительныеОперацииКлиент.ОжидатьЗавершение", ПараметрыПроцедуры);
> {InfostartToolkitPROF Обработка.ИТК_Метаданные.Форма.Основная.Форма(496)}:ИТК_ДлительныеОперацииКлиент.ОжидатьЗавершение(ДлительнаяОперация, ОповещениеОЗавершении, ПараметрыОжидания);
> {InfostartToolkitPROF Обработка.ИТК_Метаданные.Форма.Основная.Форма(470)}:ОбновитьСвойства();
> 
> по причине:
> Ошибка передачи данных между клиентом и сервером. Значение недопустимого типа.
> по причине:
> Ошибка преобразования данных XDTO:
> НачалоСвойства: Type	Форма: Элемент	Тип: {http://www.w3.org/2001/XMLSchema}QName
> по причине:
> Ошибка отображения типов:
> Отсутствует отображение для типа '{http://v8.1c.ru/8.1/data/enterprise/current-config}DocumentObject.бит_му_ОбесценениеДебиторскойЗадолженности'

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/203860806-60e82661-9c65-4108-8cbb-714375ee3619.png)

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2022.5.1
