### ISSUE TITLE
Некорректная работа с признаком модификации формы

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#650]
**Описание ошибки**

1. Сразу при открытии консоли кода или запроса данные считаются измененными, и при попытке закрыть форму, появляется предложение о сохранении данных, которых по сути еще нет.
2. После сохранения данных в файл признак модификации формы не исчезает, вопрос о сохранении данных при закрытии консоли появляется.
3. После чтения данных из файла признак модификации формы не исчезает, вопрос о сохранении данных при закрытии консоли появляется.

**Ожидаемое поведение, если бы ошибки не было**
В определенные моменты данные в форме консоли не должны считаться измененными, "звездочка" в заголовке формы должна отсутствовать и при попытке закрыть консоль вопроса о сохранении быть не должно. К таким моментам относятся:
- консоль только что открыта;
- данные консоли только что записаны в файл или в настройки;
- данные консоли только что прочитаны из файла или из настроек.

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проверяю все нормально, разберись поглубже

**Comment by Evg-lylyk** [comment]
У меня данная проблема не наблюдается, метод устанавливает текст не должен приводить к модифицированности
Попробуй почистить кэш и удалить каталоги
РабочийКаталогДанныхПользователя() (На клиенте) \ ITK_Monaco*

**Comment by d-hurricane** [comment]
> метод устанавливает текст не должен приводить к модифицированности
За что купил, за то продал. С одними и теми же аргументами метод почему-то меняет признак модифицированности формы, при том именно со второго раза. В первый вызов не меняет.
Очистка кэша не помогла.

**Comment by Evg-lylyk** [comment]
Попробуй метод updateText заменить на setText

**Comment by Evg-lylyk** [comment]
Воспроизвел проблему
