### ISSUE TITLE
Инструмент вставки произвольной строки в консоль кода как строковый литерал

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#651]
**Существует проблема**
При вводе кода в консоли порой возникает необходимость вставить в код из буфера обмена какой-либо текст и оформить его в виде строкового литерала. Обычный способ вставки в документ текста из буфера обмена не подходит, т.к. итоговый строковый литерал может содержать синтаксические ошибки:
- отсутствие переносов строк, когда вставляемый текст многострочный;
- отсутствие экранирования одинарных и двойных кавычек.

**Хотелось бы иметь следующую функциональность**
Нужен инструмент, возможно по типу конструктора строк на разных языках, благодаря которому вставляемый в код текст из буфера обмена будет преобразован к корректному строковому литералу.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.5.0

**Comment by Evg-lylyk** [comment]
Пока не хочется делать еще один пункт который нужен очень редко, и  никто знать не будет что он есть
