### ISSUE TITLE
Несериализуемые данные в качестве результата в консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#653]
**Описание ошибки**
В консоли кода если переменной `Результат` присвоить несериализуемое значение, то при выполнении кода возникнет ошибка:

> Ошибка при вызове метода контекста (ПоместитьВоВременноеХранилище)
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(4407)}:ТекущийРезультат.Адрес = ПоместитьВоВременноеХранилище(Результат.Результат, УникальныйИдентификатор);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(4330)}:ОбновитьРезультатСервер(Результат.АдресРезультата);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3656)}:ОбновитьРезультатВыполнения(Результат);
> {ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(63)}:ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
> {(1)}:Модуль.ОжидатьЗавершение(Параметры[0],Параметры[1],Параметры[2])
> {InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(75)}:Выполнить(Выражение);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(20)}:ВыполнитьМетод(ПолноеИмя, Параметры);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ДлительныеОперацииКлиент.Модуль(199)}:ИТК_БСПКлиентСервер.ВыполнитьПроцедуру("ДлительныеОперацииКлиент.ОжидатьЗавершение", ПараметрыПроцедуры);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3545)}:ИТК_ДлительныеОперацииКлиент.ОжидатьЗавершение(ДлительнаяОперация, ОповещениеОЗавершенииВыполнения(Строка), ПараметрыОжидания);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3484)}:ВыполнитьОперациюЧерезДлительныеОперации(ОбрабатываемаяСтрока, НаименованиеОперации, Режим, ИгнорироватьЛимитСтрок);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(1413)}:ВыполнитьОперацию("Выполнение");
> 
> по причине:
> Переданное значение не может быть помещено во временное хранилище

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль кода. Ввести код `Результат = ФабрикаXDTO;`
2. Выполнить код. Убедиться, что при выполнении возникла описанная выше ошибка.

**Ожидаемое поведение, если бы ошибки не было**
При выполнении приведенного кода ошибки быть не должно. В качестве результат должен отображаться тип присвоенного значения - ФабрикаXDTO.

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 2022.5.2 (костылек, но пока так)
