### ISSUE TITLE
Редактор объекта - просмотр движений

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#655]
**Описание ошибки**
В редакторе объекта при просмотре движений при нажатии кнопки "отображать пустые" появляется ошибка. (Документ не проведен и у него нет движений).

![Параметры](https://user-images.githubusercontent.com/18395787/206108659-f91b1c32-2cc1-44bf-aa8c-405ca62210e3.gif)

**Окружение:**

   Infostart Toolkit PROF 2022.5.02

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спс, исправлено в 2022.5.3
