### ISSUE TITLE
Консоль запросов - задваивает текст запроса после редактирования.

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#656]
**Описание ошибки**
После открытия конструктора запроса - текст запроса в консоли не очищается, а к нему добавляется новый текст запроса из конструктора.

**Скриншоты**

![Параметры](https://user-images.githubusercontent.com/18395787/206110551-9dd8b5e7-6ef1-4d64-87b9-ca2c50ddfaac.gif)

**Окружение:**
Infostart Toolkit PROF 2022.5.02

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 (9.0.6.402)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спс, исправлено в 2022.5.3
