### ISSUE TITLE
Обработка исключений paste1c.ru

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#658]
**Описание ошибки**
При передаче текста запроса (или кода) на paste1c.ru там походу выполняются какие-то проверки на валидность передаваемых данных.

Например при попытке передачи такого текста запроса
![image](https://user-images.githubusercontent.com/18395787/206273503-fbde5eba-c538-47c4-9e49-5d8c837b5a5d.png)
приходит ответ с кодом 200
![image](https://user-images.githubusercontent.com/18395787/206273601-639539f1-302c-4244-af8d-5da6d6979717.png)
но при этом success = ложь
![image](https://user-images.githubusercontent.com/18395787/206273715-8e6bbf5d-2462-4118-b5fb-9882bc1cb059.png)
в ошибках приведен список ошибок
![image](https://user-images.githubusercontent.com/18395787/206273792-07377c45-441a-4e60-8196-d6e3530d6b2c.png)

Но ИТК не обрабатывают такую ситуацию и выводят такое сообщение об ошибке
![image](https://user-images.githubusercontent.com/18395787/206273913-a88abfc8-0c71-4ab3-b651-231e4b83bff1.png)

**Ожидаемое поведение, если бы ошибки не было**
Хотелось бы в случае неуспеха видеть такое описание ошибок

![image](https://user-images.githubusercontent.com/18395787/206274107-1b45dfdd-5286-41ce-baad-2e5d8e7b20ae.png)

**Окружение:**
Infostart Toolkit PROF 2022.5.02

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Вывод ошибок реализовал в 2022.5.4, на счет сервиса напишу автору постараемся решить вопрос
