### ISSUE TITLE
Консоль запросов не находит таблицу из внешнего источника при попытке выполнения запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#659]
**Описание ошибки**
![image](https://user-images.githubusercontent.com/65346358/207236597-649c32d4-1612-43e4-ac28-b008ec074321.png)
![image](https://user-images.githubusercontent.com/65346358/207236865-c69ef251-05a2-4dc5-85bf-ba877de9d810.png)

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Добавить 2 внешних источника типа "выражение"
2. Добавить их в запрос
3. Попытаться выполнить запрос

**Окружение:**

Infostart Toolkit PROF 2022.4.09

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.23.165)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.178

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Petr28** [comment]
@Evg-lylyk планируется ли поддержка в консоли запросов работы с внешними источниками данных?
Если да, то когда ожидать?

**Comment by Evg-lylyk** [comment]
Постараюсь исправить в след. мажорной версии

**Comment by Evg-lylyk** [comment]
> @Evg-lylyk планируется ли поддержка в консоли запросов работы с внешними источниками данных? Если да, то когда ожидать?

Поддержка есть, данную проблему планирую решить в 2023.5.

**Comment by Evg-lylyk** [comment]
Проверил, все работает. Нужно больше информации для воспроизведения
Возможно в коде не формировалось корректное значение таблицы значений
