### ISSUE TITLE
Ошибка конструктора запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#660]
**Описание ошибки**
1. несоответствие набора полей в области "База данных" и "Таблицы" у временной таблицы из внешнего источника.
![image](https://user-images.githubusercontent.com/65346358/207254234-153a4ae0-00e7-4007-9e54-1861781f2584.png)
2. Ошибка добавления полей (добавляются не те поля + ошибка при добавлении последнего поля)
![ОшибкаКонструктораЗапроса](https://user-images.githubusercontent.com/65346358/207254039-a3ef8ab1-c3ea-484b-8df5-8ac0bc0a7f9f.gif)
3. Непонятные поля с точкой в области "Таблицы"
![image](https://user-images.githubusercontent.com/65346358/207254272-d11b91d8-2936-4177-9436-1ac139750704.png)

Infostart Toolkit PROF 2022.4.09

Платформа: 8.3.20.1674 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.23.165)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.178

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проблема решена 2024.1
