### ISSUE TITLE
Выбирать роли в Анализе прав доступа по имени

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#664]
**Существует проблема**
Настройка фильтра по ролям в отчете "Анализ прав доступа" предоставляет список для выбора ролей, где роли представлены синонимами. Для разработчика этом может быть неудобным, т.к. он оперирует именами ролей, как они заданы в конфигурации. При этом после настройки гиперссылка фильтра содержит именно имена ролей, а не синонимы.

**Хотелось бы иметь следующую функциональность**
Предоставить возможность отображения в списке выбора имена ролей вместо их синонимов.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.5.0

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.1
