### ISSUE TITLE
Показывать неустановленные права на объект в отчете по правам доступа

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#665]
**Существует проблема**
Попытка заменить просмотр ролей в конфигураторе просмотром ролей в отчете из InfostartToolkit выявила следующие неудобства:
1. Порядок прав доступа, отображаемых в отчете, не соответствует порядку в конфигураторе. Например, для документа "Ввод по строке" в отчете выводится до интерактивных прав, а не после, как в конфигураторе.
2. Глаз привык видеть все права, возможные для объекта, однако отчет выводить только назначенные на объект права.

**Хотелось бы иметь следующую функциональность**
Во-первых, хотелось бы видеть права в отчете в том порядке, в каком они отображаются в конфигураторе. Во-вторых, хотелось бы видеть не только назначенные права на объект некоторой ролью, но и не назначенные. Это должно касаться лишь тех ролей, где есть хотя бы одно назначенное право на объект. Дополнительно хотелось бы видеть вообще все права, доступные в платформе, в т.ч. права доступа к истории версий объектов.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.5.0

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.3
