### ISSUE TITLE
Удаляются связи при перетаскивании наборов данных в СКД

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#666]
**Описание ошибки**
В конструкторе СКД тонкого клиента при попытке перетащить один из нескольких наборов данных на новую позицию в этом же списке удаляются некоторые строки на закладке "Связи наборов".

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль СКД. Запустить конструктор СКД (тонкий клиент)
2. Добавить первый набор "НаборДанны1" типа "Запрос". Ввести произвольный текст запроса, например `Выбрать 1 Как Поле1`
3. Добавить второй набор "НаборДанных2" типа "Запрос". Ввести произвольный текст запроса, например `Выбрать 2 Как Поле2`
4. Перейти на закладку "Связи наборов". Добавить связь между добавленными наборами по их единственным полям.
5. Вернуться на закладку "Наборы данных". С помощью мышки попытаться перетащить "НаборДанных1", расположенный в первой позиции, на вторую позицию.
6. Убедиться, что перетаскивание сработало, наборы данных поменялись местами, однако пропала связь между наборами.

**Ожидаемое поведение, если бы ошибки не было**
Изменение порядка наборов данных не должно приводить к удалению связей между наборами.

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено 2024.2
