### ISSUE TITLE
Добавить контекстную подсказку в выражения связей наборов данных конструктора СКД

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#668]
**Существует проблема**
При вводе связей между наборами данных в конструкторе СКД тонкого клиента отсутствует контекстная подсказка по полям наборов данных.

**Хотелось бы иметь следующую функциональность**
Не открывая по кнопке выбора в поле "Выражение" при вводе текста хотелось бы видеть выпадающий список полей набора данных, соответствующих введенному тексту.

**Дополнительный контекст**
Infostart Toolkit PROF 2022.5.0

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.2
