### ISSUE TITLE
Ошибка при редактировании параметров виртуальной таблицы для компоновки данных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#669]
**Описание ошибки**
При попытке открыть редактор параметров виртуальной таблице на закладке "Компоновка данных" конструктора запросов тонкого клиента возникает ошибка с текстом:

> Поле объекта не обнаружено (ITK_ЗначенияВнешнихИсточников)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_КонструкторЗапросов.Модуль(416)}:Форма.Object[ИдентификаторВнешнихИсточников] = Форма.Параметры[ИдентификаторВнешнихИсточников];
> {InfostartToolkitPROF Обработка.ИТК_QueryWizard171819202122.Форма.ArbitraryExpression.Форма(27)}:ИТК_КонструкторЗапросов.ФормаРедактированиеПоляПриСозданииНаСервереПередЗаполнением(ЭтотОбъект);
> {InfostartToolkitPROF Обработка.ИТК_QueryWizard171819202122.Форма.DataCompositionAvailableTableParameters.Форма(294)}:OpenForm("DataProcessor.ИТК_QueryWizard171819202122.Form.ArbitraryExpression", Params, ThisForm,,,,Notification,
> {InfostartToolkitPROF Обработка.ИТК_QueryWizard171819202122.Форма.DataCompositionAvailableTableParameters.Форма(274)}:ConditionChangeInDialog(Item.EditText, Item.Name);

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль СКД. Запустить конструктор СКД для тонкого клиента.
2. Добавить набор данных типа "Запрос". Открыть конструктор запроса.
3. Добавить в выборку любую виртуальную таблицу остатков по регистру накопления. Для ERP (УТ, КА) это может быть таблица "БонусныеБаллы.Остаток".
4. Перейти на закладку "Компоновка данных" конструктора запроса. Спозиционировать курсор на виртуальной таблице и нажать кнопку редактирования параметров.
5. Нажать кнопку выбора (троеточие) в поле "Условие". Убедиться, что появилось сообщение об ошибке.

**Ожидаемое поведение, если бы ошибки не было**
Должен открываться редактор параметра условий виртуальной таблицы.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/208005467-078637b2-24d4-420f-84ca-4de861753c1e.png)

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.2
