### ISSUE TITLE
Не добавляются поля отбора из расширения условий компоновки данных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#670]
**Описание ошибки**
В конструкторе СКД для тонкого клиента при добавлении в текст запроса условий в расширение секции "ГДЕ" с указанием псевдонима условия, ассоциированное поле с данным условием не появляется в наборе данных. Флаг "Автозаполнение" при этом установлен.

Более того, указанные поля не появляются в наборе данных даже при условии, что схема компоновки была загружена из файла, где эти поля были.

**Сценарий воспроизведения**
Шаги по воспроизведению:
Открыть консоль СКД. Запустить конструктор СКД для тонкого клиента.
Для нового набора данных вести следующий текст запроса:
```
ВЫБРАТЬ
	1 КАК ПолеВыборки
{ГДЕ
	(ИСТИНА) КАК ПолеОтбора}
```
Нажать "Проверить запрос". Убедиться, что в наборе данных автоматически появилось поле `ПолеВыборки`, но не появилось поле `ПолеОтбора`.

**Ожидаемое поведение, если бы ошибки не было**
В наборе данных должны появиться оба поля.

**Скриншоты**
![image](https://user-images.githubusercontent.com/59051827/208006726-23efd4f6-3ff5-4e55-ab3c-453038d1fe16.png)

**Окружение:**
Infostart Toolkit PROF 2022.5.0

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.267/3.2.34.8)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Решил проблему в 2024.2
