### ISSUE TITLE
Не работает подсказка в условии запрос начинающегося с НЕ

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#673]
Если пишешь условие, начинающееся с НЕ, то предложение вариантов не работает.
Приходится писать сначала без НЕ, потом возвращаться и вставлять - неудобно.

Пример:
ВЫБРАТЬ
	_ДемоКассы.Ссылка КАК Ссылка,
	_ДемоКассы.Наименование КАК Наименование
ИЗ
	Справочник._ДемоКассы КАК _ДемоКассы
ГДЕ
	НЕ _<Тут подсказка не срабатывает>

**Comment by salexdv** [comment]
Исправил

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.3.1
