### ISSUE TITLE
При попытке сохранить схему СКД в XML выводится сообщение о невозможности использования синхронных методов на клиенте

### ISSUE THREAD

**Issue by serjevski** [infostart-hub/toolkit#674]
**Описание ошибки**
При попытке сохранить схему СКД в XML выводится сообщение о невозможности использования синхронных методов на клиенте

**Сценарий воспроизведения**
Шаги по воспроизведению:
Создаем в конструкторе СКД любую схему. при попытке ее сохранить в файл кнопочкой, выделенной красным кружочком на скрине:
![image](https://user-images.githubusercontent.com/2284313/210779972-9c0d010b-6ec2-436e-894c-2c67e8c35b1a.png)
получаем сообщение об ошибке
![image](https://user-images.githubusercontent.com/2284313/210780058-1643a1c8-6b41-45c9-9b2f-02b10b54e6ce.png)

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

   - Платформа 1С: *
   1С:Предприятие 8.3 (8.3.22.1750) 
   - Имя конфигурации:  Самописка
   - Язык: Русский
   - Операционная система: Windows

   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки
===
Infostart Toolkit PROF 2022.5.04

Платформа: 8.3.22.1750 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Satis calc ()
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: ru
Режим запуска: Управляемое приложение
===

**Comment by Evg-lylyk** [comment]
Исправлено в версиях 2023.1, 2023.2
