### ISSUE TITLE
Не работает "О программе"

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#676]
**Описание ошибки**
При нажатии "О программе" появляется ошибка 
![image](https://user-images.githubusercontent.com/18395787/211306269-c5cdb3f6-b4e1-4e31-9910-381abc160330.png)

![image](https://user-images.githubusercontent.com/18395787/211306290-8b6b501b-9bde-4d5d-af0e-593b22e546bb.png)

Аналогичная проверка (с выводом ошибки) происходит при открытии консоли запросов.

**Окружение:**

   InfostartToolkitPROF 2023.1.01
   
![image](https://user-images.githubusercontent.com/18395787/211306502-3e7522d6-7fc4-49ed-83c3-2f5556efd570.png)

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.1.2

**Comment by JohnyDeath** [comment]
Да, подобная ошибка возникала при открытии любого окна в ИТК

**Comment by AnatoliyBritko** [comment]
В консоли запросов еще не показывает сам текст запроса. Не знаю это из за ошибки с версиями или отдельно что-то
![image](https://user-images.githubusercontent.com/18395787/211315071-22b78f81-4c90-45a4-a378-f7a43a72e332.png)
