### ISSUE TITLE
Запуск от имени пользователя когда пароль запрашивается при входе

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#678]
**Существует проблема**
Инструмент "Пользователи" позволяет запустить сеанс работы под конкретным пользователем из списка, не зная при этом его пароль. Однако, если запускать сеанс от имени пользователя, у которого в профиле установлен флажок "Запрашивать пароль при в ходе", то при входе появится запрос на ввод пароля. Это некорректно, т.к. пароль должен установить сам пользователь, а не разработчик, запускающий сеанс от чужого имени.

**Хотелось бы иметь следующую функциональность**
При запуске сеанса под другим пользователем временно сбрасывать не только пароль пользователя, но и признак необходимости вводить пароль при запуске.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.1.02

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.1.3
