### ISSUE TITLE
Анализ плана запроса в консоли запросов - ошибка

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#681]
**Описание ошибки**
В консоли запросов при нажатии на гиперссылку "Анализировать план запроса" появляется ошибка

![image](https://user-images.githubusercontent.com/18395787/212096503-4c69a873-3398-48c4-95b7-dd25949cbab9.png)

Ошибка возникает если в запросе идет выборка данных из таблицы значений, в колонке которой есть ссылочный тип

![image](https://user-images.githubusercontent.com/18395787/212097272-e8b7dea4-cead-40fa-8b86-8acb8e8084bb.png)

```
ВЫБРАТЬ
	Тз.Номер КАК Номер,
	Тз.Номенклатура КАК Номенклатура
ПОМЕСТИТЬ ВтТз
ИЗ
	&ТЗ КАК Тз
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	ВтТз.Номер КАК Номер,
	ВтТз.Номенклатура КАК Номенклатура
ИЗ
	ВтТз КАК ВтТз

```

также может есть воз-ть расширить надпись 
![image](https://user-images.githubusercontent.com/18395787/212098264-e6e692ec-fb33-4c12-be5a-33156a9e7d4b.png)

**Окружение:**

  Infostart Toolkit PROF 2023.1.02

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не удалось воспроизвести проблему
![Screenshot_1](https://user-images.githubusercontent.com/48444742/212699872-4465202a-c8eb-4d4c-aa3e-056c24625a8f.png)
нужно больше информации.
Надпись детализировал

**Comment by AnatoliyBritko** [comment]
> Не удалось воспроизвести проблему ![Screenshot_1](https://user-images.githubusercontent.com/48444742/212699872-4465202a-c8eb-4d4c-aa3e-056c24625a8f.png) нужно больше информации. Надпись детализировал

"Услуги перевозки" - это ссылка на справочник номенклатура
и при нажатии на "Анализировать план" - все штатно отработало?

**Comment by Evg-lylyk** [comment]
> "Услуги перевозки" - это ссылка на справочник номенклатура и при нажатии на "Анализировать план" - все штатно отработало?

Да

**Comment by AnatoliyBritko** [comment]
[1Cv8.zip](https://github.com/infostart-hub/toolkit/files/10434467/1Cv8.zip)
залил dt, база на mssql, 1C  8.3 (8.3.18.1289)

надо будет установить ИТК
в обработке будет вызов прописан

![image](https://user-images.githubusercontent.com/18395787/212886363-6de525b7-c29e-4f83-b0f8-59bdc7d66d7b.png)

**Comment by Evg-lylyk** [comment]
На твоем примере тоже не воспроизводится, может кэш почиcтить ;)
![С твоей базой тоже не воспроизводится](https://user-images.githubusercontent.com/48444742/212894117-5c7e4cf0-bd5e-407f-8f76-b7cb66a60c02.gif)

**Comment by AnatoliyBritko** [comment]
а СУБД - MSSQL ?

**Comment by Evg-lylyk** [comment]
Спс, ошибка исправлена в 2023.1.3
