### ISSUE TITLE
Если объект метаданных задача не имеет регистра адресаци, то не выводятся данные по всему объекту

### ISSUE THREAD

**Issue by Kyrales** [infostart-hub/toolkit#682]
**Описание ошибки**
Проблема в обработке Метаданных. Если объект метаданных задача не имеет регистра адресаци, то не выводятся данные по всему объекту. См. скрин

e1cib/app/Обработка.ИТК_Метаданные

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть '...'
2. Нажать '....'
3. Запустить '....'
4. Где ошибка

**Ожидаемое поведение, если бы ошибки не было**
Данные по объекту метаданных Задачи

**Скриншоты**
![image](https://user-images.githubusercontent.com/79920318/213421201-86f04bcf-2e9d-4a6e-b6fc-3e33be60382f.png)
![image](https://user-images.githubusercontent.com/79920318/213421219-76747a82-694d-490d-90b1-7d69506de5bf.png)

 
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки
Infostart Toolkit PROF 2022.5.04

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Купорос, редакция 1.3 (1.3.24.2)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.7.110

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Ошибка исправлена в следующей версии
https://github.com/infostart-hub/toolkit/releases/tag/2023.1.1
