### ISSUE TITLE
Ошибка при работе с конструктором запросов при скрытых настройках данных в консоли разработчика

### ISSUE THREAD

**Issue by ChernyakAI** [infostart-hub/toolkit#683]
**Описание ошибки**
Ошибка при работе с конструктором запросов при скрытых настройках данных в консоли разработчика.

**Сценарий воспроизведения**
1. Открыть консоль запросов
2. Нажать кнопку "Скрыть / показать настройки данных (ALT + S)". На экране останется только группа формы с Результатом.
3. Открыть конструктор запроса (F4) и добавить выборку (например, "Ссылка" из справочника "Номенклатура")
4. Нажать кнопку "ОК" для фиксации изменений.
5. Получить ошибку:
```
Значение не является значением объектного типа (setReadOnly)
{InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(258)}:ДокументHTML(Элемент).setReadOnly(Не ДоступноРедактирование);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6678)}:ИТК_РедакторКодаКлиент.УстановитьДоступностьРедактирования(ЭтотОбъект, ЭлементТекст, ДоступноРедактированиеТекста);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6578)}:ПодключаемыйЗагрузитьСостояниеРедактораКода();
{InfostartToolkitPROF Обработка.ИТК_QueryWizard171819202122.Форма.QueryWizard.Форма(9712)}:ThisForm.Close(ResultQueryText);
```
При этом запрос сохраняется, что можно увидеть, если снова отобразить группу с настройками.

**Ожидаемое поведение, если бы ошибки не было**
Отсутствие исключения.

**Скриншоты**
![image](https://user-images.githubusercontent.com/50447110/213598575-eec6f8ae-8e8a-4104-b4d7-97f32c409856.png)

**Окружение:**

```
Infostart Toolkit PROF 2022.5.04

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.318)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Спс, исправлено в 2023.2 (выйдет позже, много изменений, нужно протестировать)
