### ISSUE TITLE
Ошибка открытия конструктора запросов (тонкий улучшенный) в том случае, если выбранных полях присутствует табличная часть

### ISSUE THREAD

**Issue by ChernyakAI** [infostart-hub/toolkit#684]
**Описание ошибки**
Если в выбранных полях в запросе присутствует и выборка из табличной части, то при попытке открытия конструктора запроса возникает ошибка: "Поле объекта не обнаружено (ТипЗначения)". Проблема только в тонком улучшенном конструкторе, в обычном тонком ошибки нет.

**Сценарий воспроизведения**
1. Открыть консоль и добавить запрос (конструктором или копированием не важно). Например:
```
ВЫБРАТЬ
	Валюты.Ссылка КАК Ссылка,
	Валюты.Код КАК Код,
	Валюты.Наименование КАК Наименование,
	Валюты.Представления.(
		Ссылка КАК Ссылка,
		НомерСтроки КАК НомерСтроки,
		КодЯзыка КАК КодЯзыка,
		ПараметрыПрописи КАК ПараметрыПрописи
	) КАК Представления
ИЗ
	Справочник.Валюты КАК Валюты
```
2. Нажать в консоли кнопку "Конструктор" (F4) для вызова конструктора запроса. Получить ошибку:
![image](https://user-images.githubusercontent.com/50447110/213606289-6af51326-a748-489c-94bc-c1074b9696e9.png)

**Подробности**
Проблема в методе ИТК_КонструкторЗапросов.ЗаполнитьДополнительныеПоляПолейОбъединения(Строка, Колонка);
куда из ИТК_QueryWizard171819202122.Формы.QueryWizard.FillAliases(...) в параметр "колонка" приходят разные типы данных для поля и для таблицы:
![image](https://user-images.githubusercontent.com/50447110/213607425-3bf7de19-dd8b-4e23-b991-11a9453a79df.png) 
![image](https://user-images.githubusercontent.com/50447110/213607517-8ea76869-cc8c-40da-9296-4748517f4250.png)

**Ожидаемое поведение, если бы ошибки не было**
Открытие подобного запроса конструктором

**Окружение:**
```
Infostart Toolkit PROF 2022.5.04

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.318)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Спс, ошибка исправлена в 2023.1.3
