### ISSUE TITLE
Редактор реквизитов не показывает внутренние табличные части ПланВидовРасчета.Начисления

### ISSUE THREAD

**Issue by Kyrales** [infostart-hub/toolkit#685]
Редактор реквизитов не показывает внутренние табличные части в объекте ПланВидовРасчета.Начисления

Должен выводить:
Базовые виды расчета
Ведущие виды расчета
Вытесняющие виды расчета

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.2
