### ISSUE TITLE
Менеджер открытых форм

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#686]
Было бы здорово внедрить похожий функционал
https://infostart.ru/public/610324/

**Comment by Evg-lylyk** [comment]
Уточни какие задачи, проблемы ты хочешь с его помощью решать?

**Comment by mrChOP93** [comment]
Требуемые возможности: просмотр и изменение свойств элементов формы (Изменение доступности, видимости и тп. Просмотр имени, пути к данным и тд). Просмотр и редактирование реквизитов форм.

Например, часть формы создается программно и мне надо скрыть какой то элемент. Куда проще найти имя элемента с помощью приведенной выше обработки и в конце выполняемого кода при открытии убрать его, нежели искать код формирования данного элемента. Или, недавно надо было поправить форму графика работы в зуп. Там программно заполняется реквизит формы тз. Очень удобно было залезть в этот самый реквизит с помощью обработки и посмотреть состав строк тз (этот реквизит вообще на форме не отображался).

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.3
