### ISSUE TITLE
Консоль запроса: глюк формы при загрузке запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#688]
Не подгружается часть формы при открытии сохраненного запроса

![Глюк формы](https://user-images.githubusercontent.com/65346358/215391272-52832e08-ccb8-4b66-8a8f-1a25ef9c7d90.gif)

Infostart Toolkit PROF 2022.5.04

Платформа: 8.3.21.1624 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.24.308)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.247

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
Вроде же была решена в рамках #625

**Comment by Evg-lylyk** [comment]
> Вроде же была решена в рамках #625

Там вроде стоит "не удалось воспроизвести". Поищу в чем проблема

**Comment by d-hurricane** [comment]
> Там вроде стоит "не удалось воспроизвести".

Точно, я почему-то лишь глянул на статус, комментарий не заметил.

**Comment by Evg-lylyk** [comment]
Разобрались с этой проблемой 2023.1.4, 2023.2
