### ISSUE TITLE
Редактирование свойств пользователя

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#691]
**Существует проблема**
Есть инструмент "Пользователи", позволяет просматривать его свойства, но нет возможности редактирования этих свойств.

**Хотелось бы иметь следующую функциональность**
Часто лень через конфигуратор отключать защиту от опасных действий, хотелось бы снять флажок в карточке пользователя.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.1.02

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.3
