### ISSUE TITLE
Интеграция инструмента Пользователи с одноименным справочником БСП

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#692]
**Существует проблема**
Иногда хочется глянуть свойства пользователя информационной базы, особенно часто это может понадобиться, если появится возможность редактирования этих свойств. Сейчас справочник пользователей и одноименный инструмент InfostartToolkit располагаются в разных разделах.

**Хотелось бы иметь следующую функциональность**
Было бы удобно иметь возможность просматривать и редактировать свойства пользователя информационной базы непосредственно в форме элемента справочника пользователей. В любом виде, будь то отдельная группа формы, гиперссылка на панели навигации, кнопка формы.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.1.02

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.3 (через команду в глобальном меню)
