### ISSUE TITLE
Ошибка возврата пароля пользователю

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#697]
**Описание ошибки**
Ошибка при вызове метода контекста (Записать)
{InfostartToolkitPROF Обработка.ИТК_Пользователи.Форма.ЗапускПодПользователем.Форма(103)}:ПользовательИБ.Записать();
{InfostartToolkitPROF Обработка.ИТК_Пользователи.Форма.ЗапускПодПользователем.Форма(88)}:ВернутьДанныеАвторизацииПользователя(ДанныеАвторизации);
{InfostartToolkitPROF Обработка.ИТК_Пользователи.Форма.ЗапускПодПользователем.Форма(34)}:ВернутьДанныеАвторизации();
{InfostartToolkitPROF Обработка.ИТК_Пользователи.Форма.ЗапускПодПользователем.Форма(79)}:Закрыть();

по причине:
Заданный пароль короче установленной минимальной длины

**Сценарий воспроизведения**
При попытке закрыть окно "Запуск под пользователем" после установки ограничения длины пароля

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

<img width="478" alt="image" src="https://user-images.githubusercontent.com/65346358/221475288-be306012-2666-4640-803d-1032d90685bb.png">

**Окружение:**
Infostart Toolkit PROF 2023.1.04

Платформа: 8.3.21.1624 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.24.408)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.294

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Видимо проблема в том что текущий пароль не соответствует новым требованиям и при попытке вернуть пароль ошибка.
Чуть поработал с проблемой в версии 2023.2.1
Задал более сложный и длинный подменяемый пароль чтобы соответствовать возможным высоким требованиям

**Comment by Evg-lylyk** [comment]
Пряв воспроизвести не удалось поставил в Параметрах информационной базы минимальную длину и контроль сложности, сработал возврат пароля, возможно в клиент-сервере проявляется проблема.
