### ISSUE TITLE
Не работает экспорт результата в консоли запросов

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#698]
**Описание ошибки**
В консоли запросов при нажатии на кнопку "Экспорт в " - ничего не происходит
![image](https://user-images.githubusercontent.com/18395787/222368572-64e44366-f260-496f-87ba-49b08420bfda.png)

**Окружение:**

 Infostart Toolkit PROF 2023.2.01

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.2.2
