### ISSUE TITLE
Ошибка "Метод объекта не обнаружен (ЭтоСсылочный)" в форме просмотра таблицы значений

### ISSUE THREAD

**Issue by ChernyakAI** [infostart-hub/toolkit#699]
**Описание ошибки**
При попытке выбора в форме просмотра таблицы значений появляется ошибка отсутствующего метода:
```code
Метод объекта не обнаружен (ЭтоСсылочный)
{InfostartToolkitPROF ОбщийМодуль.ИТК_ФормаКлиент.Модуль(946)}: Если ИТК_Типы.ЭтоСсылочный(ТипЗначения, Истина) Тогда
{InfostartToolkitPROF ОбщаяФорма.ИТК_РедактированиеТаблицыЗначений.Форма(192)}:ИТК_ФормаКлиент.ОбработкаТаблицаЗначенийВыбор(ЭтотОбъект, Элемент, Поле, СтандартнаяОбработка);
```

**Сценарий воспроизведения**
1. Используя любую конфигурацию в консоли разработчика ввести запрос, где выбрать объект вместе с табличной частью.
2. Включить в консоли полную расшифровку таблиц значений
3. Выполнить запрос и перейти к просмотру содержимого табличной части
4. При выборе на любой ячейке получить ошибку.

**Ожидаемое поведение, если бы ошибки не было**
Корректный выбор значения

**Скриншоты**

![image](https://user-images.githubusercontent.com/50447110/224201233-d882ed57-7dc1-4918-9265-ebbe89de29a7.png)

**Окружение:**
```code
 Infostart Toolkit PROF 2023.2.01

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.7.206)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.7.206

Клиент:
Толстый клиент (управляемое приложение)
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Исправлена в 2023.2.2
