### ISSUE TITLE
Ошибка сохранения рабочей области консоли разработчика в файл mcr

### ISSUE THREAD

**Issue by ChernyakAI** [infostart-hub/toolkit#700]
**Описание ошибки**
При сохранении содержимого консоли разработчика в файл .mcr при определённом сценарии возникает ошибка "Значение не является значением объектного типа (ИмяТипа)".

**Сценарий воспроизведения**

Вручную:
1. Добавить в консоль разработчика схему компоновки данных
2. Нарисовать простейший отчёт с выборкой, например, по документам.
3. Добавить в параметрах СКД параметр "Период" с типом "СтандартныйПериод".
4. Добавить в дереве консоли вариант отчета для этой СКД.
5. Нажать "Анализ выполняемых запросов" для созданного варианта отчета. В открывшемся окне нажать "Анализировать запрос", чтобы он появился в дереве консоли.
6. Попытаться сохранить в файл: "Данные" - "Файл" - "Сохранить как...". При сохранении получить ошибку (скриншот).

Из отладки:
1. Перехватить исполнение СКД типового отчета, например, "Ведомость по товарам на складах" в УТ.
2. Получить перехваченную СКД в консоли разработчика и получить дерево со схемой и "вариантом".
3. Сделать анализ запроса для полученного варианта (в дереве появится "Запрос СКД (НаборДанных)")
4. Попытаться сохранить состояние консоли в файл .mcr : "Данные" - "Файл" - "Сохранить как...". При сохранении получить аналогичную ошибку.
При этом, если сначала попытаться выполнить запрос, полученный в п.3, то после этого сохранение в файл .mcr проходит уже успешно. Возможно, это связано с тем, что после выполнения запроса заполняется вкладка с параметрами запроса.

**Ожидаемое поведение, если бы ошибки не было**
Сохранение рабочей области консоли в файл .mcr

**Скриншоты**
![image](https://user-images.githubusercontent.com/50447110/224235872-6b43bd8a-6914-4f9c-8a3b-f10c73446421.png)

**Окружение:**
```code
Infostart Toolkit PROF 2023.2.01

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.318)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Толстый клиент (управляемое приложение)
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.2.2
