### ISSUE TITLE
Консоль запросов: добавить кнопку копирования запроса на встроенном языке

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#704]
**Существует проблема**
Иногда приходится часто переносить запрос из консоли в текст модуля. Переносимый запрос не всегда возможно открыть через конструктор запроса в конфигураторе (например, в расширениях). Данная кнопка позволила бы сократить рутину по выделению готового запроса из  окна "Код на встроенном языке" из консоли запросов и вставки его в модуль.

**Хотелось бы иметь следующую функциональность**
Отдельная кнопка копирования запроса на встроенном языке. 
Возможно, стоит добавить возможность помещение копируемого запроса в область, что бы было удобнее заменять длинные запросы в модуле, путем сворачивания области с запросом.
Например, при нажатии на кнопку, получаем в буфере обмена следующий текст:

```
#Область ТекстЗапроса
Запрос.Текст =
"Выбрать *
|ИЗ
|Таб КАК ТАБ";
#КонецОбласти
```

<img width="847" alt="image" src="https://user-images.githubusercontent.com/65346358/225848594-79c638a7-3af1-48e6-a5ff-d25c156bd34d.png">

**Comment by Evg-lylyk** [comment]
"Выбрать *
|ИЗ
|Таб КАК ТАБ";

Вот так более универсально и не зависит от языка на котором пишешь код

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.3
