### ISSUE TITLE
Не работает консоль консоль разработчика в Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by SeiOkami** [infostart-hub/toolkit#706]
**Описание ошибки**
Не запускается редактор кода\запроса в Ubuntu 22.04.2 LTS

> Метод объекта не обнаружен (init)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(124)}:defaultView.init(СистемнаяИнформация.ВерсияПриложения);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(426)}:ИТК_РедакторКодаКлиент.ДополнительнаяИнициализация(ЭтотОбъект, Элемент, ДополнительныеПараметры);
> 

> Метод объекта не обнаружен (setReadOnly)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(263)}:ДокументHTML(Элемент).setReadOnly(Не ДоступноРедактирование);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6699)}:ИТК_РедакторКодаКлиент.УстановитьДоступностьРедактирования(ЭтотОбъект, ЭлементТекст, ДоступноРедактированиеТекста);
> {InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6638)}:ПодключаемыйЗагрузитьСостояниеРедактораКода();
> 

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль кода
2. Падают две ошибки и редактор зависает на анимации загрузки

**Ожидаемое поведение, если бы ошибки не было**
Должно работать =)

**Скриншоты**
![image](https://user-images.githubusercontent.com/42138875/228230964-b9e814fa-dcfb-4368-8be5-7a83453a29c9.png)
![image](https://user-images.githubusercontent.com/42138875/228230998-0d0a8657-93bb-4228-980d-6d4969d8cf91.png)

**Окружение:**

> Infostart Toolkit PROF 2023.2.02
> 
> Платформа: 8.3.21.1393 (Linux x86-64)
> Режим БД: файловый
> 
> Конфигурация:
> Библиотека стандартных подсистем, редакция 3.1 (3.1.5.110)
> Основной режим запуска: Управляемое приложение
> Режим совместимости: Версия8_3_14
> Версия БСП: 3.1.5.110
> 
> Клиент:
> Тонкий клиент
> ОС: Linux x86-64 (Linux 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2)
> Язык: ru
> Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
На данный момент редактор кода Monaco в Infostart Toolkit не поддерживает работу в Linux, можно в настройках включить стандартный.
Будем работать над этой проблемой

**Comment by Evg-lylyk** [comment]
Проблема решена в 2023.3.1
