### ISSUE TITLE
В консоли запросов (Англ.) нет заголовков закладок

### ISSUE THREAD

**Issue by Murenysh** [infostart-hub/toolkit#709]
**Описание ошибки**
В консоли запросов в конструкторе запроса закладки страниц без заголовков

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Запустить конфигурацию на английском языке.
2. В консоли запросов открыть конструктор запроса
3. Закладки страниц сверху будут без заголовков

**Ожидаемое поведение, если бы ошибки не было**
Закладки с заголовками, нормальной ширины

**Скриншоты**
![2023-03-29_20-11-09](https://user-images.githubusercontent.com/75340417/228617196-9a367cc3-0d21-401c-99ae-5e44cfd44775.png)

**Окружение:**

  Infostart Toolkit CORP 2023.2.02

Platform: 8.3.19.1264 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Language: ru
Launch mode: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

Типовая с изменениями
Режим защиты от опасных действий отключен

**Comment by Evg-lylyk** [comment]
Быстро решить данную проблему не получится, будем работать.
Пока как обход в настройках включить платформенный конструктор запроса

**Comment by Evg-lylyk** [comment]
Посмотрел запуск стандартного конструктора проходит также в любой консоли запросов, видимо особенность английской версии в улучшенном конструкторе я смогу решить этот вопрос

**Comment by Evg-lylyk** [comment]
Проблема решена в 2024.1
