### ISSUE TITLE
Поиск по имени физической таблицы в структуре хранения

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#710]
Хотелось бы иметь функционал поиска по физической таблице СУБД.
Например, при расследовании блокировок через ТЖ мы получаем имя таблицы на которой произошли блокировки- требуется зная имя этой таблицы найти соответствующий объект 1С

**Comment by Evg-lylyk** [comment]
Приветствую, все понятно, это было запланировано но не успел реализовать, сделаю #672

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.3
