### ISSUE TITLE
Не открывается обработка ObjectEditor (Англ.)

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#711]
**Описание ошибки**
что конкретно происходит
При открытии обработки ObjectEditor ошибка

Неизвестное имя модуля: ОбщегоНазначения при вызове метода БСП
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСервер.Module(65)}:		ВызватьИсключение СтрШаблон("Неизвестное имя модуля: %1 при вызове метода БСП", ИмяМодуля);
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСервер.Module(18)}:	ВыполнитьМетод(ПолноеИмя, Параметры, Результат);
{InfostartToolkitCORP CommonModule.ИТК_БСППовтИсп.Module(30)}:	Возврат ИТК_БСПКлиентСервер.ВыполнитьФункцию("ОбщегоНазначения.ПодсистемаСуществует", Параметры);
{InfostartToolkitCORP DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(1451)}:	Если ИТК_БСППовтИсп.СуществуетПодсистема("СтандартныеПодсистемы.Свойства") Тогда
{InfostartToolkitCORP DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(34)}:	ДобавитьСвойствоВРеквизиты();
{InfostartToolkitCORP CommonModule.ИТК_ТуллкитКлиент.Module(33)}:	ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы, , Уникальность, , , , РежимОткрытияОкнаФормы.Независимый);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(225)}:	ИТК_ТуллкитКлиент.ОткрытьИнструмент(Строка.Идентификатор, Строка.Объект);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(218)}:	ОткрытьФормуПоСтроке(Строка);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(56)}:	ВыбраноЗначение(Элемент.ТекущиеДанные, СтандартнаяОбработка);

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть конфигурацию на английском языке
2. Через "Все функции" открыть обработку ObjectEditor

**Ожидаемое поведение, если бы ошибки не было**

**Скриншоты**

**Окружение:**

  Infostart Toolkit CORP 2023.2.02

Platform: 8.3.19.1264 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Language: ru
Launch mode: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

Типовая с изменениями
Режим защиты от опасных действий отключен

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.2.4
