### ISSUE TITLE
Не открывается обработка "Analysis of access rights to an object"

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#712]
**Описание ошибки**
что конкретно происходит
При открытии обработки Analysis of access rights to an object ошибка

`Метод объекта не обнаружен (FunctionExecutionParameters)
{(1)}:Модуль.FunctionExecutionParameters(Параметры[0])
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСервер.Module(79)}:		Результат = Вычислить(Выражение);
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСервер.Module(18)}:	ВыполнитьМетод(ПолноеИмя, Параметры, Результат);
{InfostartToolkitCORP CommonModule.ИТК_ДлительныеОперации.Module(89)}:		Возврат ИТК_БСПКлиентСервер.ВыполнитьФункцию("ДлительныеОперации.ПараметрыВыполненияВФоне", ПараметрыФункции);
{InfostartToolkitCORP Report.ИТК_АнализПравДоступа.Form.ФормаОтчета.Form(476)}:	ПараметрыВыполнения = ИТК_ДлительныеОперации.ПараметрыВыполненияВФоне(УникальныйИдентификатор);
{InfostartToolkitCORP Report.ИТК_АнализПравДоступа.Form.ФормаОтчета.Form(460)}:	ДлительнаяОперация = ОбновитьОтчетНаСервере(ПараметрыОперации, УникальныйИдентификатор);
{InfostartToolkitCORP Report.ИТК_АнализПравДоступа.Form.ФормаОтчета.Form(37)}:		ОбновитьОтчет();
{InfostartToolkitCORP CommonModule.ИТК_ТуллкитКлиент.Module(33)}:	ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы, , Уникальность, , , , РежимОткрытияОкнаФормы.Независимый);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(225)}:	ИТК_ТуллкитКлиент.ОткрытьИнструмент(Строка.Идентификатор, Строка.Объект);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(218)}:	ОткрытьФормуПоСтроке(Строка);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(56)}:	ВыбраноЗначение(Элемент.ТекущиеДанные, СтандартнаяОбработка);`

Также при отладке в конфигураторе есть ошибки:
Ошибка1:
`Поле объекта не обнаружено (Объект)
{InfostartToolkitCORP CommonModule.ИТК_ГлобальноеМенюКлиент.Module(166)}:				Поле = Владелец[ИмяКоллекцииОбъекта][Имя];
{InfostartToolkitCORP CommonModule.ИТК_ГлобальноеМенюКлиент.Module(65)}:				ДобавленоПолеОбъекта = ДобавитьПолеКоллекцииОбъектаСПопыткой(ПоляОбъекта, ОкноКлиентскогоПриложения, ТекущийЭлемент.Имя, "Объект");
{InfostartToolkitCORP CommonModule.ИТК_ГлобальноеМенюКлиент.Module(24)}:	ЗаполнитьПараметры(АктивноеОкно, Параметры);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Command.ГлобальноеМеню.CommandModule(6)}:	ИТК_ГлобальноеМенюКлиент.Открыть(ПараметрыВыполненияКоманды);
`

Ошибка 2:
`Поле объекта не обнаружено (Имя)
{InfostartToolkitCORP CommonModule.ИТК_ГлобальноеМенюКлиент.Module(169)}:				ДругоеИмя = ИТК_Строки.УдалитьПрефикс(Имя, Владелец.Имя);
{InfostartToolkitCORP CommonModule.ИТК_ГлобальноеМенюКлиент.Module(65)}:				ДобавленоПолеОбъекта = ДобавитьПолеКоллекцииОбъектаСПопыткой(ПоляОбъекта, ОкноКлиентскогоПриложения, ТекущийЭлемент.Имя, "Объект");
{InfostartToolkitCORP CommonModule.ИТК_ГлобальноеМенюКлиент.Module(24)}:	ЗаполнитьПараметры(АктивноеОкно, Параметры);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Command.ГлобальноеМеню.CommandModule(6)}:	ИТК_ГлобальноеМенюКлиент.Открыть(ПараметрыВыполненияКоманды);`

В коде расширения есть и другие обращения к реквизиту формы "Объект" вместо "Object", скорее всего там тоже будут ошибки.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть конфигурацию на английском языке
2. Из формы документа нажать Alt-T и выбрать "Analysis of access rights to an object"

**Ожидаемое поведение, если бы ошибки не было**

**Скриншоты**

**Окружение:**

  Infostart Toolkit CORP 2023.2.02

Platform: 8.3.19.1264 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Language: ru
Launch mode: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

Типовая с изменениями
Режим защиты от опасных действий отключен

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.2.4
