### ISSUE TITLE
Ошибка в функции (Англ.)

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#714]
**Описание ошибки**
что конкретно происходит
При вызове функции ИТК_БСП.ЗапрешенныеКРедактированиюРеквизитыОбъекта  ошибка

`Метод объекта не обнаружен (ЗапретРедактированияПредусмотрен)
{InfostartToolkitCORP CommonModule.ИТК_БСП.Module(21)}:		Если Модуль.ЗапретРедактированияПредусмотрен(ИмяОбъекта) Тогда
{InfostartToolkitCORP CommonModule.ИТК_РаботаСОбъектом.Module(184)}:	ЗаблокированныеРеквизиты = ИТК_БСП.ЗапрешенныеКРедактированиюРеквизитыОбъекта(ОбъектМетаданных.ПолноеИмя());
{InfostartToolkitCORP DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(702)}:		ДанныеОбъекта = ИТК_РаботаСОбъектом.ПрочитатьСтруктуруИДанные(ИзменяемыйОбъект, ДополнительныеПараметры);
{InfostartToolkitCORP DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(1293)}:	ЗаполнениеДанныхПоОбъекту(ОбрабатываемыйОбъект, , ДобавитьВИсториюВыбранных);
{InfostartToolkitCORP DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(1578)}:	ОбновитьДанныеОбъекта(ДобавитьВИсториюВыбранных);
{InfostartToolkitCORP DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(74)}:	ОбрабатываемыйОбъектИзменен(ОбрабатываемыйОбъект);
{InfostartToolkitCORP CommonModule.ИТК_ТуллкитКлиент.Module(33)}:	ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы, , Уникальность, , , , РежимОткрытияОкнаФормы.Независимый);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(225)}:	ИТК_ТуллкитКлиент.ОткрытьИнструмент(Строка.Идентификатор, Строка.Объект);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(218)}:	ОткрытьФормуПоСтроке(Строка);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(56)}:	ВыбраноЗначение(Элемент.ТекущиеДанные, СтандартнаяОбработка);
`

Для английского варианта Toolkit большая часть функционала не работает. Пока прекращаю постить сообщения об ошибках.

**Сценарий воспроизведения**
**Ожидаемое поведение, если бы ошибки не было**
**Скриншоты**
**Окружение:**

  Infostart Toolkit CORP 2023.2.02

Platform: 8.3.19.1264 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Language: ru
Launch mode: Управляемое приложение
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

Типовая с изменениями
Режим защиты от опасных действий отключен

**Comment by Evg-lylyk** [comment]
Очень много ошибок все постараюсь исправить уже в следующей версии 2023.3. Проработать и протестировать

**Comment by Serg2000Mr** [comment]
Да, спасибо )
Ожидаем...
