### ISSUE TITLE
Просмотр имени значения перечисления

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#715]
**Существует проблема**
В некоторых формах используется определение списка выбора для поля, хранящего значение типа перечисления, и при этом представление значения в списке выбора бывает сильно отличается от синонима, заданного в конфигураторе. Примером может служить поле "Способ доставки" заказа клиента в конфигурациях семейства ERP. Если разработчик хочет понять, что же за значение в этом поле хранится, ему приходится проделывать длинную цепочку действий:
* поменять значение, сохранить объект;
* открыть объект в редакторе объекта, найти нужное поле, скопировать представление;
* по представлению найти в конфигурации само значение перечисления, получив наконец его имя.

**Хотелось бы иметь следующую функциональность**
Нужна возможность узнать имя значения перечисления в некотором поле формы. В самом простом случае это может быть настройка представления для редактора объекта ("отображать перечисления в терминах конфигуратора") или же возможность в редакторе объекта "открыть" значения перечисления и увидеть его имя. Либо это можно реализовать в рамках реализации менеджера форм #686.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.2.00

**Comment by Evg-lylyk** [comment]
Может инструмент Метаданные открывается сразу на активном значении?

**Comment by d-hurricane** [comment]
Из формы документа инструмент "Метаданные" открывает описание самого документа.

**Comment by Evg-lylyk** [comment]
Инструмент может учитывать значение в ячейке ТЧ, аналогично редактору

**Comment by d-hurricane** [comment]
Если речь про глобальное меню, то картинка следующая:
![image](https://user-images.githubusercontent.com/59051827/229135918-59521649-9baa-4fd6-a66c-d7f11a81d304.png)

Редактор объекта "Самовывоз" упал с ошибкой. Открытие значения показало лишь синоним. Метаданные открывают метаданные самого перечисления, без позиционирования на нужном значении. Хотя в целом можно сказать, что сработало: в глобальном меню посмотрел синоним, в метаданных - имя, соответствующее синониму.
