### ISSUE TITLE
Генерация кода

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#716]
**Существует проблема**
Для списков значений зачастую приходится писать однотипный код.

Например есть:
ДокТип1
ДокТип2
...
ДокТипN

Нужно получить:
Процедура ОбработатьДокТип1()
      ДокОбъект = Документы.ДокТип1.СоздатьДокумент();
КонецПроцедуры
и т.д.

**Хотелось бы иметь следующую функциональность**
В консоли кода или отдельной обработкой добавить генератор однотипного кода по шаблону для списка строк

**Дополнительный контекст**

**Comment by Serg2000Mr** [comment]
![image](https://user-images.githubusercontent.com/129394542/229323524-1a72a503-35f0-43bf-b502-1b92ca836f29.png)

**Comment by d-hurricane** [comment]
Понятно, что хочется использовать один инструмент на все случаи жизни. Но мне кажется, здесь проще сторонними средствами обойтись. Мне регулярно приходится выполнять аналогичную задачу. Делаю ее с помощью Notepad++: запускаю поиск и замену, переключаю поиск на использование регулярных выражений и вуаля:
![image](https://user-images.githubusercontent.com/59051827/229447958-b8843681-eec1-46b7-85cb-eed5feee37cc.png)
![image](https://user-images.githubusercontent.com/59051827/229448092-65b2c4d1-1fb4-48af-9915-d8decd6b8550.png)

**Comment by Serg2000Mr** [comment]
> Понятно, что хочется использовать один инструмент на все случаи жизни. Но мне кажется, здесь проще сторонними средствами обойтись. Мне регулярно приходится выполнять аналогичную задачу. Делаю ее с помощью Notepad++: запускаю поиск и замену, переключаю поиск на использование регулярных выражений 

Мне на эту тему нравится мем:  Junior - ищет в интернете "синтаксис регулярных выражений". Спустя годы Senior - с таким же запросом )

Если их использовать нечасто, то вспомнить их - та еще задача.

Одна из моих любимых обработок собственного изготовления - вывод версии БСП. Состоит из пары строчек, и использую ее раз в полгода. Но каждый раз страшно доволен, что она у меня есть и сколько она мне экономит времени и головного кэша.
