### ISSUE TITLE
Конструктор запроса для СКД - ошибка при редактировании Характеристик

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#717]
**Сценарий воспроизведения**
1. Открываем конструктор СКД.
2. Создаем новый набор данных  - Запрос
3. Открываем конструктор запросов.
4. На закладке "Характеристики" при попытке указать "тип" - ошибка

![image](https://user-images.githubusercontent.com/18395787/229370073-e2201cdc-3d7a-40c5-9a26-599c0822c153.png)

![image](https://user-images.githubusercontent.com/18395787/229370079-d697042f-606b-4fdf-902f-87135889026c.png)

**Окружение:**

 Infostart Toolkit PROF 2023.2.03

Платформа: 8.3.16.1148 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлена с 2023.3
