### ISSUE TITLE
Ошибка во вложенном запросе (не добавляет текст и (или) не закрывает пустую форму)

### ISSUE THREAD

**Issue by nagaitseff** [infostart-hub/toolkit#718]
При создании вложенного запроса, если выбрать команду "Запрос" чтобы добавить текст запроса, вставить и попытаться сохранить или удалить запрос и попытаться отменить, выходит ошибка "Поле объекта не обнаружено (Query)"

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'Запрос'
2. Нажать 'Создать вложенный запрос'
    Нажать кнопку в левом нижнем углу "Запрос"
    Вставить скопированный запрос
3. Попытаться нажать ок или отмена (или удалить запрос и нажать отмена)
4. Появляется ошибка  "Поле объекта не обнаружено (Query)", окно при этом невозможно закрыть.

**Ожидаемое поведение, если бы ошибки не было**
Добавляется запрос или закрывается окно, если добавлять или сохранять не нужно

**Скриншоты**
![image](https://user-images.githubusercontent.com/32049603/230283000-5d8edf87-5186-42cd-90ea-e2cbf58b6800.png)

**Окружение:**
Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.383)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.6.437

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
Язык: ru
Режим запуска: Управляемое приложение

<!-- **Дополнительный контекст**

- Типовая конфигурация с доработками
- Включен ли режим защиты от опасных действий - нет

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести, какая у вас версия Туллкит?
Пришлите больше подробностей об ошибке например номер строки, это поможет разобраться

**Comment by nagaitseff** [comment]
Версия 2023.2.03. Сегодня не удалось воспроизвести с тем же запросом. Данная ошибка встречалась несколько раз. Попробую поймать и сразу напишу. Спасибо.

**Comment by Evg-lylyk** [comment]
Закрываю вопрос, будет информация, пиши
