### ISSUE TITLE
Активация окна "Все функции", если оно уже было открыто ранее.

### ISSUE THREAD

**Issue by ChernyakAI** [infostart-hub/toolkit#721]
**Существует проблема**

Ситуация:
1. Вызвал окно "Все функции" (Ctrl+A)
2. Отвлёкся и переключился на другое окно, например, консоль запросов и некоторое время работаю в нём. При этом "Все функции" продолжают висеть на заднем фоне.
3. Через некоторое время потребовалось опять вызвать "Все функции", но ничего не происходит, т.к. оно уже было открыто и висит где-то среди других открытых окон. Т.к. уже забыл что "Все функции" уже открыл ранее, то "подвисаешь" на некоторое время не понимая что происходит.

**Хотелось бы иметь следующую функциональность**

Активация окна "Все функции", если оно уже было открыто ранее.
Если это, конечно, возможно. Из списка окно в предприятии к уже открытым "Все функции" перейти не даёт, можно перейти только к заблокированному окну.

**Способ обхода**

Сообразить где находится потерянное окно можно, если заметить заблокированное окно на панели открытых.
![image](https://user-images.githubusercontent.com/50447110/232657974-4d42157f-9b79-4806-84bf-c675ce35e43a.png)

**Дополнительный контекст**
```
Infostart Toolkit PROF 2023.2.03

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.318)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Не знаю как это сделать Активизировать и другие изощерения не помогают
Это окно не закрывается при закрытии - оно скрывается (аналогично работает типовое). Если закрывать его то все нормально, но так не хотелось бы, то как сейчас удобно.
Когда открыто какое то окно и в нем жмут Alt + A оно как бы привязывается к открытому и при переходе к другому окну Alt+A уже его не отображает.

**Comment by Evg-lylyk** [comment]
Исправил в 2023.4, сделал как аналогичное типовое, окно блокирует весь интерфейс
