### ISSUE TITLE
Консоль запросов: метод объекта не обнаружен (FindByID)

### ISSUE THREAD

**Issue by ChernyakAI** [infostart-hub/toolkit#722]
**Описание ошибки**
Ошибка при группировке в запросе.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. В консоли запросов выбрать любую таблицу, из неё пару любых полей.
2. Перейти в консоли на вкладку "Группировка". Далее начать перетаскивать мышкой из таблицы "Поля" в таблицу "Поля группировки".
3. При втором перетаскиваемом поле получить ошибку
```
Метод объекта не обнаружен (FindByID)
{InfostartToolkitPROF Обработка.ИТК_QueryWizard...;
```
 Перенос с помощью drag-and-drop в "суммируемые поля" проходит без ошибок.

**Способ обхода**
Перенос двойным кликом мышки на поле или нажатием кнопки ">" на панели.

**Ожидаемое поведение, если бы ошибки не было**
Отсутствие исключения.

**Скриншоты**
![image](https://user-images.githubusercontent.com/50447110/232669778-214bcd33-45dd-4ed7-a7e5-f65935983791.png)

**Окружение:**
```
Infostart Toolkit PROF 2023.2.03

Платформа: 8.3.21.1644 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.8.318)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.473

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
```

**Comment by Evg-lylyk** [comment]
Исправил в 2023.4
Такая же ошибка в платформенном конструкторе тонкого клиента она появилась с 16 платформы
