### ISSUE TITLE
Не правильно работает выполнение отдельного пакета запроса

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#724]
Выводятся данные не того запроса
(внимание на название колонок и сам запрос)
<img width="697" alt="image" src="https://user-images.githubusercontent.com/65346358/235064760-397417ab-cf68-44f4-a1d7-52c3ee46815a.png">

Infostart Toolkit PROF 2023.3.02

Платформа: 8.3.21.1624 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.25.36)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.343

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
У меня не получается воспроизвести

**Comment by mrChOP93** [comment]
Завтра надо не забыть подключиться ко мне и проверить

**Comment by Evg-lylyk** [comment]
Простой пример воспроизведения
`ВЫБРАТЬ
	_ДемоБанковскиеСчета.Ссылка КАК Ссылка
ПОМЕСТИТЬ ВременнаяТаблица
ИЗ
	Справочник._ДемоБанковскиеСчета КАК _ДемоБанковскиеСчета
;

////////////////////////////////////////////////////////////////////////////////
ВЫБРАТЬ
	ВременнаяТаблица.Ссылка КАК Ссылка,
	1 КАК Поле1
ПОМЕСТИТЬ ВременнаяТаблица1
ИЗ
	ВременнаяТаблица КАК ВременнаяТаблица`
![Screenshot_1](https://user-images.githubusercontent.com/48444742/236472320-66375e84-ee13-4f0c-9d26-b346a6af2d7f.png)
