### ISSUE TITLE
Не убиваемые параметры в консоле запросов

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#729]
**Существует проблема**
Иногда надо временно закомментировать строчку запроса с условием, где есть параметр, после чего этот параметр исчезает в консоли. После возвращения строчки в запросе, параметр появляется снова, но его приходится заполнять по новой

**Хотелось бы иметь следующую функциональность**
Возможность указать у параметра, что он должен присутствовать всегда, даже, когда он не используется в запросе.

**Comment by Evg-lylyk** [comment]
В консоли запросов туллкит автоматическое получение параметров. Значение ранее установленного параметра хранится и его не видно в случае восстановлении параметра в тексте его значение восстанавливается. В случае сохранения в файл или закрытия такие значения удаляются. Не вижу смысла их хранить
