### ISSUE TITLE
Консоль запросов. Ошибка в захваченном запросе

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#731]
**Описание ошибки**
В консоли запросов при проверке захваченного запроса ошибка:
(69, 41) Поле не найдено "ВременнаяТаблицаТовары.Упаковка.ТипИзмеряемойВеличины"
КОГДА ВременнаяТаблицаТовары.Упаковка.<<?>>ТипИзмеряемойВеличины = ЗНАЧЕНИЕ(Перечисление.ТипыИзмеряемыхВеличин.Вес)

**Сценарий воспроизведения**
Шаги по воспроизведению:
В ERP 2.4 при отладке захваченного запроса из общего модуля УстановкаЦенСервер.ЗагрузитьСтарыеЦеныНоменклатурыПредприятия
через ИТК.Отл(Запрос)
Далее - Консоль запросов - Данные - Запрос (из отладки)

Запрос успешно выполняется, но перед открытием конструктора запроса появляется окно с той же ошибкой и сообщением, что текст запроса будет потерян.

**Ожидаемое поведение, если бы ошибки не было**
Открытие конструктора запроса

**Скриншоты**
![image](https://user-images.githubusercontent.com/129394542/236972614-80619139-033b-4adf-8575-fd89fc0a5386.png)
![image](https://user-images.githubusercontent.com/129394542/236972684-bda783e2-c58a-4937-9f65-25a3b923c5cf.png)
[ТекстЗапросаОшибка.txt](https://github.com/infostart-hub/toolkit/files/11426415/default.txt)

**Окружение:**

   Infostart Toolkit CORP 2023.2.03

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Serg2000Mr** [comment]
Добрый день.
Если в новом запросе в конструкторе вручную создать временную таблицу, то до закрытия он "помнит" типы полей временной таблицы и у него нет сложностей со взаимодействием с полями.
Так что мне кажется, что возможность улучшения есть.

**Comment by Evg-lylyk** [comment]
> Добрый день. Если в новом запросе в конструкторе вручную создать временную таблицу, то до закрытия он "помнит" типы полей временной таблицы и у него нет сложностей со взаимодействием с полями. Так что мне кажется, что возможность улучшения есть.

Всегда можно что то сделать, но здесь борьба с платформой
В момент создания таблицы вы прописывается типы, после выхода подобный запрос не изменить конструктором. Если в запросе содержится ошибка по мнению объекта СхемаЗапроса его нельзя изменить конструктором.

**Comment by Serg2000Mr** [comment]
Да, согласен. При выходе конструктор выдает предупреждение.
Осталась невозможность открытия таблицы параметра из захваченного запроса.
![image](https://github.com/infostart-hub/toolkit/assets/129394542/4a119bdc-a351-4afb-902a-ed9e96d68a07)
Двойной клик не открывает таблицу, пока не исправлен текст запроса.

**Comment by Evg-lylyk** [comment]
Понятно постараюсь учесть

**Comment by Evg-lylyk** [comment]
В версии 2023.5 сделал чтобы можно было редактировать параметры
