### ISSUE TITLE
Не работает подсказка для таблиц без псевдонима

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#732]
**Описание ошибки**
Не работает контекстная подсказка по полям таблицы и по некоторым ключевым словам запроса, если для таблицы не задан псевдоним.

**Сценарий воспроизведения**
Открыть консоль запросов на конфигурации, где есть справочник номенклатуры. Ввести следующий запрос:
```
ВЫБРАТЬ
	Наименование
ИЗ
	Справочник.Номенклатура
```
Начать вводить ключевое слово `ГДЕ` с новой строки. Убедиться, что в процессе ввода контекстная подсказка не отображается.

**Ожидаемое поведение, если бы ошибки не было**
Контекстная подсказка по ключевым полям не должна зависеть от наличия псевдонима у таблицы.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/8c2048d9-c0e3-46ec-af6c-b451d80fed2b)

**Окружение:**
Infostart Toolkit PROF 2023.3.02

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2
