### ISSUE TITLE
Удаление символов из запроса, при переносе его из модуля

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#733]
**Существует проблема**
При переносе запроса из модуля программы в консоль запросов, приходится в ручную удалять символы переноса строки "|" и двойные кавычки
**Хотелось бы иметь следующую функциональность**
При наличии символа переноса строки, автоматически удалять лишние символы

**Comment by Evg-lylyk** [comment]
![image](https://github.com/infostart-hub/toolkit/assets/48444742/1dad77d5-f8e9-4440-bf3e-3d150d12dd16)
