### ISSUE TITLE
Неверно работает отмена выбора прав в отчете по правам доступа

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#734]
**Описание ошибки**
В диалоге выбора ролей, если нажать "Отмена", будут установлены флажки, что ранее были сброшены.

**Сценарий воспроизведения**
Открыть отчет "Анализ прав доступа". Нажать на гиперссылку открытия диалога выбора прав. Убедиться, что флажки с прав на историю сброшены. Нажать кнопку "Отмена". Убедиться, что флажки на историю установились.

**Ожидаемое поведение, если бы ошибки не было**
Кнопка "Отмена" не должна приводить к изменению состава выбранных прав доступа.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/c05a16cb-73c4-4758-a400-0ad4f0ea031c)
![image](https://github.com/infostart-hub/toolkit/assets/59051827/a41cd792-e01a-4578-ae67-8a46ed4efcd2)

**Окружение:**
Infostart Toolkit PROF 2023.3.02

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.3.3
