### ISSUE TITLE
Неверно работает повторный отбор ролей в отчета по правам

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#735]
**Описание ошибки**
При повторном открытии диалога выбора роле в отчете по правам доступа флажки оказываются установлены на всех ролях, а не только лишь на ранее выбранных.

**Сценарий воспроизведения**
1. Открыть отчет "Анализ прав доступа". Нажать гиперссылку для выбора ролей. Выбрать любую роль, например, "ПолныеПрава", с остальных ролей снять флажки. Нажать "Ок". Убедиться, что гиперссылка "Роли" правильно отображает настроенный только что фильтр по ролям.
2. Вновь нажать на гиперссылку выбора ролей. Убедиться, что флажки в диалоге установлены напротив всех ролей, а не только напротив роли "ПолныеПрава".

**Ожидаемое поведение, если бы ошибки не было**
При повторном открытии диалога выбора ролей флажки должны быть установлены лишь напротив тех ролей, чтоб были выбраны ранее.

**Окружение:**
Infostart Toolkit PROF 2023.3.02

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.11.79/3.2.37.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.306

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.3.3
