### ISSUE TITLE
Подсказка в конструкторе строки отладки для динамического списка

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#744]
**Существует проблема**
Иногда в процессе отладки работы сложных динамических список возникает потребность получить и отладить в консоли исполняемый текст запроса динамического списка. Для упрощения перехвата исполняемого запроса уже есть задача #695 . Срок ее реализации неизвестен, а потребность в отладке сохраняется.

**Хотелось бы иметь следующую функциональность**
В качестве временного решения предлагаю дополнить подсказку конструктора строки отладки для СКД.

Сейчас уже предустановлены поля **Схема** и **Настройки** значениями `СхемаКомпоновкиДанных` и `НастройкиКомпоновкиДанных `соответственно. В выпадающем списке значений те же варианты:
![image](https://github.com/infostart-hub/toolkit/assets/59051827/9ff4c197-0bfc-4d32-bac6-704f47eb71d0)

Хочу добавить в выпадающие списки дополнительные значения:
* для поля **Схема** значение `Элементы.Список.ПолучитьИсполняемуюСхемуКомпоновкиДанных()`
* для поля **Настройки** значение `Элементы.Список.ПолучитьИсполняемуюСхемуКомпоновкиДанных()`

Еще лучше будет, если в выпадающем списке буду сохраняться введенные мной значения сразу или по нажатию на кнопку "Копировать и закрыть".

**Дополнительный контекст**
Infostart Toolkit PROF 2023.3.02

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.4, сохранение введенных значений не стал, мне кажется не особо полезно
