### ISSUE TITLE
Редактор объектов - ошибка при перетягивании табличных частей

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#745]
**Описание ошибки**
В редакторе объектов в табличных частях при перетягивании табличной части в списке происходит сбой соответствия табличных частей и содержимого

**Сценарий воспроизведения**
В документе с множеством табличных частей перетянуть первую табличную часть на последнюю. Теперь, выделяя табличные части, можно наблюдать несоответствие.

**Ожидаемое поведение, если бы ошибки не было**

**Скриншоты**
![РедакторОбъектовОшибка](https://github.com/infostart-hub/toolkit/assets/129394542/95966922-4144-4f82-9cac-5cf15274fb08)

**Окружение:**

  Infostart Toolkit CORP 2023.2.03

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: ru_RU
Режим запуска: Управляемое приложение

<!-- **Дополнительный контекст**

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.4
