### ISSUE TITLE
Пожелания по улучшению эргономики консоли разработчика

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#749]
**Существует проблема**
Не интуитивно понятный интерфейс

Консолью запросов пользуюсь только иногда из-за интерфейса с высокой когнитивной сложностью и неочевидностью.
Разбор сложного запроса в дерево - топ в топе.

Хочу попасть в настройки.
![image](https://github.com/infostart-hub/toolkit/assets/129394542/5dbf4a9b-6ac7-4d00-8214-157728e83035)
Не то. Ищу дальше
![image](https://github.com/infostart-hub/toolkit/assets/129394542/83679e9d-9049-4834-ad77-02fc6dd29d3b)
Тут нет.
![image](https://github.com/infostart-hub/toolkit/assets/129394542/ea6525ad-a732-4343-907a-52160d3de6e6)
Что выбрать?

Перегружена редко используемой информацией
![image](https://github.com/infostart-hub/toolkit/assets/129394542/87e845dc-5d0e-49e5-a7ad-f5926bd4e152)

Кто-то программирует с настольным монитором, а кто-то на ноутбуке 15" с масштабом 125%. Нужна возможность переключаться на компактный режим.
Нужна возможность увеличить окно текста запроса. Перемещать для этого ползунки неудобно. Желательно одной
кнопкой и чтобы ее не нужно было искать среди других. Например так:
![image](https://github.com/infostart-hub/toolkit/assets/129394542/9b1ce7b5-ff67-4028-848b-13e8002f1905)

Меню Данные слева наверху - в консоли везде данные, стандартное для этого положения название Файл было бы более понятным.

![image](https://github.com/infostart-hub/toolkit/assets/129394542/16bfb775-68db-4c5c-b49a-66200df6e8be)
От такого набора символов происходит когнитивная перегрузка. Похоже на ошибку <Объект не найден>

Два ряда кнопок, смещенные друг относительно друга...
![image](https://github.com/infostart-hub/toolkit/assets/129394542/fe6a45ac-0da5-48dc-b6ba-30cd28121845)

![image](https://github.com/infostart-hub/toolkit/assets/129394542/cc70fa97-a0eb-48de-affd-078bd836239e)

При редактировании наименования запроса редактирование не в дереве запросов, а переключается в другую закладку,
из которой потом возвращаться приходится. Теряется контекст и это неожиданно.
![image](https://github.com/infostart-hub/toolkit/assets/129394542/f96ce225-2829-4966-9efb-423f9e70006d)

**Comment by Serg2000Mr** [comment]
Ну и еще, что кнопка Конструктор находится каждый раз на разном расстоянии от текста запроса и приходится выискивать ее глазами среди других кнопок.
В одной базе здесь
![image](https://github.com/infostart-hub/toolkit/assets/129394542/739ac881-6310-4ed3-91bb-147b7db7e0df)
А в другой она уже смещена
![image](https://github.com/infostart-hub/toolkit/assets/129394542/877c98d3-d203-4aed-9ef4-138001968173)

**Comment by Evg-lylyk** [comment]
> **Существует проблема** Не интуитивно понятный интерфейс
> 
> Консолью запросов пользуюсь только иногда из-за интерфейса с высокой когнитивной сложностью и неочевидностью. Разбор сложного запроса в дерево - топ в топе.
> 

Нужно лучше разобраться.  Подскажите подобные инструменты на которые нужно ориентироваться где и что в плане интерфейса сделано лучше в целом :)

> Хочу попасть в настройки. ![image](https://user-images.githubusercontent.com/129394542/242407694-5dbf4a9b-6ac7-4d00-8214-157728e83035.png) Не то. Ищу дальше ![image](https://user-images.githubusercontent.com/129394542/242408018-83679e9d-9049-4834-ad77-02fc6dd29d3b.png) Тут нет. ![image](https://user-images.githubusercontent.com/129394542/242407311-ea6525ad-a732-4343-907a-52160d3de6e6.png) Что выбрать?

Данные - это подменю работы с данными
Инструменты - содержит инструменты
Еще - Тут надо искать - Настройки с шестеренкой
На мой взгляд очевидно

> 
> Перегружена редко используемой информацией ![image](https://user-images.githubusercontent.com/129394542/242411001-87e845dc-5d0e-49e5-a7ad-f5926bd4e152.png)
> 

"Поле текста расширить" видимо нужна кнопка запрос в отдельном окне
"Оранжевые полоски" - так устроен Монако большой проблемы не вижу
"Сочетание цветов выглядит грубо" в консоли 1С вроде такая же расцветка, предложи
"Хочется избавится от примечаний" не согласен очень маленький треугольник
"Картинки в шапке" не согласен не мешает


> Кто-то программирует с настольным монитором, а кто-то на ноутбуке 15" с масштабом 125%. Нужна возможность переключаться на компактный режим. Нужна возможность увеличить окно текста запроса. Перемещать для этого ползунки неудобно. Желательно одной кнопкой и чтобы ее не нужно было искать среди других. Например так: ![image](https://user-images.githubusercontent.com/129394542/242416078-9b1ce7b5-ff67-4028-848b-13e8002f1905.png)
> 

Компактный режим подумаю, но пока не планируется
Редактирование запроса в отдельном окне, можешь написать задачу

> Меню Данные слева наверху - в консоли везде данные, стандартное для этого положения название Файл было бы более понятным.
> 

Это меню работает с данными, можно сохранять в настройки, в файл... поэтому так

> ![image](https://user-images.githubusercontent.com/129394542/242412891-16bfb775-68db-4c5c-b49a-66200df6e8be.png) От такого набора символов происходит когнитивная перегрузка. Похоже на ошибку <Объект не найден>
> 

Предложи как лучше?

> Два ряда кнопок, смещенные друг относительно друга... ![image](https://user-images.githubusercontent.com/129394542/242413836-fe6a45ac-0da5-48dc-b6ba-30cd28121845.png)
> 
> ![image](https://user-images.githubusercontent.com/129394542/242415128-cc70fa97-a0eb-48de-affd-078bd836239e.png)
> 

Не понимаю, проблему, поясни, предложи

> При редактировании наименования запроса редактирование не в дереве запросов, а переключается в другую закладку, из которой потом возвращаться приходится. Теряется контекст и это неожиданно. ![image](https://user-images.githubusercontent.com/129394542/242415431-f96ce225-2829-4966-9efb-423f9e70006d.png)

Да согласен, сейчас делаю новую консоль кода... там редактирование в дереве

Много текста в одной задаче, как что то принимать к работе, если хочешь можно пообщаться. Может станет более понятнее https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
> Ну и еще, что кнопка Конструктор находится каждый раз на разном расстоянии от текста запроса и приходится выискивать ее глазами среди других кнопок. В одной базе здесь ![image](https://user-images.githubusercontent.com/129394542/242422745-739ac881-6310-4ed3-91bb-147b7db7e0df.png) А в другой она уже смещена ![image](https://user-images.githubusercontent.com/129394542/242422859-877c98d3-d203-4aed-9ef4-138001968173.png)

Размер кнопок отличается на разных языках соответственно, кнопки в разных местах. Это проблема будет касаться любой формы 1С

**Comment by Evg-lylyk** [comment]
> отличаются шрифты

это иконка - картинка

**Comment by Evg-lylyk** [comment]
Какую консоль с понятным интерфейсом используешь?

**Comment by Evg-lylyk** [comment]
Закрою, здесь продолжив в телеграм
