### ISSUE TITLE
В анализе прав доступа в списке метаданных нет общих команд

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#750]
**Описание ошибки**
При установке отбора по метаданным открывается окно Отбор метаданных. В нем нет пункта Общие команды

**Сценарий воспроизведения**
Alt-T
Анализ прав доступа
Нажать гиперссылку Все в группе Отбор напротив Метаданные:

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/1faf5656-d920-4788-a5fc-1ad851317cd2)

**Окружение:**
Infostart Toolkit CORP 2023.3.03

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19044))
Язык: ru_RU
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Реализовано в 2023.4.1
