### ISSUE TITLE
Ошибка при открытии обработки Scheduled and background jobs

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#757]
**Описание ошибки**
При открытии обработки Scheduled and background jobs появляется сообщение об ошибке

**Неизвестное имя функции РаботаСВнешнимиРесурсамиЗаблокирована для английской БСП**

`Неизвестное имя функции РаботаСВнешнимиРесурсамиЗаблокирована для английской БСП
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСерверПовтИсп.Module(192)}:		ВызватьИсключение СтрШаблон("Неизвестное имя функции %1 для английской БСП", Имя);
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСерверПовтИсп.Module(55)}:		Результат = ИмяМетодаНаАнглийском(Имя);
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСервер.Module(77)}:	ИмяФункции = ИТК_БСПКлиентСерверПовтИсп.ИмяФункцииМодуля(ЧастиИмени[1]);
{InfostartToolkitCORP CommonModule.ИТК_БСПКлиентСервер.Module(12)}:	ВыполнитьМетод(ПолноеИмя, Параметры, Результат);
{InfostartToolkitCORP CommonModule.ИТК_БСП.Module(154)}:	Возврат ИТК_БСПКлиентСервер.ВыполнитьФункцию(ИмяМодуля + ".РаботаСВнешнимиРесурсамиЗаблокирована");
{InfostartToolkitCORP DataProcessor.ИТК_РегламентныеИФоновыеЗадания.Form.Форма.Form(35)}:	Элементы.ГруппаБлокировкаРаботыСВнешнимиРесурсами.Видимость = ИТК_БСП.РаботаСВнешнимиРесурсамиЗаблокирована();
{InfostartToolkitCORP CommonModule.ИТК_ТуллкитКлиент.Module(39)}:	ОткрытьФорму(ПолноеИмяФормы, ПараметрыФормы, Владелец, Уникальность, , , , РежимОткрытия);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(226)}:	ИТК_ТуллкитКлиент.ОткрытьИнструмент(Строка.Идентификатор, Строка.Объект);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(219)}:	ОткрытьФормуПоСтроке(Строка);
{InfostartToolkitCORP DataProcessor.ИТК_ГлобальноеМеню.Form.Форма.Form(56)}:	ВыбраноЗначение(Элемент.ТекущиеДанные, СтандартнаяОбработка);
`

**Сценарий воспроизведения**
Alt-T - выбрать Scheduled and background jobs

**Окружение:**

Infostart Toolkit CORP 2023.3.03

Platform: 8.3.19.1264 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Language: ru
Launch mode: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.3.4
