### ISSUE TITLE
Ошибка в новой консоли кода при закрытом дереве данных

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#762]
**Описание ошибки**
В случае, если дерево данных скрыто, при вводе кода в консоль возникает ошибка с текстом:

> Получение элемента по индексу для значения не определено
> {InfostartToolkitPROF ОбщийМодуль.ИТК_КонсолиКлиент.Модуль(328)}:Если Данные[Имя] = Значение Тогда
> {InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(626)}:ИТК_КонсолиКлиент.РаботаСДаннымиИзменитьПоле(ЭтотОбъект, Элементы.ДеревоДанных.ТекущиеДанные, "Текст", НовыйКод);
> {InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(547)}:ИзмененКодВТекущейСтроке(НовыйКод);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(712)}:ВыполнитьОбработкуОповещения(ОповещениеМодификации);
> {InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(143)}:ИТК_РедакторКодаКлиент.ОбработкаСобытий(ЭтотОбъект, Элемент, ДанныеСобытия, СтандартнаяОбработка, ОписаниеОповещения);

**Сценарий воспроизведения**
1. Открыть новую консоль кода.
2. Сразу же скрыть дерево данных соответствующей кнопкой на основной панели команд.
3. Начать вводит код в основное поле ввода консоли

**Ожидаемое поведение, если бы ошибки не было**
Программной ошибки быть не должно.

**Окружение:**
Infostart Toolkit PROF 2023.4.00

Платформа: 8.3.21.1624 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:Комплексная автоматизация 2 (2.5.11.79/3.2.37.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.306

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спс, исправлено в 2023.4.1
