### ISSUE TITLE
Лишние пункты меню

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#763]
**Описание ошибки**
При нажатии Alt-T в меню ненужные пункты

**Сценарий воспроизведения**
Форма документа "Реализация товаров и услуг" - Alt-T
При клике на элементе-дубле ошибка

`Метод объекта не обнаружен (УникальныйИдентификатор)
{InfostartToolkitCORP ОбщийМодуль.ИТК_ТуллкитКлиент.Модуль(83)}:		Уникальность = Параметр.УникальныйИдентификатор();
{InfostartToolkitCORP ОбщийМодуль.ИТК_ТуллкитКлиент.Модуль(31)}:	ЗаполнитьПараметрыЗапускаИнструмента(Инструмент, ПолноеИмяФормы, ПараметрыФормы, Параметр, Уникальность);
{InfostartToolkitCORP Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(225)}:	ИТК_ТуллкитКлиент.ОткрытьИнструмент(Строка.Идентификатор, Строка.Объект);
{InfostartToolkitCORP Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(218)}:	ОткрытьФормуПоСтроке(Строка);
{InfostartToolkitCORP Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(56)}:	ВыбраноЗначение(Элемент.ТекущиеДанные, СтандартнаяОбработка);
`

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/663ce7ad-870e-4b68-8d50-0e5bd857082a)

**Окружение:**

Infostart Toolkit CORP 2023.3.03

Платформа: 8.3.19.1264 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.3.5
