### ISSUE TITLE
Ошибка в инструменте "Поиск ссылок на объект"

### ISSUE THREAD

**Issue by sagittarius-s** [infostart-hub/toolkit#764]
**Описание ошибки**
При выборе элемента типа "ПланВидовХарактеристик.ДополнительныеРеквизитыИСведения" возникает ошибка.

**Ожидаемое поведение, если бы ошибки не было**
Выбраться элемент и найтись ссылки на него

**Скриншоты**

![Screenshot_2](https://github.com/infostart-hub/toolkit/assets/65113366/5c7c522b-26e6-4bd4-8876-5775c5981d60)

![Screenshot_1](https://github.com/infostart-hub/toolkit/assets/65113366/d998ef9d-79af-4908-b91e-c5afb0c1a6cb)

**Окружение:**  
Infostart Toolkit CORP 2023.3.04

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.191)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.411

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести ошибку... проверил на ЕРП все ОК. Нужно больше информации
В значении не должно быть значения типа Массив

**Comment by sagittarius-s** [comment]
Разобрался. Форма выбора не штатная оказывается и у списка стоит режим выделения "Множественный", от этого он всегда и возвращает массив. Предлагаю предусмотреть такой поворот событий и брать из массива первый элемент.

**Comment by Evg-lylyk** [comment]
Принято тут надо поизучать...
Для подобных случаев в контекстном меню есть "форма выбора (универсальная)" ну или можно вставить через навигационную ссылку, GUID
