### ISSUE TITLE
Неоднозначный тип Массив параметра в новой консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#765]
**Описание ошибки**
В консоли кода при выборе типа "Массив" для параметра консоли на самом деле используется тип "СписокЗначений".

**Сценарий воспроизведения**
1. Открыть новую консоль кода
2. Перейти на закладку "Параметры". Добавить новый параметр с именем `Значение` и типом `Массив`.
3. Перейти на закладку "Код". Ввести текст `Результат = Параметры.Значение;`
4. Выполнить код. Убедиться, что в дереве "Переменные" значение результата имеет тип `СписокЗначений` вместо ожидаемого `Массив`.

**Ожидаемое поведение, если бы ошибки не было**
Либо в диалоге выбора типа параметра вместо `Массив` должно быть `СписокЗначений`, либо в результат выполнения кода должен быть типа `Массив`. В лучшем случае в диалоге выбора типа должен быть и список значений, и массив.

**Окружение:**
Infostart Toolkit PROF 2023.4.02

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.4.3
