### ISSUE TITLE
Добавлять переменные в параметры новой консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#766]
**Существует проблема**
Есть ситуации, когда требуется отладить большой кусок кода, состоящий из вызовов нескольких процедур и функций. Консоль кода не поддерживает сейчас использование процедур и функций в коде, поэтому приходится отлаживать код частями: сначала выполнить один кусок кода, потом используя его результаты выполнить другой кусок кода и т.д. Сейчас, чтобы использовать результаты предыдущего куска кода в последующих итерациях отладки, требуется вручную добавлять параметры консоли кода, значения которых отображаются в дереве переменных.

**Хотелось бы иметь следующую функциональность**
Нужна команда в дереве переменных, благодаря которой можно будет добавить в список параметров консоли нужную переменную со своим значением.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.4.02

**Comment by nick-ez** [comment]
Было-бы прикольно вызывать из одного кода, другой код (в рамках проекта консоли кода) с передачей параметров

**Comment by Evg-lylyk** [comment]
> Было-бы прикольно вызывать из одного кода, другой код (в рамках проекта консоли кода) с передачей параметров

Такого не планируется, поддержка процедур планируется
