### ISSUE TITLE
Замер производительности для новой консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#767]
**Существует проблема**
Нередко помимо замера производительности запроса хочется провести эксперимент и для разных алгоритмов на встроенном языке, какой из алгоритмов окажется быстрее. Сейчас в новой консоли кода отсутствует встроенный замер времени выполнения, как это было для старой консоли запросов.

**Хотелось бы иметь следующую функциональность**
Сейчас же хотелось бы не только встроенный замер для новой консоли кода, но и инструмент для сравнения результатов. Предполагаемый сценарий таков: добавляем несколько листингов кода в дерево данных, каждый из которых содержит свой вариант реализации одной и той же задачи, далее выделяем несколько листингов в дереве и запускаем замер. На выходе имеем таблицу с именами алгоритмов (элементов дерева данных) и временем выполнения каждого из них.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.4.02

**Comment by Evg-lylyk** [comment]
Скорость есть в шапке результата, более сложный подход может в будущем
