### ISSUE TITLE
Ошибка при редактировании движений в редакторе объекта

### ISSUE THREAD

**Issue by Karejl** [infostart-hub/toolkit#780]
**Описание ошибки**
при попытки отредактировать движения(регистры хозрасчетный и накопления) любого документа выходит ошибка:

Индекс находится за границами массива
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(926)}:НайденнаяСтрока = НайденныеСтроки[0];
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(397)}:СохранитьИзмененнуюТаблицуЗначений("Движения", "РедактируемыеДвижения");
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(622)}:Элементы.Движения.ОтборСтрок = ОтборСтрок;
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1126)}:ОбновитьЭлементыФормы();
{InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(1085)}:ОбновитьДанныеОбъекта();
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(594)}:ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(312)}:ОповеститьОЗавершенииДлительнойОперации(Контекст.ОповещениеОЗавершении,
{ОбщаяФорма.ДлительнаяОперация.Форма(213)}:Закрыть();
{ОбщаяФорма.ДлительнаяОперация.Форма(166)}:ЗавершитьДлительнуюОперациюИЗакрытьФорму(ДлительнаяОперация);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(594)}:ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(586)}:ОповеститьОЗавершенииДлительнойОперации(ДлительнаяОперация.ОповещениеОЗавершении,
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(541)}:ЗавершитьДлительнуюОперацию(ДлительнаяОперация, Результат);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(394)}:Если ОбработатьРезультатАктивнойОперации(Операция, Результат) Тогда
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(286)}:ОбработатьРезультатОперации(АктивныеДлительныеОперации, Операция, Результат);
{ОбщийМодуль.СерверныеОповещенияКлиент.Модуль(354)}:ДлительныеОперацииКлиент.ПослеПериодическогоПолученияДанныхКлиентаНаСервере(
{ОбщийМодуль.СерверныеОповещенияКлиент.Модуль(201)}:ПроверитьПолучитьСерверныеОповещенияСПоказателями(СостояниеПолучения, Показатели);
{ОбщийМодуль.СерверныеОповещенияГлобальный.Модуль(13)}:СерверныеОповещенияКлиент.ПроверитьПолучитьСерверныеОповещения();

**Окружение:**

   - Платформа 1С: 8.3.22.2143
   - Имя конфигурации: ERP 2.5.8

   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести, напиши мне в телеграм, может подключусь, посмотрим. Попробуй еще кэш почистить

**Comment by Evg-lylyk** [comment]
Разобрались, исправлено в 2023.4.6
