### ISSUE TITLE
Не выводит результат запроса с итогами

### ISSUE THREAD

**Issue by sagittarius-s** [infostart-hub/toolkit#781]
**Описание ошибки**
Не выводится результат запроса:
```
ВЫБРАТЬ
	ВТ_Документы.КакойТоДокумент КАК Документ,
	ТИПЗНАЧЕНИЯ(ВТ_Документы.Документ) КАК ТипДокумента,
	ВТ_Документы.Период КАК Период
ИЗ
	ВТ_Документы КАК ВТ_Документы

ИТОГИ ПО
	Документ,
	ТипДокумента
```
Если оставить итоги только по "ТипДокумента" - работает.
Падает при попытке оформления ячейки, не может получить представление от "Неопределено".

**Ожидаемое поведение, если бы ошибки не было**
Результат запроса с итогами по двум колонкам

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/65113366/8ab21105-0331-4b18-a959-243d13d9e4da)

Тут спотыкается:
![image](https://github.com/infostart-hub/toolkit/assets/65113366/9c470802-fe8f-48a2-939f-52e4f84ef563)

По стеку приходит "Неопределено"
![image](https://github.com/infostart-hub/toolkit/assets/65113366/93a9d415-f069-4f20-8d0a-c87b035aee97)

**Окружение:**
Infostart Toolkit CORP 2023.3.04

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.191)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.5.411

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Напишите мне в https://t.me/EvgLylyk нужно получше разобраться

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.4.6

**Comment by Evg-lylyk** [comment]
Сейчас уже не помню в чем дело, нужно больше информации для воспроизведения или подключусь посмотрю
