### ISSUE TITLE
Формат сохранения файла Консоли запросов

### ISSUE THREAD

**Issue by nick-ez** [infostart-hub/toolkit#782]
**Хотелось бы иметь следующую функциональность**
Я сохраняю файл запроса в папке репозитория ГИТ проекта ЕДТ, и т.к. бинарный или архив? отслеживать изменения, стандартными функциями ЕДТ не возможно, сейчас это выглядит так 

![image](https://github.com/infostart-hub/toolkit/assets/91209214/37bfbc0e-07bf-4095-9d64-874257486b63)

Вариант реализации:  в настройках сделать опцию формат сохранения файла консоли запросов / кода.

Спасибо за Ваш продукт.

**Comment by Evg-lylyk** [comment]
Данное пожелание уже есть, в новой консоли кода уже реализован открытый формат
