### ISSUE TITLE
Консоль кода не видит параметры

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#786]
**Описание ошибки**
Консоль кода не видит параметры
Ошибка: {4} Переменная не определена (ДатаНачала)

**Сценарий воспроизведения**
Добавить параметр в консоли кода. Например ДатаНачала, указать тип, заполнить.
В окне кода написать Сообщить(ДатаНачала);

**Ожидаемое поведение, если бы ошибки не было**
Вывод переменной в окне результатов

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/2de2354f-3daa-4022-a127-371347da7812)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/c062ea51-115b-45d5-9fa4-0dd10e50219a)

**Окружение:**

Infostart Toolkit PROF 2023.4.08

Платформа: 8.3.21.1775 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Надо писать Параметры.ДатаНачала
