### ISSUE TITLE
В консоли кода серверный контекст выполняется в фоне

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#787]
**Описание ошибки**
Не срабатывает точка останова при установке контекста Сервер. Необходимо включать автоподключение фоновых заданий.

**Сценарий воспроизведения**
В консоли кода установить контекст Сервер. Установить точку останова в серверном модуле. Запустить процедуру сервеного модуля. Точка останова не сработала.

**Ожидаемое поведение, если бы ошибки не было**
Точка останова сработала

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**
Infostart Toolkit PROF 2023.4.08

Платформа: 8.3.21.1775 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.1
