### ISSUE TITLE
Редактор объекта - ошибка в найти колонку

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#790]
**Описание ошибки**
В редакторе объекта перейти к редактированию табл. частей. Нажать кнопку "Найти колонку..." и в открывшейся форме нажать Отмена.

**Скриншоты**
![Параметры](https://github.com/infostart-hub/toolkit/assets/18395787/ee64b9e7-79c3-4a42-b995-e0cba7f14ebd)

**Окружение:**

 Infostart Toolkit PROF 2023.4.08

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление холдингом, редакция 3.1 (3.1.14.27)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.5.180

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спс. Проблема исправлена в 2023.4.9
