### ISSUE TITLE
Запрос к внешнему источнику данных не отрабатывает

### ISSUE THREAD

**Issue by Petr28** [infostart-hub/toolkit#793]
**Описание ошибки**
При попытке выполнения запроса через консоль запросов к подключенному внешнему источнику данных консоль запросов падает. 
Стандартная консоль запросов отрабатывает этот же запрос. 

**Скриншоты**
![Скриншот 11-09-2023 09 56 43](https://github.com/infostart-hub/toolkit/assets/16154543/b47d4f34-fd16-4f64-b954-87c097eec5cc)

** Окружение **
Infostart Toolkit PROF 2023.4.08

Платформа: 8.3.23.1865 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление нашей фирмой, редакция 1.6 (1.6.17.174)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.2.264

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
По проблеме похоже ошибка возникает при подцветке особых значений не знал что в запросе возможны двоичные данные видимо во внешних источниках это возможно. В стандартной консоли нет подцветки особых значений NULL и прочего... можете в настройках Toolkit ее отключить
Приветствую, лучше если мы свяжемся в телеграм https://t.me/EvgLylyk
разберемся как исправить эту проблему

**Comment by Evg-lylyk** [comment]
Проблема исправлена в 2023.4.9, сегодня добавлю на Инфостарт
