### ISSUE TITLE
Консоль СКД - ошибки при импорте xml схемы с макетами

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#799]
**Описание ошибки**
При загрузке xml схемы, в которой есть макеты:

1.  Задваивает строки на вкладке макеты.  При нажатии на кнопку "Ок" - лишние области удаляются
![См](https://github.com/infostart-hub/toolkit/assets/18395787/780a9cce-fc6c-4b23-9da3-598976ecc916)
Также не пишет адрес области
![image](https://github.com/infostart-hub/toolkit/assets/18395787/fb93c5f4-6a9b-4987-bddc-e2479e23fdd4)

2. Ошибка при импорте объединенной области макета.
В конфигураторе в макете объединение ячеек
![image](https://github.com/infostart-hub/toolkit/assets/18395787/9fa85ee0-9202-4541-9af8-51d40bc85bbb)
При импорте в консоль ошибка
![image](https://github.com/infostart-hub/toolkit/assets/18395787/fe9bd301-c8fe-46ae-87fd-e6d2191df2e8)

**Окружение:**
 Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление холдингом, редакция 3.1 (3.1.14.27)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.5.180

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1
