### ISSUE TITLE
Ошибка в консоле запросов

### ISSUE THREAD

**Issue by Keyn1** [infostart-hub/toolkit#802]
**Описание ошибки**
Открываю консоль запросов и выскакивает ошибка

Индекс находится за границами массива
{InfostartToolkitPROF ОбщийМодуль.ИТК_Туллкит.Модуль(39)}:Возврат НайденныеРасширения[0].Версия;
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиентСерверПовтИсп.Модуль(11)}:Возврат ИТК_Туллкит.Версия();
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиентСервер.Модуль(49)}:Возврат ИТК_ТуллкитКлиентСерверПовтИсп.Версия();
{InfostartToolkitPROF ОбщийМодуль.ИТК_РедакторКодаКлиент.Модуль(31)}:ПолноеИмяКаталога = СтрШаблон(ШаблонИмениКаталога, КаталогДанныхПользователя, ИТК_ТуллкитКлиентСервер.Версия());

далее окошко с текстом запроса рисуется желтой рамкой но запрос не показывается. Констуктор запускается вроде работает, при нажатии ок создаются параметры запроса, но сам запрос не видно, окно пустое.

**Сценарий воспроизведения**
Как получилась ошибка я точно не уверен, но примерно так.

Я работаю удаленно по RDP. Мой сеанс RDP завис, и я не могу в него войти. Далее администратор удаляет мой сеанс виндовс. Понятное дело консоль была открыта, и в ней был открытый запрос.

Далее все запускаю, и я как понимаю, консоль пытается восстановить то сброшенное состояние, у ней это не получается и выходит эта ошибка.

Если запустить о программе, выходит ошибка. 
и если встать отладкой на ошибке здесь
Функция Версия() Экспорт
	
	Отбор = Новый Структура;
	Отбор.Вставить("Имя", ИТК_ТуллкитКлиентСервер.Идентификатор());
	
	НайденныеРасширения = РасширенияКонфигурации.Получить(Отбор);
	
->   Возврат НайденныеРасширения[0].Версия; //  НайденныеРасширения будет пустой массив
	
КонецФункции

**Ожидаемое поведение, если бы ошибки не было**
Я считаю, что НЕ НУЖНО!!! восстанавливать мой сброшенный сеанс., тогда бы наверное ошибки не было.
не нужно открывать мои старые запросы, и делать что я не просил.
Т.е. консоль запросов должна работать как программа Word. Я нажимаю Файл-Открыть и тогда должен открываться файл с запросом.
Если это не делал, открывается чистая консоль для работы с новым запросом!!!
Для меня важнее чтобы работала консоль всегда а не последняя минута работы, ведь запрос сохраняется каждую минуту.

Подскажите как восстановить работоспособность?

**Окружение:**

   - Платформа 1С: *   - 1С:Предприятие 8.3 (8.3.22.1750)
   - Имя конфигурации: *  ИУС ТОИР сильно переписанная
   - Язык: * рус
   - Операционная система: * win 10
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки
Если нажать О программе опять выходит ошибка
Индекс находится за границами массива
{InfostartToolkitPROF ОбщийМодуль.ИТК_Туллкит.Модуль(39)}:Возврат НайденныеРасширения[0].Версия;
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиентСерверПовтИсп.Модуль(11)}:Возврат ИТК_Туллкит.Версия();
{InfostartToolkitPROF ОбщийМодуль.ИТК_ТуллкитКлиентСервер.Модуль(49)}:Возврат ИТК_ТуллкитКлиентСерверПовтИсп.Версия();
{InfostartToolkitPROF ОбщаяФорма.ИТК_ОПрограмме.Форма(6)}:Версия = ИТК_ТуллкитКлиентСервер.Версия();
{InfostartToolkitPROF Обработка.ИТК_Поддержка.Команда.ОПрограмме.МодульКоманды(6)}:ОткрытьФорму("ОбщаяФорма.ИТК_ОПрограмме");

<!-- **Дополнительный контекст**

- Типовая или не типовая конфигурация ?
- не типовая
- 
- Включен ли режим защиты от опасных действий
- выключен 
-

**Comment by Keyn1** [comment]
удалось восстановить работу через удаление расширение и повторную установку

**Comment by Evg-lylyk** [comment]
Приветствую.
Похоже на какую то платформенную ошибку, все что делает эта функция ищет установленное расширение и берет его версию. А тут расширение установлено а его не находит. 

`Я считаю, что НЕ НУЖНО!!! восстанавливать мой сброшенный сеанс., тогда бы наверное ошибки не было.
не нужно открывать мои старые запросы, и делать что я не просил.
Т.е. консоль запросов должна работать как программа Word. Я нажимаю Файл-Открыть и тогда должен открываться файл с запросом.
Если это не делал, открывается чистая консоль для работы с новым запросом!!!`

Не говорю что механизм идеален, он нужен как узнать что он существует. В других программах работает схоже.

`Для меня важнее чтобы работала консоль всегда а не последняя минута работы, ведь запрос сохраняется каждую минуту.`

Вы столкнулись с какой-то непонятной ошибкой.
