### ISSUE TITLE
Консоль разработчика - ошибка при точке с запятой в конце запроса

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#803]
**Описание ошибки**
Если запрос содержит в конце точку с запятой, при попытке выполнить запрос - ошибка

**Сценарий воспроизведения**
выполнить в консоли разработчика запрос "ВЫБРАТЬ "" КАК ПустаяСтрока;"

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/73e22818-fa4e-47e9-803f-47f909961528)

**Окружение:**

Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.443)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.369

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
В 2023.5 исправил эту ошибку
