### ISSUE TITLE
Не сбрасывается поиск при повторном открытии меню Все функции

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#805]
**Описание ошибки**
При повторном открытии меню Все функции (Alt-A) не сбрасывается предыдущий поиск. 
Приходится очищать поиск перед новым вводом в окне поиска или очищать поиск и сворачивать дерево для визуального поиска.

**Ожидаемое поведение, если бы ошибки не было**
При повторном открытии чистое окно поиска, свернутое дерево.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/f83c2d0f-6825-4d0b-8365-1ff388c0b581)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

   - Платформа 1С: *
   - Имя конфигурации: *
   - Язык: *
   - Операционная система: *
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Поведение схоже со стандартной формой, обычно его открывают и сразу поиск, т.к. объектов много

**Comment by Serg2000Mr** [comment]
В стандартной форме так же, да. Но например я не только поиском пользуюсь. Если нужно в Стандартные-Управление расширениями формы, то мне проще открыть его в дереве, чем вспоминать, как оно называется. Часто используемые обработки тоже перенесены в начало списка, чтобы их было просто находить. А результаты прошлого поиска сбивают с мысли. Для повторного открытия объекта я скорее в историю полезу.

**Comment by Evg-lylyk** [comment]
Реализовано "по другому" в 2023.5
