### ISSUE TITLE
В консоли запросов игнорируется настройка вывода временных таблиц пакета

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#806]
**Описание ошибки**
В консоли запросов игнорируется настройка вывода временных таблиц пакета

**Сценарий воспроизведения**
Выполнить запрос, который содержит временную таблицу и обычный запрос. Временная таблица выведена не будет несмотря на настройку на закладке Дополнительно:  "Выводить"

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/dfb4593f-61bc-4f9f-aaf5-345ec244ee4d)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
В версии 2023.5 добавил пояснение на форму
