### ISSUE TITLE
Журнал регистрации IS - не работает кнопка очистки поля Данные

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#807]
**Описание ошибки**
Обработка Журнал регистрации (Toolkit) (ИТК_ЖурналРегистрации).
В настройках фильтра у поля "Данные" не работает кнопка Очистка.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/93330168-8253-4b10-96c1-003160c78443)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5
