### ISSUE TITLE
Некорректная работа поиска в "Поиск по структуре хранения"

### ISSUE THREAD

**Issue by denk-32** [infostart-hub/toolkit#809]
**Описание ошибки**
Поиск возвращает пустой результат.

**Сценарий воспроизведения**
В строке поиска ввести название в терминах 1С. Например: поступление.

**Ожидаемое поведение, если бы ошибки не было**
Должен вывести список таблиц документа

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/37189132/6fbd4563-9f57-41a5-a1a3-fc0c3ddd2ee2)

**Окружение:**

   - Платформа 1С: 1С:Предприятие 8.3 (8.3.23.1912) Версия для разработчиков.
   - Имя конфигурации: Демонстрационная конфигурация "Библиотека стандартных подсистем", редакция 3.1 (3.1.9.179)
   - Язык: Русский
   - Операционная система: Windows 10, 22H2, 19045.3570
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

<!-- **Дополнительный контекст**

Скорее всего некорректно задан поиска в цикле в модуле ИТК_ПоискПоСтруктуреХранения.РезультатПоиска().
В цикле ИмяТаблицыХранения всегда равно имени таблицы в терминах СУБД. 
Возможно причина в том что нет проверки по какому имени искать. По имени в терминах СУБД или по имени терминах 1С.
После доработки присвоения значения переменной ИмяТаблицыХранения в зависимости от того в каких терминах выполняется поиск, результат стал появляться.
![image](https://github.com/infostart-hub/toolkit/assets/37189132/49566dba-f0c9-4c3a-a6c8-f6935d49dab3)

**Comment by Evg-lylyk** [comment]
Такое поведение не подразумевалось, поиск идет по структуре хранения это поля на английском что в терминах 1С что в терминах СУБД.
В версии 2023.5 переделал добавил в поиск поле Метаданные
