### ISSUE TITLE
Консоль разработчика - ошибка определения типа параметра

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#810]
**Описание ошибки**
При захвате запроса через Итк.Отл(Запрос) изменился тип параметра со строки на число.
`Запрос = Новый Запрос;

Запрос.УстановитьПараметр("ГодДатыСверки", Формат(Объект.ДатаСверки, "ДФ=yyyy"));

Запрос.Текст = "ВЫБРАТЬ ПЕРВЫЕ 1
	               |	КурсыВалют.Период КАК Период,
		       |	ГОД(КурсыВалют.Период) КАК Год,
	               |	КурсыВалют.Валюта КАК Валюта,
	               |	КурсыВалют.Курс КАК Курс
	               |ИЗ
	               |	РегистрСведений.КурсыВалют КАК КурсыВалют
	               |ГДЕ
	               |	ГОД(КурсыВалют.Период) = &ГодДатыСверки";

ИТК.Отл(Запрос);`

**Сценарий воспроизведения**
Захватить запрос, указанный выше.
Параметр ГодДатыСверки  будет определен как число, хотя в запросе он строка.

По-видимому, тип взялся из типа значения ГОД(КурсыВалют.Период)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Случай конечно странный, понятно же что такой отбор не работает, в функцию отладки добавил чтобы подобные выражения переносились как Выражение.
С версии 2023.5
