### ISSUE TITLE
Конфигурация Drive - нет заголовков закладок

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#811]
**Описание ошибки**
Консоль разработчика - Конструктор запроса - нет заголовков закладок.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/ced6ab6c-aafa-4a39-85d3-82bb13310242)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Platform: 8.3.22.2239 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Language: ru
Launch mode: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Знаю об этой проблеме, это в платформе так, я могу только дополнительно перевести свой конструктор

**Comment by Serg2000Mr** [comment]
Да, было бы здорово. Я уже переводил до обновления IS Toolkit, нужно снова.

**Comment by Evg-lylyk** [comment]
> Да, было бы здорово. Я уже переводил до обновления IS Toolkit, нужно снова.

Ну так со мной мы списался, я бы внес в релиз. Там получается нужно перевести на английский, указать синонимы в Обработках ИТК_QueryWizard*

**Comment by Serg2000Mr** [comment]
Это было еще на заре эпох, я с тех пор c Drive не работал, и думал, что ты это исправил, так как я уже писал об этом.

**Comment by Evg-lylyk** [comment]
Решено с 2024.1
