### ISSUE TITLE
Файл по-разному отображается в списке переменных в зависимости от контекста

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#812]
**Описание ошибки**
При выполнении в консоли кода, содержащего переменную типа `Файл`, в списке переменных ее тип отображается по-разному в зависимости от контекста исполнения кода:
- на клиенте - `Файл`
- на сервере - `Неопределено`

**Сценарий воспроизведения**
1. Открыть консоль кода. Ввести код `Результат = Новый Файл();`
2. Выбрать контекст "Клиент" и выполнить код. Убедиться, что в списке переменных `Результат` имеет тип `Файл`.
3. Выбрать контекст "Сервер" и выполнить этот же код. Убедиться, что в списке переменных `Результат` имеет тип `Неопределено`. Ожидалось `Файл`.

**Ожидаемое поведение**
Тип переменных, отображаемых в списке переменных консоли, не должен зависеть от контекста выполнения кода.

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.21.1890 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Управление нашей фирмой, редакция 3.0 (3.0.5.183)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: 3.1.8.438

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
У меня нет Файл = Неопределено может это в клиент-серверном варианте
Проработал расшифровку типа Файл
![image](https://github.com/infostart-hub/toolkit/assets/48444742/fe820213-d81b-4bb7-88b0-a87fc8d53bb6)
