### ISSUE TITLE
Консоль кода требует обязательную точку с запятой в конце последней инструкции листинга

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#813]
**Описание ошибки**
Если в конце листинга кода не поставить точку с запятой для последней инструкции, будет выдано сообщение об ошибке:

> Ожидается символ ";"

**Сценарий воспроизведения**
1. Открыть консоль кода.
2. Ввести в одну строку кода `А = 0` (без точки с запятой в конце).
3. Нажать "Выполнить"
4. Убедиться, что выполнение кода неожиданно завершилось с ошибкой.

**Ожидаемое поведение, если бы ошибки не было**
Встроенный язык 1С не обязывает разработчика ставить точку с запятой в конце блока условного оператора, в конце процедуры или функции и т.п. Ожидается, что и консоль кода не будет требовать точку с запятой в конце введенного пользователем кода.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/912f02d5-a8ff-4d97-a0c0-404a95a8e8d9)
![image](https://github.com/infostart-hub/toolkit/assets/59051827/fbe78164-b8b3-4425-9412-192a83a7ed43)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.21.1890 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Управление нашей фирмой, редакция 3.0 (3.0.5.183)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: 3.1.8.438

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
В 2023.5 автоматически добавляю ";", надеюсь с этим не будет проблем
