### ISSUE TITLE
Консоль разработчика, на платформе 8.3.23.1912, не верно определяется "IDПроцесса"

### ISSUE THREAD

**Issue by LkMaksimka** [infostart-hub/toolkit#815]
**Описание ошибки**
Не возможно посмотреть план запроса, выходит ошибка

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открываю **Консоль разработчика**
2. Выполняю простой запрос
`ВЫБРАТЬ ПЕРВЫЕ 10`
`	КлючиАналитикиУчетаНоменклатуры.Номенклатура.Артикул КАК НоменклатураАртикул`
`ИЗ`
`	Справочник.КлючиАналитикиУчетаНоменклатуры КАК КлючиАналитикиУчетаНоменклатуры`

4. Нажимаю **Анализировать план запроса**
5. Выходит ошибка

**Ожидаемое поведение, если бы ошибки не было**
Должна была открыться форма с планом запроса

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/23025375/cd040fcd-9c8a-4ee8-89b8-3b389e1de81b)

![image](https://github.com/infostart-hub/toolkit/assets/23025375/d185c5d9-b288-44b9-8da9-e7d9d7a38c56)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.23.1912 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.14.74)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Приветствую, попробуй в модуле ИТК_АнализПланаЗапроса
`Функция ИдентификаторПроцессаОС() Экспорт

	ВнешняяКомпонента = ИТК_ОбщийПовтИсп.ВнешняяКомпонентаДиагностикиКонтекста();
	Возврат ВнешняяКомпонента.ПолучитьИдентификаторПроцесса();
	
КонецФункции`

поменять
Возврат ВнешняяКомпонента.ПолучитьИдентификаторПроцесса();
на
Возврат ВнешняяКомпонента.ПолучитьИдентификаторПотока();

**Comment by LkMaksimka** [comment]
Добрый вечер, не помогло 
![image](https://github.com/infostart-hub/toolkit/assets/23025375/0c71034c-1283-4c95-9981-d356e7a80757)

![image](https://github.com/infostart-hub/toolkit/assets/23025375/6cf63fec-52b7-4dd6-86a0-b08bd893bd07)

**Comment by Evg-lylyk** [comment]
Еще можно попробовать код этой функции из типовой консоли запросов от 1С
`Функция ИдентификаторПроцессаОС()
	
	ИДТекущегоПроцесса = Неопределено;
	ОбъектСистемы = Новый COMОбъект("WScript.Shell");
	Если ИДТекущегоПроцесса = Неопределено Тогда 
		Процесс = ОбъектСистемы.Exec("rundll32.exe kernel32,Sleep");
		ИДТекущегоПроцесса = ПолучитьCOMОбъект("winmgmts:{impersonationLevel=impersonate}!\\.\root\CIMV2:Win32_Process.Handle='" + Формат(Процесс.ProcessID,"ЧГ=0") + "'").ParentProcessID;
		Процесс.Terminate();
	КонецЕсли;
	
	Возврат ИДТекущегоПроцесса;
	
КонецФункции`

**Comment by LkMaksimka** [comment]
Добрый день, работает, но форма "План выполнения запроса" пустая.
![image](https://github.com/infostart-hub/toolkit/assets/23025375/1cf7ee4a-b2da-42c4-9872-7eb565207456)
![image](https://github.com/infostart-hub/toolkit/assets/23025375/f05a691d-f45f-4fa3-bec9-fe08f847553a)

[logcfg.txt](https://github.com/infostart-hub/toolkit/files/13292159/logcfg.txt)

[23110807.log](https://github.com/infostart-hub/toolkit/files/13292147/23110807.log)

**Comment by Evg-lylyk** [comment]
Удалось решить проблему?

**Comment by LkMaksimka** [comment]
Нет, не удалось

**Comment by Evg-lylyk** [comment]
Давайте вернемся к вопросу и попробуем разобраться мой телеграм https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
Прошу как будет возможность выйти на связь в телеграм https://t.me/EvgLylyk
Попробуем разобраться

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1
