### ISSUE TITLE
При записи объекта в редакторе объектов ошибка

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#816]
**Описание ошибки**
В редакторе объекта при записи ошибка:
`
Поле объекта не обнаружено (ТекстСообщения)
{InfostartToolkitPROF DataProcessor.ИТК_РедакторОбъекта.Form.Форма.Form(973)}:ПараметрыОжидания[ПолеТекстСообщения] = НСтр("ru = 'Запись объекта'; en = 'Object entry'");
{mngcore/MessageBox.clf(4)}:Close(-100);
`
Объект при этом записывается

**Сценарий воспроизведения**
Alt-T - Edit object - изменить - сохранить

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/24ce1e18-741b-4ac5-9a03-7dd0a405158f)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Platform: 8.3.22.2239 (Windows x86-64)
Mode IB: client-server

Configuration:
1C:Drive, version 1.3 (1.3.13.4)
Basic launch mode: Управляемое приложение
Compatibility mode: Version8_3_14
SSL version: 3.0.1.331

Client:
Thin client
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Language: ru
Launch mode: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.4.10
