### ISSUE TITLE
Ошибка в конструкторе запросов при смене таблицы

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#82]
Версия 1.3.1

Открываю конструктор запросов 
Выбираю заменить таблицу
![image](https://user-images.githubusercontent.com/18395787/95430673-c449b600-0954-11eb-9a13-2b1ac537db4d.png)

Разворачиваю дерево и получаю такие ошибки
![image](https://user-images.githubusercontent.com/18395787/95430737-d9264980-0954-11eb-9baa-980ae36e9893.png)

![image](https://user-images.githubusercontent.com/18395787/95430793-efcca080-0954-11eb-8962-8546f912792f.png)

**Comment by Evg-lylyk** [comment]
Спасибо за информацию
Исправлено с версии 1.4
