### ISSUE TITLE
Ошибка при отладке запроса

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#820]
**Описание ошибки**
при захвате запроса через Итк.Отл(Запрос) - ошибка
`
Ошибка при вызове метода контекста (ПолучитьДанные)
{InfostartToolkitPROF ОбщийМодуль.ИТК_Отладка.Модуль(184)}:ТаблицаЗначений = ВременнаяТаблица.ПолучитьДанные().Выгрузить();
{InfostartToolkitPROF ОбщийМодуль.ИТК_Отладка.Модуль(19)}:ДанныеОбъекта = ДанныеЗапросаИзОбъекта(Объект, ДополнительныеПараметры, ТекстОшибки);
{InfostartToolkitPROF ОбщийМодуль.ИТК.Модуль(121)}:Возврат ИТК_Отладка.СохранитьДанные(Объект, ТипОбъекта, ТипХранения, ДополнительныеПараметры);
{InfostartToolkitPROF ОбщийМодуль.ИТК.Модуль(16)}:Возврат СохранитьДанныеОтладки(Объект, ИТК_Перечисления.ТипХраненияДанныхНастройка(), Имя, Параметр1, Параметр2);
{Документ.СчетФактураВыданный.МодульМенеджера(5172)}:А = Итк.Отл(Запрос);
{ВнешняяОбработка.СчетФактураВыданныйРусэкспортЕАЭС.МодульОбъекта(189)}:ДанныеДляПечати = МенеджерОбъекта.ПолучитьДанныеДляПечатнойФормыСчетФактура(ПараметрыПечати, СтруктураОбъектов.Значение);
{ВнешняяОбработка.СчетФактураВыданныйРусэкспортЕАЭС.МодульОбъекта(68)}:УправлениеПечатью.ВывестиТабличныйДокументВКоллекцию(
{ОбщийМодуль.УправлениеПечатью.Модуль(1727)}:ВнешняяОбработкаОбъект.Печать(
{ОбщаяФорма.ПечатьДокументов.Форма(557)}:УправлениеПечатью.ПечатьПоВнешнемуИсточнику(
{ОбщаяФорма.ПечатьДокументов.Форма(52)}:КоллекцияПечатныхФорм = СформироватьПечатныеФормы(Параметры.ИменаМакетов, Отказ);
{ОбщийМодуль.УправлениеПечатьюСлужебныйКлиент.Модуль(245)}:ОткрытьФорму("ОбщаяФорма.ПечатьДокументов", ПараметрыОткрытия, Форма);
{ОбщийМодуль.УправлениеПечатьюКлиент.Модуль(182)}:ВыполнитьОбработкуОповещения(ОписаниеПроцедурыЗавершения, СписокДокументов);
{ОбщийМодуль.УправлениеПечатьюСлужебныйКлиент.Модуль(32)}:УправлениеПечатьюКлиент.ПроверитьПроведенностьДокументов(ОписаниеОповещения, ОбъектыНазначения, Форма);
{ОбщийМодуль.ДополнительныеОтчетыИОбработкиКлиент.Модуль(510)}:МодульУправлениеПечатьюСлужебныйКлиент.ВыполнитьОткрытиеПечатнойФормы(
{ОбщийМодуль.ДополнительныеОтчетыИОбработкиКлиент.Модуль(270)}:ВыполнитьОткрытиеПечатнойФормы(ВыполняемаяКоманда, Форма, ВыполняемаяКоманда.ОбъектыПечати);
{ОбщийМодуль.УправлениеПечатьюСлужебныйКлиент.Модуль(96)}:МодульДополнительныеОтчетыИОбработкиКлиент.ВыполнитьНазначаемуюКомандуПечати(ОписаниеКоманды, Форма);
{ОбщийМодуль.УправлениеПечатьюСлужебныйКлиент.Модуль(20)}:ВыполнитьПодключаемуюКомандуПечатиЗавершение(Истина, ПараметрыВыполнения);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(281)}:ВыполнитьОбработкуОповещения(Обработчик, ПараметрКоманды);
{ОбщийМодуль.ПодключаемыеКомандыКлиент.Модуль(35)}:ПродолжитьВыполнениеКоманды(ПараметрыВыполнения);
{Документ.СчетФактураВыданный.Форма.ФормаДокумента.Форма(808)}:ПодключаемыеКомандыКлиент.НачатьВыполнениеКоманды(ЭтотОбъект, Команда, Объект);

по причине:
Ошибка при получении данных временной таблицы.
по причине:
{(1, 15)}: Неоднозначное поле "ПредставлениеВыставленКомиссионеру.СчетФактура"
SELECT * FROM <<?>>ПредставлениеВыставленКомиссионеру
`

При этом запрос выполняется без ошибок

**Сценарий воспроизведения**
Конфигуратор - добавить перед выполнением пакета запроса в код строку Итк.Отл(Запрос)

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/08fa74ec-d1fe-4582-95ce-f096b0275cbd)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.443)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.369

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Похоже на баг платформы, пока оставлю может еще столкнемся.
По идее можно добавить попытку и вернуть более читаемое сообщение
