### ISSUE TITLE
Поддержка типа "Уникальный идентификатор" при редактировании таблицы значений во внешних источниках консоли разработчика

### ISSUE THREAD

**Issue by DenisAndriyanov** [infostart-hub/toolkit#822]
При работе в консоли разработчика в редакторе таблицы значений при загрузке таблицы из буфера обмена, для колонки со значениями GUID по умолчанию устанавливается тип "Строка", в дальнейшем при смене типа колонки на "Уникальный идентификатор" все значения обнуляются и принимают значение:
Было: 8fade22a-8b98-11e2-82dd-bcaec51b91f9 (Строка)
Стало: 00000000-0000-0000-0000-000000000000 (Уникальный идентификатор).

Так же не помогает вариант изначально для колонки установить тип "Уникальный идентификатор" и загрузить таблицу из буфера. В этом случае устанавливается тип "Строка".

Шаги по воспроизведению:
0. Скопировать в буфер обмена таблицу с колонкой содержащей значения GUID
1. Открыть 'Редактор таблицы значений'
2. Нажать 'Загрузить - Из буфера обмена'
3. Для колонки с GUID поменять тип на 'Уникальный идентификатор'
4. В таблице с данными все значения GUID обнулятся принимая вид "00000000-0000-0000-0000-000000000000".

**Ожидаемое поведение, если бы ошибки не было**
На 4-м шаге строковые значения GUID "8fade22a-8b98-11e2-82dd-bcaec51b91f9" поменяли свой тип на "Уникальный идентификатор" сохранив свое изначальное строковое представление.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/11434767/399a468d-5749-46e1-800c-7dd65d88ab11)

**Окружение:**
Infostart Toolkit PROF 2023.4.08

Платформа: 8.3.23.1912 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.111)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.502

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение
   
- Типовая или не типовая конфигурация: не типовая
- Включен ли режим защиты от опасных действий: отключен

**Comment by Evg-lylyk** [comment]
Проблема решена в 2023.5.1
