### ISSUE TITLE
Неверно представлено соответствие на панели результата консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#823]
**Описание ошибки**
В консоли кода на панели результата "Переменные" некорректно отображаются ключи переменной-соответствия, представляющие собой значения **непримитивных** типов (например, ссылки).

**Сценарий воспроизведения**
1. Открыть консоль кода. Ввести текст:
```
Результат = Новый Соответствие;
Результат.Вставить(1, "Первый");
Результат.Вставить("2", "Второй");
Результат.Вставить(Перечисления.СтавкиНДС, "Третий");
Результат.Вставить(Справочники.СтавкиНДС.БезНДС, "Четвертый");
```
2. Развернуть ветку переменной `Результат` на панели результата выполнения кода для просмотра содержимого соответствия.
3. Убедиться, что первые два ключа - `1` и `"2"` - отображаются корректно, последние два - ссылки - представления не ссылок, а типов (или менеджера объекта конфигурации).

**Ожидаемое поведение, если бы ошибки не было**
Хотелось бы видеть в качестве ключей соответствия сами значения, а также их тип.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/c66e5b40-0897-4145-9086-96b319dc5325)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.21.1890 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Управление торговлей, редакция 11 (11.5.11.86)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.357

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.1
