### ISSUE TITLE
Вставка литералов типа Дата и Строка в консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#824]
**Существует проблема**
Иногда возникает потребность вставить некоторое значение даты в консоли кода, скопировав ее и поля даты в другой форме или просто ввести дату привычным способом: день, месяц, год. Однако встроенный язык 1С требует для ввода литерала даты, во-первых, переключить раскладку для ввода одинарных кавычек, а во-вторых, вводить его в непривычном порядке: год, месяц, день.

Схожая проблема есть и со вставкой многострочного текста в код. Сейчас при наборе текста вручную в момент перехода на новую строку автоматически вставляется символ вертикальной черты, что здорово. Но этого же механизма не хватает при вставке многострочного текста из буфера обмена, чтобы каждая новая строка вставки автоматически предварялась вертикальной чертой.

**Хотелось бы иметь следующую функциональность**
Наравне с командой контекстного меню "Вставка ссылки на объект БД" хотелось бы иметь команды:
* Вставка даты - для открытия диалогового окна ввода даты, после выбора которой автоматически в код вставлялся бы литерал даты с нужным значением.
* Вставка строки - для открытия диалогового окна ввода многострочного текста.

Возможно, еще лучше будет, если можно будет обойтись без использования диалоговых окон. Например:
* при вставке даты в локальном формате между одинарными кавычками, консоль будет парсить вставляемый текст и приводить его к формату даты, требуемому встроенным языком 1С;
* при вставке текста из буфера обмена между двойными кавычками, каждая новая строка вставляемого текста будет автоматически предваряться вертикальной чертой.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.4.09

**Comment by d-hurricane** [comment]
Я совсем забыл, что в консоли кода появились параметры. :-) В принципе, их можно считать решением проблемы.

**Comment by Evg-lylyk** [comment]
Хорошо ;)
