### ISSUE TITLE
Ошибка при открытии консоли разработчика

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#826]
**Описание ошибки**
При открытии консоли разработчика ошибка "Ожидается ВЫБРАТЬ"

**Сценарий воспроизведения**
Alt-T - Консоль запросов

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/89a6d3c2-f9c0-4bee-b211-bee3147faec7)

**Окружение:**
Infostart Toolkit PROF 2023.4.10

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.443)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.369

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Такая проблема уже описана #748
Согласен что это проблема, но считаю ее незначительной т.к. если нажать выполнить будет такая ошибка... это когда то был реализован такой подход.

**Comment by Serg2000Mr** [comment]
Это не незначительная проблема, а раздражающий фактор. Именно поэтому я второй раз про нее пишу.

**Comment by Evg-lylyk** [comment]
Я помню, свой взгляд тебе описал

**Comment by Serg2000Mr** [comment]
Ладно, буду патчи писать.

**Comment by Evg-lylyk** [comment]
> Ладно, буду патчи писать.

Постараюсь исправить
