### ISSUE TITLE
Загрузка данных во внешний источник из табличного документа в консоли запросов

### ISSUE THREAD

**Issue by vlhown** [infostart-hub/toolkit#827]
В консоли запросов при загрузке данных во внешний источник из табличного документа Excel числовые значения автоматически распознаются как имеющие тип "Строка, Дата".
Если вручную поменять тип колонки на Число, часть значений пропадает.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль запросов, создать новый запрос.
2. Добавить новый внешний источник данных таблицу значений.
3. Нажать "Загрузка", выбрать "Из табличного документа", указать прилагаемый файл.
4. Будет предложено загрузить идентификаторы Код и Сумма. Загрузить.
5. Видим в загруженных данных, что колонка Сумма имеет тип "Строка, Дата", значения распознаны как дата.
6. Вручную меняем тип на Число(15,2). Часть значений (которые были распознаны как дата) пропадает.

[ПримерExcel.xlsx](https://github.com/infostart-hub/toolkit/files/13447123/Excel.xlsx)

При загрузке из табличного документа mxl возникает ошибка проверки мутабельных значений на заполненность.
![image](https://github.com/infostart-hub/toolkit/assets/151819771/4fe90ed0-4bd0-4893-989f-9cc9f13f1f75)

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/151819771/ee4e92b5-7aea-41b8-a9dd-838cad64076c)
**Окружение:**

![image](https://github.com/infostart-hub/toolkit/assets/151819771/599d60cc-ca36-4605-9c67-763d778e781c)
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.1

**Comment by vlhown** [comment]
Ошибка с исчезновением числовых значений при смене типа колонки со Строка на Число вроде бы ушла.
Но осталась (появилась) ошибка при смене типа на Дата - в колонке исчезают значения, и не отдельные, а все.

**Comment by Evg-lylyk** [comment]
Еще раз поправил в 2023.5.4
