### ISSUE TITLE
Невозможно удалить дополнительный реквизит объекта

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#829]
**Описание ошибки**
В редакторе объектов нет возможности удалить дополнительный реквизит объекта (ТЧ ДополнительныеРеквизиты)

В списке табличных частей ТЧ ДополнительныеРеквизиты отсутствует, а в списке реквизитов возможности удалять реквизиты нет.

**Окружение:**
Infostart Toolkit PROF 2023.4.10

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.8.443)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.369

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
Действительно, здесь редактор объекта ведет себя иначе, нежели типовой механизм редактирования доп. реквизитов в БСП:
- при присваивании пустого значения доп. реквизиту БСП удаляет соответствующую строку ТЧ "ДополнительныеРеквизиты"
- инструменты разработчика же оставляют строк в ТЧ на месте и хранят в ней пустое значение.
Полагаю, правильнее было бы редактору объекта вести себя так, как ведет типовой механизм.

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.1
