### ISSUE TITLE
Конструктор в консоли запросов не показывает все поля временной таблицы

### ISSUE THREAD

**Issue by vlhown** [infostart-hub/toolkit#830]
Собственно, все в заголовке темы

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/151819771/9d515839-07f8-4053-8524-cbf983c8d24e)
![image](https://github.com/infostart-hub/toolkit/assets/151819771/7666d49d-7c4e-4396-b0cc-3eee9bf63058)

**Окружение:**

Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.23.1912 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.113)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.162

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1
