### ISSUE TITLE
В редакторе объектов не отображаются стандартные табличные части Планов видов расчетов

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#832]
**Описание ошибки**
В редакторе объектов не отображаются стандартные табличные части Планов видов расчетов

**Сценарий воспроизведения**
Открыть редактор объекта Плана видов расчетов, у которого заполнены одна или несколько стандартных таблиц:
ВытесняющиеВидыРасчета
ВедущиеВидыРасчета
БазовыеВидыРасчета

На закладке "Табличные части" выделить такую таблицу. Содержимое табличной части не отображается.

То же самое у Планов счетов (таблица "Виды субконто")

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/a56f9a09-2628-4e0d-8fd1-c294219c4ae7)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.1
