### ISSUE TITLE
При переименовании параметра в консоли кода контекстная подсказка содержит старые варианты

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#833]
**Описание ошибки**
В консоли кода при каждом переименовании некоторого параметра в контекстную подсказку для параметров добавляется новый вариант именования этого параметра, но не удаляются старые.

**Сценарий воспроизведения**
1. Открыть консоль кода
2. Перейти на закладку "Параметры". Добавить новый параметр "Код1" произвольного типа.
3. Переименовать параметр на "Код2", затем сразу же на "Код3".
4. Перейти на закладку "Код". Ввести "Параметры", поставить точку для вызова контекстной подсказки.
5. Убедиться, что при наличии в списке параметров всего одной позиции, контекстная подсказка будет содержать три предложения: Код1, Код2 и Код3.

**Ожидаемое поведение, если бы ошибки не было**
Контекстная подсказка для объекта "Параметры" должна содержать актуальный перечень параметров, т.е. в данном примере только "Код3".

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/d894c5bb-376e-45f3-85a0-f8f3357624fc)

**Окружение:**
Infostart Toolkit PROF 2023.4.09

Платформа: 8.3.21.1895 (Linux x86-64)
Режим БД: клиент-серверный

Конфигурация:
Управление нашей фирмой, редакция 3.0 (3.0.5.183)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: 3.1.8.438

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.1
