### ISSUE TITLE
Убрать дополнительный клик при запуске под другим пользователем и добавить кнопку для открытия элемента справочника "пользователи"

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#843]
**Существует проблема**
1. требуется дополнительное нажатие мышкой для запуска под пользователем
2. не удобно искать пользователя в справочнике пользователи

**Хотелось бы иметь следующую функциональность**
1. запускать под пользователем сразу по нажатию на кнопку 
![image](https://github.com/infostart-hub/toolkit/assets/65346358/9f13f695-282c-4685-abca-cd64dc4007f8)
2. добавить кнопку для открытия элемента справочника в форму элемента и списка
![image](https://github.com/infostart-hub/toolkit/assets/65346358/33258efa-0cad-4e6c-a98d-64aa0b7f4aad)

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.1
