### ISSUE TITLE
Ошибка при импорте в консоль запросов параметра с типом Табл. значений.

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#844]
**Описание ошибки**
При импорте в консоль запроса параметра с типом табл. значений - ошибка.

`
	ТЗ = Новый ТаблицаЗначений;
	ТЗ.Колонки.Добавить("ТипЧисло", Новый ОписаниеТипов("Число",Новый КвалификаторыЧисла(10, 0, ДопустимыйЗнак.Любой)));
	ТЗ.Колонки.Добавить("ТипСтрока", Новый ОписаниеТипов("Строка", ,Новый КвалификаторыСтроки(10, ДопустимаяДлина.Фиксированная)));
	
	НоваяСтрока = ТЗ.Добавить();
	НоваяСтрока.ТипЧисло  = 1;
	НоваяСтрока.ТипСтрока = "a";
	
	Запрос = Новый Запрос;
	Запрос.Текст = 
	"ВЫБРАТЬ
	|	ТЗ.ТипЧисло КАК ТипЧисло,
	|	ТЗ.ТипСтрока КАК ТипСтрока
	|ПОМЕСТИТЬ ВТТЗ
	|ИЗ
	|	&ТЗ КАК ТЗ
	|;
	|
	|////////////////////////////////////////////////////////////////////////////////
	|ВЫБРАТЬ
	|	ВТТЗ.ТипЧисло КАК ТипЧисло,
	|	ВТТЗ.ТипСтрока КАК ТипСтрока
	|ИЗ
	|	ВТТЗ КАК ВТТЗ";

	Запрос.УстановитьПараметр("ТЗ",ТЗ);

       // ИТК.ОТЛ(Запрос,"ТЗ");
	РезультатЗапроса = Запрос.Выполнить();

`

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/18395787/46e644d0-59de-4b1b-b75b-523ad5985983)

**Окружение:**

  Infostart Toolkit PROF 2023.5.00

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 для Беларуси (2.4.8.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.1.434

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by AnatoliyBritko** [comment]
может это взаимосвязано, но если например текст меняю таком образом, то 

`

	ТЗ = Новый ТаблицаЗначений;
	ТЗ.Колонки.Добавить("ТипЧисло", Новый ОписаниеТипов("Число",Новый КвалификаторыЧисла(10, 0, ДопустимыйЗнак.Любой)));
	ТЗ.Колонки.Добавить("ТипСтрока", Новый ОписаниеТипов("Строка", ,Новый КвалификаторыСтроки(10, ДопустимаяДлина.Фиксированная)));
	
	НоваяСтрока = ТЗ.Добавить();
	НоваяСтрока.ТипЧисло  = 1;
	НоваяСтрока.ТипСтрока = "a";
	
	Запрос = Новый Запрос;
	Запрос.Текст = 
	"ВЫБРАТЬ
	|	Контрагенты.Ссылка КАК Ссылка
	|ИЗ
	|	Справочник.Контрагенты КАК Контрагенты
	|ГДЕ
	|	Контрагенты.ИНН В(&ТЗ)";

	Запрос.УстановитьПараметр("ТЗ",ТЗ);
	Выполнить(" ИТК.ОТЛ(Запрос,""ТЗ"")");
	РезультатЗапроса = Запрос.Выполнить();

`

то в консоль запрос импортируется без ошибок, но в параметрах 

![image](https://github.com/infostart-hub/toolkit/assets/18395787/bd59ac04-034e-4b62-a4c4-2e786a1ad431)

**Comment by AnatoliyBritko** [comment]
еще дополнение
в коде в запрос передается непустой массив, при импорте в ИТК в параметрах Результат = Неопределено;

![image](https://github.com/infostart-hub/toolkit/assets/18395787/d08a7c01-a064-43c0-a66f-f480608d9c11)


![image](https://github.com/infostart-hub/toolkit/assets/18395787/c464006e-b96c-4d23-a422-cd0553703eb6)

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.2
