### ISSUE TITLE
Слишком строгие требованию к путям данных полей СКД

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#854]
**Описание ошибки**
Новый конструктор СКД предъявляет слишком строгие требования для путей к данным, в частности для вычисляемых полей. Сейчас, как я понимаю, путь к данным должен удовлетворять требованиям, предъявляемым к именам переменных встроенного языка. Однако платформа в пути данных позволяет:
- указать точку, т.о. образовывая составной путь из группы и вложенного поля;
- указывать пробелы, дефисы и прочее, для чего путь к данным (или часть составного пути) необходимо заключить в квадратные скобки.

С другой стороны нынешний конструктор СКД позволяет указывать недопустимые имена, совпадающие с ключевыми словами (выдержка из синтакс-помощника):
- ВЫБОР (CASE)
- ЕСТЬ (IS)
- ИНАЧЕ (ELSE)
- КОГДА (WHEN)
- КОНЕЦ (END)
- НЕ (NOT)
- ПОДОБНО (LIKE)
- РАЗЛИЧНЫЕ (DISTINCT)
- СПЕЦСИМВОЛ (ESCAPE)
- ТОГДА (THEN) 

**Ожидаемое поведение, если бы ошибки не было**
Необходимо привести требования к указываемым путям к данным в конструкторе СКД к требованиям платформы.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/bc728a4b-ffef-479b-ae8f-e349e279947c)
![image](https://github.com/infostart-hub/toolkit/assets/59051827/73cd9293-5079-4461-8c91-e90e392a0a5b)
![image](https://github.com/infostart-hub/toolkit/assets/59051827/4b000de3-b54d-4e5c-a890-0f8938fb2bc5)

**Окружение:**
Infostart Toolkit PROF 2023.5.01

**Comment by Evg-lylyk** [comment]
Реализовал в 2024.2, часть перенес в другую задачу
