### ISSUE TITLE
Консоль разработчика - Ошибка при загрузке схемы СКД из файла

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#855]
**Описание ошибки**
При загрузке схемы СКД из файла XML ошибка:

Преобразование значения к типу Число не может быть выполнено
{InfostartToolkitPROF ОбщийМодуль.ИТК_Строки.Модуль(176)}:Возврат Число(Результат);
{InfostartToolkitPROF ОбщийМодуль.ИТК_СКДКлиентСервер.Модуль(45)}:НомерСтроки = ИТК_Строки.РазборПрочитатьЦелоеЧисло(ТекстОшибки, Индекс);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(4049)}:ИзменяемыеПоля.Вставить("Ошибка", ИТК_СКДКлиентСервер.ИнформацияООшибке(ТекстОшибки));
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3680)}:ПроверитьСхемуКомпоновкиДанных(ТекущиеДанные);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]

**Сценарий воспроизведения**
Консоль разработчика - Добавить - Схему компоновки данных - Еще - Загрузить схему из файла

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/2557e039-f2b2-4b2c-b208-8a07fd969998)

**Окружение:**
Infostart Toolkit PROF 2023.4.10

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.7
