### ISSUE TITLE
Некорректный hot key для некоторых инструментов.

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#858]
**Описание ошибки**
На некоторые команды назначено сочетание ctrl + C. Соотв. при попытке что-то скопировать в 1С - запускаются инструменты.

![image](https://github.com/infostart-hub/toolkit/assets/18395787/2d6f8bfa-4f64-4c87-bfbe-63afb24d7302)

**Окружение:**

Infostart Toolkit PROF 2023.5.02

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 для Беларуси (2.4.8.4)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_12
Версия БСП: 3.0.1.434

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.3
