### ISSUE TITLE
загрузка схемы из файла

### ISSUE THREAD

**Issue by Bobli7** [infostart-hub/toolkit#859]
**Описание ошибки**
что конкретно происходит
e1cib/command/Обработка.ИТК_КонсольРазработчика.Команда.КонсольСхемКомпоновкиДанных

при загрузке схемы скд из файла не загружается второй набор данных

![image](https://github.com/infostart-hub/toolkit/assets/88534816/261c4672-6068-4539-911a-70926b8b7d05)

Infostart Toolkit CORP 2023.5.03

Платформа: 8.3.20.2184 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6 (6.0.39.08)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: 2.3.5.9

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19042))
Язык: ru
Режим запуска: Управляемое приложение

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть '...'
2. Нажать '....'
3. Запустить '....'
4. Где ошибка

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

   - Платформа 1С: *
   - Имя конфигурации: *
   - Язык: *
   - Операционная система: *
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Не совсем понимаю какой по описанному контексту ко мне вопрос

Видимо такая логика что СКД считает что можно удалить второй набор, анализ показывает особенности внутренней работы СКД.

**Comment by Evg-lylyk** [comment]
Может легче будет в телеграм https://t.me/EvgLylyk

**Comment by Bobli7** [comment]
второй набор используется для вывода второго варианта одного отчета, но в ИР его отладить не получится

**Comment by Evg-lylyk** [comment]
Так что не так я не понимаю

**Comment by Bobli7** [comment]
как отлаживать второй набор данных в ИР?

**Comment by Evg-lylyk** [comment]
Там многое нужно рассказать здесь сложно, не готов объяснять давай те созвонимся в Телеграм, писал выше

**Comment by Bobli7** [comment]
ок, в какое время в Телеграмм удобен созвон?

**Comment by Evg-lylyk** [comment]
Вопрос не касается инструментов

**Comment by Evg-lylyk** [comment]
Чтобы получить настройки по варианту, нужно затянуть их из отладки
https://infostart.ru/1c/articles/1321263/
Либо задать вручную

**Comment by Evg-lylyk** [comment]
Это говорит человек который ни разу не открывал консоль СКД и не запоминает как называются инструменты которыми он пользуется. Рекомендую использовать другое и лучше разобраться потом вернутся и попробовать понять описанные проблемы.

**Comment by Evg-lylyk** [comment]
Удачи, какие то моменты когда нить доработаю. У меня задача которая бы вам помогла есть в очереди только до нее пока дело не дошло еще 175 на очереди. Вам нужно учится работать с тем что есть.

**Comment by Bobli7** [comment]
вопрос исчерпан)
