### ISSUE TITLE
Отображение доп сведений в списке пользователей в отчете анализа прав

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#865]
**Существует проблема**
При наличии нескольких пользователей с одинаковым именем и фамилией, не понятно, кого выбирать из списка

![image](https://github.com/infostart-hub/toolkit/assets/65346358/a835c67c-064d-4086-b2c7-13cd6751a3c6)

**Хотелось бы иметь следующую функциональность**
Выводить доп данные по пользователю, как минимум- имя пользователя для входа

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.1 Пока добавил Полное имя, Имя, Уникальный идентификатор
По умолчанию отключены: Имя, Уникальный идентификатор
В будущем легко можно будет расширить набор полей
