### ISSUE TITLE
При нажатии комбинации копирования открывается консоль СКД

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#868]
**Описание ошибки**
Пытаюсь скопировать ячейку Ctrl-C. Вместо этого открывается консоль разработчика со схемой компоновки данных

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/d246bfbb-c156-4c4f-8459-6c37889d5455)

**Окружение:**
Infostart Toolkit PROF 2023.5.04

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.5 (вчера выложил на Инфорстарт)

**Comment by Serg2000Mr** [comment]
Ок, обновился
