### ISSUE TITLE
Отчет по правам отображает права, недоступные пользователю 

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#869]
**Описание ошибки**
В отчет попадают права, которые не доступны пользователю
![image](https://github.com/infostart-hub/toolkit/assets/65346358/89e6939e-a464-44c1-9788-065d88fbe1fe)
![image](https://github.com/infostart-hub/toolkit/assets/65346358/f1d4b423-4359-4a50-a5f4-aeccbcbc7237)
![image](https://github.com/infostart-hub/toolkit/assets/65346358/863fc657-5a9f-4fd5-91e8-21204c983058)
![image](https://github.com/infostart-hub/toolkit/assets/65346358/bbc30f88-aa03-4ef4-b370-7fdbabbb8b1c)

**Окружение:**
Infostart Toolkit PROF 2023.5.03

Платформа: 8.3.21.1622 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:WMS Логистика. Управление складом, ред. 5.0 (5.0.2.2)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_14
Версия БСП: 3.1.3.523

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправил в 2023.5.6
