### ISSUE TITLE
Консоль запросов ошибка при выполнении вложенного запроса

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#870]
**Описание ошибки**
При выполнении запроса из пакетного запроса, ошибка

`Поле объекта не обнаружено (Тип)
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3588)}:ТребуетсяОбновлениеРезультатаВыполнения = (ТекущиеДанные.Тип = ИТК_Перечисления.ЭлементДанныхКод());
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(625)}:ВыполнитьОбработкуОповещения(ОповещениеОЗавершении, Результат);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(617)}:ОповеститьОЗавершенииДлительнойОперации(ДлительнаяОперация.ОповещениеОЗавершении,
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(555)}:ЗавершитьДлительнуюОперацию(ДлительнаяОперация, Результат);
{ОбщийМодуль.ДлительныеОперацииКлиент.Модуль(69)}:ОбработатьРезультатАктивнойОперации(РасширенныеПараметры, ДлительнаяОперация);
{(1)}:Модуль.ОжидатьЗавершение(Параметры[0],Параметры[1],Параметры[2])
{InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(135)}:Выполнить(Выражение);
{InfostartToolkitPROF ОбщийМодуль.ИТК_БСПКлиентСервер.Модуль(20)}:ВыполнитьМетод(ПолноеИмя, Параметры);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ДлительныеОперацииКлиент.Модуль(200)}:ИТК_БСПКлиентСервер.ВыполнитьПроцедуру("ДлительныеОперацииКлиент.ОжидатьЗавершение", ПараметрыПроцедуры);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3489)}:ИТК_ДлительныеОперацииКлиент.ОжидатьЗавершение(ДлительнаяОперация, ОповещениеОЗавершенииВыполнения(Строка), ПараметрыОжидания);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(6941)}:ВыполнитьОперациюЧерезДлительныеОперации(ОбрабатываемаяСтрока, НаименованиеОперации, Режим, ИгнорироватьЛимитСтрок);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3965)}:ВыполнитьОбработкуОповещения(ОписаниеОбработчика);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(3430)}:ЗапуститьОбработчикСПроверкойНаВозможностьВыполнения(ОписаниеОбработчика, НаименованиеОперации, ОбрабатываемаяСтрока);
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(1411)}:ВыполнитьОперацию("Выполнение");

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]`

Пакет захвачен из отладчика

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/ca635152-e317-4ae3-b2a0-5020808d32f1)

**Окружение:**
Infostart Toolkit PROF 2023.5.05

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Думаю таже ошибка #863
