### ISSUE TITLE
Функция Итк.МВТ искажает имена временных таблиц

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#875]
**Описание ошибки**
Функция Итк.МВТ(МенеджерВременныхТаблиц) искажает имена временных таблиц, добавляя к ним _число

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/174a545c-7d96-4562-afd8-a4fab3a2a45b)

**Окружение:**
Infostart Toolkit PROF 2023.5.06

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Это количество строк, есть неудобства, но пока это наиболее читаемых вариант

**Comment by Serg2000Mr** [comment]
Может быть сделать не в виде структуры, а в виде таблицы значений? Тогда можно будет отсортировать по алфавиту, т.к. таблиц бывает много.
