### ISSUE TITLE
Консоль СКД - не выполняются верхние запросы пакета

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#886]
**Описание ошибки**
При выполнении запроса пакета в дереве запроса выводится ошибка, что временная таблица не найдена. При этом временная таблица создается в подзапросе выше.

**Сценарий воспроизведения**
Открыть консоль СКД
Загрузить схему из XML
Открыть анализ исполняемых запросов
Выбрать набор данных - анализировать запрос
Выбрать подзапрос пакета, использующий временную таблицу из пакета - Выполнить
Получаем ошибку, что временного запроса нет. Возможно не выполняются ветки выше перед выполнением текущей.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/5ed83d85-3117-4bdf-999b-c6ca99c58202)

**Окружение:**
Infostart Toolkit PROF 2023.5.06

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Толстый клиент (управляемое приложение)
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Скинь пожалуйста текст запроса

**Comment by Evg-lylyk** [comment]
Столкнешься пиши, я постараюсь оперативнее разобраться
