### ISSUE TITLE
Дать больше информации об ошибке в консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#887]
**Существует проблема**
При возникновении исключения во время выполнения кода в консоли по скудному описанию ошибки бывает непонятна первопричина этой ошибки. Подозреваю, что под полем ввода кода выводится лишь краткая информация об ошибке, тогда как нередко бывает нужна именно первопричина - значение поля "Причина" объекта типа "ИнформацияОбОшибке.

Демонстрационный пример проблемы. Введем в консоль кода следующий текст:
```
Запрос = Новый Запрос;
Запрос.Текст = "Выбрать 1/0 как Поле";
Запрос.Выполнить();

```
Выполнение этого кода завершиться ошибкой. Информация об ошибке в виде гиперссылки под полем ввода гласит:

> {3} Ошибка выполнения запроса

Этой информации явно недостаточно, чтобы понять, в чем именно заключается ошибка, что именно необходимо исправить в запросе.

**Хотелось бы иметь следующую функциональность**
Было бы здорово иметь доступ и к причине возникшей ошибки. Например, в случае, если в перехваченной Инструментами разработчика ИнформацииОбОшибке() поле "Причина" заполнено, выводить под листингом кода помимо краткого описания ошибки еще и гиперссылку "Подробнее", по нажатию на которую появится информация уже о первопричине.

![image](https://github.com/infostart-hub/toolkit/assets/59051827/2b791dd7-fdd3-4643-b90f-068c25977a97)

**Дополнительный контекст**
Infostart Toolkit PROF 2023.5.06

**Comment by Serg2000Mr** [comment]
Вещь нужная, но есть и временный вариант решения:
https://infostart.ru/1c/articles/982008/

**Comment by Evg-lylyk** [comment]
Доработано в 2024.4
