### ISSUE TITLE
Просмотр многострочного текста в переменных консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#888]
**Существует проблема**
Если в результате выполнения некоего кода в консоли была зафиксирована переменная, содержащая многострочный текст, то этот текст нет возможности удобно посмотреть в списке переменных консоли кода.

Существуют следующие способы обхода:
- навести курсор на значение переменной и попытаться разглядеть текст во всплывающей подсказке;
- скопировать текст из таблицы и вставить его в блокнот, где уже и изучать.

![image](https://github.com/infostart-hub/toolkit/assets/59051827/75bcdf26-f4da-4b76-bf3d-cd88d91bada2)

**Хотелось бы иметь следующую функциональность**
Нужна возможность просмотреть большой текст в отдельном окне непосредственно в консоли кода.

**Дополнительный контекст**
Infostart Toolkit PROF 2023.5.06

**Comment by d-hurricane** [comment]
Попытался глянуть многострочный текст через сообщения, но там ровно та же проблема. Кажется, что в объединенной консоли разработчика была возможность открыть сообщение пользователю двойным кликом мыши. Мне кажется, что в самостоятельной консоли кода эта же фичи была бы полезна, в том или ином виде.

**Comment by Evg-lylyk** [comment]
Проблема решена в 2024.1.1 и в переменных и в сообщениях
