### ISSUE TITLE
Консоль запросов - Обработка результата - Не связаны контексты Перед, Основной и После

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#890]
**Описание ошибки**
В консоли запросов при обработке результата окна Перед, Основной и После не знают о переменных друг друга

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/aa561c81-c412-41df-905e-b23a7e4aca1f)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/5d5e4842-7ae4-4aed-a760-238859834ee7)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/a9cb3101-4c15-4924-a154-2a87386f316a)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/990c5298-b687-4bbe-bdd9-c217f7d10fbc)

**Окружение:**
Infostart Toolkit PROF 2023.5.07

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Толстый клиент (управляемое приложение)
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Это так всегда и было есть ДополнительныеСвойства они передаются

**Comment by Serg2000Mr** [comment]
Интуитивно ожидается единый контекст.
И из справки это тоже непонятно
![image](https://github.com/infostart-hub/toolkit/assets/129394542/c4ef5375-4f69-4c93-9024-7534f8bc3cc7)
Тем более, что ДополнительныеСвойства есть и у объектов БД

**Comment by Evg-lylyk** [comment]
Согласен, но пока так. Могу записать пожелание
