### ISSUE TITLE
Добавить инструмент Регистрация изменений на узлах

### ISSUE THREAD

**Issue by dronicbest** [infostart-hub/toolkit#891]
**Существует проблема**
В инструментах разработчика Старых, есть очень классный функционал: Регистрация изменений на узлах.
Совсем не давно работал с базой данных, подключенной через Web.
Нужно было зарегистрировать в плане обмена много данных по определенному отбору (В идеале можно еще и с помощью запроса).
Очень не хватило данной функциональности.

**Хотелось бы иметь следующую функциональность**
Примерно так это выглядит у Старых
![Снимок экрана 2024-01-19 122045](https://github.com/infostart-hub/toolkit/assets/6423688/c6952419-f51a-465a-9db4-2e29d275cdd7)
Возможность регистрирования изменений на узле подбором из формы списка (С настраиваемым отбором).
Возможность регистрирования изменений на узле при помощи запроса, и из консоли запроса (Добавить там пункт)
![Консоль](https://github.com/infostart-hub/toolkit/assets/6423688/2f3242b3-d984-489c-87b2-7fbbd152912c)

**Дополнительный контекст**
Infostart Toolkit PROF 2023.5.07

**Comment by Evg-lylyk** [comment]
Приветствую, спс. Принято в последующем мажорном релизе займусь этим

**Comment by Evg-lylyk** [comment]
Ссылки по теме:
https://infostart.ru/1c/tools/1343897/
https://its.1c.ru/db/metod8dev/content/5013/hdoc

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.4
