### ISSUE TITLE
Выполнение произвольного алгоритма для выделенного объекта

### ISSUE THREAD

**Issue by mrChOP93** [infostart-hub/toolkit#892]
**Существует проблема**
Иногда нужно выполнить произвольный алгоритм для объектов.

Например, нужно вызвать команду синхронизации для ряда серий номенклатур, которые не выгрузились в другую базу, из тч документа. Делать для этого отдельный запрос с обращением по веб сервису в другую базу- куда накладнее, нежели глазами сравнить документы.

**Хотелось бы иметь следующую функциональность**
Хотелось бы иметь возможность вызвать произвольный код для выделенного объекта через alt+t, по аналогии вызова того же редактора объекта. Так же, в меню должен быть выбор алгоритма с последующим сохранением выбора.

**Comment by Evg-lylyk** [comment]
Давно ведь есть команда глобального меню "Обработать в консоли кода"
Подходит?

**Comment by mrChOP93** [comment]
Блин, когда обсуждали в чате данную проблему, пришли к выводу, что она не совсем подходит, но почему, уже не вспомню)

**Comment by Evg-lylyk** [comment]
> Блин, когда обсуждали в чате данную проблему, пришли к выводу, что она не совсем подходит, но почему, уже не вспомню)

В телеграмме обсуждали!? Какой у тебя там адрес

**Comment by Evg-lylyk** [comment]
Будет реализовываться в задаче #1007
