### ISSUE TITLE
Текст запроса в коде из файла *.mcr

### ISSUE THREAD

**Issue by nick-ez** [infostart-hub/toolkit#894]
**Хотелось бы иметь следующую функциональность**
Чтоб не копировать туда сюда текст запроса, хотелось бы в коде получать текста запроса из файла *.mcr консоли запросов какой нибудь экспортной функцией.
Может быть оно и есть. 

Вариант реализации  
Запрос.Текст = ИТК.ТекстЗапроса(ПутьИмяФайла, "Передставление")

**Comment by Evg-lylyk** [comment]
Приветствую, не понимаю зачем это, какой сценарий?

**Comment by nick-ez** [comment]
Когда на этапе разработки/отладки вносятся изменения в запрос, чтоб его не копировать в код а получать не посредственно из сохраненного файла консоли,  а потом уже заменять на текст запроса.

**Comment by Evg-lylyk** [comment]
> Когда на этапе разработки/отладки вносятся изменения в запрос, чтоб его не копировать в код а получать не посредственно из сохраненного файла консоли, а потом уже заменять на текст запроса.

Не понимаю, зачем? Можем переговорить в телеграме https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
Разобрались
