### ISSUE TITLE
В консоли запросов в параметрах не все планы запросов

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#896]
**Описание ошибки**
В консоли запросов в параметрах при попытке назначить параметру узел плана обмена выводятся не все 
планы обмена.

**Сценарий воспроизведения**
Открыть консоль запросов. Создать запрос к изменениям объекта метаданных. В отборе указать ОбъектМетаданныхИзменения.Узел = &Узел.

На закладке Параметры попытаться установить узел нужного плана обмена. Вместо полного списка планов выводится только малая часть. Права доступа Полные, в конструкторе запросов в дереве остальные планы обмена видны.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/e53277da-2ffa-4f71-a519-4b4783e049c2)

**Окружение:**
Infostart Toolkit PROF 2023.5.07

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
А может быть там что не во всех планах изменения этого объекта регистрируются?

**Comment by Serg2000Mr** [comment]
Да, похоже на то. Мой косяк.
