### ISSUE TITLE
Ошибка при копировании в буфер обмена

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#897]
**Описание ошибки**
В консоли запросов в конструкторе строки отладки при нажатии на кнопку "Копировать и закрыть" - ошибка

Ошибка при получении значения атрибута контекста (clipboardData)
{InfostartToolkitPROF ОбщийМодуль.ИТК_БуферОбменаКлиент.Модуль(42)}:Возврат htmlfile.ParentWindow.ClipboardData.Getdata("Text");
{InfostartToolkitPROF ОбщийМодуль.ИТК_БуферОбменаКлиент.Модуль(15)}:Если Текст = Текст() Тогда
{InfostartToolkitPROF Обработка.ИТК_КонструкторСтрокиОтладки.Форма.Основная.Форма(147)}:ИТК_БуферОбменаКлиент.Копировать(Результат);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка]
по причине:
Произошла исключительная ситуация: Ошибка при вызове OpenClipboard

[ОшибкаИспользованияВстроенногоЯзыка]

То же самое и в окне О программе" по кнопке Копировать

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/3bde2234-4264-4186-8a4c-9e1aad534b47)

**Окружение:**
Infostart Toolkit PROF 2023.5.07

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
![image](https://github.com/infostart-hub/toolkit/assets/48444742/0618681d-1231-4198-9d9a-e62dad90d0b4)
можешь скорректировать код и проверить работает ли у тебя второй вариант

**Comment by Serg2000Mr** [comment]
Наверное, не получится. Не знаю, что был за глюк, но кнопка Копировать в О программе опять работает нормально. Если опять повторится, то попробую.
