### ISSUE TITLE
Поддержка процедур и функций в консоли кода

### ISSUE THREAD

**Issue by Evg-lylyk** [infostart-hub/toolkit#902]
Исполнение в консоли кода процедур и функций с указанием контекста
Подобный функционал есть в Универсальных инструментах, изучить тему

**Comment by nick-ez** [comment]
Также там можно, помимо основной конфигурации, добавить xml и расширений, для контекстной подсказки. У Вас по мойму сейчас так нельзя. Хотелось бы иметь такую возможность.

**Comment by Evg-lylyk** [comment]
> Также там можно, помимо основной конфигурации, добавить xml и расширений, для контекстной подсказки. У Вас по мойму сейчас так нельзя. Хотелось бы иметь такую возможность.

Не понимаю о чем речь... какой xml?

**Comment by nick-ez** [comment]
Разобрался, прошелся отладчиком, надо положить папку с выгруженными файлами расширения, в папку "EXTENSIONS", спасибо.

**Comment by nick-ez** [comment]
> Не понимаю о чем речь... какой xml?

Извиняюсь за путаницу, в ЕДТ так называется, вот я так и написал (
![image](https://github.com/infostart-hub/toolkit/assets/91209214/91704399-6bfa-4c0a-829e-207277dec612)
