### ISSUE TITLE
Консоль кода: очень хочется, чтобы параметры были на виду и их можно было быстро изменять, а не в отдельной закладке (в этом случае не видно кода).

### ISSUE THREAD

**Issue by ITDevPr0** [infostart-hub/toolkit#910]
Консоль кода: очень хочется, чтобы параметры были на виду и их можно было быстро изменять, а не в отдельной закладке (в этом случае не видно кода).

Например, справа от кода.
Или внизу слева от результата выполнения.

![image](https://github.com/infostart-hub/toolkit/assets/140257571/6777eac7-e565-459b-ab20-66df5f9d33cc)

**Comment by Serg2000Mr** [comment]
И тянуться туда направо, кстати, неудобно.

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.1.1

**Comment by ITDevPr0** [comment]
Спасибо большое!
Очень ждем!)
