### ISSUE TITLE
Ошибка при выполнении команды "Заполнить" для номера строки табличной части в редакторе объекта

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#913]
**Описание ошибки**
В редакторе объекта, если при активной колонке "Номер строки" табличной части нажать на кнопку "Заполнить..", то возникнет исключение с текстом:

> Поле объекта не обнаружено (ДоступныеТипы)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ПодключаемыеКомандыКлиент.Модуль(108)}:ДопустимыеТипы = ЭлементКолонка.ДоступныеТипы;
> {InfostartToolkitPROF Обработка.ИТК_РедакторОбъекта.Форма.Форма.Форма(564)}:ИТК_ПодключаемыеКомандыКлиент.ОбработатьКомандуРаботыСТаблицейЗначений(ЭтотОбъект, Команда.Имя, Истина);

**Ожидаемое поведение, если бы ошибки не было**
Очевидно, что команда заполнения для колонки с номером строки не применима, но сообщение об ошибке стоит сделать более дружелюбным к пользователю. Ведь пользуясь инструментом впервые пользователю может быть неочевидно, что именно делает кнопка и что нужно перед ее использованием выбрать какую-то конкретную колонку.

**Окружение:**
Infostart Toolkit PROF 2023.5.07

Платформа: 8.3.21.1890 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Управление торговлей, редакция 11 (11.5.11.86)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.357

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.1
