### ISSUE TITLE
Консоль кода - странная ошибка при отмене проведения документа

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#914]
**Описание ошибки**
При выполнении кода отмены проведения документа - ошибка :

Ошибка при вызове метода контекста (ВыполнениеНаСервере)
{InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(955)}:ДлительнаяОперация = ВыполнениеНаСервере(УникальныйИдентификатор, Код, Параметры, Строка);
{InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(426)}:НачатьВыполнениеНаСервере(Данные.Текст, Данные.Параметры, Строка);

по причине:
Ошибка конфигурации.
Соединение с сервером баз данных удерживается после окончания вызова сервера 1С:Предприятия.
Возможно, не был освобожден менеджер временных таблиц.
Объект, удерживающий менеджер временных таблиц, помещен в кэш или образовал цепочку
циклических ссылок.

**Сценарий воспроизведения**
Консоль кода, выполнить код
`Док = Параметры.Док1.ПолучитьОбъект();
Док.Записать(РежимЗаписиДокумента.ОтменаПроведения);
`
Вид документа ОперацияБух
В другой консоли кода такой ошибки нет. После перезагрузки Предприятие ошибка воспроизводится.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/2ae2298e-4aea-4224-a0a4-d6cd7453fcdb)

**Окружение:**
Infostart Toolkit PROF 2023.5.08

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.4.14.181)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_16
Версия БСП: 3.1.5.385

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.2
