### ISSUE TITLE
Ошибка при добавлении внешнего источника в консоли запросов

### ISSUE THREAD

**Issue by vlhown** [infostart-hub/toolkit#915]
**Описание ошибки**
При попытке изменить имя еще не сформированного внешнего источника возникает ошибка, дальнейшего добавления внешних источников не происходит.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль запросов.
2. Перейтина вкладку Внешние источники, нажать кнопку Добавить - появится строка с внешним источником Таблица1.
3. Начать набирать на клавиатуре новое имя таблицы - появится всплывающее окно с полем ввода имени таблицы.
4. Завершить ввод имени и нажать ОК (Enter) - появится сообщение об ошибке "Значение не является значением объектного типа (Имя)", строка с внешним источником исчезнет, но в заголовке вкладки будет указано, что есть 1 запись.
5. Дальнейшие нажатия кнопки Добавить строки не добавляет, но увеличивает счетчик в заголовке вкладки.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/151819771/88a706e2-c5b6-4d1b-9f70-a7819901c3b2)
![image](https://github.com/infostart-hub/toolkit/assets/151819771/aa43072d-ccdc-400e-a7e2-11e91063cff6)

**Окружение:**
Infostart Toolkit PROF 2023.5.08

Платформа: 8.3.23.2040 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.152)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.232

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не удается воспроизвести ошибку.
Возможно поможет удалить расширение и установить заново.
