### ISSUE TITLE
Ускорить поиск во Все функции

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#916]
**Существует проблема**
Раньше "Функции для технического специалиста" открывались очень долго. Но потом, видать, разработчики платформы прочитали статью на Инфостарте https://infostart.ru/1c/tools/1617861/. И теперь открываются они быстро, но отстает обработка "Все функции". Если первый раз открыть "Все функции" и вбить что-нибудь в поиске, то на большой конфигурации типа ERP приходится ждать секунд восемь, пока поиск произведется.

**Comment by Evg-lylyk** [comment]
Согласен, поработаю над этим

**Comment by Serg2000Mr** [comment]
Быстро :)

**Comment by Serg2000Mr** [comment]
Эффективно болеть тоже надо уметь :D
