### ISSUE TITLE
Консоль запросов выдает ошибку на последнюю закомментированную строку запроса

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#917]
**Описание ошибки**
Если закомментировать последнюю строку запроса, то консоль запросов выдает ошибку

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/61e5648c-f9cd-4af8-be60-b33725c65362)

**Окружение:**
Infostart Toolkit PROF 2023.5.08

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2023.5.9, 2024.1.2
