### ISSUE TITLE
Неверное позиционирование ошибки в консоли кода при наличии пустой строки вначале листинга

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#919]
**Описание ошибки**
Если листинг кода содержит первой пустую строку, консоль кода будет неверно позиционировать курсов сообщения об ошибке в случае возникновения таковой.

**Сценарий воспроизведения**
1. Открыть консоль кода.
2. Ввести код (пустая строка вначале обязательна):
```bsl
 
А = 1;
Б = 10 / 0;
```
3. Выполнить код.
4. Убедиться, что мигающий красным цветом курсор будет спозиционирован на строке "А", а не на строке "Б", содержащей реальное место возникновения ошибки.

**Ожидаемое поведение, если бы ошибки не было**
Курсор должен быть спозиционирован на строке "Б", т.к. именно там возникла ошибка деления на ноль.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/b6f9f246-96cb-48bb-9635-ce9c7825f9f4)

**Окружение:**
Infostart Toolkit PROF 2024.1.00

Платформа: 8.3.21.1890 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Управление торговлей, редакция 11 (11.5.11.86)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.357

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22621))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.3
