### ISSUE TITLE
Консоль по умолчанию открывается на странице "Прочее", а не "Текст", как хотелось бы

### ISSUE THREAD

**Issue by kuntashov** [infostart-hub/toolkit#92]
Открываю консоль разработчика и она почему-то по умолчанию открывается на странице "Прочие".
Ожидал, что откроется на странице "Текст", т.к. это основная рабочая область для меня.

Возможно, я не типичный пользователь, но для меня основной сценарий работы с консолью:
- открыть для отладки запроса
- отладить запрос
- закрыть без сохранения запроса
- иногда во время разработки требуется возможность сохранить состояние редактируемого в консоли запроса между сеансами перезапуска конфигурации

Т.е. я не храню долгосрочно запросы средствами УИР/ИР/какой-либо другой консоли.

Версия консоли: 1.3.1

**Comment by Evg-lylyk** [comment]
Согласен, исправлено в 1.4
