### ISSUE TITLE
Вставка точки маршрута в запрос через команду Вставка предопределенного...

### ISSUE THREAD

**Issue by L0z4** [infostart-hub/toolkit#920]
**Описание ошибки**
В консоли запросов команда км "Вставка предопределенного" не позволяет вставить значение точки маршрута бизнес-процесса

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открываем диалог "Вставка предопределенного в текст запроса"
2. Выбираем Тип объекта "ТочкаМаршрутаБизнесПроцесса" и нужный биз.процесс в поле "Имя Объекта"
3. Поле "Имя предопределенного" остается не активным для ввода, списка точек маршрута нет. 

**Ожидаемое поведение, если бы ошибки не было**
Ожидаю поведение поля "Имя предопределенного" аналогичное полю "Ссылка" в диалоге "Вставка ссылки на объект" в консоли кода.

**Скриншоты**
![1cv8c_5Fv97gF1vv](https://github.com/infostart-hub/toolkit/assets/17232472/670a3569-5162-44aa-8c8e-366862620f2f)

**Окружение:**

   - Платформа 1С: 8.3.23.1912
   - Имя конфигурации: Infostart Toolkit CORP 2023.5.09
   - Язык: RU
   - Операционная система: Windows 11

**Comment by Evg-lylyk** [comment]
Спс за информации. Исправлено в 2023.5.10
