### ISSUE TITLE
Просмотр/редактирование/сохранение данных формы

### ISSUE THREAD

**Issue by maxis33** [infostart-hub/toolkit#921]
**Существует проблема**
В любой открытой управляемой форме есть реквизиты, которые как-то заполняются, но посмотреть чем они заполнены без конфигуратора почти нельзя. Это как реквизиты "объекта", так и дополнительные реквизиты формы.
А иногда объект не записывается по какой-то причине, и все данные формы (внесенные строки и др) теряются из за невозможности записать документ/справочник..

**Хотелось бы иметь следующую функциональность**
Получить аналог "Редактор объекта" для любой открытой формы.
 * Просмотр/редактирование реквизитов
 * Сохранение в любой форме (XML или другой).
**Дополнительный контекст**
-

**Comment by maxis33** [comment]
Нашел похожее пожелание...
https://github.com/infostart-hub/toolkit/issues/686

**Comment by Evg-lylyk** [comment]
Да в планах, можно ждать в последующей мажорной версии
