### ISSUE TITLE
Поиск и замена в блоке в консоли запросов

### ISSUE THREAD

**Issue by vlhown** [infostart-hub/toolkit#932]
**Существует проблема**
В консоли запросов отсутствует опция поиска и замены всех вхождений внутри блока.

**Дополнительный контекст**
Часто, например, когда формируется объединение запросов, удобно копипастнуть несколько раз первый запрос объединения, а потом контекстной заменой поменять нужные фрагменты текста. Но для этого нужна контекстная замена внутри блока.

**Comment by Evg-lylyk** [comment]
Что это такое? Нужны разъяснения

**Comment by Evg-lylyk** [comment]
![image_2024-03-16_13-59-56](https://github.com/infostart-hub/toolkit/assets/48444742/627e2031-c6d6-4f1d-84ea-5f6a684fe97c)
