### ISSUE TITLE
Консоль кода не выводится колонка Значение

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#933]
**Описание ошибки**
В консоли кода при пустом значении результата не выводится колонка Значение. Это сбивает с толку.
Кроме того, в колонке тип выводится только псевдоним типа, по которому бывает сложно определить сам тип, особенно
для значений ПВХ.

**Скриншоты**
![Консоль кода](https://github.com/infostart-hub/toolkit/assets/129394542/9cefaea2-bb42-4a7b-9ea7-0ef1badb6d4e)

**Окружение:**
Infostart Toolkit PROF 2024.1.03

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.2, и добавил картинку типа
