### ISSUE TITLE
Консоль регламентных и фоновых заданий - обновляется список регламентных заданий при каждом действии.

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#934]
**Существует проблема**
В файловой базе мне понадобилось отключить все регламентные задания. Через консоль это оказалось делать очень долго.
После снятия пометки активности регламентного задания зачем-то происходит обновление всего списка регламентных заданий.

![Консоль регламентных](https://github.com/infostart-hub/toolkit/assets/129394542/eb5993f7-3666-4b74-b532-94f736328495)

При переключении закладки Фоновые - Регламентные тоже длительное обновление.

**Comment by Evg-lylyk** [comment]
![image](https://github.com/infostart-hub/toolkit/assets/48444742/1d62a671-e3c4-4496-bb3a-921dc6919d95)
У меня подобного не происходит, база файловая, 1С:Предприятие 8.3 (8.3.21.1775)
