### ISSUE TITLE
В Редакторе объектов у родителя нельзя выбрать группу

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#935]
![image](https://github.com/infostart-hub/toolkit/assets/129394542/6fda5d21-faea-4ffb-b339-6c19f7c84a19)

**Окружение:**
Infostart Toolkit PROF 2024.1.03

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
У меня на разных справочниках выбирается (через кнопку выбрать).
Возможно какой-то внутренний код мешает можно попробовать через Универсальную форму выбора

**Comment by Serg2000Mr** [comment]
Я проверил на типовой ERP в справочнике "Дополнительные отчеты и обработки" - та же самая ошибка.

**Comment by Evg-lylyk** [comment]
> Я проверил на типовой ERP в справочнике "Дополнительные отчеты и обработки" - та же самая ошибка.

Через универсальную форму выбора все получилось
С другими справочниками есть проблема именно в ЕРП, разбираюсь

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.4
