### ISSUE TITLE
Ошибки преобразования типов при загрузке из табличного документа во внешнюю таблицу консоли запросов

### ISSUE THREAD

**Issue by vlhown** [infostart-hub/toolkit#936]
1. Теряется время при преобразовании строки в дату в формате "дата и время".
![image](https://github.com/infostart-hub/toolkit/assets/151819771/f61f5af1-cea4-4d00-86a4-b0843f968bf4)
![image](https://github.com/infostart-hub/toolkit/assets/151819771/c5954da8-05c4-42a7-9775-5a2433d3db19)
![image](https://github.com/infostart-hub/toolkit/assets/151819771/5e2a9565-330c-4489-8455-7c0d2aa15a54)

2. При указании типа строка с фиксированной длиной все равно получается неограниченная строка и при сравнении приходится использовать конструкцию ВЫРАЗИТЬ(<поле> КАК СТРОКА(<длина>))

Infostart Toolkit PROF 2024.1.03

Платформа: 8.3.22.2106 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом КОРП, редакция 3.1 (3.1.27.152)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.232

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by vlhown** [comment]
Сорри, в пункте 2 - не фиксированная, а переменная длина.

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.5
