### ISSUE TITLE
Ошибка в консоли разработчика

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#938]
**Описание ошибки**
В дереве консоли при наличии запроса и схемы СКД при активизации схемы ошибка

Поле объекта не обнаружено (ЗначенияПараметров)
{InfostartToolkitPROF ОбщийМодуль.ИТК_КонсольРазработчикаДанныеКлиент.Модуль(89)}:Результат = Данные.ЗначенияПараметров[Имя];
{InfostartToolkitPROF Обработка.ИТК_КонсольРазработчика.Форма.Основная.Форма(760)}:ЗначениеПараметра = ИТК_КонсольРазработчикаДанныеКлиент.ЗначениеПараметраЗапроса(ТекущиеДанные, СтрокаПараметр.Имя, СтрокаПараметр.ТипЗначения);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]

**Сценарий воспроизведения**
Открыть консоль разработчика
Добавить запрос  Выбрать &Парам
Заполнить значение параметра
Добавить схему СКД
Переключаться в дереве с запроса на схему

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/4249b7d4-b43b-4493-bc18-12614bca5d41)

**Окружение:**
Infostart Toolkit PROF 2024.1.04

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Толстый клиент (управляемое приложение)
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Попробовал, не удалось воспроизвести на 2024.1.4

**Comment by Serg2000Mr** [comment]
Вот пруф:
![Ошибка консоли](https://github.com/infostart-hub/toolkit/assets/129394542/a57140e2-0fe6-4210-94c5-f915582df71e)

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.5
