### ISSUE TITLE
Приложение падает при наличии циклических ссылок в результате выполнения кода в консоли

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#939]
**Описание ошибки**
Если в результате выполнения кода в консоли на выходе получаются переменные, содержащие циклические ссылки, то завершается такое выполнение аварийным завершением работы приложения 1С.

**Сценарий воспроизведения**
Ввести в консоли кода следующий текст и нажать "Выполнить":
```bsl
ф = Новый Структура;
ф.Вставить("ф", ф);
```
Убедиться, что приложение упало.

**Ожидаемое поведение, если бы ошибки не было**
Приложение не должно падать. В идеале предупреждать пользователя, что результат вычислений содержит циклические ссылки. На помощь здесь может прийти метод глобального контекста `ПроверитьЦиклическиеСсылкиВстроенногоЯзыка`.

**Окружение:**
Infostart Toolkit PROF 2024.1.00

Платформа: 8.3.21.1895 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Управление торговлей, редакция 11 (11.5.11.86)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_17
Версия БСП: 3.1.7.357

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Почитал про ПроверитьЦиклическиеСсылкиВстроенногоЯзыка
Не знаю чем это поможет? Код до выполнения я передать не могу. 
Этот метод видимо нужен чтобы разбираться с проблемами.
