### ISSUE TITLE
Копирование в буфер текста ошибки

### ISSUE THREAD

**Issue by irtk** [infostart-hub/toolkit#940]
**Описание ошибки**
При попытке копирования в буфер обмена информации "О программе" возникает ошибка
Ошибка при получении значения атрибута контекста (clipboardData)
{InfostartToolkitPROF ОбщийМодуль.ИТК_БуферОбменаКлиент.Модуль(42)}:Возврат htmlfile.ParentWindow.ClipboardData.Getdata("Text");
{InfostartToolkitPROF ОбщийМодуль.ИТК_БуферОбменаКлиент.Модуль(15)}:Если Текст = Текст() Тогда
{InfostartToolkitPROF ОбщаяФорма.ИТК_ОПрограмме.Форма(46)}:ИТК_БуферОбменаКлиент.Копировать(ИнформацияДляТехническойПоддержки);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка]
по причине:
Произошла исключительная ситуация: Ошибка при вызове OpenClipboard

[ОшибкаИспользованияВстроенногоЯзыка]

**Окружение:**
Infostart Toolkit PROF 2024.1.05

Платформа: 8.3.24.1342 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Разведка (0.0.6)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 14393))
Язык: ru
Режим запуска: Управляемое приложение
<!-- **Дополнительный контекст**

- не типовая конфигурация 
- без БСП
- Включен ли режим защиты от опасных действий
- защита от опасных действий отключена

**Comment by Evg-lylyk** [comment]
Можем вместе посмотреть как решать эту проблему?
Напишите мне в Телеграм https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
С версий 2024.2 добавил попытку и поддержку копирование в буфер через методы платформы 8.3.24
