### ISSUE TITLE
В форме регламентных заданий добавить длительность

### ISSUE THREAD

**Issue by irtk** [infostart-hub/toolkit#941]
**Существует проблема**
Сейчас при запуске фонового задания из формы Обработка.ИТК_РегламентныеИФоновыеЗадания.Форма.Форма есть колонка "Длительность" Но она показывает длительность только для завершенных заданий/ Если задание в процессе выполнения, длительность не будет заполняться… 

**Хотелось бы иметь следующую функциональность**
Удобно было бы, если бы, когда задание в процессе, длительность показывалась бы от старта задания до текущего момента, а когда выполнено - то длительность выполнения. Так не надо в уме вычислять, а сколько же оно работает, если еще не закончилось.

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.2
