### ISSUE TITLE
Переименование регламентных заданий

### ISSUE THREAD

**Issue by irtk** [infostart-hub/toolkit#942]
**Описание ошибки**
В Форме Обработка.ИТК_РегламентныеИФоновыеЗадания.Форма.Форма показываются регламентные задания. Если после того, как задание запущено, переименовать его в конфигураторе, то в режиме предприятия оно останется прежним.

**Ожидаемое поведение, если бы ошибки не было**
Хотелось бы, чтобы если задание переименовывается в конфигураторе, то оно переименовывалось бы и в предприятии сразу, или была бы возможность обновить названия регламентных заданий принудительно…

**Comment by Evg-lylyk** [comment]
Поля Наименование объекта Регламентное задание не меняется после изменений в конфигураторе.
Типовая обработка работает также. При желании можно зайти и заменить вручную. Это не частая операция.
Я могу справа от наименования добавить кнопку обновить если Наименование поменялось, так подойдет?
