### ISSUE TITLE
Отсутствие права "Администрирование расширений конфигурации"

### ISSUE THREAD

**Issue by aleksandrivan0v** [infostart-hub/toolkit#945]
**Описание ошибки**
Если у пользователя отсутствует право "Администрирование расширений конфигурации", то при открытии Консоли запросов возникает ошибка "Нарушение прав доступа!".

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть 'Консоль запросов'
2. Где ошибка: 
1) в общем модуле ИТК_Туллкит: функция Версия()
2) аналогичная ошибка  в общем модуле ИТК_Метаданные: функция ИспользуютсяРасширения()

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/144006419/a717aafe-7424-4ca3-b6ac-c7feb2f1315b)
![image](https://github.com/infostart-hub/toolkit/assets/144006419/6168155f-4a20-4c96-87ae-d09a3c500c37)
![image](https://github.com/infostart-hub/toolkit/assets/144006419/af6184a1-04d6-4164-9013-c2e5eff177b9)
![image](https://github.com/infostart-hub/toolkit/assets/144006419/eca5fa7e-1450-4249-8234-2c482605d90e)

**Окружение:**
Infostart Toolkit CORP 2023.5.08

Платформа: 8.3.23.2040 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Бухгалтерия предприятия КОРП, редакция 3.0 (3.0.147.30/3.1.58.11)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.209

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение
   
**Дополнительный контекст**
Предлагаю добавить установку привилегированного режима перед обращением к менеджеру расширений конфигурации (как реализовано в БСП).

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.1.6, 2024.2
