### ISSUE TITLE
При нажатии Ctrl+C происходит вызов Консоли разработчика (СКД)

### ISSUE THREAD

**Issue by Mikha197** [infostart-hub/toolkit#950]
**Описание ошибки**
При нажатии Ctrl+C происходит вызов Консоли разработчика (СКД)

**Сценарий воспроизведения**
Скопирование в буфер нажатием Ctrl+C

**Окружение:**

   - Платформа 1С: *
   КА2.5.12
   - Язык: *
Русский   
- Операционная система: *
 Windows  
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

<!-- **Дополнительный контекст**
Типовая

**Comment by Evg-lylyk** [comment]
Приветствую, обновится до актуальной версии
