### ISSUE TITLE
Поиск по наименованию выдает неполные результаты

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#953]
**Описание ошибки**
В окне Все функции (Toolkit) при поиске по "номенклатур" происходит неполная выдача соответствий.

**Сценарий воспроизведения**
![Неполный поиск](https://github.com/infostart-hub/toolkit/assets/129394542/72f9bd2f-f256-4551-ad72-269a00417ab1)

**Окружение:**
Infostart Toolkit PROF 2024.1.05

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Не ищет более 50, нужно уточнить запрос, где-то вывожу пояснение здесь его нет

**Comment by Serg2000Mr** [comment]
Где можно отключить это ограничение?

**Comment by Evg-lylyk** [comment]
Оно защито в коде

**Comment by Serg2000Mr** [comment]
Его можно будет убрать в будущих релизах?

**Comment by Evg-lylyk** [comment]
Зачем? Так задумано. Представь в запросе будет "а" В результате будет 1000 объектов зачем их выводить.

**Comment by Serg2000Mr** [comment]
Да, это ожидаемый и интуитивно понятный результат. В большинстве реализаций поиска по наименованию так и сделано.
