### ISSUE TITLE
Не помещается наименование модуля регламентного задания

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#955]
**Описание ошибки**
В обработке "Регламентные и фоновые задания" при открытии регламентного задания, имя метода может не помещаться ни в размеры поля, ни в подсказку. При нажатии на гиперссылку ничего не происходит, а хотелось бы скопировать это поле.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/319183ce-54cc-4f33-8f51-cea0d07963ed)

**Окружение:**
Infostart Toolkit PROF 2024.1.05

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.167)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.144

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.1
