### ISSUE TITLE
Консоль кода не работает при наличии менеджеров временных таблиц запроса

### ISSUE THREAD

**Issue by AKazakov1C** [infostart-hub/toolkit#959]
![image](https://github.com/infostart-hub/toolkit/assets/116161950/733bc743-4b66-4217-9844-3f5a9e78d16e)

Infostart Toolkit PROF 2024.1.06

Платформа: 8.3.24.1467 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Зарплата и управление персоналом, редакция 3.1 (3.1.29.21)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.290

в инструментах от  https://github.com/cpr1c/tools_ui_1c тоже самое работает

**Comment by d-hurricane** [comment]
Подозреваю, что проблема в сохранении ссылки на менеджер временных таблиц для последующего вывода ее в панель с переменными. Как способ обхода проблемы просто в конце листинга кода присвойте `Неопределено` переменной с менеджером временных таблиц, а также переменной с запросом, если таковая есть:
```bsl
ВременныеТаблицы = Новый МенеджерВременныхТаблиц;

Запрос = Новый Запрос();
Запрос.Текст = "ВЫбрать 1 поместить ВТ";
Запрос.МенеджерВременныхТаблиц = ВременныеТаблицы;
Запрос.Выполнить();

// Строчки ниже освободят менеджер временных таблиц от ссылок на него,
// что позволит платформе корректно его закрыть до передачи управления клиенту.

ВременныеТаблицы = Неопределено;
Запрос = Неопределено;
```

**Comment by AKazakov1C** [comment]
Спасибо! Способ обхода рабочий.
