### ISSUE TITLE
Не работает параметр типа "Массив" в консоли кода

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#960]
**Описание ошибки**
Значение параметра с типом `Массив` не передается в контекст исполнения кода. Вместо массива (или списка значений) в контекст передается `Неопределено`.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль кода
2. Добавить параметр "Показатели" типа "Массив". Добавить к значению параметра несколько элементов, например, числовых.
3. Выполнить код `А = Параметры.Показатели;`
4. С помощью списка переменных убедиться, что переменная `А` не является коллекцией.
5. Попытаться в коде обратиться к элементам `А`. Убедиться, что такое обращение приводит к ошибке.

**Ожидаемое поведение, если бы ошибки не было**
Массив чисел должен быть доступен в контексте выполнения кода.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/371a41ad-4b7a-4af4-a5fa-09af6a30a9d0)

**Окружение:**
Infostart Toolkit PROF 2024.2.01

Платформа: 8.3.22.2501 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Демо конфигурация (1.0.0.1)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Спасибо, ошибка уже исправлена 2024.2.2
