### ISSUE TITLE
Ошибка в консоли кода при работе со списком значений в клиентском контексте

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#961]
**Описание ошибки**
При попытке создать список значений и наполнить его данными в клиентском контексте приводит к возникновению ошибки:

> Ошибка при вызове метода контекста (ПроверитьЦиклическиеСсылкиВстроенногоЯзыка)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ИсследованиеЗначенийКлиентСервер.Модуль(435)}:ЦиклическиеСсылки = ПроверитьЦиклическиеСсылкиВстроенногоЯзыка(Значение);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ИсследованиеЗначенийКлиентСервер.Модуль(212)}:ПредставлениеЭлемента = ПредставлениеЭлементаЗначения(ЭлементСписка.Значение);
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ИсследованиеЗначенийКлиентСервер.Модуль(37)}:ОписаниеЗначения = ОписаниеЗначения(Значение);
> {InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(742)}:ИТК_ИсследованиеЗначенийКлиентСервер.ЗаполнениеСтрокиНаФорме(НоваяСтрока, Переменная.Представление, Переменная.Значение)
> {InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(648)}:ДанныеРезультатата = ОбновитьРезультатВыполненияНаКлиенте(Результат);
> {InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(406)}:ОбновитьРезультатВыполнения(Результат);
> 
> [ОшибкаВоВремяВыполненияВстроенногоЯзыка]
> по причине:
> Несоответствие типов (параметр номер '1')
> [ОшибкаИспользованияВстроенногоЯзыка]

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть консоль кода.
2. Выбрать контекст: Клиент.
3. Ввести код:
```bsl
А = Новый СписокЗначений();
А.Добавить(10);
```
4. Выполнить код. Убедиться, что выполнение кода завершается ошибкой.

**Ожидаемое поведение, если бы ошибки не было**
Код должен выполняться без ошибок, как это работает в серверном контексте.

**Окружение:**
Infostart Toolkit PROF 2024.2.01

Платформа: 8.3.22.2501 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Демо конфигурация (1.0.0.1)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
На моей 2024.2.2 не воспроизводится, как она будет проверь может эта какая-то платформенная особенность

**Comment by nick-ez** [comment]
2024.2.1, 1С:Предприятие 8.3 (8.3.24.1368) тоже все ок
![image](https://github.com/infostart-hub/toolkit/assets/91209214/1370c567-87b1-4cd8-b389-d899a2255001)

**Comment by Evg-lylyk** [comment]
> Похоже, дело не в платформе, а в наличии БСП. На УТ11.5 взлетело, на пустой конфигурации с парой справочников - нет. @Evg-lylyk , проверь у себя еще раз, пожалуйста.

Хорошо

**Comment by Evg-lylyk** [comment]
Поправил в 2024.2.2
