### ISSUE TITLE
Не работают команды туллкита для модальных окон

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#963]
**Описание ошибки**
Если форма элемента справочника открыта модально, то команды туллкита не работают.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/72b6f0d8-f053-4f83-9f18-ee453af04f16)

**Окружение:**
Infostart Toolkit PROF 2024.1.06

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.232)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.232

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
![image](https://github.com/user-attachments/assets/a640a0f2-25d2-4b0e-85c9-a6218eb85aac)
Попробовал в ERP все открылось, пояснишь?

**Comment by Evg-lylyk** [comment]
Нет информации, закрываю
