### ISSUE TITLE
При вызове туллкит из формы внешнего отчета ошибка

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#964]
**Описание ошибки**
Если в форме внешнего отчета или обработки нажать Alt-T, то появляется ошибка

Метод объекта не обнаружен (Метаданные)
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(286)}:ПолноеИмяОбъектаМетаданных = Значение.Метаданные().ПолноеИмя();
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(222)}:ДобавитьВДоступныеОперацииПоЗначению(Родитель, ПолеОбъекта, Истина, Порядок);
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Форма.Форма.Форма(20)}:ДобавитьВДоступныеОперацииПоКонтексту(ДоступныеОперации, НавигационнаяСсылка, ПоляОбъекта);
{InfostartToolkitPROF ОбщийМодуль.ИТК_ГлобальноеМенюКлиент.Модуль(26)}:ОткрытьФорму("Обработка.ИТК_ГлобальноеМеню.Форма", Параметры, Источник, Уникальность, Окно, НавигационнаяСсылка);
{InfostartToolkitPROF Обработка.ИТК_ГлобальноеМеню.Команда.ГлобальноеМеню.МодульКоманды(6)}:ИТК_ГлобальноеМенюКлиент.Открыть(ПараметрыВыполненияКоманды);

[ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]

**Окружение:**
Infostart Toolkit PROF 2024.1.06

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.232)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.232

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Нужно детальнее попробовал несколько отчетов, все ОК
