### ISSUE TITLE
Журнал регистрации не отображает все события

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#965]
**Описание ошибки**
В журнале регистрации при отключенном фильтре не все события

**Сценарий воспроизведения**
выполнить код `ЗаписьЖурналаРегистрации("ДатаНачала", УровеньЖурналаРегистрации.Ошибка, , Дата(2024, 1, 1));`
Убедиться, что в журнале регистрации этой записи нет. Потом открыть типовой журнал регистрации и обнаружить запись.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/ac0ed4d5-5317-4866-ad08-d801a1213f7e)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/3bd29caf-a92c-4258-9d05-6d53afd9f716)

**Окружение:**
Infostart Toolkit PROF 2024.1.05

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.249)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.290

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Проверил все ОК
![image](https://github.com/infostart-hub/toolkit/assets/48444742/2ccd8dc5-10f4-40fc-85ac-030e41221fa6)

**Comment by Serg2000Mr** [comment]
Это уже не впервые такое. Значит сценарий более сложный. Буду ждать пока
снова появится.

вт, 18 июн. 2024 г., 16:19 Люлюк Евгений ***@***.***>:
