### ISSUE TITLE
Не работает гиперссылка в консоли кода

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#966]
**Описание ошибки**
В консоли кода при нажатии на гиперссылку выборки, открывается пустое окно. В выборке данные есть.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/129394542/f45de490-7e70-4741-967c-6ae2a0b06972)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/59ef1a75-ce04-42a6-bdca-d48ad6c4de27)
![image](https://github.com/infostart-hub/toolkit/assets/129394542/ce013546-a959-4314-a346-d632d532309a)

**Окружение:**
Infostart Toolkit PROF 2024.1.06

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.232)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.232

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.2
