### ISSUE TITLE
Ошибка при открытии таблицы в исследователе значений

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#968]
**Описание ошибки**
При попытке открыть для просмотра кликом по гиперссылке таблицу значений в форме исследователя значений возникает ошибка:

> Поле объекта не обнаружено (Значение)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_ИсследованиеЗначенийКлиент.Модуль(46)}:Если ТипЗнч(ВыбраннаяСтрока.Значение) = Тип("Строка") Тогда
> {InfostartToolkitPROF Обработка.ИТК_ИсследованиеЗначений.Форма.ОсновнаяФорма.Форма(38)}:ИТК_ИсследованиеЗначенийКлиент.РезультатПеременныеВыбор(ЭтотОбъект, Элемент, ИдентификаторСтроки, Поле, СтандартнаяОбработка);

**Сценарий воспроизведения**
1. Открыть редактор кода. Ввести следующий текст:
```bsl
Результат = Новый Структура();
Результат.Вставить("Таблица", Новый ТаблицаЗначений());
```
2. Выполнить код.
3. На панели переменных найти `Результат` и кликнуть по гиперссылке в ячейке значения. Откроется окно исследователя значений с полями структуры.
4. Вновь кликнуть в открывшемся окне по гиперссылке значения для просмотра уже содержимого таблицы значений. Убедиться, что вместо открытия новой формы исследователя с пустой таблицей значений возникнет окно с ошибкой.

**Ожидаемое поведение, если бы ошибки не было**
Ошибки быть не должно.

**Окружение:**
Infostart Toolkit PROF 2024.2.01

Платформа: 8.3.22.2501 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
RDV Market Core (3.0.10.170)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_18
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.2
