### ISSUE TITLE
Сохранять отображение дерева данных между сеансами работы с консолями

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#970]
**Существует проблема**
Зачастую при работе с консолями, особенно с консолью кода, мне не требуется вводить несколько листингов кода, т.е. панель дерева данных используется крайне редко. При этом она занимает ценное пространство. Ее можно скрыть специальной кнопкой, однако при следующем запуске консоли дерево данных вновь будет отображаться.

**Хотелось бы**
Сохранения видимости панели дерева данных между сеансами работы с консолью. Т.е. это должно быть пользовательской настройкой.

**Дополнительный контекст**
Infostart Toolkit PROF 2024.2.01

Платформа: 8.3.22.2501 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
RDV Market Core (3.0.10.170)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_18
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by d-hurricane** [comment]
Я мог бы просто через "Изменить форму" скрыть эту панель. Но этому препятствует ошибка #969.

**Comment by Evg-lylyk** [comment]
Сделал в консоли кода в консоли разработчика пока не стал.
Смущает что когда ты откроешь данные к которых 10 строк, а дерево скрыто, очень не очевидно получается где данные?
Для консоли кода думаю вообще не нужно дерево оно может открывать *.bsl и все (но так это уже будет 3-ая консоль кода)
