### ISSUE TITLE
Изменение типа выделенных параметров в консоли запросов

### ISSUE THREAD

**Issue by sagittarius-s** [infostart-hub/toolkit#971]
**Существует проблема**
Когда есть множество параметров одного типа данных, приходится для каждого отдельно выбирать тип.

**Хотелось бы иметь следующую функциональность**
Чтобы команда выбора типа срабатывала на выделенные строки, а не на одну.

![image](https://github.com/infostart-hub/toolkit/assets/65113366/b56c748d-b3f3-4841-b1e0-b8e609795d8c)

**Дополнительный контекст**
Infostart Toolkit CORP 2024.1.06

**Comment by Evg-lylyk** [comment]
Реализовано в 2024.3
