### ISSUE TITLE
В окне Все функции добавить кнопку поиска

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#973]
**Существует проблема**
В окне Все функции не автоматического запуска поиска. Нужно нажимать ввод, чтобы поиск запустился. 

![image](https://github.com/infostart-hub/toolkit/assets/129394542/a0f23048-bba2-4555-a914-9328d6cecbda)

Это поведение поля поиска отличается от окна Глобальное меню и большинства других полей ввода, где поиск запускается автоматически. Поэтому почти каждый раз сначала ждешь, что поиск запустится сам, а потом нажимаешь на ввод.

**Хотелось бы иметь следующую функциональность**
Включить автопоиск или добавить справа кнопку поиска как в панелях навигации.

![image](https://github.com/infostart-hub/toolkit/assets/129394542/11b7a06e-11db-495a-94ff-0d7ebaceb8fc)

**Comment by Evg-lylyk** [comment]
Добавлено в 2024.4
