### ISSUE TITLE
Ошибка при использовании в англоязычной конфигурации

### ISSUE THREAD

**Issue by dubovtsovalexey** [infostart-hub/toolkit#974]
**Описание ошибки**
Ошибка при попытке открытия любой формы списка с подключаемыми командами БСП.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть любую форму списка с подключаемыми командами БСП
2. Ошибка: Command kind name "ИТК_Подменю" does not meet naming requirements for variables.
(Не проходит проверка имя вида команды AttachableCommands.CheckCommandsKindName(KindName))

**Ожидаемое поведение, если бы ошибки не было**
Открытие форм списка без ошибок, или возможность отключить в настройках подключаемые команды ИТК.

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/173784723/b75aae6b-daa6-4df1-b181-df456f17bd9c)

**Окружение:**

Infostart Toolkit PROF 2024.2.02

Platform: 8.3.24.1548 (Windows x86-64)
Mode IB: client-server

Configuration:
Configuration (3.1.10.146)
Basic launch mode: Managed application
Compatibility mode: Version8_3_21
SSL version: 3.1.10.146

Client:
Thick client (managed application)
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Language: en
Launch mode: Managed application

**Comment by Evg-lylyk** [comment]
Пробую на ERP: WE все нормально. Нужно с вами связаться
https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
Могу попробовать адаптировать к вашей конфигурации, но нужно больше информации
