### ISSUE TITLE
Не работает заявленный функционал в англоязычной версии

### ISSUE THREAD

**Issue by dubovtsovalexey** [infostart-hub/toolkit#978]
**Описание ошибки**
Не работает заявленный функционал в англоязычной версии

**Сценарий воспроизведения**
1. Storage structure - не отображает никаких данных
2. Object editor - не отображает реквизиты для редактирования
3. Access right analys - формирует пустой отчет
4. Metadata - не отображает никаких данных
5. Search for object references - бесконечное формирование отчета
6. Object comparison - формирует пустой отчет
7. Sceduled and background jobs - ошибка при открытии
8. Search and replacement links - бесконечное формирование отчета

**Ожидаемое поведение, если бы ошибки не было**
Ожидается, что решение, которое приобреталось с прицелом на англоязычную конфигурацию, будет работать в заявленном режиме.

**Скриншоты**
1.
 ![image](https://github.com/infostart-hub/toolkit/assets/173784723/74ed2e0b-8e32-42c8-b501-ba91b6b36377)
2.
 ![image](https://github.com/infostart-hub/toolkit/assets/173784723/94a51618-4f6b-4bee-8601-1effe2cd444d)
3. 
 ![image](https://github.com/infostart-hub/toolkit/assets/173784723/acb6dd21-c4a2-435a-931a-08aed99a768e)
4. 
![image](https://github.com/infostart-hub/toolkit/assets/173784723/56c56a28-93ce-4140-890a-25aa364e83a0)
5.
![image](https://github.com/infostart-hub/toolkit/assets/173784723/77dcd9fc-5bd5-4b4f-870b-4b831bb0ac2b)
6.
![image](https://github.com/infostart-hub/toolkit/assets/173784723/fe80200e-93af-4078-b061-6be6b487aab7)
7. 
![image](https://github.com/infostart-hub/toolkit/assets/173784723/dca26bd0-5431-45dc-910e-275c657f6eca)
9. 
![image](https://github.com/infostart-hub/toolkit/assets/173784723/73f1e629-34b1-49fe-bcd9-4f2cdc404730)

**Окружение:**
Infostart Toolkit 2024.2.02

Platform: 8.3.24.1548 (Windows x86-64)
Mode IB: client-server

Configuration:
Configuration (3.1.10.146)
Basic launch mode: Managed application
Compatibility mode: Version8_3_21
SSL version: 3.1.10.146

Client:
Thick client (managed application)
OS: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 17763))
Language: en
Launch mode: Managed application

**Comment by Evg-lylyk** [comment]
Приветствую, срочно займусь этими проблемами.
Можете со мной связаться https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.3
