### ISSUE TITLE
Консоль СКД ошибка при редактировании параметров

### ISSUE THREAD

**Issue by AnatoliyBritko** [infostart-hub/toolkit#979]
**Описание ошибки**
В конструкторе СКД при установке значения параметра возникает ошибка.

**Сценарий воспроизведения**
Шаги по воспроизведению:
1.В консоли открываю конструктор СКД. Добавляю набор данных. Прописываю запрос.
![image](https://github.com/infostart-hub/toolkit/assets/18395787/e6a0ef0b-36e4-42f4-80f3-203faff55496)

2. Захожу на вкладку параметры. Устанавливаю значение и получаю ошибку

![image](https://github.com/infostart-hub/toolkit/assets/18395787/d924919e-d02e-4d9d-97b4-fbc80c1bb160)

Infostart Toolkit PROF 2024.2.02

Платформа: 8.3.22.1923 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
Альфа-Авто: Автосалон+Автосервис+Автозапчасти КОРП. Редакция 6
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_10
Версия БСП: 2.3.5.8

Клиент:
Тонкий клиент
ОС: Windows x86 (Microsoft Windows 10 version 10.0  (Build 17763))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.4
