### ISSUE TITLE
В консоли запросов исправить/доработать загрузку данных внешнего источника

### ISSUE THREAD

**Issue by Terverus** [infostart-hub/toolkit#980]
В консоли запросов при загрузке данных из табличного документа или буфера обмена все данные читаются как СТРОКА.
И нет никакой возможности для управления приведения типами.

Допустим загрузилась колонка со строками вида "25.06.2024 23:07:07".
При изменении типа колонки "Строка" на тип "Дата" все строки приводятся к датам вида 25.06.2024 00:00:00, то есть теряется время.

Дальнейшим запросом приведение дат невозможно или трудоемко. 
Да и другие поля хорошо бы приводить к ссылочным типам доп. обработкой перед отправкой их в запрос.

Предлагаю добавить возможность прописать алгоритм обработки строки при загрузке из внешнего файла/буфера.
Или добавить алгоритм при изменении типа колонки, чтобы всю колонку преобразовать в нужные данные.
Без этого внешний источник данным просто бесполезен, вообще никак условия соединений запроса не работают.

**Comment by Evg-lylyk** [comment]
Приветствую, проверил в 2024.2 "25.06.2024 23:07:07" преобразуется корректно
Если нужны ссылочные типы можно работать через ЗначениеСтрокаВнутр буфер самой простой и ограниченный вариант.
Еще можно поставить у источника тип выражение получая его данные кодом.
Если у вас во внешнем источнике код справочника, ссылку можно получать соединением.
Есть вопросы, пожелания можем связаться лично https://t.me/EvgLylyk

**Comment by Terverus** [comment]
Добрый день!Что значит дата преобразуется корректно?Как это повторить?У меня прямо сейчас загружена таблица с колонкой дат и преобразуется она некорректно.У меня реальная рабочая ситуация, в которой консоль запросов оказалась бесполезной.Этого всего наверное можно было бы избежать, если бы прям во время отладки можно было выгружать в файл дамп параметров запроса, с готовыми таблицами значений, а не выгружать их в текстовые таблицы через «вывести список», как это сделано в Запроснике. То есть выгружается файл запроса, по кнопке загружается и текст запроса и его параметры.А Вы один ведете разработку? Никак нельзя участвовать в развитии, и не просто подавать идеи? Мне было бы не так это важно, если бы мы всем отделам именно Вашими инструментами не пользовались)Отправлено с iPhone27 июня 2024 г., в 10:52, Люлюк Евгений ***@***.***> написал(а):﻿
Приветствую, проверил в 2024.2 "25.06.2024 23:07:07" преобразуется корректно
Если нужны ссылочные типы можно работать через ЗначениеСтрокаВнутр буфер самой простой и ограниченный вариант.
Еще можно поставить у источника тип выражение получая его данные кодом.
Если у вас во внешнем источнике код справочника, ссылку можно получать соединением.
Есть вопросы, пожелания можем связаться лично https://t.me/EvgLylyk

**Comment by Evg-lylyk** [comment]
Какая у вас версия Туллкит?
"А Вы один ведете разработку?" Да
"Никак нельзя участвовать в развитии, и не просто подавать идеи?" можно но это обсуждать нужно. Не считаю полезным делать все что кто-то говорит... нужно обсуждать
Если мы с вами свяжемся поговорим, я попробую помочь. Не все из того что вы пишите я понимаю на 100%
