### ISSUE TITLE
Ошибка редактирования параметров консоли кода  после загрузки из файла

### ISSUE THREAD

**Issue by xnd1124** [infostart-hub/toolkit#981]
**Описание ошибки**
После редактирование параметра в консоли кода возникает ошибка 
Значение не является значением объектного типа (Параметры)
{InfostartToolkitPROF Обработка.ИТК_КонсольКода.Форма.Форма.Форма(251)}:ДанныеСтрокиПараметры = ДанныеСтроки.Параметры;

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Открыть пустую консоль кода
2. Создать параметр с любым значением
3. Сохранить консоль в файл
4. Открыть файл
5. Отредактировать значение параметра
6. После завершения редактирования возникает ошибка

**Окружение:**

   Infostart Toolkit PROF 2024.2.02

Платформа: 8.3.24.1548 (Windows x86-64)
Режим БД: файловый

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.17.84)
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: 3.1.9.337

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Пробую в 2024.2.3 все ОК возможно она исправлена в ней. Работал недавно над подобной проблемой
