### ISSUE TITLE
Отсутствует контекстная подсказка менеджера констант

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#983]
**Описание ошибки**
В консоли кода отсутствует контекстная подсказка менеджера констант. При этом сами константы в конфигурации существуют (см. скрин из редактора констант).

**Скриншоты**
![image](https://github.com/infostart-hub/toolkit/assets/59051827/374f73d3-4610-4453-a4c1-9c0e79959290)
![image](https://github.com/infostart-hub/toolkit/assets/59051827/7127b25a-dc01-4289-9076-978b7bb39de4)

**Окружение:**
Infostart Toolkit PROF 2024.2.02

Платформа: 8.3.22.2501 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
RDV Market Core (3.0.10.172)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_18
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.4
