### ISSUE TITLE
Не работает установка расписания задания из списка регламентных заданий

### ISSUE THREAD

**Issue by d-hurricane** [infostart-hub/toolkit#985]
**Описание ошибки**
При попытке изменить расписание регламентного задания непосредственно в списке заданий в момент записи расписания возникает ошибка:

> Поле объекта не обнаружено (Метаданные)
> {InfostartToolkitPROF ОбщийМодуль.ИТК_РегламентныеЗадания.Модуль(242)}:ИТК_Избранное.ЗаписатьВИзбранное(ВидИнструмента, Свойства.Метаданные, Свойства.Избранное);
> {InfostartToolkitPROF Обработка.ИТК_РегламентныеИФоновыеЗадания.Форма.Форма.Форма(706)}:ИТК_РегламентныеЗадания.Записать(Свойства);
> {mngbase/JobSchedule.lf(291)}:Close(True);
> 
> [ОшибкаВоВремяВыполненияВстроенногоЯзыка, ОшибкаИспользованияВстроенногоЯзыка]

**Сценарий воспроизведения**
1. Открыть инструмент "Регламентные и фоновые задания".
2. Выделить любое из регламентных заданий в списке, и в колонке "Расписание" нажать на гиперссылку с представлением установленного расписания задания.
3. В открывшемся диалоговом окне конструктора расписания настроить любое расписание и нажать "Ок".
4. Убедиться, что после нажатия на "Ок" возникает сообщение об ошибке, текст которой приведен выше.

**Ожидаемое поведение, если бы ошибки не было**
Ошибки быть не должно, расписание задания должно измениться.

**Окружение:**
Infostart Toolkit PROF 2024.2.02

Платформа: 8.3.23.2040 (Windows x86-64)
Режим БД: файловый

Конфигурация:
Конфигурация ()
Основной режим запуска: Управляемое приложение
Режим совместимости: НеИспользовать
Версия БСП: БСП не установлена

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 22631))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.2.4
