### ISSUE TITLE
В консоли запросов не сбрасывается текущая строка для нового запроса

### ISSUE THREAD

**Issue by Serg2000Mr** [infostart-hub/toolkit#995]
**Описание ошибки**
В консоли запросов при изменении запроса и уменьшении количества строк, текущая строка остается для предыдущего запроса.
Это приводит к тому, что приходится перематывать на начало табличного документа

**Скриншоты**
![Текущая строка в консоли запросов](https://github.com/user-attachments/assets/9554e5c4-d66c-4187-814d-25be4fd4922c)

**Окружение:**
Infostart Toolkit PROF 2024.2.06

Платформа: 8.3.22.2239 (Windows x86-64)
Режим БД: клиент-серверный

Конфигурация:
1С:ERP Управление предприятием 2 (2.5.12.270)
Основной режим запуска: Управляемое приложение
Режим совместимости: Версия8_3_21
Версия БСП: 3.1.9.302

Клиент:
Тонкий клиент
ОС: Windows x86-64 (Microsoft Windows 10 version 10.0  (Build 19045))
Язык: ru
Режим запуска: Управляемое приложение

**Comment by Evg-lylyk** [comment]
Исправлено в 2024.4
