### ISSUE TITLE
Обновление конфигурации 1с

### ISSUE THREAD

**Issue by ZaytsevDM** [infostart-hub/toolkit#996]
**Описание ошибки**
При обновлении вспомогательных данных возникает ошибка из за заимствованной роли Администратор в расширении 
Infostart Toolkit: CORP 2.04

**Сценарий воспроизведения**
Шаги по воспроизведению:
1. Обновить конфигурацию 1с, при включенном расширении Infostart Toolkit
2. выполнить обновлении вспомогательных данных

**Ожидаемое поведение, если бы ошибки не было**
Что должно быть результатом: успешное завершение обновления

**Скриншоты**
![photo_2024-08-14_08-38-45](https://github.com/user-attachments/assets/f953404d-2752-47c9-ac82-a32fdb6cecf1)
![Screenshot_2](https://github.com/user-attachments/assets/749ee4a4-e109-4819-8803-3c31584bd1d0)

**Окружение:**

   - Платформа 1С: 8.3.22.2239
   - Имя конфигурации: ERP 2.5
   - Язык: Руский
   - Операционная система: Windows Server 2022 Datacenter
   
Информацию можно получить подсистема Infostart Toolkit - О программе - Информация для технической поддержки

**Comment by Evg-lylyk** [comment]
Уходим от заимствованных ролей, удалям код который с ними взаимодействует
